### ISSUE TITLE
Filenaming:  Invalid File Extension Warning

### ISSUE THREAD

**Issue by Jay-Cup** [opentoonz/opentoonz#1537] opened 2017-10-23 21:49 UTC
I have spent a large amount of time on a scene only for it to smack me in the face with a warning (Filename_.avi has an invalid extension format.) at the end of the rendering process. I am using windows 7 and opentoonz 1.1.3, and rendering out AVI files at 1920x1080. The scene was rendering out fine for a time, and then strangely decided I was using the wrong file extension, though I don't recall changing anything. Opentoonz is also sticking an underscore at the end of the filename for no apparent reason.

**Comment by shun-iwasawa** [comment] 2017-10-24 01:48
Thank you for posting the issue. For sequential image files with underscore ( like `foo_0001.png` , `foo_0002.png` ... ) OpenToonz uses the name `foo_.png` to handle them altogether as one level. It seems that the `filename_.avi` was misunderstood as such sequential image files.

> Opentoonz is also sticking an underscore at the end of the filename for no apparent reason.

I couldn't reproduce this behavior so far. Is there any conditions for occurrence?

**Comment by Jay-Cup** [comment] 2017-10-29 21:20
I was able to reproduce the underscore issue on a fresh scene. On the output settings window I stuck an underscore at the end of the filename, then rendered it. After getting the warning, I remove the underscore and hit render again and the underscore is forced into the filename and the error persists.

**Comment by RodneyBaker** [comment] 2019-10-26 03:11
@Jay-Cup Are you still experiencing invalid filenaming issues?

**Comment by Jay-Cup** [comment] 2019-11-07 04:25
@RodneyBaker I haven't had any issues with the newer releases.

**Comment by RodneyBaker** [comment] 2019-11-07 13:25
Thanks @Jay-Cup for the follow up.
Will close this issue.

**Closed by RodneyBaker** 2019-11-07 13:25 UTC
Labels: Bug
