### ISSUE TITLE
Crash with particles and swatch panel opened

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3489] opened 2020-09-18 15:14 UTC
**Describe the bug**

When you add particles and use swatch viewer in camera preview, adding a control image will crash OT. It's something that not happening in 1.3 version.

**To Reproduce**

1. Add a particle fx
2. Open swatch viewer and enable camera preview
3. Add 1 control image from source tab

**Expected behavior**

No crash

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows 10]
 - OpenToonz Version: Last NB
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by jeremybullock** [comment] 2020-09-18 19:12
I've tracked it down to #3139 
Something in there is causing the crash.

**Comment by RodneyBaker** [comment] 2022-02-24 06:44
As with report #3491 I am unable to reproduce this problem on latest nightly release.

**Comment by openanim** [comment] 2022-02-26 00:06
This keeps happening sometimes it happens right after opening the swatch viewer panel, sometimes after choosing 1 or more control images, or by going to the timeline
![crash_swatch viewer](https://user-images.githubusercontent.com/29790512/155819229-33a4b96b-0c6c-4b06-bc4b-464a63d5ff15.gif)
.

**Comment by RodneyBaker** [comment] 2022-02-26 00:51
Make sure you are using the latest nightly release to test this as it contains a fix related to particles (and the controller).

**Comment by openanim** [comment] 2022-02-26 13:23
I think I am using the latest build but confirm if not. I get the crash also from the same NB build from a different computer
<img width="531" alt="CaptureOT_NB" src="https://user-images.githubusercontent.com/29790512/155844935-a9ff5f03-9cc3-49fc-9ea7-1f9e0b55fedb.PNG">
.

**Comment by RodneyBaker** [comment] 2022-02-26 15:29
Did you build this yourself?

I ask because there is no nightly build for today (26 Feb) and yet your version is dated today.

If using a personal build, highly recommend testing with an official release as that will reduce many variables.

**Comment by openanim** [comment] 2022-02-26 16:48
No, I don't do builds. I used the version dated 2022-02-25 19:32:37 UTC in the NB releases page
<img width="1194" alt="builds_OT" src="https://user-images.githubusercontent.com/29790512/155851277-ef430994-f50b-4017-9c50-b565c10d92ae.PNG">

but my previous screenshot that was the information I got from the "about" section with this build. Reinstalling the build today, just to be sure, the date looks slightly different, unless I got it wrong nb last time. 

<img width="465" alt="Capture_last_nb" src="https://user-images.githubusercontent.com/29790512/155851290-1d429519-1c82-4adf-9972-0c9fe888407c.PNG">

Could the difference in date and time display be related to the fact of different geographical areas and time zones?

But I still get the crash.

**Comment by RodneyBaker** [comment] 2022-02-26 17:24
Thanks for the clarification.  I'll guess what we are seeing is build time in Japan.
Apologies for the diversion...

We'll have to find a way to dive deeper into the bug/crash.

**Comment by artisteacher** [comment] 2023-01-19 03:33
I don't have an FX settings panel docked, so I'm most likely to get crash after double-clicking on an FX node to open the floating window. It's not every time. However, as long as I save first, I don't crash.

**Comment by RodneyBaker** [comment] 2023-11-19 09:16
Closing as the originator of the report has ghosted themselves.
Note:  There may be information cotained in this report that should be captured in other appropriate report.

**Closed by RodneyBaker** 2023-11-19 09:16 UTC
Labels: bug, needs info, crash
