### ISSUE TITLE
Can't export to video format because opentoonz is a snap (Linux)

### ISSUE THREAD

**Issue by DustRavenN** [opentoonz/opentoonz#3493] opened 2020-09-20 11:14 UTC
I can't use ffmpeg because Opentoonz is a snap and can't access my pc files (/usr/bin/ffmpeg) even with the --classic flag when you install the package pls help me and tell me how to fix this big problem ...
another solution would be to **put Opentoonz in the official linux packages**
PS : i'm on Ubuntu

**Comment by RodneyBaker** [comment] 2020-09-20 11:35
Unfortunately this appears to be a limitation of the snap distro.
Is there some reason you cannot use one of the other Linux releases such as Morevna or OTX?

As for this report, it is a duplicate of other similar reports.
You may want to look into what those users did to resolve their problem but I imagine they either only use image formats that do not require ffmpeg or they have moved to another release of Opentoonz.

Here's a link for OTX:
https://github.com/manongjohn/OTX/releases/download/OTX-2020-09-04/OpenToonz-OTX-linux.tar.gz

And here for Morevna:
https://github.com/morevnaproject-org/opentoonz/releases

**Comment by DustRavenN** [comment] 2020-09-20 11:55
I prefer to stay on Ubuntu, is there a reason Opentoonz is not an official package?

**Comment by RodneyBaker** [comment] 2020-09-20 12:03
If it's not yet available I would guess that no one has ported to over to Ubuntu.

**Comment by manongjohn** [comment] 2020-09-20 12:14
There is no official Linux version of OpenToonz and it is not officially supported by Dwango/Digital Video. Any linux version that is created is made by the community.

The only way to get official OT on linux is to compile from source, use snap/flatpak versions or use OT variants with Linux AppImages like OTX and Morevna.

OTX is an AppImage built on Ubuntu 16.04 and closely resembles what is in OT. Included are a few items not yet in the official release but pending to be included.

.

**Comment by RodneyBaker** [comment] 2020-09-21 15:28
Closing as the solution is provided although it doesn't address the underlying problem of current snap linux distros support short of contacting the creators of those resources and advocating for appropriate updates/support.  Where those releases fall short it is important to communicate that to those who maintain those specific releases so they will know of the issues.

@manongjohn confirms that OTX is built on Ubuntu that would appear to be the ideal solution (as the maintainer of that  build he should know).

Recommendation:  Please try the OTX release and report back on your experience here.

**Closed by RodneyBaker** 2020-09-21 15:28 UTC
Labels: duplicate
