### ISSUE TITLE
Vector sub tab should highlight the chosen tab

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3205] opened 2020-04-01 20:02 UTC
### Issue Summary

It may be just my own perception, but I find that the editor style panel in the vector part with the generator trail vector brushes tabs should rather highlight the chosen tabs and not the opposite. It would be easier to see which one is active.

The colors textures vectors rasters tabs just above, for example, work this way. This is the case with almost all the panels such as a palette or stop motion.

### Screenshot or Video Reference

this might not be enough obvious  in the gif

![highlight the chosen tab](https://user-images.githubusercontent.com/29790512/78181169-33a19300-7464-11ea-8efa-cc6ac9bf5f46.gif)
### Expected Results

Vector sub tab should highlight the chosen tab

### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by DarrenTAnims** [comment] 2020-04-02 08:44
The Generated, Trail & Vector Brushes boxes aren't tabs. They're buttons to show/hide those collections. So they can't highlight which is selected.

**Comment by turtletooth** [comment] 2020-04-04 16:51
@DarrenTAnims is right.  They are buttons and the reason they get darker instead of highlighted is that they are in the pressed state when that part is visible.

**Comment by turtletooth** [comment] 2020-04-04 16:53
I understand the confusion though. . . 
It would take a custom stylesheet change for that part to fix.

**Comment by RodneyBaker** [comment] 2020-04-11 11:35
Closing as the tabs are working as designed.
Agree that some improvement would be ideal in the future.

**Closed by RodneyBaker** 2020-04-11 11:35 UTC
Labels: feature request, workflow
