### ISSUE TITLE
Astropad Compatibility?

### ISSUE THREAD

**Issue by PolyStoryGuy** [opentoonz/opentoonz#4735] opened 2023-02-04 21:21 UTC
To Whom It Might Concern,

I was hooked up to my iPad Pro 12.9 inch thru Astropad in Opentoonz 1.6, when all of a sudden, my Opentoonz crashed on me again! Please do something.

PolyStoryGuy

**Comment by RodneyBaker** [comment] 2023-02-04 21:32
Perhaps an unintended duplicate of #4736?

**Closed by RodneyBaker** 2023-02-04 21:32 UTC
Labels: referral / thirdparty
