### ISSUE TITLE
Feature Request: for auto inbetween mode should have some options : drawing order and sign of direction like CACANi animation software

### ISSUE THREAD

**Issue by arh2009** [opentoonz/opentoonz#763] opened 2016-08-26 12:00 UTC

**Comment by RodneyBaker** [comment] 2016-08-26 15:32
This is a duplicate of another feature request but I can't find the number at the moment...

**Comment by turtletooth** [comment] 2016-08-26 18:51
Duplicate of #545

**Closed by turtletooth** 2016-08-26 18:51 UTC
Labels: Feature Request
