### ISSUE TITLE
Duplictated room widget on OSX with full screen mode

### ISSUE THREAD

**Issue by jcome** [opentoonz/opentoonz#453] opened 2016-06-16 04:13 UTC
<img width="1024" alt="duplicated room widget" src="https://cloud.githubusercontent.com/assets/417336/16105294/91bea6aa-33bb-11e6-8224-9af646876b30.png">

**Comment by matitanimata** [comment] 2016-06-20 07:04
same thing for me (el capitan)

**Comment by artisteacher** [comment] 2017-05-22 20:38
Duplicate of #271.

**Closed** 2017-05-22 20:42 UTC
Labels: Duplicate, OS: MacOS
