### ISSUE TITLE
Codec problem

### ISSUE THREAD

**Issue by SPH404** [opentoonz/opentoonz#4053] opened 2021-08-31 10:29 UTC
Hi,

I bought a new PC (w10) to be able to work on it with OpenToonz 1.5
When I want to render an anim in Xvid (avi), I realize that I don't have Xvid in the drop-down list:
http://xmas.free.fr/codec_ot15.jpg
I installed some codecs (although w10 did contain some) but the list is still ridiculously small.

What to do to include codecs in OT?

Thx

**Comment by artisteacher** [comment] 2021-09-01 02:43
I don't think you can add codecs - unless you build OT yourself and do some coding to include them.

**Comment by SPH404** [comment] 2021-09-01 08:54
My question remains: how to update the list of codecs (especially Xvid)?
Please don't let me down! 😥

**Comment by SPH404** [comment] 2021-09-01 11:11
On the other hand, good news: on my new computer, the ffmpeg works (I can render in MP4)

**Comment by SPH404** [comment] 2021-10-02 09:51
Hello everyone,

It is not normal that OT only offers this:
http://xmas.free.fr/codec_ot15.jpg
I don't have the xvid codecs. And also the sprite boards. Also, I don't have image by image (in png)

This should be integrated into OT

Also, move the keys at the same time as moving the columns.

Strongly OT1.6 😉

**Comment by artisteacher** [comment] 2021-10-02 13:33
There should be a spritesheet option as one of the formats in the output settings.

Do you mean you are looking for an apng format?

You can already move keys and columns at the same time - you just have to follow specific steps. Select your frames and keys by holding down on CTRL (CMD on macOS) while selecting. Release. Then use the dragbar to move the frames to the new position - the keyframes will move too.

**Comment by gab3d** [comment] 2021-10-03 04:12
@SPH404 

Just to try it, I've downloaded and installed Xvid, from its [website](https://www.xvid.com/), and it shows in the codec dropdown list 

![imagen](https://user-images.githubusercontent.com/18104091/135739381-0c095806-0494-44fa-b8cd-044bd30f8c01.png)

**Comment by SPH404** [comment] 2021-10-05 10:29
Hello everyone,

Thanks gab3d. Indeed, your link to an xvid installation allowed me to have an xvid option in the drop-down list of OT:
http://xmas.free.fr/ot3.bmp

Thanks for that. 😉

**Comment by RodneyBaker** [comment] 2021-10-19 22:43
It looks like this issue is resolved by installing the coded.
Opentoonz then automatically recognizes the codec if/when it is fully installed.

Closing but please feel free to add additional comments and information here or (for any reproducable bug) launch a new report.

Thanks!

**Closed by RodneyBaker** 2021-10-19 22:43 UTC
Labels: question
