### ISSUE TITLE
Pressure sensitivity not working with N-trig input

### ISSUE THREAD

**Issue by Ozillion** [opentoonz/opentoonz#1830] opened 2018-02-25 07:04 UTC
I am using Surface Pro 2017 with Surface Pen and I can't get the pressure to work. I do have the pressure ticked in OpenToonz and it does work in other software (tested only Krita and OneNote)

![image](https://user-images.githubusercontent.com/6342837/36638861-48ce6be6-19f7-11e8-9a04-0c8b52db30f7.png)

The line tapers and breaks when drawn fast. It looks like it doesn't register the stroke immediately and just draws a straight line instead of a curve at the start of the stroke.

![image](https://user-images.githubusercontent.com/6342837/36638921-6b8aaa68-19f8-11e8-9be8-6114ba32613c.png)

I have seen a somewhat similar effect in Photoshop when using Wacom Intuos tablet and it may be a Windows Ink issue. I used to disable it but now I think I need it for the pen to work on the screen so hopefully it's a different problem or a stupid mistake on my part.

Oh, I also tried changing compatibility in properties to Windows 7/8 but it didn't change much. At least didn't fix the pressure sensitivity dilema.

**Comment by NoahFarron** [comment] 2018-02-25 12:31
I have a similar issue that I posted in #1816 where the line looks like it breaks or loops through itself if you draw quickly. Krita also has a very similar problem in 3.3.3 but looks to be resolved in 4.0, the issue is with OpenGL so could the same issue apply to Toonz? In Krita, switching to ANGLE fixes it.

The bottom image you posted on the right (the one with the long straight line) looks like the double-click distance issue with Windows Ink. With a Wacom tablet, you can set the double-click distance to off to fix it under Wacom Tablet Properties panel. I have no idea for N-Trig, I think you could open the Pen and Touch window (type flicks in search) and go to the Pen Options tab, double click Press and Hold and uncheck "Enable press and hold for right-clicking".

Something you could try, is try installing the oldest available version of Toonz (1.0) to see if it's any better, it was marginally better when I tried it and the brush lag really kicks in after 1.1.2.

https://github.com/opentoonz/opentoonz/releases/tag/v1.0

**Comment by Ozillion** [comment] 2018-02-25 12:55
@NoahFarron So I disabled the Press and Hold but it didn't change anything. Although it's nice to have this option disabled as I don't use it and I know it causes troubles with Wacom tablets. I installed version 1.0 and although lines didn't skip as much I still didn't have pressure sensitivity. To clarify the lines skipping is a relatively minor issue to begin with. But I thought it would give clues as to what the problem could be so I mentioned it in op. I reinstalled the old version again and nothing changed really. I looked through settings and couldn't find OpenGL toggle(not certain if the option is available) but I agree that it could be OpenGL. When I had this problem in Krita a restart usually fixed it.

**Comment by NoahFarron** [comment] 2018-02-25 16:02
@Ozillion Yeah there is no option in Toonz for the renderer.

I read awhile back that on Windows 10 1709 (Fall Creators Update) the flicks (Pen and Touch) panel doesn't seem to work, Microsoft seem to have done something to Windows Ink in the update. There could be an option in the Settings app, go to Devices > Pen & Windows Ink.

You can try turning it off in the registry, though this may not apply to you if you're not running the update. Run regedit and navigate to `Computer\HKEY_CURRENT_USER\Software\Microsoft\Wisp\Touch`, double click on `TouchMode_hold` and check the value.

0 > disabled
1 > enabled

You can change it to any of those, then log out and log back in again.

For pressure, I'm still unsure. You could check in OpenToonz ToolOptions window to make sure size min and size max are not the same value.

**Comment by dimon45666** [comment] 2018-04-14 15:56
Никита,найдись плес

**Comment by Ozillion** [comment] 2018-04-16 17:58
Димас, я написал в скайпе и в стиме. атветь. 
Или дай почту/другое средство связи.

**Comment by manongjohn** [comment] 2018-11-23 13:37
The latest nightlies have included an OpenToonz setting for Windows Ink support.  If enabled, it should fix this issue.  Can you confirm?

**Comment by RodneyBaker** [comment] 2018-12-03 22:22
@Ozillion @HaydenFarron this should be resolved in current nightly releases.
Closing this pending report of related issues.

**Closed by RodneyBaker** 2018-12-03 22:22 UTC

**Comment by manongjohn** [comment] 2018-12-22 13:30
@dasiaparks
What OT version are you currently running? What OS version are you on?

1) Current and precious official releases do not support Windows Ink. Did you disable Windows Ink in your Huion tablet properties? If disabling there still did not work, you may need to download and install WinTab drivers for your OS version.

2) Try a fresh install.  Rename your C:\OpenToonz... stuff folder to something else as a backup and uninstall current version then reinstall the lastest again.

If you can install the latest nightly version, it has Windows Ink support, which you can enable in OT preferences.

**Comment by Dasiaparks** [comment] 2018-12-23 03:03
i'm on a windows 10 OS... i tried installing version 1.2.1 of OT but no matter what it crashes on launch.... so i installed version 1.1.3 which works but the pen pressure does not. my windows ink is disabled not only on my tablet but on my computer as a whole... and as for the driver update... when i do that my tablet doesn't respond... so i'm stuck with the old driver.... and yes i uninstalled and reinstalled the program many times.... @manongjohn what do you mean by Wintab driver?

**Comment by manongjohn** [comment] 2018-12-23 04:04
@Dasiaparks Wintab driver is another type of driver for digitizer tablets.  Not all drawing software supports Windows Ink.  WinTab driver should provide the pen pressure you are missing since you are using a version of OT without Windows Ink support.  Check your machine's manufacturer to see if they provide WinTab drivers for it.

I'm more curious what error you are getting with 1.2.1.  If you looked in Windows Event Viewer logs right after OT's crash, it might point to the problem.

**Comment by Dasiaparks** [comment] 2018-12-23 04:10
![screenshot 187](https://user-images.githubusercontent.com/46064382/50380725-1669fc00-0647-11e9-9be4-29a4be52dd84.png)
i'm getting this error with v 1.2.1

**Comment by Dasiaparks** [comment] 2018-12-23 04:10
@

**Comment by Dasiaparks** [comment] 2018-12-23 04:11
@manongjohn

**Comment by Dasiaparks** [comment] 2018-12-23 04:30
also i updated my driver and have wintab and still the pressure sensitivity is not working in Ot.... could it be something with the setting?

**Comment by Dasiaparks** [comment] 2018-12-23 04:34
@RodneyBaker I TRIED THAT AND IT STILL CRASHES

**Comment by RodneyBaker** [comment] 2018-12-23 04:38
Your keyboard may have issues too as it looks like your caps lock got stuck.

Have you read through the various topics in the OpenToonz forum where users with Huion tablets were having issues that got resolved?

https://groups.google.com/forum/#!searchin/opentoonz_en/huion%7Csort:date

**Comment by Dasiaparks** [comment] 2018-12-23 04:45
i'll have a read

**Comment by Dasiaparks** [comment] 2018-12-23 04:59
ok so i read through the page and i saw recommendations to turn off  windows ink, update the driver, go into preferences, or just reinstall OT. i have done all of this but my problem still remains. any more suggestions?

**Comment by Dasiaparks** [comment] 2018-12-23 05:04
in my event log i'm seeing this in reference to opentoonz
![screenshot 189](https://user-images.githubusercontent.com/46064382/50380923-aa8b9180-064e-11e9-8381-d73111038b39.png)

**Comment by Dasiaparks** [comment] 2018-12-23 05:17
i still don't know why the latest version (and the nightly) are crashing

**Comment by gab3d** [comment] 2018-12-23 05:30
another dumb question:
why is the opentoonz1.2.exe inside a OpenToonz 1.1 folder?
is that alright?


Em Dom, 23 de dez de 2018 02:04, Dasiaparks <notifications@github.com
escreveu:

**Comment by Dasiaparks** [comment] 2018-12-23 05:45
ok so i'm more confused... but here is how the lines come out using varying pressures... are there any problems with my settings?
![screenshot 191](https://user-images.githubusercontent.com/46064382/50381109-74511080-0654-11e9-91ba-42fc0e754884.png)

**Comment by RodneyBaker** [comment] 2018-12-23 06:38
As Gab3D points out... your installation directory states Opentoonz 1.1.
That suggests to me that you likely need to do a clean install because you very likely have some very old files gumming up the works.  This would extend to your stuff directory too and I'd recommend at least temporarily renaming that to make sure you get all fresh files.

There is an uninstall.exe file inside the Program Files directory where OpenToonz is installed.

Aside:  With two major issues being faced... one a crashing issue and the other a pen/pressure issue the most pressing of the two is the crashing issue.  I wouldn't spend a lot of time of the pen issue until I get the crashing issue resolved.

**Comment by Dasiaparks** [comment] 2018-12-23 06:58
ok so i renamed the installation directory but no change..
![screenshot 193](https://user-images.githubusercontent.com/46064382/50381482-8d5ebf00-065e-11e9-9070-040cac81866a.png)

**Comment by RodneyBaker** [comment] 2018-12-23 07:03
Renaming the directory isn't going to get the job done.

**Comment by Dasiaparks** [comment] 2018-12-23 07:06
so do i delete all traces of opentoonz then reinstall?

**Comment by RodneyBaker** [comment] 2018-12-23 07:17
While a rare occurence.... I almost never suggest such a thing.... unfortunately it looks to me like that is the stage you are at.

I suggest you rename the stuff directory at C:\Opentoonz 1.2 stuff
you an just add something like the word  "OLD" or "backup" or  the current date at the end.
The important thing being that when you install you will get a fresh stuff directory installed and all your settings will get refreshed as well.  If you have any scene files in the old stuff directory they are still there in the old renamed directory.

Also something to check is whether or not your Windows settings have you in Touch Mode or Desktop mode.   Desktop mode being more optimal for working with dedicated desktop applications such as Opentoonz that aren't optimized for touch.

**Comment by Dasiaparks** [comment] 2018-12-24 05:20
hello goodnight... soo i renamed the stuff folder, turned off touch mode, used the uninstaller from the directory to uninstall the program, and updated my graphics card driver... but still the crashing happens (ps it happened from the first time i installed the program..... the very first time)
this is how i renamed the directory files... did i do it correctly? 
![screenshot 195](https://user-images.githubusercontent.com/46064382/50391356-1e46a080-071a-11e9-912a-e0e447a04a20.png)

**Comment by RodneyBaker** [comment] 2018-12-24 05:51
The fact that neither of your stuff directories is named as it should be when installing suggests that no... you have not done something correctly.

**Comment by manongjohn** [comment] 2018-12-24 05:51
Unfortantely it appears there is an issue with OT 1.2.1 and your graphics card. However, it also appears there are other software out there that also crashes on the same dll of your graphics card that OT 1.2.1 is crashing on. 

I recommend searching online to see how others fixed their crash on that specific dll as it might also fix OT 1.2.1.

Sadly, if you cannot fix the crash on that dll and you cannot change your graphics card, it appears you are stuck on OT 1.1.3. The only way I think you'll be able to get pen pressure in 1.1.3 on Win10 is to get WinTab or Ntrig drivers working.

**Comment by Dasiaparks** [comment] 2018-12-24 05:53
ok thanks for your help and patience... i'll figure something out
