### ISSUE TITLE
Cannot save scene on project root

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#3821] opened 2021-03-25 12:28 UTC
**Describe the bug**
trying to save a scene in the root folder for projects gets a critical error

**To Reproduce**
1.create a project
2.save scene

**Expected behavior**
save the scene

**Screenshots**
![1](https://user-images.githubusercontent.com/36406840/112472662-29029c80-8d4c-11eb-9c65-8574cc82323d.png)

**Device Information:**
 - OS: windows 10
 - OpenToonz Version: 1.5rc
 - GPU: radeon rx 550
 - GPU Driver Version: 21

i am using the opentoonz stuff in a SSD

notes:
i can save the scene file in a custom location: i can save in an HDD, but not in a SSD

**Comment by shun-iwasawa** [comment] 2021-03-25 13:49
Unfortunately I couldn't reproduce the problem yet.

> To Reproduce
> 1.create a project
> 2.save scene

I wonder why the popup says that the current project is `sandbox` although you created a project at step1.

Just in case, do you have a write access to the destination folder?

**Comment by DarrenTAnims** [comment] 2021-03-25 17:12
In your screenshot, you haven't created a new project. It's still showing the Sandbox in the project dropdown. So it sounds like you've done something out of the ordinary. You can only create projects in the folders described as a project folder in your preferences.

**Comment by DarrenTAnims** [comment] 2021-03-25 17:19
In your screenshot, you haven't created a new project. It's still showing the Sandbox in the project dropdown. So it sounds like you've done something out of the ordinary. You can only create projects in the folders described as a project folder in your preferences.
If you're intentionally trying to create a scene in the sandbox and it's telling you that it can't save it then it's either a permissions issue (so you'll need to check if you have write access to that folder), or it's a virus program issue. You'll want to tell your virus program to ignore the Projects folder in your OpenToonz Stuff folder.

**Comment by manongjohn** [comment] 2021-03-25 17:28
I dont think the issue is the creation and use of a project or not. It's still trying to save to an apparently valid project...sandbox...but failing to.

The problem may appear be something related to saving to SSD mapped drives or mapped drives in general?

I say this because I've seen a few reports from users having trouble saving anything where they mention and a few of them mentioned an SSD drive.

**Comment by age3rcm** [comment] 2021-03-26 00:33
![OpenToonz_wVkFiBD6cY](https://user-images.githubusercontent.com/36406840/112560222-77965200-8db1-11eb-9d71-b46878d1a29c.png)
this is from a new project

and like DarrenT said, this is fixed if i deactivate the antivirus program

**Comment by age3rcm** [comment] 2021-03-26 00:34
yet, if i start the program as administrator, the issue still persists with the antivirus part

**Comment by age3rcm** [comment] 2021-03-26 00:38
i have added "exceptions" settings for the opentoonz stuff folder, and opentoonz install folder and also opentoonz aplication
now its possible to save without disabling antivirus

**Comment by RodneyBaker** [comment] 2021-03-28 00:10
Closing although I think it important to note that Antivirus software is causing some known issues that users have to learn the hard way.  I'm not sure how we can best educate them to anticipate problems and troubleshoot in cases where antivirus software is being overly aggressive which then leads to unexpected problems in Opentoonz.

**Closed by RodneyBaker** 2021-03-28 00:10 UTC
