### ISSUE TITLE
Open toonz needs a lot of work.

### ISSUE THREAD

**Issue by Bearleyart** [opentoonz/opentoonz#94] opened 2016-03-28 21:44 UTC
first of all. for me at least this update fixed the crashing on startup. but man this program crashes more times than flash.

you have to save in many steps or you will lose all your work. so I need to save the scene and each and every one of my levels?! Tedious.

Is it really that hard to make a "save all" button?! and just have it save the entire project?!

next I bring up the fact the program starts up with none of your basic tools showing! like WHAT!? WHY!? WHAT SENSE DOES THIS MAKE!?

even with auto saving I still keep losing work because every time I save I need to save all my levels and the scene,

and when you're working on 5 levels this makes an already tedious process like Animation ten times more frustrating!

all in all.,

 Make saving simple, have the tools up when you first start the program, ADD A BUTTON FOR THE ONION LAYERS!,

**Comment by odysseywestra** [comment] 2016-03-28 21:55
As much as we appreciate your honest feedback, this is not the place for reviews. Any general comments about opentoonz should be posted on our Google Groups page:

https://groups.google.com/forum/#!forum/opentoonz_en

We're sorry that you frustrated with using opentoonz, however it still in its infancy and I would like ask you for our patience as it's being worked on.

Closing since this is not a bug report.

**Closed by odysseywestra** 2016-03-28 21:55 UTC
