### ISSUE TITLE
undo in raster level happens in  different order

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1700] opened 2017-12-18 12:03 UTC
After drawing in raster level with mypaint brush the undo doesn't happen in order. example if i draw number 1 2 and 3 in that order when i undo the undo happens in 2 and then 1 skipping the 3 or part of 3 strokes
open Toonz 1.2.0. This happens randomly. Is there any solution   
window 10

**Comment by sksiebert** [comment] 2017-12-24 14:10
I think I have **similar struggles,** I'm currently working on raster levels with imported images. I'm rigging and making meshes and just doing a lot of things and I can't rely on undo anymore because either it decide to not work at all (as if it didnt save any action in contemporary memory), or it just goes back a random step, throwing off my entire routine, it doesnt't even undo the thing i last did, it just goes back to a random point of my WIP without changing the thing i originally did wrong.

e.g. i conntected all elements for rigging, after completing that i was busy moving all parts around. then i did 1 mistake and wanted to "undo". It undid my entire stafe schematic, but left the action i wanted to undo untouched. 

**Open Toonz 1.2, Windows 10**

A short-time temporary fix to the problem is saving and restarting OpenToonz completely. However, after a while the same problem occurs again.

**Comment by RodneyBaker** [comment] 2018-03-22 20:17
@bebinalpha and @sksiebert Is this is still an issue?

**Comment by sksiebert** [comment] 2018-03-23 15:46
For me it is still an issue It only happens for me with Version 1.2.0.
I've kind of gotten used to work around it by simply not using the undo function, but it does eat a lot of time and concentration.


 

Gesendet: Donnerstag, 22. März 2018 um 21:17 Uhr
Von: Rodney <notifications@github.com>
An: opentoonz/opentoonz <opentoonz@noreply.github.com>
Cc: sksiebert <sophiesiebert92@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [opentoonz/opentoonz] undo in raster level happens in different order (#1700)


@bebinalpha and @sksiebert Is this is still an issue?

**Comment by jpturcotte** [comment] 2018-03-23 16:19
@sksiebert If at all possible, could you try with the latest nightly, please? https://github.com/opentoonz/opentoonz/releases/tag/nightly (Disregard the date.)

**Comment by sksiebert** [comment] 2018-03-24 13:51
Hi,

I have tested the build quickly, with raster, vector Levels and imported images.
For the most part this works WAY better than before, I can use the undo function quite reliable. While testing, I had one raster layer with multiple Actions, which seemed to have a slightly messed up history

(1. 3 normal strokes
(2. Multiple dots (tried the raster brushes which still don’t seem to work for me for some reason)
(3. Some other lines)

The undo Action removed everything in order, but the dots (which were made with some of the brushes) were treated as a single object and removed all at once, instead of individually one after another .

Otherwise it seems to work fine! Thank you so much!


Von: J.P. Turcotte
Gesendet: Freitag, 23. März 2018 17:20
An: opentoonz/opentoonz
Cc: sksiebert; Mention
Betreff: Re: [opentoonz/opentoonz] undo in raster level happens in differentorder (#1700)

@sksiebert If at all possible, could you try with the latest nightly, please? https://github.com/opentoonz/opentoonz/releases/tag/nightly (Disregard the date.)

**Comment by artisteacher** [comment] 2018-03-24 17:26
@sksiebert - Are you trying to use the raster (Mypaint) brushes on a Toonz Raster level (green)? They only work on standard raster levels (blue).

**Comment by HighMountainShoeCobbler** [comment] 2018-06-22 19:06
I was told to add to this.  This is also happening to me, but on vector layers.  It undoes the step before the last step making it close to impossible to use.  Randomly.  I do not know if it was doing it on raster levels because I was using just OT Vector layers.

Win 7 64 Ultimate
OT 1.2.0

**Comment by manongjohn** [comment] 2018-06-23 14:10
Due to the randomness of this problem (I couldn't easily reproduce myself) it might help if as soon as this happens if you opened the History window (Ctrl-H) and send us a screen shot of it so maybe we can see what lead up to it.

If you are having frequent issues, you might want to have this window open while working. And if you notice an entry was not made and it should have, it wont undo. If you see it happen or maybe an Undo was created but still didn't undo, that might help us narrow it down, I think.

**Comment by HighMountainShoeCobbler** [comment] 2018-07-28 20:35
I have no idea.  The last release of opentoonz crashes on launch now.  I
can't even use the program.  I've had to switch to Adobe Animate!  😑

Sorry.  I was looking forward to trying it out too!

**Comment by artisteacher** [comment] 2018-07-28 21:14
@HighMountainShoeCobbler does [the latest nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly) launch? I would try a clean install (rename, move, or delete the old stuff folder before installing).

**Comment by RodneyBaker** [comment] 2020-01-03 22:53
Closing this as likely resolved and/or abandoned.
Original reporter has also deleted their github account.
Also, #1735 is currently still open which makes for likely duplicates.

**Closed by RodneyBaker** 2020-01-03 22:53 UTC
Labels: Needs Info
