### ISSUE TITLE
Crash with Plastic Paper

### ISSUE THREAD

**Issue by ricolandia** [opentoonz/opentoonz#1473] opened 2017-09-13 19:28 UTC
Hi! To explain it better, here is a screencast:
https://youtu.be/bfyaD2aTqFE

Tested in a 3rd machine. Same problem.
I've imported a bitmap > Use plastic paper to map it(first ) > use the bone tool to build structure > when I change it to animation mode..crashes( always )

Notebook1:
Ubuntu 16.04
core i3
4gb ram
Intel Graphics( default)

Notebook2:
Elementary OS LOKI (Ubuntu 16.04)
core i5
4gb ram
Intel Graphics( default)

Notebook3:
Xubuntu (Ubuntu 16.04 )
Pentinum Quad Core
4gb ram
Intel Graphics( default)

**Comment by manongjohn** [comment] 2017-09-14 03:05
I cannot reproduce this on a normal Windows build.  Might be specific to the Morevna build.

**Comment by morevnaproject** [comment] 2017-09-15 05:06
This is very similar to the issue I had with other Windows machine - #1199.

I will try to reproduce it on my Linux machines. Anyone else can help with testing on Linux?

**Comment by WPFilmmaker** [comment] 2017-09-16 10:32
@morevnaproject I tried to reproduce it on Lubuntu 16.04.2 but couldn't reproduce the step with the mesh as it shows a blank page: https://s26.postimg.org/4uq4l67wp/morevnaarm.png (the pic I used is a png with transparent background created in GIMP). I don't understand whether it is an issue with the PNG I used or a bug. Any idea?

@ricolandia can you provide the image you used?I will try with that and see if I can reproduce.

**Comment by morevnaproject** [comment] 2017-09-19 16:34
@WPFilmmaker Please make sure you have cell with image selected before you click "Create mesh". It glitches sometimes and wrong selection is set - this might be a reason why you get empty page.

I am using this image (build skeleton works) - 
![047-01](https://user-images.githubusercontent.com/332868/30603801-e3efec44-9d92-11e7-93c8-3b7486eb6b07.png)

**Comment by WPFilmmaker** [comment] 2017-09-23 14:39
@morevnaproject Thanks for the hint! You were right, I selected the Box and was able to see the Mesh. 

I tried to reproduce the crash but wasn't able, everything worked fine.

I am running OpenToonz 1.1.3 Appimage (Morevna Edition) on Lubuntu 16.04.3 on a 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz ,12GB of ram, GeForce 940Mwith the latest opensource drivers.

**Comment by ricolandia** [comment] 2017-10-14 01:28
Sorry for the late response. I was travelling( again ).
Well, I always have a crash. Now I am in a different machine.
Attached is a png file( the same happened with this one ).

**Comment by ricolandia** [comment] 2017-11-08 09:31
Hi Folks!
Sorry, the problem only happens with the appimage version.
I've tested again with 2 new ways:
1- using the GETDEB( .DEB file ), and it worked.
2- compiled from source, worked again.

So, the problem is really with the appimage version.

**Comment by olivi55** [comment] 2017-11-15 17:01
Hi everyone, I got exactly the same problem on a Windows 10 64bit with 1.1.3 version...it happens each time I click "Animate" after creating a skeleton on a mesh...it happens exactly the same way that how it happens in @ricolandia 's video

**Comment by morevnaproject** [comment] 2017-12-06 11:16
@olivi55 Please let me know - are you using official version or Morevna Edition?

**Comment by olivi55** [comment] 2017-12-06 16:46
@morevnaproject I think it's official version... What is Morevna Edition exactly?

**Comment by manongjohn** [comment] 2017-12-06 17:14
@olivi55 
I am still unable to duplicate this issue on a Windows 7 64 bit machine.  I even tried with the latest nightly (built Dec 6 2017)

Have you tried the latest nightly?

**Comment by olivi55** [comment] 2017-12-06 21:54
@manongjohn I didn't try the latest nightly yet...I'll try it tomorrow, this problem happens only on my University Club's computer...

I tried also some things to find where the problem could be...
I noticed that if I unlink the drawn object from its created mesh in the Stage Schematic, I'm able to do whatever as it would normally do with the mesh's skeleton and modifications are well applied to the mesh...but as soon as I connect again the mesh to the real object, it crashes instantly as if it couldn't apply changes from the mesh to the object.

**Comment by morevnaproject** [comment] 2017-12-08 16:35
> I think it's official version... What is Morevna Edition exactly?

@olivi55 The official version shows green splash screen at startup. For Morevna Edition the splash screen has violet color. Which color has your version?

@ricolandia I think the problem is something in between of QT version and your system drivers.

Please let me know the following information:

1. Videocard model and driver version (did you used standard OS drivers or installed the ones from Intel website?)
2. Version of QT your system uses.

Thank you!

**Comment by ricolandia** [comment] 2017-12-16 11:11
Standard drivers. The result on terminal is:
"3rd Gen Core processor Graphics Controller"

QMake and QT Version:
"QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu"

**Comment by olivi55** [comment] 2017-12-18 13:27
@morevnaproject ok I just checked, I'm using Official Version, and @manongjohn, the problem is still here with the new 1.2 version, plus the new problem of not having anything displayed in the viewer which I temporarily fixed using a [modfied version of the portable version](https://gumroad.com/l/ZgxH) but plastic tool crash problem is still there...

**Comment by morevnaproject** [comment] 2018-01-08 11:43
@ricolandia Can you please check if the plastic tool still crashes for you on the latest version? - https://morevnaproject.org/2018/01/08/opentoonz-morevna-edition-version-1-2-0-2/

**Comment by RodneyBaker** [comment] 2022-02-17 13:41
At over four years old... closing as likely resolved and/or abandoned.

**Closed by RodneyBaker** 2022-02-17 13:41 UTC
Labels: linux, needs info
