### ISSUE TITLE
Autosave causes problem when drawing

### ISSUE THREAD

**Issue by MisterABK** [opentoonz/opentoonz#1736] opened 2018-01-15 11:34 UTC
I have autosave on a very frequent setting (because of opentoonz's current stability issues!) When the autosave happens in the middle of of drawing a stroke, following the autosave the line drawing continues. Except I have invariably moved my wacom pen during the autosave, so when I start drawing again somewhere else, opentoonz draws a big line from the previous cursor position. It would be better if autosave simply terminated the line drawing.

A similar problem occurs when panning (using spacebar) or zooming (using the wacom pad) in the middle of drawing a line.

**Comment by RodneyBaker** [comment] 2018-01-15 18:48
The immediate workaround should be to set your autosave to save less frequently.
To narrow down the focus of this problem... How frequently do you currently have it set to save?

**Comment by MisterABK** [comment] 2018-01-15 18:53
I suppose that is a workaround of sorts, but the frequent autosaves were themselves a workaround for the software's instability. At one point, after a succession of crashes, I had it at 3 mins. It's less frequent now, but the problem with the line continuing to draw after panning suggests that there is an issue with drawing not terminating when it should. My workaround is just erasing the unwanted lines, which slows down work.

**Comment by RodneyBaker** [comment] 2018-01-15 19:36
Understood.  As we live in the world of open source workarounds will be the ongoing fix until such a time as the problem is resolved.  One of the things we as users can do to help move those things along is fully document the problems, identify potential workarounds and perhaps most importantly get our productions finished.  

Autosave itself is a recently added feature and every time a feature is added it increases the potential for unintended consequences such as what you are experiencing now.  This is unfortunate but part of the process.  I personally turned Autosave off because I didn't like being interupted and tend to rely on Save As and Save All where if I have never saved a Scene I'll Save As and name it appropriately and then later upon any significant change Save As again under a new name (usually a letter added to the end of the filename).  I then use Save All each time I get to the point of changing anything of significance... or just before rendering or when taking a break.... etc.  I love having Autosave available but prefer to be the one making the decisions.  And perhaps most importantly, since turning off Autosave I don't think I have lost any files.

While there are always exceptions to every rule I don't think it wise to ever set Autosave to anything less than 15 minutes.  This isn't to say that files shouldn't be saved during that time... but save them manually.  I'd be easy enough to check but I'm curious to see if the Autosave timer restarts at the time of manual saving of the file.

**Comment by xavzz** [comment] 2018-04-15 19:31
Sorry, guys, for bothering but this issue seems to be still open.. Have there been any changes? I deal with the same problem and followed the suggested workarounds but it still hurts to work this way..

**Comment by artisteacher** [comment] 2018-04-15 20:03
There was a fix in February for some of the tablet & brush behaviors. Autosave is now delayed until a stroke is completed. Using a tablet and autosave is still not perfect - at least in OS X. The menu sometimes becomes disabled and there still can be unintended strokes. If you haven’t tried [the latest nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly), it is worth giving it a try.

**Comment by RodneyBaker** [comment] 2018-12-04 01:21
@MisterABK Does this problem persist with the current nightly builds?
I confess I almost never use the autosave feature (I save manually ever time I get to a point where it make sense to save such or wherever I naturally pause) so I'm not the ideal person to review this.

**Comment by MisterABK** [comment] 2018-12-04 09:49
I tried to test it, but I'm afraid the nightly build messed up the FX
schematic on the project I'm working on, so for now I'd prefer to wait
until there's a stable build to test.

**Comment by artisteacher** [comment] 2018-12-04 13:18
How did it mess up the schematic? There have been several updates to the schematic - #2034, #2191, #2192, #2196, #2241. Some of the changes require updating at least the style sheet - I recommend renaming the stuff folder when you install so that everything is up-to-date.

**Comment by MisterABK** [comment] 2018-12-04 13:23
FX nodes were no longer visible. This might be a deliberate change that I
misunderstood, but while experimenting I deleted a column and Opentoonz
froze.  I couldn't force quit. I had to restart the computer, so I thought
it would be better not to work on a current project in the nightly build

**Comment by manongjohn** [comment] 2018-12-04 13:55
When the Fx nodes disappeared, did you try to recenter and/or fit to window buttons? Did they come back after you rebooted.

I know there was an odd issue (still open) where empty columns in the spreadsheet somehow caused the nodes to disappear. Had to remove all empty columns then rearrange/fit to window for them to come back.

**Comment by MisterABK** [comment] 2018-12-04 14:07
I reinstalled 1.2.1 straight away after the crash, I'm afraid.

This is what my FX Schematic looks like in 1.2.1

![image](https://user-images.githubusercontent.com/35302593/49447137-aac20b00-f7cd-11e8-8583-827310774a8c.png)

I just reinstalled the nightly build linked above and this is what the Schematic looks like:
![image](https://user-images.githubusercontent.com/35302593/49447039-6e8eaa80-f7cd-11e8-9f68-256298cd7387.png)

The FX nodes are still being applied though, I just can't see them.

**Comment by manongjohn** [comment] 2018-12-04 14:34
The bottom image is the Stage Schematic View, switch it to the Fx Schematic by clicking the bottom right button on schematic viewer.

**Comment by MisterABK** [comment] 2018-12-04 15:07
I see! I thought it was probably me being confused, but I didn't want to
risk replicating the crash in case I damaged the project.

**Comment by RodneyBaker** [comment] 2018-12-11 21:58
This topic has drifted from being a problem with drawing while using Autosave to one with a focus on issues in the Schematic.  As there are several reports (and PRs!) open on those and other issues related to Schematic as well as several related to Autosave this may be a report that can close.

We'll leave it open as a primary report for issues deemed related to Autosave.
Please refer to other issues for those dealing with Schematic.

**Comment by RodneyBaker** [comment] 2019-01-08 16:40
Closing pending additional research and development of issues with Autosave as a general category.

**Closed by RodneyBaker** 2019-01-08 16:40 UTC
Labels: Bug, UX Enhancement
