### ISSUE TITLE
Function Editor: Ease In / Ease Out labels inverted?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2710] opened 2019-08-17 03:52 UTC
https://opentoonz.readthedocs.io/en/latest/editing_curves_and_numerical_columns.html#using-ease-in-ease-out-interpolations

![function_editor_iEase](https://user-images.githubusercontent.com/18104091/63206314-90446f00-c088-11e9-8885-854b841598b8.png)

In the Function Editor, Interpolation area, by the best of my knowledge, the text labels for the Ease In and Ease Out value fields are inverted. (both for Ease In/Out and Ease In/Out % interpolations).
I mean, the first value is really **Ease Out**, and the second one **Ease In**, even though the labels say otherwise.

Ease In = an easing (deceleration) when the time is approaching the end of a segment (or the last keyframe of it). That's why the "In", because the time is progressively entering the realm of that keyframe.

Ease Out = an easing (acceleration) when the time is going out of the beginning of a segment (or the first keyframe of it). That's why the "Out", because the time is progressively leaving the realm of that keyframe.

That's the way all other animation software use those terms. 🤔

**Comment by RodneyBaker** [comment] 2019-12-30 02:48
Relates to #2929

**Comment by RodneyBaker** [comment] 2020-01-15 21:08
I was under the impression the inverting of ease was resolved.
@gab3d Can you confirm?

**Comment by manongjohn** [comment] 2020-01-15 21:36
This was not fixed by #2929.  This request is a label change to read "Ease Out/In" instead of "Ease In/Out".

In #2929, there are 2 separate eases "Ease In" and "Ease Out", but the actual easing drawn was backwards so I had to fix the easing to match the direction.

Keep in mind there are 3 different types of easing in our software.  "Ease In", "Ease Out" and "Ease In/Out".  There is nothing wrong from drawing "Ease In/Out" other than the label describes it backwards.

**Comment by RodneyBaker** [comment] 2020-01-15 22:09
So, is it safe to answer this reports question (in title) in the negative?
I don't know of any plan to change the current order as the use of 'in' preceding 'out' is the norm and generally preferred.  The use of 'Ease Out/In' would therefore be confusing.

I suppose the underlying question I'm asking is... can this issue be closed?
If not, what is a reasonable way forward?

**Comment by manongjohn** [comment] 2020-01-15 22:39
Put it to a vote?

React on this specific post with
👍 = Yes. Change It
👎 = Leave it as is
Any other reaction = Doesn't matter to me

**Comment by RodneyBaker** [comment] 2020-01-15 23:01
Thanks @manongjohn 
I voted but more out of desire to move the issue forward than anything else although... not trying to weasel out here... my vote does express my personal preference.

We may want to chart a course in the future for those where a vote doesn't go in a preferred direction... which is going to happen.  For example:  We can strive to identify in the application, preferences, config, qss/less, code, etc. where the desired change can still be effected.  In this way all users, especially those who build their own releases or know someone willing do build a variant can achieve their personal goals.

Part of this on my part is also a desire to not see issues/reports remain open and stagnate without good reason.
Closing of an issue/PR does not mean the issue cannot be reconsidered at a later time.
It could be that the time is just not yet right or practical for implementation.

**Comment by beeheemooth** [comment] 2020-01-16 00:04
@manongjohn you must be kidding, I can not put a dislike on your comment. :)

By the way, I often ask myself the question: why is there an "Ease In / Out", but no "Ease Out / In"? This is like discrimination for interpolation. ^_^

**Comment by gab3d** [comment] 2020-01-16 15:46
@RodneyBaker @manongjohn 
I've just read this one.... 
This request is not about writing *Ease Out/In*, instead of *Ease In/Out*, but about inverting the labels shown in the first screen shot.
Which are still effectively inverted, as I tested yesterday while translating the last string changes.

In fact, yesterday I had to translate them badly (inverse to what they actually mean) on purpose, so at least in the Spanish UI (which is what I can control) it will show them in the correct order [in the Function Editor] 
So, now, whenever this gets fixed, I'll have to fix my translation too. 😅

To make it clearer: 
what the UI should look like in the Interpolation area of the Function Editor is this:
![Easing](https://user-images.githubusercontent.com/18104091/72539449-134b3a80-385e-11ea-91e8-794d0da69f40.png)

**Comment by manongjohn** [comment] 2020-01-16 15:58
So you want to only change "Ease In / Ease Out" to "Ease Out / Ease In" but leave everything else as "Ease In/Out"?    "Ease In/Out is just a shortened version of "Ease In / Ease Out".  It would be rather inconsistent if they didn't show the same thing.

**Comment by gab3d** [comment] 2020-01-16 16:36
ermmm... I don't know if we're talking the same things here, and don't want to add more confusion 😱

please let me express it in the most explicit way that I can currently think of:

1. Firstly, I'm talking only about the Function Editor Interpolation section in this Issue.
2. I don't have any sort of problem with **Interpolation dropdown menu names**, and the way they are written. That includes specially the one that is shown in the above screenshot "Ease In / Ease Out" (even if it was written in the more compact for: "Ease In/Out", it'd be the same). 
I find it when both In and Out words are present in a title, the most *easy to read* way to put them is putting *In* first and then *Out*. And is also the way I find them written in most other software too.
3. For the two individual parameters shown to control the "Ease In / Ease Out" interpolation type. I think the correct order to show them is to show first (above) the one that affects the moment in time that comes first, and then the one that affects the later moment. So concretely in this case they should be shown as **Ease Out** (above) and **Ease In** (below). And again, that is the most usual way I've seen them presented in most other software I've used.

Sorry if there were so many words for something that perhaps was already clear, but I wanted to explain myself in the most unobscure way possible. 🖖

**Comment by artisteacher** [comment] 2020-01-16 16:59
I always thought that ease in was supposed to be for accelerating while ease out is supposed to be for decelerating. When using ease in/out for web design and in Adobe Animate, that is how it works. Doing a Google search, I've seen conflicting information on what the terms are actually intended to mean for animators. 

As a native English speaker, I automatically associate the words "ease in" with something like "slow enter" or "start slow". If something is starting slowly, the logical progression is that it will accelerate. In the same way, I automatically associate the words "ease out" with "slow exit" or "end slow". If something is ending slowly, it makes sense that it would be decelerating. Reversing the terms just doesn't make sense to me.

**Comment by manongjohn** [comment] 2020-01-16 17:00
We are talking about the same thing, in my opinion.

At the end of the day that dropdown option is doing what most software label as "Ease In/Out".  The difference here is it is labeled in a very wordy way, whereas in other areas of OT it's just truncated to use In/Out, most likely to save horizontal space like on toolbars and context menus.   So changing it here would be inconsistent to how that interpolation method is labeled elsewhere in OT.

Would it just be easier to relabel the Function Editor option to "Ease In/Out" to be consistent with the rest of the application?

[ASIDE] Why don't also have just "Ease In" and "Ease Out" options?  We do for Auto-Inbetweens and Brush Range function...why not for the animating?

**Comment by manongjohn** [comment] 2020-01-16 17:56
@artisteacher There is definitely conflicting information for Ease In and Ease Out on the net,  It gets even more confusing when they also explain Ease In/Out as a 3rd easing option. It took me a bit to get it straight in my head.

If you go by the Animator's Survival Kit (the Holy Grail for Animators?), then Ease Out is basically acceleration from stop (start slow, end fast), and Ease In is deceleration to stop (start fast, end slow).

Based on that the "Ease In/Out" interpolation option which is both in 1 action is technically labeled backwards for what it is actually doing. Even explanations on-line typically show the action as Ease Out followed by Ease In, but we all still say Ease In/Out anyway.

**Comment by gab3d** [comment] 2020-01-16 18:19
@manongjohn 
As I see it, 

1. The concept of what is *Ease In* (a slow ending of a segment motion), and *Ease Out* (a slow start of a segment motion) is now uniformly used throughout OT, the only discrepancy I find now is in the order of these two labels here in the Function Editor.

This image is the result of *Ease In* and *Ease Out* applied in Auto-inbetween, which is consistent with the concepts of *In* being a smooth ending, and *Out* a smooth beginning :
![imagen](https://user-images.githubusercontent.com/18104091/72550776-367fe500-3872-11ea-9c90-67523c44599c.png)


2. The other issue, is that saying "Ease In/Out" (instead of the more real Ease Out/In) could be seen by a purist to not be correct. But in this case I favor nice wording over technical correction for a function that anyways will be doing both things, an accelerarion and a deceleration).

@artisteacher 
To me you're assingning contradicting meanings to each term:

> "ease in" with something like "slow enter" or "start slow".
> I automatically associate the words "ease out" with "slow exit" or "end slow".

It's certainly not the same to "enter something in a slow fashion (or slowing down) thn to start something in a slow maner. in fact in one case (the correct one to me) there is an action that is ending, while in the other one there is an action that is starting.
The same, but in reverse applied to the meanings you assing to the ease out concept.

So which one is the correct here, because both of them can't be, in this context? 💁‍♂️
To me the correct are the ones which you mention in first term, in each case.

**Comment by manongjohn** [comment] 2020-01-16 19:46
@gab3d I think we're on the same page in terms of the definitions and what OT is doing in terms of executing the 3 different types of interpolation.

As I see it these are the options
1. Leave the labels as is and do nothing
2. Change just the Function Editor label to `Ease In/Out` to match the label that is used everywhere for this specific type of interpolation option
3. Change all versions and variants of Ease In/Out to Ease Out/In to be consistent technically and visually throughout the application.

I suppose whatever we decide here should also apply to Ease In/Out % option.

If I had to change anything, I'd go with Option 2 otherwise I'd prefer Option 1.

**Comment by gab3d** [comment] 2020-01-16 20:29
@manongjohn  
> I think we're on the same page (...)

hehe, not quite sure yet, let's see.. 😸 
(again, sorry if it's me that it's not understanding what you mean)

But, taking your 3 options as a guide:
(1) No
(3) No

(2) 
>Change just the Function Editor label to Ease In/Out to match the label that is used everywhere for this specific type of interpolation option

My answer would be also: No. 

What I think should be changed is what I try to show in this picture:
![Easing_new](https://user-images.githubusercontent.com/18104091/72560011-e2323080-3884-11ea-8ce7-572f11d4324e.png)

That is: The position of the labels describing what both of these parameters represent. (Not changing the position of the parameters themselves onscreen, but just their displayed names).
With that we restore coherence throughout the program.

> I suppose whatever we decide here should also apply to Ease In/Out % option.

I agree on this

**Comment by manongjohn** [comment] 2020-01-16 21:04
Lol.  Ok. So Drop downs stay the same, and it still says Ease In/Out everywhere.  You just want to switch the Ease In and Ease Out edit boxes within the pane.  Got it (this time...I hope...).

Should just posted that image to begin with. :P

Might be a smidge more than just a label change. The labels can be switched, but do the edit boxes also need to be switched?  Does the top box actually control Ease Out already?  More than likely it is controlling Ease In so it will also need to be switched.  Either way, not a difficult change.

So in similar vain...

For Speed In/Out, I'm assuming `First Speed` is the same as `Speed Out` (as in moving away from something) and `Second Speed` the same as `Speed In` (as in moving towards something).  Or is it actually backwards? In such case, the labels can stay the same, but the edit boxes need to be switched.

**Comment by gab3d** [comment] 2020-01-16 21:19
> Lol. Ok. So Drop downs stay the same, and it still says Ease In/Out everywhere. You just want to switch the Ease In and Ease Out edit boxes within the pane. Got it (this time...I hope...).

🎉 🎆 🎈 😂  yes, that's it.


> Should just posted that image to begin with. :P

yeah, most probably.

> The labels can be switched, but do the edit boxes also need to be switched?

please no. if you also switch the edit boxes we're on the same boat again.
the edit boxes are in the correct place, but the labels doesn't describe the correctly, that's the problem.

you can mentally replace "ease out" --> "acceleration", and "ease in" --> "deceleration". 
with this in mind, think of what you use the edit boxes for, and you will see the first edit box (the upper one) is controlling an acceleration, from the start of the segment onwards (but it says "ease in", and that would be "deceleration", well, that's the problem).
the same happens with the other one...

so, boxes are correctly placed, but with wrong names besides them.

**Comment by gab3d** [comment] 2020-01-16 21:35
> For Speed In/Out, I'm assuming First Speed is the same as Speed Out (as in moving away from something) and Second Speed the same as Speed In (as in moving towards something). Or is it actually backwards? In such case, the labels can stay the same, but the edit boxes need to be switched.

I think those names are correctly placed, as *first* and *second* are properly describing their order in the segment. In fact, I've translated them in Spanish as "Initial Velocity" and "Final Velocity" to try and be a little more descriptive, but that doesn't change the concept radically either.

On a side note: To me, all the numeric values in the Speed In/Out interpolation type are rocket science, and don't expect any normal user to be using them, but just use the tangent handles instead, to control them. In fact, in Spanish I labeled that interpolation type as *Bezier*, because I couldn't figure out anything meaningful if I respected the "speed" concept, the name refers to. 💁‍♂️

**Comment by manongjohn** [comment] 2020-01-16 21:42
I took a quick look.  The Ease In and Out labels are definitely backwards for what the edit box is coded for.  Guess it's technically a bug since it's not doing what the screen says it should be doing?

At any rate, the 2 line change would update both Ease In/Out and Ease In/Out % interpolations at the same time since it uses the same code. I'll submit a PR this evening to switch the labels as it is definitely wrong.

The Speed In/Out labels and boxes are correct and do not need to be changed.

**Comment by beeheemooth** [comment] 2020-01-16 22:04
@gab3d what problems? You can write these words in the Spanish translation on the contrary ;) it seems that I did it in the first translation ^_^

**Comment by gab3d** [comment] 2020-01-16 22:09
@shun-iwasawa 
Please, in time I'd need to know if this PR would go in v1.4, as in that case I'd have to correct that two strings in my latest translation too.

**Comment by manongjohn** [comment] 2020-01-16 23:21
@gab3d I can switch the translations in the .ts file and regenerate the qm file and include it with my PR

**Comment by gab3d** [comment] 2020-01-16 23:39
@manongjohn 
totally! that'd be just awesome
thanks!!

**Comment by shun-iwasawa** [comment] 2020-01-17 00:49
> @shun-iwasawa
> Please, in time I'd need to know if this PR would go in v1.4, as in that case I'd have to correct that two > strings in my latest translation too.

As @manongjohn pointed, I confirmed the labels are used as opposite of what is named in variables to be controlled. (Digital Video may have swapped the labels on purpose in order to make it intuitive.)
It's too late for the release candidate which I'm about to release, but I think it can be directly included in v1.4 official release. It will not affect other functionalities as long as the changes are done only in the labels.

**Comment by artisteacher** [comment] 2020-01-17 03:41
Thanks @gab3d and @manongjohn for the clarification. I want to make sure I can explain this clearly to my students, so that they can catch on more quickly than I have 🙃

Would this be correct?
Ease In = ease in from speed = gradually decelerate to stopped position
Ease Out = ease out to speed = gradually accelerate from stopped position

**Comment by manongjohn** [comment] 2020-01-17 03:52
@artisteacher Yes. That is correct.

**Closed** 2020-01-22 13:58 UTC
Labels: UI, bug
