### ISSUE TITLE
Selected column does not highllight in FX schematic

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#4696] opened 2023-01-05 19:47 UTC
### Description

![creega1_ Creega __OpenToonz_1 6 OpenToonz_hAqihxux13](https://user-images.githubusercontent.com/36406840/210866959-e204a520-609d-4136-b9ce-05c319b11105.png)

### Steps to Reproduce

1. select column
2. try to find on fx schematic

### Screenshots, Video & Crash Logs

![creega1_ Creega __OpenToonz_1 6 OpenToonz_hAqihxux13](https://user-images.githubusercontent.com/36406840/210867183-bbbb053b-0c82-407b-bb50-e1f3b123aed5.png)

### OpenToonz Version

1.6

### OpenToonz Version Information

29 december 2022

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment] 2023-01-19 20:03
This report is (mostly) a duplicate of #4514 although it nat point more directly to the underlying problem.
Will keep both open for the present.

**Closed** 2023-03-31 14:33 UTC
Labels: bug
