### ISSUE TITLE
Undo's Issue OSX

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1804] opened 2018-02-14 18:11 UTC
I cannot reproduce when it happens, because it seems random, but sometimes when I try to undo a previous action with CMD+Z a message appears: "No more undo operations available".
When that happens, I cannot undo any previous action.

Thanks!

**Comment by shun-iwasawa** [comment] 2018-02-15 02:45
For now the undo will be cleared when saving level.
This behavior was implemented reflecting a request from Ghibli staffs but I'm thinking it can be preference-optional.

Please let me know if you faced the issue under any other situations.

**Comment by DotSilva** [comment] 2018-02-15 09:26
Ok. Because I am learning how to use OT and have certain expectations of how things would behave (based on other software), some features might be perceived as issues. Thanks for the detailed explanation. Now I know why it happens.

**Comment by RodneyBaker** [comment] 2018-02-15 15:08
A possible workaround...

Undo itself may be cleared upon saving a level but I don't believe the Undo History itself is released or cleared.  Therefore we should be able to use the History window to dial backwards and forwards to where we wish to have the project state.

To test, just open the History window via Windows>History and compare what is available after saving via Undo and via the History Window.

I'm more of a fan of History than Undo as the former provides a better view on what is actually happening with Undo/Redo.  Users than rely heavily on Undo/Redo should consider using the History window as it can transform 'mistakes' into purposeful operation.

**Comment by DotSilva** [comment] 2018-02-15 15:49
I never have opened the History window but now I see how it can be very useful (thanks Rodney). I have, however, some additional thoughts (after testing it more insightfully):

1) When I save a Level, the History resets and I lose all the previous operations;
2) The message I randomly get ("No more undo operations available") usually happens after a 'Save All', and I don't usually save only a Level.

Is it the normal behaviour?

**Comment by RodneyBaker** [comment] 2018-02-15 16:14
> When I save a Level, the History resets and I lose all the previous operations;

That may be normal behavior.

In the test that I just ran before posting the History didn't clear upon saving... so that is why I thought it might be an option.  This is an area we can look into a little more in that I used Save Scene and then Save All in my test.  I did not specifically use Save Level.  That may be the difference?  No, I don't think so.  When I 'Save All Levels' manually the history doesn't clear and still allows me to Undo.

*I think* HIstory is per session.
When I save and then reopen the History is reset.

So, a question:
Is you History clearing immediately after Saving or does it clear upon loading a scene?
If it is clearing then we might be seeing a difference with the Undo process between PCs and Macs.

Hmmmm..... On a PC I seem to be able to access Undo/Redo as well as History until such as time as I refresh the Scene in some way (such as via reloading).

This leads me to think the restriction might only be implemented for Macs.
Perhaps that is what Ghibli used.

**Comment by DotSilva** [comment] 2018-02-16 13:51
Ahhhh! Finally, after a lot of testing and using the History Panel (very handy indeed!), I've discovered why the History suddenly resets: when I 'Create Mesh' with the Plastic Tool! It always resets the previous history operations.
Because I never 'Save Level' on its own (I always use the 'Save All' and that doesn't reset history), I found it a bit strange why it was happening. Hope it helps!

**Comment by artisteacher** [comment] 2018-02-16 13:57
Maybe that behavior is due to the fact that plastic deformed drawings cannot be edited?

**Comment by RodneyBaker** [comment] 2018-02-16 13:58
Interesting.
I wonder if that could be considered a bug.
It certainly does not seem that clearing History would be an intentional desire of Creating a mesh with the plastic tool.

**Comment by artisteacher** [comment] 2018-02-16 21:37
I would definitely consider it a bug! It could have been a deliberate coding choice to prevent modifying the plastic level, but even so, clearing the history for all levels seems overkill and undesirable. A better behavior would be for creating a mesh to be added to history. Then returning to a step before the mesh was created would result in the mesh being removed from the Xsheet - also returning the mesh to an editable state.

Does history reset after making a plastic mesh in other OS?

**Comment by RodneyBaker** [comment] 2018-02-16 22:26
> Does history reset after making a plastic mesh in other OS?

I can confirm that on Win 10... yes... History does clear/reset upon creation of plastic mesh.

**Comment by RodneyBaker** [comment] 2018-03-22 17:21
Just adding a note to say...

Currently I'm observing that History doesn't clear upon any saving (in Win 10) whereas I was thinking it did (at least for Level saves).

I'm curious if this is something new because I thought it did reset.

Regardless, I'm liking that it does not reset!
(need to do more testing)

**Comment by RodneyBaker** [comment] 2018-12-11 18:33
Closing this as the original Undo issue is resolved and OPR deleted their github account.
Additional improvements and enhancements to Undo and History can be expected in the future.
Please post specific bugs related to Undo and/or History as new issues as they are identified.

**Closed by RodneyBaker** 2018-12-11 18:33 UTC
Labels: OS: MacOS
