### ISSUE TITLE
(WIP) Command Bar missing icons. [$45]

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2111] opened 2018-06-28 16:28 UTC
### Issue Summary

The bar of commands is a great tool very practical, in the different wishes expressed in #1526 for its improvements, I personally think that the most urgent it is to give him the missing icons. I open a bounty for this purpose because there are many and we end up with a very long command bar with the names of the commands instead of icons. It would be great to be able to give it icons that fit in the current coherence.

**Comment by openanim** [comment] 2018-06-28 16:35
I opened the bounty https://www.bountysource.com/issues/60247847-command-bar-missing-icons

**Comment by artisteacher** [comment] 2018-07-03 12:20
As there are a lot of commands without icons, this will probably take a few rounds. What commands should have the highest priority? If everyone can share the commands they use in the command bar that are missing icons, that will give a good direction to start with - especially if there is overlap. 

Personally, I’d like to see:
- each 2
- each 3
- each 4
- clone
- delete
- remove unused levels
- insert multiple keys
- remove multiple keys

**Comment by artisteacher** [comment] 2018-07-03 12:34
I completely agree, if there are existing icons being used for the same commands elsewhere, they should definitely be used for the command bar.

**Comment by openanim** [comment] 2018-07-03 13:19
I agree too, it seems obvious to me to stay consistent.

the commands that I use the most or I’d like to see are

- enter group
- Exit group 
- ungroup
- group
- bring to front
- bring forward
- send backward
- send back
- zero thickness
- fill check
- gap chek
- remove vector overflow
- new note level
- add frames
- palette
- style editor
- schematic
- output settings

**Comment by artisteacher** [comment] 2018-07-03 17:09
On a related note, I really think “send back” really should be “send to back” for consistency & clarity.

**Comment by RodneyBaker** [comment] 2018-07-03 21:20
@artisteacher said:

> On a related note, I really think “send back” really should be “send to back” for consistency & clarity.

I am in agreement with you here as 'Send back' and 'Send to Back' might appear to be different things and the latter would convey what is happening more accurately.

'Send back' as a terminology actually means 'Send Backward' as in move the selection one step further away from the top toward the back of the stack.  But that's not the intention of the process that will be launched when 'Send Back' is triggered.
'Send to back' more obviously means push the current selection all the way to the end of the stack.
'Send Backward' does convey pushing the current selection toward the back.  It doesn't intrinsically carry with it the sense of moving only one step but that can easily be discovered by the user.

Having the 'Send to Back' terminology mirror that of 'Bring to Front' would also be appropriate.

Good idea.

**Comment by artisteacher** [comment] 2018-07-04 03:43
I've started with a few of the icons. If anyone has suggestions to improve them, please chime in.
![potential_new_icons](https://user-images.githubusercontent.com/21159116/42255404-8e4ba18e-7f19-11e8-9aec-7f885d8729c6.png)
1. New note level
2. Remove unused levels
3. Each 2
4. Each 3
5. Each 4
6. Group
7. Enter Group
8. Exit Group
9. Ungroup
10. Insert Multiple Keys
11. Remove Multiple Keys
12. Bring to Front
13. Bring Forward
14. Send Backward
15. Send to Back

**Comment by artisteacher** [comment] 2018-07-05 02:05
<img width="160" alt="screen shot 2018-07-04 at 10 03 55 pm" src="https://user-images.githubusercontent.com/21159116/42298883-3adc090e-7fd6-11e8-8a45-f67dcf7c67f0.png">

16. Fill check
17. Gap Check
18. Remove vector overflow

**Comment by openanim** [comment] 2018-07-10 12:19
@artisteacher 

Thank you for these icons :)  If I have to do a feedback about that, here's what I think :

I'm not sure that should be taken as an improvement. It's more of a personal feeling. I think that the prohibition sign is not the most appropriate to designate "remove" at least that's not what it first evokes me. Maybe try to see if an alternative will give a better result. Why not try with a cross or just the bar of your sign without the round for exemple.

fill check seems to me too close to the normal fill icon, with a risk of confusion. Maybe propose an alternative too. Like showing a geometric shape closed and not closed, an eye in combination of the bucket can be possible tracks. Note that these are just ideas, I'm not sure it will be better.

After like that was said above, the main thing is that an icon is available, it can always be improved, redesign etc if necessary later. 

I will also add 3 commands. insert above / after ,  insert below / before and fold column that already has some kind of icon.

**Comment by artisteacher** [comment] 2018-07-13 03:46
Alternate versions of remove unused levels and remove multiple keys:
<img width="126" alt="dd84ee7b-83d7-4482-877e-d7cee2fbadc0" src="https://user-images.githubusercontent.com/21159116/42671395-bb192e64-862d-11e8-99d6-9f58ab70c2b0.png">
<img width="106" alt="3f0d9a80-3a67-42a4-b42a-dc357881e6cb" src="https://user-images.githubusercontent.com/21159116/42671396-bb32e7d2-862d-11e8-859e-76d1eeb8185b.png">

**Comment by artisteacher** [comment] 2018-07-13 04:00
Fill check take 2:
<img width="93" alt="c8336889-30af-40ca-8425-e14954fe3579" src="https://user-images.githubusercontent.com/21159116/42671643-13d6ccea-862f-11e8-9adb-2b1ecc5fdcb9.png">

Any suggestions for zero thickness, insert above/after and below/before?

**Comment by openanim** [comment] 2018-07-13 17:56
Thank you for these alternatives. Sorry but I did not understand the meaning of your sentence "fill check take 2" does this mean that the two icons are for fill check?

If so, I thought the right icon was for gap check I confuse? Which seems to me so well.

Some additional suggestions.

Still about gap check, why not add a magenta or other line in the small gap to show its activated state ? But personally, I like how it is now, too.

![gap checkpng](https://user-images.githubusercontent.com/29790512/42704661-07b941c0-86d1-11e8-90e2-e31a1a308693.png)

I also like fill check like that, after staying on your initial idea, maybe the addition of a geometric shape behind the fill icon as in the example below, may also be appropriate ?

![fill check](https://user-images.githubusercontent.com/29790512/42704721-3ba24996-86d1-11e8-89a5-3d3f472c9ae4.png)

Regarding remove. It is true that compared to your first version, it is difficult to see that these are keys. What if you removed a bar to get something like that or made the cross smaller in a corner at the top or bottom of the keys like the little check symbol you made ?
![sans titre](https://user-images.githubusercontent.com/29790512/42704838-af39f4d0-86d1-11e8-9123-75bc0b9d6c92.png)
![remove key](https://user-images.githubusercontent.com/29790512/42704809-96c5dafe-86d1-11e8-9dd3-f034e62bf613.png)
About Zero thickness, why not make a shape with a continuous or discontinuous line in zero thickness inside or use the pump tool with an eye somewhere and a line ?

For insert commands, I think we can use the icons close to what you did with each commands. By adding arrows to show where this is done. Or the possibility of shifting to the right / left of the column to show the effect that will occur, as is the case with MS software. What do you think ?

![insert colomun](https://user-images.githubusercontent.com/29790512/42705348-4d3daafe-86d3-11e8-911b-0f63b699712b.png)

![exeample insert](https://user-images.githubusercontent.com/29790512/42705007-358ba7ea-86d2-11e8-9759-997afcc089fb.png)
![insert colomun_2](https://user-images.githubusercontent.com/29790512/42705065-68089174-86d2-11e8-85be-fdcf3deb1ef8.png)

Others additional suggestions, are welcome.

**Comment by openanim** [comment] 2018-07-13 18:04
Another suggestion ![insert colomun3](https://user-images.githubusercontent.com/29790512/42706662-dfb8d526-86d7-11e8-8298-436e6eb273a0.png)

**Comment by artisteacher** [comment] 2018-07-13 19:16
Take 2 means attempt #2. The first icon is for fill check and the second is for gap check. I”ve been hesitant to add magenta to the gap check icon as the rest of the icons in the command bar are monochromatic. 

Thanks for the suggestions. I wasn’t sure if the insert commands could use different icons. Making 4 icons is certainly easier for that then just 2.

**Comment by openanim** [comment] 2018-07-13 19:38
Thanks for the precision, I think for gap check we can leave as your first version too.  Or we can do like some icons that changes depending on whether the command is activated or not. An additional suggestion, very fast, for both insert / xsheet timeline.
![both ins](https://user-images.githubusercontent.com/29790512/42710571-d03941a0-86e4-11e8-8d27-74b6dbdeb627.png)

**Comment by 711GM** [comment] 2018-12-07 10:20
Why don't we discuss icons anymore?

**Comment by artisteacher** [comment] 2018-12-07 13:12
Sorry, I got caught up in the start of the school year. I'm actually moving this month so I don't have time to make more progress at the moment. I can upload the icons that I made if someone wants to do the coding side.

**Comment by RodneyBaker** [comment] 2018-12-07 21:04
@711GM said:  > Why don't we discuss icons anymore?

We do discuss icons.
The person working on this one stopped working on it however.

What would you like to discuss about icons?

**Comment by artisteacher** [comment] 2018-12-08 01:18
Here you go! I've added "show zero thickness", "add frames", "insert above/after", and "insert below/before". Several icons have 2 versions. All of the file names describe the command the icons should be used for. A few of the proposed icons are still missing, but the majority are here.
![icons](https://user-images.githubusercontent.com/21159116/49679821-41a3f700-fa5c-11e8-9bb4-baf5b687ed04.png)
[Icons 2018.zip](https://github.com/opentoonz/opentoonz/files/2659230/Icons.2018.zip)

**Comment by openanim** [comment] 2018-12-21 20:35
When it's good, do not forget to claim the bounty, Artisteteacher.

**Comment by manongjohn** [comment] 2019-03-03 03:12
If we're good with the icons that have been provided so far, I can certainly implement them and start the PR for it. Just give me the word.

Possible suggestions for those without icons:
Palette - Artist's painting palette
Style Editor - Artist's painting palette with a pencil, brush or digital pen perhaps?
Delete - Trashcan
Fold Columns - 3 columns made to look like a partially folded pamphlet.  Maybe make it diagonal to represent either xsheet or timeline?
Schematic - 3 small squares in some formation with a line connecting 2 squares to 1.
Output Settings - Monitor icon with a pencil?

**Comment by artisteacher** [comment] 2019-03-03 04:01
@manongjohn  - Thanks for the suggestions & being willing to do the implementation end of things. Are there any other commands that you feel could really use some icons?

**Comment by konero** [comment] 2019-03-03 21:14
Concept from my old, failed attempt at mono icons when I did the viewer. 🤕 

![old_a](https://user-images.githubusercontent.com/19820721/53699677-deb7c700-3de2-11e9-8235-868cdb6a78c9.png)

The plan was to allow OpenToonz to change the color of the icons by itself from a drop down or something, that way only one icon file needs to be maintained to be compatible across all themes. So in this instance, "Toonz Raster, "Raster" and "Vector" levels share the same icon, except OpenToonz changed the color.

I managed to invert them with my prototype, but I couldn't get it working in OpenToonz anyway, nevermind swapping the color to a defined one.

![dd1](https://user-images.githubusercontent.com/19820721/53700362-55f05980-3de9-11e9-81d1-665162e3de94.png)

I wanted to bring this up cause some guys from Blender told me it's what they're doing in 2.80. If anyone out there can do it, maybe something to look into.

**Comment by manongjohn** [comment] 2019-03-04 03:36
@artisteacher If you could add to these to the inital set, that would be great: Cut, Copy, Paste Insert, Paste Insert Above/After

**Comment by artisteacher** [comment] 2019-03-10 21:39
I believe this is the rest of the proposed icons. Palette/style editor icons inspired by @konero.
<img width="667" alt="Screen Shot 2019-03-10 at 5 38 25 PM" src="https://user-images.githubusercontent.com/21159116/54091845-580f6680-435b-11e9-964f-ad9672423de9.png">

I'll export & upload the svg if these are all set.

**Comment by artisteacher** [comment] 2019-03-10 23:59
@konero it would be great to be able to swap out the colors for the icons so that they could easily be customized for each theme. If someone is able to figure out the coding end of that, I could switch any icons I've made to work with a single color and no outline.

**Comment by manongjohn** [comment] 2019-03-11 00:33
Icons look great! 

Only one I would suggest modifying a bit is the Style Editor. I think the brush needs to be a little more prominent somehow to make it more editor-like?

**Comment by artisteacher** [comment] 2019-03-11 01:35
Thanks! What about this:
<img width="202" alt="Screen Shot 2019-03-10 at 9 35 13 PM" src="https://user-images.githubusercontent.com/21159116/54095219-7043ad80-437c-11e9-9c64-5eeaf3de49d7.png">

**Comment by artisteacher** [comment] 2019-03-11 01:45
Or maybe this one:
<img width="228" alt="Screen Shot 2019-03-10 at 9 44 58 PM" src="https://user-images.githubusercontent.com/21159116/54095450-c82ee400-437d-11e9-945d-200d8e1cdfed.png">

**Comment by manongjohn** [comment] 2019-03-11 02:16
I am leaning more towards the brush one.

For the both versions, and also the pencil part of the Output Setting icon, can you see how they would look with the eraser end tilted up instead of down? I think that is more of the standard look.

**Comment by artisteacher** [comment] 2019-03-11 03:00
<img width="72" alt="Screen Shot 2019-03-10 at 10 59 42 PM" src="https://user-images.githubusercontent.com/21159116/54097821-37113a80-4388-11e9-9ded-3624e6c53136.png">

**Comment by manongjohn** [comment] 2019-03-11 03:09
Those look better to me. Not sure which Style Editor one I like better now. 🙂

Feel free to include them all and I can see which one looks best once added.

**Comment by artisteacher** [comment] 2019-03-11 03:53
Here's the 2nd half of the new svg files:
[More command bar icons.zip](https://github.com/opentoonz/opentoonz/files/2950569/More.command.bar.icons.zip)

**Comment by manongjohn** [comment] 2019-03-11 17:59
Can you add an icon for Cut?

**Comment by manongjohn** [comment] 2019-03-11 19:57
As I was getting ready to start making the PR for this, I was taking a good look at the icons and trying to decide which of the multiple versions would be good to use.  I'm afraid the Remove Unused Level may be mistaken for a Delete Level.

Perhaps if the Level icon behind the X was a dashed line without fill to signify it was already removed and not being used?

**Comment by artisteacher** [comment] 2019-03-12 02:08
Here are a few options:
<img width="47" alt="Screen Shot 2019-03-11 at 10 06 22 PM" src="https://user-images.githubusercontent.com/21159116/54169646-f843b900-4449-11e9-8bce-ce1fa1e32c14.png">
[Archive.zip](https://github.com/opentoonz/opentoonz/files/2954881/Archive.zip)

**Comment by manongjohn** [comment] 2019-03-12 10:42
Thanks.

I've chosen to incorporate the following icons as shown from my Command bar:

![image](https://user-images.githubusercontent.com/19245851/54192591-bbe67c00-448e-11e9-84e5-ed71e5232754.png)

Legend:
1. Add Frames, Bring Forward, Bring to Front, Clone (cells), Copy, Cut, Delete
2. Each 2, Each 3, Each 4, Enter Group, Exit Group, Fill Check, Fold Column
3. Gap Check, Group, Insert, Insert Above/After, Insert Multiple Keys, New Note Level, Output Settings
4. Palette, Paste Insert, Paste Insert Above/After, Paste Into, Remove Multiple Keys, Remove All Unused Levels, Remove Vector Overflow
5. Schematic, Send Backward, Send to Back, Studio Palette, Style Editor, Ungroup, Zero Thick Lines

Some observations against the Default theme:
- `Delete`: There was already a delete icon so I reused that to be consistent.
- `Cut`: is a bit hard to read.
- `Bring Forward`, `Bring to Front`, `Send Backward`, `Send to Back` : The dark squares blend too much with the background color.
- `Insert`: This command is rather generic, usable for Cells, Nodes, Levels, etc.  The icon is highly specific to Xsheet/Timeline so it doesn't quite make much sense for other areas of OT. I think we need to rethink this.
- `Insert Above/After`, `Paste Insert Above/After`:  These are specific to Xsheet/Timeline so the general image is ok. The arrows are a bit hard to read, though.
- Some of the images in their active state seem a bit fuzzy. 
- Some of the smaller/finer details get a bit lost against the darker backgrounds after they shrink down (i.e checks in Fill/gap check, lines in Schematic

**Comment by artisteacher** [comment] 2019-03-12 14:24
That insert icon is supposed to be for Insert Below/Before and was intended to be Xsheet/Timeline specific.  In the context menu for the column/layer headers, the command is described as either "Insert Before" or "Insert Below" - is that the same as just "Insert"? Mac keyboards don't have an insert key, so I always forget that inserting is a thing and don't use it.

I'll take a look at the icons with smaller details/dark values and work on making them clearer. This is totally where @konero's idea for flat svg's that change color based in the theme would be helpful!

**Comment by manongjohn** [comment] 2019-03-12 14:51
Unfortunately that's not how the Insert command is coded.  There is technically only 1 Insert action defined but it will do different things based on where you are in OT.  The icon is only defined 1x at the time of command creation and isn't switched contextually.

**Comment by konero** [comment] 2019-03-12 17:57
@artisteacher I spoke to somebody about flat icons, he says it's easy to do in Qt to change their colors, you have to mask the pixmap (transparent or a specific color) then fill the mask. That'd allow the user to pick their own color in preferences (or use a pre-defined type).

IDK a lot about mask, is it expensive I wonder? 🤔 

Here's the snippet he gave me, crazy syntax though.

```
// function...
pixmap = QPixmap(file.svg)
mask = pixmap.createMaskFromColor(QColor('black')), Qt.MaskOutColor)
pixmap.fill((QColor('white'))
pixmap.setMask(mask)

// call it...
foo.setIcon(QIcon(pixmap))

// alternate... if you want to color everything
mask = pixmap.createMaskFromColor(QColor('transparent')), Qt.MaskInColor)
```

Just for reference, anyway.

**Comment by artisteacher** [comment] 2019-03-12 18:27
Cool! Could this be adjusted to change multiple colors for one image?

**Comment by openanim** [comment] 2019-03-18 12:39
@artisteacher would it be possible to add save level and save scene icons ?

**Comment by artisteacher** [comment] 2019-06-20 19:14
Is there anyone who would be interested in the coding component for icon masking? 

With such a small size, it's tricky getting the icons clear and readable for every theme. It would make some of these icons a lot easier to design if the colors (or even a single color) could be set in the theme. If it's just not going to happen, I can continue trying to perfect this icon set...

**Comment by MrBlockCat** [comment] 2020-04-05 03:38
These icons look great! I don't know C++, but I did find this on [a post](https://stackoverflow.com/a/38369468) which looks like it may be very helpful:

```
pixmap = QPixmap(filename)
mask = pixmap.createMaskFromColor(QColor('black'), Qt.MaskOutColor)
pixmap.fill((QColor('red')))
pixmap.setMask(mask)

btNew = QToolButton()
btNew.setIcon(QIcon(pixmap))
```

Perhaps if QColor('black') were set to 'white' and QColor('red') to a theme dependent color, and some other tweaks beyond my understanding were made, this could work?

**Comment by openanim** [comment] 2020-06-17 11:06
@artisteacher 

I do not know if you received the email from bounty source following their modification of the conditions of use (otherwise refer to the post of shun iwasawa in #1349), can you please, claim the bounty for the icons made.

**Comment by artisteacher** [comment] 2020-08-27 12:26
@openanim - I think @konero should get the bounty - #3457

**Comment by openanim** [comment] 2020-09-09 22:16
Thanks @artisteacher for your suggestion and your work on this aswell.
@konero as suggested above your awesome work in related PR fullfills by far this request. Can you please claim the bounty ? Thank you so much that make OT very clean.

**Comment by RodneyBaker** [comment] 2020-09-23 21:59
Closing so that Bounty Source can see the issue as resolved.
It will be good to add a comment that the bounty was paid out and received.

**Closed** 2020-09-23 22:16 UTC
Labels: bounty, enhancement, roadmap
