### ISSUE TITLE
.psd import OpenToonz 1.5 (Windows)

### ISSUE THREAD

**Issue by rabe01** [opentoonz/opentoonz#3994] opened 2021-06-25 12:26 UTC
Importing .psd files OpenToonz 1.5
I saw that this problem was worked on - and closed - back in 2017. But even today, in 2021, I cannot properly import .psd files - neither from Krita, Clipstudio Paint or Photoshop CS6.
Tools like Moho or Cartoon Animator naturally import characters with many layers into different layers.
Although OpenToonz offers to import layers into multiple columns, I constantly have difficulties:
- psd code name error
- Alpha channel doesn't seem to be working (Alpha with "halo")
- Imported images must first be "combined" with a raster-layer in order to be editable ...
Am i too stupid or can someone help? Or should that be improved in OpenToonz?
Greetings

**Comment by RodneyBaker** [comment] 2021-06-27 01:21
@rabe01 Can you post/attach a .PSD file that you are finding to be particularly troublesome.
That will help greatly with testing.  

The Alpha with halo issue seems related to Premultiplied Alpha.

![image](https://user-images.githubusercontent.com/2576432/123530038-d377bc00-d6bb-11eb-9691-7409e5472238.png)

If you can supply any more information on the PSD code name error that will be appreciated.  Perhaps some screenshots or video capture?

Thanks!

**Comment by shun-iwasawa** [comment] 2021-06-28 06:49
> Imported images must first be "combined" with a raster-layer in order to be editable

OT currently cannot write images in PSD format, thus the file is loaded with a read-only flag.

Regarding the `psd code name error` , there are some lines ([this](https://github.com/opentoonz/opentoonz/blob/5aa5de6505d2612661466a707fdfd8392082cae5/toonz/sources/common/psdlib/psd.cpp#L1230) and [this](https://github.com/opentoonz/opentoonz/blob/5aa5de6505d2612661466a707fdfd8392082cae5/toonz/sources/common/psdlib/psd.cpp#L1254)) showing such error message under some conditions. As @RodneyBaker pointed, posting the problematic psd file would be helpful to find the cause in detail.

**Comment by rabe01** [comment] 2021-06-28 14:53
Sorry for my late reaction.
@shun-iwasawa thanks for the tipp to convert .psd-file in raster-layer. But in most cases I cannot import a .psd file at all.
I can not attache an example of a simple .psd-file here. I have sent a mail to Rodney. Hope it helps.

Greetings

**Comment by rabe01** [comment] 2021-06-30 18:05
Hi,
I am here one more time. Maybe someone knows a reason why I can't load .psd files into OpenToonz?
![BS-psd-import](https://user-images.githubusercontent.com/33298695/124009656-27491480-d9de-11eb-8dd1-762b9d8726ed.PNG)
It seems, if it are not possible to attach .psd-files here?
Other tools, like Tahoma can import the .psd-file without problems.

**Comment by gab3d** [comment] 2021-06-30 18:29
Please try to use a simpler filename, like "test.psd" and see if it loads...

**Comment by gab3d** [comment] 2021-06-30 18:34
Sidenote:
While trying to load a PDS myself to see if it worked on my side, I came across a possible bug:
...while being read only, it is still possible to apply some level effects to PSDs, like Binarize, Brightness and Contrast or Adjust Levels.

I'm not sure this is a problem, or it could be even be seen as a feature.
In any case, I think it could be a good idea to alert users about those changes not being saved when they leave the session.

**Comment by rabe01** [comment] 2021-06-30 18:43
@gab3d – I had suspected myself that it might be due to file names - or because it was imported earlier - but nothing seems to be changing.
I didn't apply any effects or anything like that either - just three simple layers.

**Comment by gab3d** [comment] 2021-06-30 19:49
can you upload it to check it?

**Comment by rabe01** [comment] 2021-06-30 20:42
I think I can't upload a .psd file here. 
Here is link to Dropbox:
[psd-file](https://www.dropbox.com/s/7yr6g6epd6ruwyg/a.psd?dl=0)

**Comment by RodneyBaker** [comment] 2021-07-01 03:43
Strange.  It loads for me here (using both the import and load options).

**Comment by rabe01** [comment] 2021-07-01 10:50
Hello,
I have uninstalled OpenToonz - and now installed the latest version - I can import .psd files :-)
I have no idea why that was.
Now it seems to be working. Thank you for your help.

**Comment by RodneyBaker** [comment] 2021-07-01 11:00
Interestingly, you seem to be able to use PSD files now and most of my current tests fail.  ;)
Funny... and frustrating... how that works.

Glad to hear you are having some success though.

**Comment by rabe01** [comment] 2021-07-01 11:11
I don't know how long this will work. I completely uninstalled OpenToonz (BCU-Uninstaller) - then installed the last release.
The next problem for me now is that when I try to combine psd levels with raster-levels, I get duplicate levels.
I'm starting to think that it seems to be better to import .png images into OpenToonz - not as elegant as all layers at once as .psd ...
Maybe that's still developing?

**Comment by artisteacher** [comment] 2021-11-29 23:05
Regarding importing PSD - sometimes PSD exported from the Procreate app need pre-multiply turned on. Is there any down side to having it on by default? The display without it can be really rough looking.

Also, I've found a bug where importing layers as columns (as a sub-xsheet), inserts empty columns before the PSD sub-scene. It seems to be one empty column per PSD layer.

**Comment by shun-iwasawa** [comment] 2021-11-30 00:34
@artisteacher 
Usually the `Premultiply` option should be turned on when loading PSD levels according to the Preferences settings. ( See `Preferences > Loading > Level Settings by File Format > Adobe Photoshop` )
Neither problems could be reproduced on my end. It may be because I tested with PSD files saved with PhotoShop, not with Procreate. Can you please post a sample file for reproducing the bug?

**Comment by artisteacher** [comment] 2021-11-30 01:53
This one is from Affinity Designer and doesn't have the visual distortion that can happen when premultiply is off. At least on macOS, it does import with premultiply off, even though it should be on according to the loading preference:
<img width="317" alt="Screen Shot 2021-11-29 at 8 39 32 PM" src="https://user-images.githubusercontent.com/21159116/143970184-aad3968f-f219-49ae-b909-1640ec048058.png">
Looking at the level settings, you can see that premultiply is not checked:
<img width="363" alt="Screen Shot 2021-11-29 at 8 35 37 PM" src="https://user-images.githubusercontent.com/21159116/143970210-76ce902c-e93e-4a6c-a813-cdd75d21f7cb.png">
It also results in empty columns on import when using these settings:
<img width="384" alt="Screen Shot 2021-11-29 at 8 43 45 PM" src="https://user-images.githubusercontent.com/21159116/143970448-2e6ebb77-d701-4626-ab38-1e4eaed1bed5.png">


[loadtest.psd.zip](https://github.com/opentoonz/opentoonz/files/7622260/loadtest.psd.zip)

If you need it, I'll try to get one with the premultiply off visual distortion - a couple students made files that did it.

**Comment by shun-iwasawa** [comment] 2021-12-01 00:39
@artisteacher 
Thank you for uploading the sample file, I could reproduce the problem 👍

**Comment by shun-iwasawa** [comment] 2021-12-01 01:19
Regarding the missing premultiply option problem:
Please check `Preferences > Loading > Level Settings by File Format` combo box and see if there is an empty item on top of the PhotoShop item. If yes, try removing it and loading the PSD file again.

When I removed the default setting for PNG format I forgot to reduce the size of reserved items and it caused the empty item which overrides the other conditions. I'll fix it right away. sorry for the trouble!

**Comment by artisteacher** [comment] 2021-12-01 01:30
Yes, removing the empty item fixes the premultiply issue. Thanks for looking into this!

**Comment by RodneyBaker** [comment] 2021-12-09 20:23
I believe this report can be closed now but... not sure.
@rabe01 Are you still having any issues with PSD import?

**Comment by RodneyBaker** [comment] 2022-03-16 18:36
Closing as abandoned and/or likely resolved.
@rabe01 Please let us know if you are still experiencing any problems.

**Closed by RodneyBaker** 2022-03-16 18:36 UTC

**Comment by rabe01** [comment] 2022-03-16 19:21
Yes gladly. 
Thanks 
Continued success

**Comment by rabe01** [comment] 2022-12-14 21:49
Hello, it's me again - after a long time: I finally played around with OpenToonz and Tahoma again.
Unfortunately, the PSD import still doesn't work for me.
OpenToonz doesn't seem to be able to import layers into columns. The imported PSD cannot be edited either – usable!
Tahoma seems to import the layers correctly in columns, they can also be animated - but unfortunately not edited (not painted, not erased, not converted to raster levels (maybe still export? But that doesn't seem to be a sensible option).
Are there any new developments in PSD import? I think that would be an important feature!
Best regards
