### ISSUE TITLE
Mesh cannot be generated

### ISSUE THREAD

**Issue by medmedin2014** [opentoonz/opentoonz#3978] opened 2021-06-13 12:09 UTC
With OpenToonz 1.5 the mesh of plastic tool cannot be generated
```
OpenToonz: 1.5
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.4.123-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
```
![Screenshot_20210613_001412](https://user-images.githubusercontent.com/7027319/121806620-8110b700-cc48-11eb-8077-7ad30dba1864.png)

**Comment by RodneyBaker** [comment] 2021-06-14 04:47
At a guess I'd say this is a Linux issue and there may be a report open for that.
Just to be sure though, it looks likeyou are creating a mesh with an imported bitmap image** can you create a plastic mesh with say... a simple vector filled shape?  Or a similar shape on a toonz raster level?

**This aspect would normally still result in a mesh being create although one that consists of the rectangle covering the entire image.  Just adding this for general informational purposes to collect more information.

**Comment by medmedin2014** [comment] 2021-06-14 10:26
It doesn't work with imported svg, neither with filled shapes on raster or on vector level.

**Comment by RodneyBaker** [comment] 2022-09-25 06:10
Closing this as a duplicate of other reports related to Plastic Mesh generation.
One workaround (unconfirmed on Mac) that appears to work on Linux is to collapse the vector level into a subxsheet and then use that to create the mesh.

@medmedin2014 Please let us know if the issue persists.

**Closed by RodneyBaker** 2022-09-25 06:10 UTC
Labels: os-linux
