### ISSUE TITLE
OSX 10.11.3 – Crash on Save Scene / New Level

### ISSUE THREAD

**Issue by geoffkhli** [opentoonz/opentoonz#162] opened 2016-04-12 14:18 UTC
I've just downloaded OpenToonz (_1.0) for my OSX 10.11.3 (Capitan) and can't seem to get started – the program crashes and I get an error message when I try to save my scene or create a new Level.

Is anyone else having this problem?

**Comment by isampera** [comment] 2016-04-12 22:01
I have the exact same problem. Don't know what to do tho..

**Comment by ullebulle** [comment] 2016-04-12 22:24
I also have the same problem, but only on version 1.0.1, not in 1.0
I'm also on OS X 10.11.4

**Comment by Harold19776** [comment] 2016-04-13 01:54
ullebulle, where did you find version 1.0.1 for Mac? I see the update for Windows but I can't find the mac update...

**Comment by kogaki** [comment] 2016-04-20 02:00
This problem must be caused by absent of `lzodriver` in OSX. We fixed that in #205 . 
You can try fixed version from `nightly build`. If the problem still have been there, please reopen. Thanks.

**Comment by ullebulle** [comment] 2016-04-20 06:35
With the latest nightly build, this still happens, but only when creating a new "Toonz Raster Level"
OSX 10.11.5

**Comment by kogaki** [comment] 2016-04-20 07:35
Hmm.. it doesn't happen in my environment(10.11.3). Can you find `lzocompress` in `/Applications/OpenToonz_1.0.app/Contents/MacOS/`? We think the absent of this file is the cause of the problem.

**Comment by ullebulle** [comment] 2016-04-20 10:09
Yes, the lzocompress file is there
https://dl.dropboxusercontent.com/u/215022/OT/Sk%C3%A4rmavbild%202016-04-20%20kl.%2012.05.57.png

**Comment by kogaki** [comment] 2016-04-20 12:43
It looks OK, so there should be another bug... If you have installed xcode and lldb, printing backtrace can really help us understanding the problem. Anyway, thank you for reporting.

**Comment by ullebulle** [comment] 2016-04-20 12:54
Ok, I have Xcode installed but not lidb, tell me how to install, with mac port?, I gladly help
Skickat från min iPhone

**Comment by kogaki** [comment] 2016-04-20 13:42
Thanks! Just `xcode-select --install` in your terminal will do.  (see http://stackoverflow.com/questions/34680789/how-to-install-lldb-on-mac/34680858 )

And following is a step to get backtrace
1. run `lldb /Applications/OpenToonz_1.0.app/Contents/MacOS/OpenToonz_1.0` in terminal
2. `(lldb) run` in lldb
3. Let OpenToonz crash
4. `(lldb) bt` in lldb
5. backtrace will shown in lldb

If you share the backtrace, we can see which function went wrong.

**Comment by ullebulle** [comment] 2016-04-20 19:37
Thank you for information.
I tried what you instructed and when I make a new "Toon Raster Level" Opentoonz hangs instead of crashing and this is what I get in the terminal so far:
https://dl.dropboxusercontent.com/u/215022/OT/terminal%20log.rtf
So I could accomplish the the 2 first steps and on step 3, OT hangs instead of crashing

**Comment by ullebulle** [comment] 2016-04-20 19:46
This is the OS X crash log from "new toonz raster level" crash, if it is to any help?
https://www.dropbox.com/s/wb6t95b8ay5uqga/new%20toonz%20raster%20level%20crash%20osx.rtf?dl=0

**Comment by kogaki** [comment] 2016-04-21 06:25
@ullebulle thank you for sharing the crash report. It taught us the crash was caused by zero-sized image (or negative size). And now I can reproduce!

I found some combination of parameters about image size can cause this bug. 

This goes crash
![2016-04-21 15 14 58](https://cloud.githubusercontent.com/assets/17926501/14699678/afbb96f8-07d4-11e6-9731-02fafe767b22.png)

This goes well
![2016-04-21 15 15 53](https://cloud.githubusercontent.com/assets/17926501/14699687/bdd260e6-07d4-11e6-959e-65a27938a23b.png)

Of course we will try to handle correctly, anyway, could you try parameters above?

**Comment by ullebulle** [comment] 2016-04-21 09:17
Sorry but crashing with those parameters as well :(
Here's OS X crash log:
https://www.dropbox.com/s/r5z5ajxm5owx7xm/TR-Crashlog-w-right%20parameters.rtf?dl=0

**Comment by agbarrows** [comment] 2016-05-01 17:54
i have the same problem with the 1.0.2 release.. it crashes when i save the scene and when i try to create a raster level.. the problem was not present in version 1.0
.
i run on mac OS X El Capitan

**Comment by agbarrows** [comment] 2016-05-01 18:23
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (lx > 0 && ly > 0), function TRaster, file /Users/keisuke_ogaki/.jenkins/jobs/opentoonz/workspace/toonz/sources/common/traster/traster.cpp, line 32.

thi is the message error i have when crashes trying to create a new raster level...

**Comment by kogaki** [comment] 2016-05-16 14:32
There must remain problem. So I reopend this isssue. Let's figure out that.

**Comment by Harold19776** [comment] 2016-06-08 02:07
> hi all,
> is opentoonz still crashing on mac's?
> 

Yeah :-(

**Comment by kogaki** [comment] 2016-06-08 02:48
#333 solved the problem partially. So we need more info of crashes. Could anyone provide crash report like https://github.com/opentoonz/opentoonz/issues/162#issuecomment-212576276 ?

**Comment by ullebulle** [comment] 2016-06-08 07:24
Hi, I started the "lldb /Applications/OpenToonz_1.0.app/Contents/MacOS/OpenToonz_1.0"-trick, unfortunately I could not make OT crash :) 
I made a fast test with the latest OT build, made a Vector layer, a Toonz Raster Layer and a Raster layer.
The issue I had with OT crashing when making a Toonz Raster Layer is gone:)
I used the brushtool on all of the layers and I also used the geometrytool on all, no crashes so far, I will make some more work on OT later when I can find the time

**Comment by Dragularos** [comment] 2016-06-13 00:17
Maybe i can help. I'm using version 1.0.2 on OSX 10.11.5 and i experience the problem when i try to create a new level WITHOUT telling him to choose a folder where to put the drawings in. 

When i do nothing you can see "+drawings" in the line: "Save In:" 
After clicking the ok button he asks me to CREATE A NEW FOLDER "+drawings". When i say: Yes, it crashes.

See here: 

![bildschirmfoto 2016-06-13 um 02 05 07](https://cloud.githubusercontent.com/assets/19895943/15994749/ff690b2a-310c-11e6-9a61-b377ec179fab.png)

**Comment by agbarrows** [comment] 2016-06-17 16:31
ok...
i installed 1.0.3
all the "create ToonzRaster Level" and Save scene or Save All are not fixed...
i made a backtrace of a normal crash event...created a level (vector) and drawing in it...
then i press Save All Option..
this is the backtrace

Process 6411 stopped
* thread #1: tid = 0x1c39ae, 0x00000001046d89ac libpng16.16.dylib`___lldb_unnamed_function6$$libpng16.16.dylib + 315, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001046d89ac libpng16.16.dylib`___lldb_unnamed_function6$$libpng16.16.dylib + 315
libpng16.16.dylib`___lldb_unnamed_function6$$libpng16.16.dylib:
->  0x1046d89ac <+315>: vxorps %xmm0, %xmm0, %xmm0
    0x1046d89b0 <+319>: vmovups %xmm0, (%rax)
    0x1046d89b4 <+323>: movq   $0x0, 0x10(%rax)
    0x1046d89bc <+331>: leaq   -0x4e8(%rbp), %rsi

**Comment by agbarrows** [comment] 2016-06-17 18:08
i installed the 1.0.3
the tone raster level issue stills here.. this is the report

Process 6655 stopped

* thread #1: tid = 0x1cc961, 0x00007fff8c13691a
libsystem_kernel.dylib`write + 10, queue = 'com.apple.main-thread', stop
reason = signal SIGPIPE

    frame #0: 0x00007fff8c13691a libsystem_kernel.dylib`write + 10

libsystem_kernel.dylib`write:

->  0x7fff8c13691a <+10>: jae    0x7fff8c136924            ; <+20>

    0x7fff8c13691c <+12>: movq   %rax, %rdi

    0x7fff8c13691f <+15>: jmp    0x7fff8c12f7f2            ; cerror

    0x7fff8c136924 <+20>: retq


2016-06-13 2:18 GMT+02:00 Phil <notifications@github.com>:

> Maybe i can help. I'm using version 1.0.2 on OSX 10.11.5 and i experience
> the problem when i try to create a new level WITHOUT telling him to choose
> a folder where to put the drawings in.
>
> When i do nothing you can see "+drawings" in the line: "Save In:"
> After clicking the ok button he asks me to CREATE A NEW FOLDER
> "+drawings". When i say: Yes, it crashes.
>
> See here:
>
> [image: bildschirmfoto 2016-06-13 um 02 05 07]
> <https://cloud.githubusercontent.com/assets/19895943/15994749/ff690b2a-310c-11e6-9a61-b377ec179fab.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/opentoonz/opentoonz/issues/162#issuecomment-225468813>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARzwMvf1O-s1ddKnu6UezQNkHZhIixd1ks5qLKG6gaJpZM4IFb6F>
> .
>



-- 
Gabriele Barrocu

Località Caliogna 38
15010 Melazzo AL
cell 3473540934

**Comment by turbocactus** [comment] 2016-08-11 20:29
I am experiencing this issue with version 1.1.1 - the program seems to work well but immediately crashes when trying 'save all' or 'save scene'. I am using OSX 10.11.5.

**Comment by 1l0** [comment] 2016-09-13 01:42
On OS X 10.11.6
with OpenToonz 1.0: I can save scenes but it crashes by another reason.
with OpenToonz 1.1.1: It crashes on saving anything.

**Comment by artisteacher** [comment] 2017-05-22 19:33
I'm not having this issue on the mac's I have access to (10.11.4, 10.11.6, and 10.12.4). I did have an old mac running 10.9.5 that experienced this issue but since updating the OS, I haven't had this problem. Is anyone still experiencing this crash?

**Comment by RodneyBaker** [comment] 2018-11-30 18:52
@geoffkhli @isampera @ullebulle @Harold19776 @Dragularos   If you are still having any related issues please let us know.  Closing.

**Closed by RodneyBaker** 2018-11-30 18:52 UTC
Labels: Crash, OS: MacOS
