### ISSUE TITLE
The problem with the interface.

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#1528] opened 2017-10-18 08:02 UTC
On one of the computers, the interface looks ill-defined. What do I need to do to fix this? Also there is no one function.  (Command Bar )

![image](https://user-images.githubusercontent.com/25137502/31706947-66d7a1da-b3f3-11e7-9a11-5f06c570234d.png)

![image](https://user-images.githubusercontent.com/25137502/31707019-a4c3c53c-b3f3-11e7-9cd5-7a696dbcc40e.png)

**Comment by shun-iwasawa** [comment] 2017-10-18 08:48
For now, we are trying to migrate Qt from 5.6 to 5.9 ( #1517 ).
In association with that, I changed the settings of Jenkins CI to use Qt5.9 .
The UI glitch appears in the frame slider is the problem caused by it.
It will be fixed after #1517 is merged.  Meanwhile please use [the previous nightly builds](https://github.com/opentoonz/opentoonz_nightlies/releases) ( `2017-10-11 07:59:00 UTC` build works OK) or try @turtletooth 's latest OTX which will be released for testing Qt5.9 .

Regarding the missing command in the menu bar, I think it is because the old personal menu bar setting exists in `Stuff\profiles\layouts\personal\Default.username` . Please try the clean install.

**Comment by Agnyy** [comment] 2017-10-18 08:58
Thanks helped. Спасибо :-)

**Closed** 2017-10-18 08:59 UTC

**Comment by shun-iwasawa** [comment] 2017-10-20 04:42
@Agnyy 
I temporary reverted Jenkins to Qt5.6 so the nightly builds will be back to normal tomorrow.
After merging #1517 , I'll change it to 5.9 again.
