### ISSUE TITLE
Fill tool don´t work

### ISSUE THREAD

**Issue by DroneXD** [opentoonz/opentoonz#1492] opened 2017-09-27 17:53 UTC
I can´t use the fill tool in opentoonz (it sometimes don´t work), 
Help
![sinzxccz titulo](https://user-images.githubusercontent.com/30803348/30928941-3f5057e2-a3bd-11e7-9f20-914560fe4ac0.png)
The black zone work, but the white zone don´t work
Sorry I don´t speack English fine :P

**Comment by DroneXD** [comment] 2017-09-27 17:53
Help :(

**Comment by gab3d** [comment] 2017-09-27 17:56
can you show us only the lines (without the black part filled)?

**Comment by DroneXD** [comment] 2017-09-27 19:20
yes :)
![lines](https://user-images.githubusercontent.com/30803348/30933050-a94d7b78-a3c9-11e7-988e-a09265e59652.png)

**Comment by gab3d** [comment] 2017-09-27 19:56
I've imported your image, cleaned up and then converted it to vectors.
Used the Tape (Cinta) tool to close the open left part, and then filled it with no problems.

![fill_issue](https://user-images.githubusercontent.com/18104091/30934401-e16510a0-a3a3-11e7-8373-2176e00dcfe6.png)

You could also use the Fill Check (Comprobación de áreas rellenables) option, as shown in the following capture, to check and see if the different areas in your drawing are closed, so they can be filled.

![fill_issue2](https://user-images.githubusercontent.com/18104091/30934648-9cf92d2e-a3a4-11e7-914b-1dfea45b6a9d.png)

**Comment by Orphanlast** [comment] 2017-09-27 21:18
Coloring typically works when you convert it to a toonz raster. That's how I color all my images, even if the vector work is layered on top of it.

**Comment by DroneXD** [comment] 2017-09-28 16:08
veo que hablas Español, me puedes explicar?

**Comment by DroneXD** [comment] 2017-09-28 16:27
no es la primera vez que me pasa, ya que muchas veces no se me colorea.
Generalmente al volverlo a dibujar se soluciona , pero es muy tedioso

**Comment by gab3d** [comment] 2017-09-30 18:48
@dronexd
sorry, but we should speak English only, here.
you can meet me in the Opentoonz en Español Facebpok page if you want to discuss in Spanish.

**Comment by turtletooth** [comment] 2018-01-20 04:06
This is a duplicate of previously discussed fill issues.

**Closed by turtletooth** 2018-01-20 04:06 UTC
