### ISSUE TITLE
Windows 10: creating New Toonz Raster Layer crashes

### ISSUE THREAD

**Issue by bigjko** [opentoonz/opentoonz#91] opened 2016-03-28 17:52 UTC
The program crashes if I try to create a Toonz Raster level, but Toonz Vector and Raster work fine.

On Windows 10.

**Comment by odysseywestra** [comment] 2016-03-28 19:15
Thank you for bug report. Could you provide us 15-30 video illustrating this problem?

**Comment by bigjko** [comment] 2016-03-28 21:06
Sure! It's v1.0.1, btw.

https://www.youtube.com/watch?v=28mJOuC1QVs

**Comment by odysseywestra** [comment] 2016-03-28 21:48
Okay I can confirm this on my Windows 10 VM. When I did this, it say `lzcompress.exe` has stopped working so it's probably related to that.

How I reproduced the steps:
* Open Command Prompt
* Type in `"C:\Program Files\OpenToonz 1.0\OpenToonz_1.0.exe"` and Hit Enter
* Right Click on a Cell on the Xsheet and Click on `New Level`
* Name Level and Change type to Toonz Raster Level
* OpenToonz should crash with `lzcompress.exe` error.

**Comment by brambox** [comment] 2016-03-29 20:48
Toonz Raster is broken and crashes on windows 8.1+  
I hope we can get fix sometime soon.
As that is the biggest thing in Toonz!

**Comment by Goofybud16** [comment] 2016-03-30 01:26
Toonz Raster and Raster layers also appear to be broken in the Linux build from PR #51.

If I select either and create the layer, the application segmentation faults (equivalent of "Stopped Responding" on Windows.)

Has anyone seen if this causes crashes on Mac?

**Comment by brambox** [comment] 2016-03-30 02:57
Creating normal raster and toonz raster works on mac os x but its still hard to use it as there are tons of weird issues.
For example not always when you draw it actually  doing it...  
Also the program closes on own pretty often.

**Comment by yvanc** [comment] 2016-03-30 21:23
I was testing things out and I noticed that this bug was not present in OpenToonz1.0.
This bug only came along in the new release OpenToonz1.0.1.

**Comment by Gulwer** [comment] 2016-04-01 21:16
Hi
OSX version has the problem with crashing when creating a toonz raster level. it is present in the latest version 1.0.1. I tried Toonz 1.0 also and it did not crash so the problem came with the update. 

[Toonz_rasterlevel.pdf](https://github.com/opentoonz/opentoonz/files/200370/Toonz_rasterlevel.pdf)

**Comment by SafariMonkey** [comment] 2016-04-02 01:44
So it's confirmed as a regression in 1.0.1. Thanks for the info!

**Comment by CodyEakins** [comment] 2016-04-10 18:25
Encountered the same problem; trying to create a Toonz Raster Level consistently crashes the program.
I hope this gets fixed soon; I was looking forward to experimenting with the Style Editor recoloring my raster strokes.

**Comment by AyameLee** [comment] 2016-04-12 17:57
Thanks @CodyEakins I missed this thread.

Encountered same issue. When creating a new Toonz Raster Level using OpenToonz **1.0.1** it will crash when pressing OK/Apply.

This does not happen with **1.0**.

**-Event Info-**

Faulting application name: **lzocompress.exe**, version: 0.0.0.0, time stamp: 0x56f8c7f6
Faulting module name: **lzocompress.exe**, version: 0.0.0.0, time stamp: 0x56f8c7f6
Exception code: 0xc0000005
Fault offset: 0x0000000000001130
Faulting process ID: 0x364
Faulting application start time: 0x01d194da3bf0094b

**Comment by turtletooth** [comment] 2017-01-30 17:10
Seems to be fixed. Closing

**Closed by turtletooth** 2017-01-30 17:10 UTC
Labels: Bug, OS: Windows
