### ISSUE TITLE
Stylesheet problems?

### ISSUE THREAD

**Issue by brupelo** [opentoonz/opentoonz#101] opened 2016-03-29 11:26 UTC
First time I've built OpenToonz on windows7 and the process went quite smooth. Problem appears when i try to run the program, the UI is rusty, here's how it looks:

cleanup - http://screencast.com/t/vpddvRC7jEO
http://screencast.com/t/YeGHlXxFu2Dd
inknpaint - http://screencast.com/t/2TQwz4jR
xsheet - http://screencast.com/t/8rFQZL07r1VQ
batches - http://screencast.com/t/9icPlWpEBRG
browser - http://screencast.com/t/exETOuq3oQ

Maybe it's a problem with the stylesheets? I've seen another user's snapshots and their UI look&feel look good.

**Comment by blurymind** [comment] 2016-03-29 11:52
Yes, it does look confusing, doesn't it? :)
Here you can download a fix for the stylesheet: https://github.com/opentoonz/opentoonz/issues/80
Please take some time to post a comment on your opinion. feedback much appreciated.

**Comment by brupelo** [comment] 2016-03-29 12:16
@blurymind Thanks for the fast response! so, I've tried both of your layout set files {OpenToonz.harlequin.zip , OpenToonz.betterRoomsLayout-ver1.zip} and my problem still persists, here's a new set of snapshots showing you how the rooms look like:

cleanup - http://screencast.com/t/JjTyrDs1ty
inknpaint - http://screencast.com/t/LWR9vik61
xsheet - http://screencast.com/t/LWR9vik61
pltedit - http://screencast.com/t/EnayhvHz
xsheet - http://screencast.com/t/EnayhvHz
browser - http://screencast.com/t/18JgbKds
farm - http://screencast.com/t/18JgbKds

As you can see, the arrangement of widgets & layouts is now much better as you've explained in the other thread... but my black glitches still remain, any clue why is this?

Thanks!

**Comment by cryovat** [comment] 2016-03-29 12:26
That's what the program looks like without any stylesheet loaded or with one that's empty. Are you sure that OpenToonz can find the styles?

Not sure where it looks in a custom built version, but on the installed binary version, there ought to be a folder named something akin to OpenToonz_1.0_stuff in the c:\ root that contains the files from the [stuff](https://github.com/opentoonz/opentoonz/tree/master/stuff) folder in the repository.

**Comment by brupelo** [comment] 2016-03-29 12:34
@cryovat Awesome! I missed one step, in my release folder I hadn't copied the stuff assets, so that was it, it was generating some by-default assets without any stylesheet. Now it looks nice!

Btw, to get familiar with the software first, tutorials, examples and so on... Any place to look at? I mean, it's great to contribute with the developing but first it'd be recommended to get familiar with the software :)

**Comment by cryovat** [comment] 2016-03-29 12:43
Documentation is pretty sparse right now unfortunately, so your best bet at the moment is the [User group](https://groups.google.com/forum/#!forum/opentoonz_en).

**Comment by odysseywestra** [comment] 2016-03-29 18:04
Closing as a duplicate of #80, since they both cover the same usability bug.

**Closed by odysseywestra** 2016-03-29 18:04 UTC
Labels: Duplicate
