### ISSUE TITLE
Red cells (erasure of drawings)

### ISSUE THREAD

**Issue by SPH404** [opentoonz/opentoonz#4047] opened 2021-08-22 09:42 UTC
Hi,

I have a huge problem with opentoonz. I can no longer render an AVI rendering. So, I uninstalled opentoonz to reinstall it elsewhere. Always the same problem.
But when I wanted to open one of my anim: 
http://northpark.chez.com/2021-08-22%2011_25_23-.png
... the cells are empty (their name is red)!
Where are the contents of my cells located?
In short, I'm afraid of having lost everything !!

Mad

**Comment by DarrenTAnims** [comment] 2021-08-22 10:33
Did you move your project?
The red cells just show that the drawings aren't in the place they were saved as, in the scene.

**Comment by artisteacher** [comment] 2021-08-22 23:52
You might want to check the drawings and extras folder for the project to see if the drawings, or their backups (with extension .bak) are there. 

If you had saved/loaded your images outside of the project and the project was moved in the reinstall, the paths to those assets would likely need to be corrected.

**Comment by RodneyBaker** [comment] 2022-02-17 04:48
@SPH404 We must assume you have resolved your problem by now but please let us know if that is not the case.

For specific play by play troubleshooting you may wish to visit one of the Opentoonz discords where users hang out and help each other in real time.

Closing as this is largely a duplicate of other 'red cell' missing levels most often repaired by by locating the levels and making sure they are in the place Opentoonz expects to find them.

Please let us know if you are still having problems.

**Closed by RodneyBaker** 2022-02-17 04:48 UTC
