### ISSUE TITLE
wav files with progressive numeration - file naming issues

### ISSUE THREAD

**Issue by matitanimata** [opentoonz/opentoonz#1996] opened 2018-05-23 07:54 UTC
it seems that OT, if you have a bunch of wav files with a progressive numeration, take them as one single file, like an image sequence. Same sort of bug that I've found on OTX with .tnz files. Obviously it can't load them in the x-sheet. Maybe an option to recognize things as part of a sequence or not could be helpful, someone could need to import just one image among a sequence. Another problem with file naming in the latest versions is with png from storyplanner. Storyplanner can export a storyboard as a toonz project, generating several .tnz files and extras folder with wav and images inside. Images are in png format and are named like this: Scene_009_001_8.png 
In OT previous versions it worked quite fine, in the last version (I'm trying the latest nightly build) it gives back this message: "malformed frame name: skipping frame" and it is unable to load the image in the x-sheet.

**Comment by artisteacher** [comment] 2018-05-23 12:06
In OpenToonz, if you name files with a period or underscore before the number (ie. name.0001.jpg or name_001.png) it will automatically be recognized as a sequence. That definitely should happen to any audio files though. I can reproduce on OS X. @manongjohn, perhaps you could take a look?

I was interested to find that I can name scenes within OT with _# (i.e. name_01 or etc.) and they are not recognized as a sequence. However trying to name a scene with .# (ie. name.001 or etc.) is prohibited.

**Comment by artisteacher** [comment] 2018-05-23 13:28
Once OT recognizes the wav files as a sequence, it is unable to load them into the Xsheet & only a single frame displays - like what you see trying to load a 32bit wav file. Renaming should work as a workaround.

**Comment by RodneyBaker** [comment] 2018-05-23 13:35
To join in the bandwagon... I've had a similar issue with PDF files where I get the malformed filename error.

Perhaps there needs to be a whitelist of files OT should consider as sequence-able files.
I wouldn't think a blacklist would work because there'd be an infinite number of possibilities for what extensions should be left out.

**Comment by matitanimata** [comment] 2018-05-23 13:43
the weird thing is that with an older version (january 2018 OTX) there is not this problem, this is quite important because affects the compatibility with storyplanner, which is an important tool in a toonz based pipeline. Renaming is of course a good workaround, but not when you have a lot of files and deadlines are approaching...

**Comment by RodneyBaker** [comment] 2018-05-23 13:59
Perhaps something has fairly recently changed in the way OT parses the REGEX code used to identify sequences.  I know a recent change was committed to deal with issues of images that either started with or terminated with a zero.  The leading zero is/was a common problem for me because of other programs that render out images starting with 0 and where 0 is used to pad the filename so that by entering "image000.tga" that program knows the sequence can run from 0 to 999 frames.  Similarly entering "image00.png" let's the program know you want a png sequence allowing 0 to 99 frames.  In this way also sequences don't break because of missing padding where "image9.jpg" does not logically follow after "image08.jpg".

All of this is different from this reported issue because it focuses on the extension and so I will guess that in the recent change that corrected other errors in RegEx the code now refers to *.* instead of things like *.png.  Or to put it another way the OT file browser now considers every file format to be a potential sequence and not just image formats.

**Comment by RodneyBaker** [comment] 2018-05-23 14:06
Here are the issues/changes that immediately return via search on "regex":

https://github.com/opentoonz/opentoonz/issues?utf8=%E2%9C%93&q=regex

**Comment by matitanimata** [comment] 2018-05-23 14:10
maybe an option to disable the sequence recognition could be a good solution?

**Comment by RodneyBaker** [comment] 2018-05-23 14:12
This appears to be a potential candidate:

https://github.com/opentoonz/opentoonz/commit/d8339e9782f1ebcf4ce4ea21c56cee1e523ab4e6#diff-b4d2c01baf408bf0330917eefbc08f0eR483

**Comment by shun-iwasawa** [comment] 2018-05-23 14:13
For now the file can be sequential or not is identified by the extension list specified [here ](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/tsystem/tfilepath.cpp#L75-L80). It should be whitelist-based, as @RodneyBaker suggested. And I think I can modify it by checking the file extensions registered in OT.

**Closed** 2018-05-24 07:45 UTC
