### ISSUE TITLE
What's the file/class/location where the final keyframe and/or function and/or curve data is read from?

### ISSUE THREAD

**Issue by Bracket-H** [opentoonz/opentoonz#4155] opened 2021-11-17 09:01 UTC
I've spent the last 4 hours trying to trace it in the codebase, and I'm giving up and asking now.

Where is the point located where some object asks about the value for some animated parameter?
I want to throw an experimental rounding there to see if it fixes the 'fractional' decimal problems for raster levels.

**Comment by shun-iwasawa** [comment] 2021-11-18 01:14
The transformation parameters of columns/pegbars are stored in the class `TStageObject` . (see [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/include/toonz/tstageobject.h#L526-L527) in the code)

I'm not sure what "the 'fractional' decimal problems" actually is, but if you are looking for the way to remove antialiasing caused by some operation, checking the resampling algorithms and switch them to nearest neighbor may work.

**Comment by Bracket-H** [comment] 2021-11-18 03:21
Thank you.
The fractional decimal problems are related to image interpolation. It's an issue very quickly met in 2D game development while using 3D technology (rasterizing textured polygons and dealing with pixels) underneath it.

A pixel is a dot on a grid, right? 
1080 p for example has 1080pixels vertically, and 1920 horizontally.

So if we imagine that set of pixels as a series of boxes (an array), you might get something like:
pixels[0][100] (despite this being common array notation, only IMAGINE it, conceptualize it as a mental array, with the indices being coordinates, more than memory locations)
In a pixel perfect world, when a pixel is exactly in one of those boxes, like pixels[0][100] = RGB(255,0,0)
Then only that single pixel would, after rendering displayed.
But now consider this location.

pixels[0.5361][100.51] = RGB(255,0,0)
This is the input for the renderer, but ULTIMATELY, on the final actual pixel grid, there are no fractions. Imagine a color dot matrix LCD for that if you want.
Where does the red pixel show up?

A 2D game that renders flat textured polys, will try to rasterize this by spreading the pixels via interpolation 'across' these fractional pixels. You might get full saturated red on pixels[0][100] but since it's fractional, you might get a pinkish pixel on pixels[0][101] since the final, rasterized result HAS to collapse into that grid.

In opentoonz, you would get interpolation, even if you didn't turn on resampling and/or antialiasing (or used nearest neighbor).

This not only makes pixel perfect 2D 'pixel art' animation that uses keyframes to move around nigh impossible.
But even anti aliased image data gets sort of 'smeared' even with high resampling and the like.

Here some images to help tie down this lengthy text explanation 
(all images are preview images with closest pixel/nearest neighbor)
(you might have to expand/zoom the pictures to prevent interpolation there, in other words, look at them zoom 1:1)

Picture 1, whole number pixel coordinates, 0, 0 no distortion/interpolation:
https://i.imgur.com/KXGfihf.png

Picture 2, both pixels fractional, distortion/interpolation in both X and Y directions, still nearest neighbor!:
https://i.imgur.com/kFJO1Wo.png

Picture 3, X coordinate whole, Y fractional, clean pixels on the X axis, smearing on the Y axis:
https://i.imgur.com/x0KMW12.png

Picture 4, both coordinates whole again, no smearing:
https://i.imgur.com/nOcsM8x.png

You can also test this with actual animation.
Here is to reproduce this.

Make a new scene.
draw something aliased with the pencil brush, turn on nearest neighbor in the render settings.
Add a keyframe at frame one, with x/y coordinates 0,0
Add a keyframe at another frame , let's use 115 (100 would give a clean interpolation), with coordinates 100,100.
Choose linear interpolation in the interpolation settings for that keyframe pair.

preview and check the output. You will see a lot of smudging, even with the nearest neighbor resample option on.

Then, instead of using linear interpolation, use expression interpolation for both X and Y part of the column:
Go to frame 1, enter the following expression `(floor(t*100))` and apply it for both X and Y (so the drawing moves to the upper right)

preview and check the output. You will see pixel perfection because now coordinates are whole numbers with no fractional part which the software has to figure out how to color where.


Additional (optional) reading:


Note how I/you had to specify the target coordinate of '100' in the expression to achieve this perfect rounded position?
This is due to several issues too.
Because OT expressions cannot use the current value of something as a 'temporary variable' to do operations on. 
You cannot do something like "get current value, floor/ceil it, and then use this modified value" because you'll get a 'circular reference error' Because it wants to set itself as the value, and working with the value to modify it 'in situ' isn't possible.

But this means, you can't use a second keyframe with a value as a 'target' value for interpolation (unless I just don't know how to do it) like in the non expression interpolation.
If you have a keyframe at frame 1, and it's value is 0, and the interpolation is linear, and the next keyframe is at frame 150, and the value is 100, then OT will happily (albeit fractionally) work with that.

A workaround for that is to use a proxy/target object where you keyframe the wanted values and use that as a reference in the expression of the first object, but that's real crappy to use and gets out of hand quickly.

And aaaaall of this...is why I want to mess around with a toggleable 'default rounding' for raster levels.
You check a box or something, and then, even if the data coming from the keyframe system is fractional (which IS useful to  evenly space something over time), for the raster level, in the final location, it will be rounded.

I hope this makes/made sense.

Fixing this would fix several issues others had, especially for the pixel perfect pixel artists out there.
I'm not one of them, but the smudging always annoys me even for normal animation, especially since it can be prevented.

**Comment by Bracket-H** [comment] 2021-11-18 04:05
By the way, I think this could potentially fix some issues in certain effects, too.
Tile, and Tile_Iwa for example, if you tile a scaled source/input column, then you get visible, interpolated/smudged gaps between the tile boundaries.

That too is an intepolation error resulting from the program trying to collapse partial/fractional pixel coordinate input into whole 'dot matrix display' like final image data.

This is just speculation though, about that fixing the effects, but I was reminded of that just now so, I'm adding it to the pile of arguments for this rounding option (which should use actual rounding and not just a ceiling or floor)

**Comment by shun-iwasawa** [comment] 2021-11-18 04:11
> Make a new scene.
> draw something aliased with the pencil brush, turn on nearest neighbor in the render settings.
> Add a keyframe at frame one, with x/y coordinates 0,0
> Add a keyframe at another frame , let's use 115 (100 would give a clean interpolation), with coordinates 100,100.
> Choose linear interpolation in the interpolation settings for that keyframe pair.
> preview and check the output. You will see a lot of smudging, even with the nearest neighbor resample option on.

Have you tried setting the interpolation in the **PREVIEW** Settings to nearest neighbor?

**Comment by Bracket-H** [comment] 2021-11-18 04:15
Oops, no, I didn't. That does seem to work (might have edge cases but not sure right now)
But, nearest neighbor was just for illustration anyway.

Fractional pixel data is still suboptimal for rasters...

**Comment by Bracket-H** [comment] 2021-11-18 04:23
I tested it a bit, and pixels went from one spot to the other at about 0.5 thresholds, aka "the game thing".

But again, that is a cludge...it locks one into nearest neighbor, and it still only moves pixels at a fractional value which is awkward to think around (especially for those who don't know, I would guess)
Why not fix it at the source? The root?

**Comment by shun-iwasawa** [comment] 2021-11-18 06:21
> But again, that is a cludge...it locks one into nearest neighbor, and it still only moves pixels at a fractional value which is awkward to think around (especially for those who don't know, I would guess)
Why not fix it at the source? The root?

Hmm IMO the nearest neighbor is the most reasonable way to avoid antialiasing.
The "default rounding" option in your proposal would work on position (X and Y) but I have no idea how to handle other transformations like scaling (especially when scaling less than 100%) , rotation and shear.

**Comment by Bracket-H** [comment] 2021-11-18 07:02
Yeah, something strange is going on, that's why I'll experiment with it myself when I've read more into the code.
And it's not really to avoid anti aliasing, it's to avoid unwanted interpolation, which is kind of the same thing, but you can have anti aliased lines get interpolated further based on fractional values the program tries to fill into the final grid.

Basically, what I am getting at is improved predictability/determinism. Less surprises, etc. Where a pixel from 1 to 2 should move from one place to the neighbor with 1 -> 2, and not from 1.5 to 2.5, etc

**Comment by RodneyBaker** [comment] 2022-01-05 23:44
Closing this as a question that is at least partially answered.
Feel free to continue discussion here or open a new report as necessary.

**Closed by RodneyBaker** 2022-01-05 23:44 UTC
Labels: question

**Comment by shun-iwasawa** [comment] 2023-06-12 09:21
I have not yet been able to reproduce the problem of the lines being smudgy even though the pixel units are used and the column positions are integer values.
If you don't mind, could you please share the scene and level data you used in the video?

**Comment by shun-iwasawa** [comment] 2023-06-13 01:02
Thank you for sharing the scene.
In the current master branch of OpenToonz, I switched the preferences to pixel units and then opened the scene.
Obviously, the values between the keys had fractional values. This would cause the lines to be resampled.

What version of OpenToonz are you using? Have you made any customizations to it.. ?

![image](https://github.com/opentoonz/opentoonz/assets/17974955/7dfdecb6-29fe-45b9-a443-7ee6553cd097)

**Comment by shun-iwasawa** [comment] 2023-06-13 01:10
And switching the Resample Balance to `Closest Pixel (Nearest Neighbor)` keeps the rendered line aliased even if the column is placed at fractional position.
![image](https://github.com/opentoonz/opentoonz/assets/17974955/a1333724-b0ee-4141-b768-6d463b5a867e)

**Comment by shun-iwasawa** [comment] 2023-06-13 07:49
Hmm, maybe I am still not quite understanding your idea. I still don't understand why Nearest Neighbor is not sufficient for you under no scaling or rotation.

Another method would be to use expressions to convert the position to an integer value. This method can also render pixel perfect lines.
![image](https://github.com/opentoonz/opentoonz/assets/17974955/ad490ab5-4194-4041-95da-c9225c1dc3b0)
