### ISSUE TITLE
Cursor issue when painting/drawing in the Viewer OSX

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1853] opened 2018-03-08 11:37 UTC
Whenever I select a color from the Color Wheel or a Level from the Timeline/XSheet, and return to the Viewer to paint, the arrow cursor appears on top of the painting circle, making it very difficult/annoying  to accurately paint.

I've attached a video for better visualisation of the issue. Hope it helps! Thanks!
[Screen Rec.mov.zip](https://github.com/opentoonz/opentoonz/files/1792977/Screen.Rec.mov.zip)

**Comment by artisteacher** [comment] 2018-03-08 14:49
Are you using a tablet?

**Comment by DotSilva** [comment] 2018-03-08 16:48
Yes, a Wacom Tablet. The OS is Sierra 10.12.6

**Comment by artisteacher** [comment] 2018-03-13 18:28
This is probably related to #1796. I have the same issue. When using a tablet, OT does not correctly recognize hovering, so the tooltips do not change as expected. Hopefully the fantastic @shun-iwasawa will be able to fix this at some point.

Does adjusting your wacom settings make any difference?

**Comment by artisteacher** [comment] 2018-12-03 04:14
Duplicate of #1796 - hovering not recognized when using a tablet on MacOS.

**Comment by RodneyBaker** [comment] 2018-12-03 04:20
Concur.  Closing.  Topic also abandoned by @ghost... as is the referenced duplicate which for now will remain open.

**Closed by RodneyBaker** 2018-12-03 04:20 UTC
Labels: Duplicate, OS: MacOS
