### ISSUE TITLE
possible bug with opentoonz hook tool?

### ISSUE THREAD

**Issue by sergiofrias** [opentoonz/opentoonz#1385] opened 2017-08-07 13:03 UTC
hello , hook tool doesn't display number in the viewer please check this video:

https://www.youtube.com/watch?v=Gyiq2b7Y7pA

I tried this with morevna and experimental,i didn´t test this in the oficial release.

is this a bug? thank you.

**Comment by WPFilmmaker** [comment] 2017-08-08 13:17
It looks like a glitch to me. 

I am able to reproduce it using OpenToonz 1.1.3 Appimage (Morevna Edition), running it on Lubuntu 16.04.3, 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz,GeForce 940M, 12GB of ram with the latest opensource drivers.

Let's see if @morevnaproject knows more.

**Comment by sergiofrias** [comment] 2017-08-11 12:49
Thank you @WPFilmmaker ,so i did a few more tests with the oficial 1.1.3 ,the problem also resides in this build... i tried the oficial 1.1.2 release and is working ok. 
I hope the developers can fix this issue on the next release.

**Comment by turtletooth** [comment] 2017-08-11 16:01
Confirmed on fresh build.

**Comment by turtletooth** [comment] 2017-09-09 21:25
Fixed in #1466

**Closed** 2017-09-11 08:01 UTC
Labels: Bug
