### ISSUE TITLE
Unknown publisher listed in the installer

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#2793] opened 2019-09-20 16:23 UTC
### Issue Summary

There is assign publisher to OT in Control Panel Programs.

But it seems don't assign publisher to the installer. maybe some people have trouble with it.

### Screenshot or Video Reference

Control Panel Programs:
![OT unknown publisher in the installer 01](https://user-images.githubusercontent.com/16509592/65342052-2408de00-dbe7-11e9-9df1-198eea57367b.jpg)

the installer (UAC is default in Windows 7)
![OT unknown publisher in the installer 02](https://user-images.githubusercontent.com/16509592/65342059-2834fb80-dbe7-11e9-871e-76e92fbaad78.jpg)

### System Information
* **OpenToonz Version**: 1.3 Stable, NB `55a5931`
* **Operating System**: Windows 7

**Comment by RodneyBaker** [comment] 2019-09-20 18:15
Perhaps this relates to:

**Comment by RodneyBaker** [comment] 2019-09-20 21:21
A likely resolution at least for the Inno Setup Windows installer:

https://stackoverflow.com/questions/3643596/how-to-add-publisher-for-setup

As far as I can tell this issue is only with the Windows installer.

**Comment by artisteacher** [comment] 2019-09-20 22:15
This happens on macOS too. To override and actually run the install, you need to open through the context menu in Finder.
<img width="416" alt="Screen Shot 2019-09-20 at 6 13 37 PM" src="https://user-images.githubusercontent.com/21159116/65361697-8b686300-dbd2-11e9-9ada-543c3fd291ab.png">

**Comment by RodneyBaker** [comment] 2024-05-14 01:40
Closing this as a duplicate of #273 with known workarounds.
This does effect all operating systems.

**Closed** 2024-05-14 01:40 UTC
Labels: refactor / build, known issue, duplicate
