### ISSUE TITLE
'Merge TLV levels' applies wrong style after first frame

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2475] opened 2019-01-10 15:38 UTC
Edit: I meant to write ToonzRaster rather than ToonzVector

Repro Steps:
1. Create 2 or more ToonzRaster levels
2. Use a different color for each level to differentiate them
3. Draw 2 or more frames on each level using the Brush Tool
4. Select all levels and choose 'Merge TLV Levels' from the 'Xsheet' dropdown
5. The first merged frame should be correct, but in all subsequent frames, the lines will have the same style - that of the first level

Also, undoing the merge with Ctrl-Z does not update the viewer, this causes the incorrectly colored lines to remain as such until the user performs an action that causes a refresh.

Image reference:
Frame 2 before merging - each line is correctly colored:
![image](https://user-images.githubusercontent.com/42905003/50978922-535e3b80-14ed-11e9-974a-6bce68858196.png)

Frame 2 after merging - both lines are now red:
![image](https://user-images.githubusercontent.com/42905003/50978868-332e7c80-14ed-11e9-9410-70aaac381cc9.png)

**Comment by RodneyBaker** [comment] 2019-01-10 18:05
Are the palettes for each of these levels the same?
It'll be good rule out that upon merging the color of the one isn't shifting to the next available color due to differing palettes.

**Comment by beeheemooth** [comment] 2019-01-10 18:06
@WolfInABowl Did you mean Toonz Raster Levels?

The problem you describe happens if you change the color of the black default style.
If you create a new style, draw drawings with it and apply Merge TLV Levels then the merge will be successful.

**Comment by beeheemooth** [comment] 2019-01-10 18:13
![ezgif-1-6ef23e88ca25](https://user-images.githubusercontent.com/25724133/50988053-15c0d900-1514-11e9-8c55-ef0e8285a4fd.gif)

**Comment by WolfInABowl** [comment] 2019-01-10 21:07
@beeheemooth Yes I did mean to write ToonzRaster, sorry for the mix-up.
Thanks for letting me know about how to alleviate the issue

**Comment by RodneyBaker** [comment] 2019-01-10 21:44
If this is resolved please close the issue.
It's alway best if the originator closes their own report as that truly gives us a sense that the problem is resolved.

If still an issue in any regard we can fine tune the topic title and description.

**Closed** 2019-01-10 22:23 UTC
