### ISSUE TITLE
posting a  memo make opentoonz unable to save.

### ISSUE THREAD

**Issue by matitanimata** [opentoonz/opentoonz#3956] opened 2021-05-23 09:54 UTC
if you post a memo on the xsheet, when trying to save OT will give you an error, you won't be able to save until you discard the memo.

OT 1.5 on mac pro late 2013 - mac Os Mojave -- (I will try on windows 10 asap) ---

![Schermata 2021-05-23 alle 11 48 12](https://user-images.githubusercontent.com/20012515/119255720-905a9280-bbbd-11eb-9941-6be6d7502a92.png)

**Comment by RodneyBaker** [comment] 2021-05-23 12:43
This has been reported as a Mac only issue although it's not clear why it would be Mac only.

**Comment by RodneyBaker** [comment] 2021-07-08 14:13
@matitanimata  I'm curious if this is fixed in recent nightlies.
Even if not, perhaps #3910 still relates to the bug.

**Comment by artisteacher** [comment] 2021-07-09 01:24
Using Big Sur, I'm getting a crash on saving when there's a memo - both in the latest nightly and releases before #3910. Not a problem on Tahoma. 

[memo-crash.txt](https://github.com/opentoonz/opentoonz/files/6788068/memo-crash.txt)

**Comment by RodneyBaker** [comment] 2022-02-19 10:13
This still appears to be a Mac only issue.
@manongjohn describes the problem in the comments his fix in Tahoma2D.

**Comment by RodneyBaker** [comment] 2022-02-19 10:17
Closing this as a duplicate of #3843

**Closed by RodneyBaker** 2022-02-19 10:17 UTC
Labels: bug, mac
