### ISSUE TITLE
Decreasing hardness causes crash.(gif)

### ISSUE THREAD

**Issue by norrinra** [opentoonz/opentoonz#1926] opened 2018-04-23 01:59 UTC
![untitled](https://user-images.githubusercontent.com/30438394/39103367-05aa152a-46b3-11e8-97e8-57e7042e3900.gif)

[report.txt](https://github.com/opentoonz/opentoonz/files/1936372/report.txt)

**Comment by shun-iwasawa** [comment] 2018-04-23 02:32
Confirmed crash. Thank you for the report.

**Comment by shun-iwasawa** [comment] 2018-05-17 07:27
This seems to be resolved with #1904

**Closed by shun-iwasawa** 2018-05-17 07:27 UTC
Labels: Crash
