### ISSUE TITLE
Missing mypaint icons

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1382] opened 2017-08-06 18:56 UTC
@blackwarthog thanks so much for the mypaint brushes! They are so fun to paint with. I've noticed a couple icons are missing in the style editor:
<img width="339" alt="screen shot 2017-08-06 at 2 36 37 pm" src="https://user-images.githubusercontent.com/21159116/29006001-8a3cc050-7ab5-11e7-9cbe-2809e75a7f85.png">
<img width="307" alt="screen shot 2017-08-06 at 2 36 49 pm" src="https://user-images.githubusercontent.com/21159116/29006002-8c1b0b98-7ab5-11e7-9559-5d70e957358e.png">
The brushes themselves seem to work just fine.

I've tried a clean reinstall, restarting the computer & etc. but the problem remains. It looks like the icons actually exist in the stuff folder's mypaint folders, so maybe it's just a path/naming issue?
<img width="210" alt="screen shot 2017-08-06 at 2 45 54 pm" src="https://user-images.githubusercontent.com/21159116/29006030-1ba5a0c0-7ab6-11e7-8740-094d3fb03817.png"><img width="205" alt="screen shot 2017-08-06 at 2 46 37 pm" src="https://user-images.githubusercontent.com/21159116/29006031-1baf36e4-7ab6-11e7-9955-6e7ca94c8609.png">

I'm using the latest nightly build on OS X 10.12.6.

**Comment by blackwarthog** [comment] 2017-08-07 03:33
This related with behavior of TFilePath parser and dots.
The path `stuff/library/mypaint brushes/kaerhon_v1/smudge_ink(0.7)_sm.myb` splitted to following parts:
Parent directory: `stuff/library/mypaint brushes/kaerhon_v1`
Base name: `smudge_ink(0`
Extension: `myb` 

This functionality uses to parse frame sequences (for ex. /pippo/pluto.0001.gif - name is pluto, extension is gif). But we use TFilePath in many aspects not only for reading and writing frames.

So we need to add two additional methods into TFilePath class: getNameWithExtension, getNameWithoutExtension. And, may be rename TFilePath::getName func, i'm not sure.

@shun-iwasawa, @turtletooth, what you think?

**Comment by RodneyBaker** [comment] 2017-08-07 03:42
Perhaps it might be appropriate for the MyPaint brushes to default to a particular icon if/when a specific icon is not found (assuming it doesn't already).  Then when users create their own brushes but fail to create an icon it will still have a representative image.

I created a few test brush with MyPaint and they immediately appeared in OT.   That's very neat.

Just when I think I have a favor MyPaint brush I discover a new one.  :)

**Comment by morevnaproject** [comment] 2017-08-11 16:26
> Perhaps it might be appropriate for the MyPaint brushes to default to a particular icon if/when a specific icon is not found (assuming it doesn't already)

@RodneyBaker  The problem not with missing icon. The problem is that OT's internal TFilePath parser incorrectly treats filenames (tries to turn them into image-sequences). See message by @blackwarthog above. ^__^

**Comment by artisteacher** [comment] 2017-11-04 06:14
A temporary solution could be to rename the brushes (exchange the period for a dash or underscore).

**Comment by jpturcotte** [comment] 2018-02-26 18:47
Can we have an update on this? @blackwarthog Would you be ready to take it on?

**Comment by artisteacher** [comment] 2018-02-27 14:31
@manongjohn, this looks to be related to what you've been working on.

**Comment by morevnaproject** [comment] 2018-02-27 17:18
@jpturcotte At the moment @blackwarthog is occupied by implementing Assistant Tool bounty.

**Comment by manongjohn** [comment] 2018-02-27 21:54
I've included a fix for this in my current PR addressing seq num saving and detecting.

**Closed** 2018-04-23 04:34 UTC
Labels: UI
