### ISSUE TITLE
Duplicate content in drop down menu - Cell dragging Behaviour

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1454] opened 2017-09-02 16:34 UTC
![duplicate drop-down content](https://user-images.githubusercontent.com/16509592/29997184-2ebc1f46-9022-11e7-9cc8-cdc24894056d.jpg)

**Comment by artisteacher** [comment] 2017-09-02 16:49
This looks like a duplicate of #1276

**Closed** 2017-09-02 16:52 UTC
