### ISSUE TITLE
Deleting or reordering my frames.

### ISSUE THREAD

**Issue by bleptomaniac** [opentoonz/opentoonz#3619] opened 2020-12-05 12:21 UTC
I have two issues with opentoonz. For the most part I find it an alright software, however I've found that sometimes it will glitch out and reorder all of my frames; as in, the spacing stays the same, but the frames are in the wrong order (usually skipped one forwards or backwards.) I also find that sometimes it will just corrupt all of my frames from one of the layers, which can sometimes cost me months of hard work. It shows up as the dots behind the frames being red, and I cannot get them back. I'd love a solution to these problems, though I understand if it's just my computer being bad!

**Comment by RodneyBaker** [comment] 2021-01-07 20:55
Sorry to hear of your problems and apologies for the delay in response.
At this time I can only recommend sharing additional information... such as a screen capture video and/or project file but... even before doing that I would suggest making sure you have tested to see if the problem is resolved in a recent nightly release (the release linked on the official site is a year old and many bug fixes and changes have been made since then).

Link to most recent nightly as of this date:  
https://github.com/opentoonz/opentoonz_nightlies/releases/tag/nightly_fea3b63487f2f339b3cbcfa90776a59ec7d392c3

**Comment by RodneyBaker** [comment] 2022-03-28 04:01
Given the amount of bug fixes and adjustments since this report was first issued it would be good to get an update on this report.  Especially given the timeframe of this report and some particularly nasty bugs that could relate to corrupted scenes hopefully the problems identified have long been resolved.

@bleptomaniac  Are you still experiencing similar issues using recent releases?

**Comment by RodneyBaker** [comment] 2023-07-14 22:30
Will close as a stale troubleshooting issue in need of more information.
@bleptomaniac This may be something others can assist with via one of the Opentoonz discords.
If nothing else it might help firm up the information of the report.

**Closed by RodneyBaker** 2023-07-14 22:30 UTC
Labels: needs info, troubleshooting
