### ISSUE TITLE
where is the Ubuntu (or Debian) PPA?

### ISSUE THREAD

**Issue by nitrofurano** [opentoonz/opentoonz#49] opened 2016-03-26 15:04 UTC
is anyone creating a PPA for OpenToonz? where from can we find it?

**Comment by SajeOne** [comment] 2016-03-26 15:07
#34

**Comment by justinclift** [comment] 2016-03-26 17:32
@nitrofurano It doesn't (yet) compile on Linux.  People are looking into it in #34 though.

Any chance you're skilled/interested with C++? :smile:

**Comment by Samuraiwill** [comment] 2016-03-27 06:42
Install wine and install the Windows version, works nicely if you have the specs.

**Comment by nitrofurano** [comment] 2016-03-27 23:12
thanks! ( @justinclift i really wished to help, my humble coding experience still doesn’t go much longer than “hello world” in Python and Lua... :S )

**Comment by Xananax** [comment] 2016-03-28 08:43
Actually, I tried to get it to run on wine and got crashes. Any pointers on how to make that work?

**Comment by Samuraiwill** [comment] 2016-03-28 09:58
If your specs are somewhere in the i5, i7 range, 64bit, then I assume it's a wine issue.  Try updating wine and install the OpenToonz locally in a folder on your Desktop in Ubuntu. Delete the files for the app in your .wine (Program folder associated with the app). I find troubles and crashes happen in the profile folder of OpenToonz (found in the OpenToonz 1.0 Stuff folder, I believe). It's quite buggy all-in-all.
Once you get it to work, I suggest saving a copy of those files because you will run into issues, especially when drawing and messing around with the menus/layout.

I think it works best thus far with compositing, I've also added an Anime room to unearth all the menus that are otherwise hidden from plain site.  
![playback_start_marker](https://cloud.githubusercontent.com/assets/7943869/14075782/159998b0-f517-11e5-856d-6d197e3b5c1f.png)

**Comment by legocef01** [comment] 2016-03-28 10:00
@Samuraiwill  I installed the windows version on Wine and tried to follow the official tutorial from the old vendor (Digital Video). At the first time, it was correct as you said, but I noticed that the monitor window of scenes, where you see the animation, don't works as expected. When you start the program, you can drag on the monitor scene with the left click and hold. But, if you do a right on this monitor and after tried to drag as before, nothing happens. 
If you start the program with terminal, you can see these errors : 

--------------------------------------------------------------------------------------------
fixme:heap:HeapSetInformation 0x1e74000 0 0x23fcc0 4
fixme:ver:GetCurrentPackageId (0x23f440 (nil)): stub
fixme:console:AttachConsole stub ffffffff
fixme:system:SetProcessDPIAware stub!
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
fixme:wgl:X11DRV_wglGetPixelFormatAttribivARB unsupported 2008 WGL Attribute
fixme:ver:GetCurrentPackageId (0x33f90c (nil)): stub
fixme:ntdll:server_ioctl_file Unsupported ioctl 110004 (device=11 access=0 func=1 method=0)
fixme:wgl:X11DRV_wglGetPixelFormatAttribivARB unsupported 2008 WGL Attribute
fixme:wgl:X11DRV_wglGetPixelFormatAttribivARB unsupported 2008 WGL Attribute
fixme:wgl:X11DRV_wglGetPixelFormatAttribivARB unsupported 2008 WGL Attribute
fixme:wgl:X11DRV_wglGetPixelFormatAttribivARB unsupported 2008 WGL Attribute
fixme:wgl:X11DRV_wglGetPixelFormatAttribivARB unsupported 2008 WGL Attribute
fixme:wgl:X11DRV_wglGetPixelFormatAttribivARB unsupported 2008 WGL Attribute
--------------------------------------------------------------------------------------------

That is just an example among some other minors buggy behaviours of OpenToonz Windows version under Wine. I don't know if it's just me or not, but, I deceided to wait a nice build of OpenToonz under linux as I am seeing that some people are trying to do it. By seeing the content of source code, I think that it will not be very difficult.

**Comment by legocef01** [comment] 2016-03-28 10:09
I have the specs and I installed OpenToonz under a virgin environment folder with Playonlinux

**Comment by Samuraiwill** [comment] 2016-03-28 10:10
I stopped running it through terminal (launching/opening). It seemed to work better for me using the desktop Icon it creates.  Yeah, I would love to see a proper build for OpenToonz Linux.  I know I can't do it, I'm trying to compile book screen captures at the moment with what I can get before it crashes.  I don't think many people are having a lot of luck with this app across all the platforms.  Very odd, I wonder what Ghibli was running this on or are we all being sold this idea.  They used it for Clean Up and Probably colouring.  I would think they would have used AE or Retas Pro! to compile like other Japanese studios.

**Comment by Samuraiwill** [comment] 2016-03-28 10:16
I never heard of Playonlinux, I'm technically a noob but I know wine works for me.  Can you bypass Playonlinux and just use wine?  If you happen to see a build before I do, can you post it here?  I don't know why they left Linux out of the dev.

**Comment by legocef01** [comment] 2016-03-28 10:42
Normally, Playonlinux is the best way if you want to install a program in wine without the disturbance of comming from previous installations on configurations. But I installed as you said, ... same behaviour. 

Me too I wondered. OpenToonz has some old style, and they said that the program Toonz was sold about 10000€ (or $) !!! 

But this program can be the "blender" on 2D animation in free/open source world. ... Do not forget Synfig too!!
 
I hope that Synfig, the free 2D animation software on the place, will take many good things from the source code of openToonz, so that they can rapidly grow and have stuffs that they don't have yet.

**Comment by justinclift** [comment] 2016-03-28 11:14
@nitrofurano No worries at all.  I think we're all looking forward to when this works on Linux/BSD/etc. :smile:

**Comment by odysseywestra** [comment] 2016-03-28 19:33
I'm going to close this since it was originally a duplicate of #34 and is off topic. I would highly encourage you to continue this conversation over on our Google Groups page:

https://groups.google.com/forum/#!forum/opentoonz_en

**Closed by odysseywestra** 2016-03-28 19:33 UTC
Labels: User Support

**Comment by AlyShmahell** [comment] 2017-05-01 19:29
I created such a ppa, the resulting installation works well after changing ownership of the opentoonz local config folder:   
`$USER:$USER $HOME/.config/OpenToonz -R  
`
here is the link:  
[ppa:alyshmahell/opentoonz](https://launchpad.net/~alyshmahell/+archive/ubuntu/opentoonz)  
I hope this helps, be sure to test and send feedback!
