### ISSUE TITLE
OpenGL changes / Performance Optimizations / Lags

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1638] opened 2017-12-02 20:29 UTC
In the Google Plus community, someone posted this video comparing playback in 1.1.3 to the latest OTX which uses the new Q OpenGl changes.  Would those be affecting performance of OpenToonz?

**Comment by manongjohn** [comment] 2017-12-02 21:38
Fyi, Link missing.

I did find and watch it. When working on some of my recent PRs, I did try to compare performance between my local build against the released 1.1.3 I had and didn't see anything like that.  Not sure how complex his scene is vs what I was testing with.

**Comment by turtletooth** [comment] 2017-12-02 21:44
Oops. Link: https://www.youtube.com/watch?v=gxPslhzTXr8&feature=youtu.be

**Comment by BrundleThwaite** [comment] 2017-12-03 05:16
Yes. The Q Open Gl changes are affecting playback which is much slower on my machine (I'm also on a PC, currently i'm running Windows 10 ) with both the nightly builds and the OTX builds.

In my case there is severe input lag as well. [#1592]( (https://github.com/opentoonz/opentoonz/issues/1592).)

**Comment by RodneyBaker** [comment] 2017-12-15 00:48
@turtletooth 
Not that this is something you don't already know but in downloading and installing your modified v1.2 OTX things are definitely faster.

**Comment by manongjohn** [comment] 2017-12-15 02:04
In light of the issues the QOpenGL changes are causing,  I suggest that code should be backed out and reissue 1.2 without it. This way we can take time to vet the changes without feeling rushed to get a proper fix out.

**Comment by turtletooth** [comment] 2017-12-15 03:00
Do you think we should make QOpenGL an option in preferences labeled experimental?  (I'm not even sure there is a way to get preferences to all the files needed.

**Comment by manongjohn** [comment] 2017-12-15 03:12
That's an option.  I believe in After Effects, or some other program I ran across researching openGL and nvidia cards,  it had a setting to use OpenGL or not. I guess this way,  if we find someone is having problems  related to opengl, they can opt out of it without having to drop to an older version. Problem with that is whatever fix needed opengl would be broken.

**Comment by shun-iwasawa** [comment] 2017-12-15 03:18
Yes if we need to revert QGLWidget again, I think QOpenGLWidget-based viewer should be kept somehow, as preference-optional or entirely separate class considering that QGLWidget is obsolete.

To my frustration I couldn't reproduce the problem yet and cannot investigate in which part of the QOpenGL function causes such reported slowness. I'll try to find another machine in my office and run the software.

@turtletooth In your recent OTX did you just revert QOpenGL to QGL, keeping the Qt version unchanged from 5.9? Does it fix the problem?

**Comment by turtletooth** [comment] 2017-12-15 03:25
@shun-iwasawa It's this branch https://github.com/turtletooth/opentoonz/tree/revert
I built it on qt 5.6, but I don't see any reason it wouldn't build on 5.9.

I'd definitely like to keep QOpenGl as an option.

**Comment by turtletooth** [comment] 2017-12-15 03:27
I can try a test build on 5.9 and ask some folks who have the issues to test it out.

**Comment by artisteacher** [comment] 2017-12-15 03:43
I hope you all can figure out the problem quickly! On the positive side, 1.2 is a significant improvement for the OT experience in OS X.

**Comment by turtletooth** [comment] 2017-12-15 04:33
@shun-iwasawa @manongjohn Here is a build with the same branch on 5.9
https://drive.google.com/file/d/1fx6ZEzraweA1m3XxZZFY4Grem6gDRO01/view?usp=sharing

I don't get the glitches on my hardware, so I can't tell if there is a performance difference.

**Comment by manongjohn** [comment] 2017-12-15 04:47
@turtletooth Confirmed my issue (blank viewer) is still working correctly with the build on 5.9.

**Comment by jpturcotte** [comment] 2017-12-15 20:01
@turtletooth Grimik on Discord says the Qt 5.9 build does not lag either.

**Comment by shun-iwasawa** [comment] 2017-12-27 03:16
I'm tackling with rewriting all the graphics functions based on OpenGL 3.3 core profile. It seems to take a few more weeks.

**Comment by manongjohn** [comment] 2018-01-04 02:03
If it's going to be a few more weeks before the rewrite is done, we should take several weeks after for testing by a few people on different platforms before it goes live to the general public.

If it's going to take that long, we really should apply the reversion code to the core OT installer and only redirect to Morevna or OTX for users that have issues related to that platform.

Seeing some reviews of 1.2 and the increasing number of reports of the same show-stopping issues, really makes OT look really bad. In my opinion, It's killing the excitement of the new/fixed stuff that was also in this release that wasn't impacted by the OpenGL change.

**Comment by BrundleThwaite** [comment] 2018-01-04 05:25
I will test as much as possible. But It will depend on how much work I get (I work freelance). If I had not been in production I would have found this issue earlier.

**Comment by gab3d** [comment] 2018-01-04 06:47
@manongjohn 
I agree.

**Comment by RodneyBaker** [comment] 2020-01-31 14:31
Most of this report dealt with QOpenGL issues related to v1.2.
I'm not sure of current status.
Recommend review.

**Comment by RodneyBaker** [comment] 2022-12-23 04:59
Closing as outdated with recommendation to open a new report on any OpenGL optimization efforts.

**Closed by RodneyBaker** 2022-12-23 04:59 UTC
Labels: bug
