### ISSUE TITLE
Avast antivirus:  Blue Screen with Opentoonz installation

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3204] opened 2020-04-01 16:05 UTC
### Issue Summary

Something that has happened to me in the past few days, unfortunately several times.

When I install opentoonz and its NB variants, I get a blue screen and my PC crashes without my being able to do anything about it. This seems to be due to the fact that the installer is not signed. I had to create path exceptions in avast to prevent this from happening again. The weird thing is that it hadn't happened before.

I cannot determine the cause.
### Expected Results

No crash

### System Information

Windows 10
cintiq companion 8 
8 g
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment] 2020-04-01 16:36
Possibly relates to #2793 and #273

The following is somewhat unlikely to be related but I've been curious...
@openanim If not too much of a pain and you could temporarily remove those path exceptions from your antivirus software...

I'd be interested in knowing if Opentoonz check for updates is in any way causing some of these reported issues.  The way to check would be for someone on those systems to turn off the update check in Preferences and report if the presumed antivirus problem still persists.

Thus far those that have reported the issue haven't provided feedback which can be used to gauge the degree of success or to validate the cause of the issue.

So... if you find yourself with lots of time to spare...   ;)

The point being that I would expect most antivirus not to like the telemetry check for updates.
This likely can only be validated via those systems that have more restrictive antivirus settings set.

**Comment by openanim** [comment] 2020-04-01 18:17
So you ask me if I want to crash my pc again :) ?

I will try to see that in the next few days. I just have to uncheck  

> the check the latest version of Opentoonz at launch  option ? 

I also have an 

> automatically refresh the folder contents

 I don't know what it is purpose but it is also check. I also uncheck ?

**Comment by openanim** [comment] 2020-04-02 15:24
I tried it by uncheck all but same thing happened
![20200402_171558](https://user-images.githubusercontent.com/29790512/78266935-b418d000-7506-11ea-99db-d2b34ce8a527.jpg)

**Comment by manongjohn** [comment] 2020-04-02 16:15
I have this problem with Avast when installing new versions of OT or variants as well.  

Normally, when opening it for the 1st time after install, Avast tries to scan it.  When Avast starts scanning it, I normally kill the scan right away. Then I get a CyberCapture popup. In the popup I would click on "More details" to expand it.  I would then, uncheck the "Upload file to Avast..." and click "Run anyway".  After doing that it doesn't try to scan it on launch anymore.

When OT runs it tries to run lzocompress.exe. and lzodecompress.exe when using any type of raster level.  When those are encountered for the 1st time, Avast tries to scan each one as they start up.I have to do the same thing again...killing it quickly and then dealing with the CyberCapture popup.  If I don't kill the scans, that's usually when OT crashes on me and sometimes leads to BSD (blue screen of death).  Usually after doing that once, it doesn't scan anymore.

Unfortunately I think it's what Avast is doing with OT while it is scanning it that causes the problem.  Avast likes to move things aside temporarily when scanning which is a problem for OT when the process it was expecting suddenly disappears or doesn't run like it expected it to. OT typically crashes in that case and may cause BSD.

**Comment by openanim** [comment] 2020-04-02 18:54
@manongjohn 

>  If I don't kill the scans, that's usually when OT crashes on me and sometimes leads to BSD (blue screen of death). Usually after doing that once, it doesn't scan anymore.

This is exactly what was also usually happening to me, unfortunately now I don't have time to do anything as soon as the pop arrives my PC crashes.

I do not know what can explain this change.

**Comment by manongjohn** [comment] 2020-04-02 19:13
> I do not know what can explain this change

I've used Avast for many many years. Avast has changed over time adding new measures and such to catch stuff with good reason.

I usually keep my mouse pointer close to where the Avast popup display so i can get to them quickly and close them. I guess the alternative is to put an exception path.

**Comment by RodneyBaker** [comment] 2022-03-29 09:36
Closing as a duplicate of #2793, #273 and others.

**Closed by RodneyBaker** 2022-03-29 09:36 UTC
Labels: crash, known issue, workaround, referral / thirdparty

**Comment by RodneyBaker** [comment] 2022-04-01 22:06
Tagging as roadmap to make sure we explore best practices for playing nice with antivirus programs.
