### ISSUE TITLE
ToonzRaster Tape Tool crash

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#3088] opened 2020-02-03 20:35 UTC
gif example:
![Tape Crash](https://user-images.githubusercontent.com/42905003/73688733-8f4ddb00-46c4-11ea-9dd8-505dbf322cf3.gif)

The crashes triggered by the tape tool aren't super predictable but I have come to a fairly reproducible method.

Notes:
Normal mode does not trigger crashes.
Large target areas do not seem to cause crashes.
The tighter the target area around the gap, the more likely the crash.

Repro steps:
1. Create a new ToonzRaster level
2. Draw a shape with a small gap
3. Using the Tape Tool in Rectangular, Freehand, or Polyline mode, draw a target area that is tight around the gap.

OT will likely crash, otherwise the taping failed and you can try again

This gif shows that the large target areas close the gap without issue, however the tighter target area (after a few attempts) causes a crash upon attempting the close the gap:
![Tape Crash 2](https://user-images.githubusercontent.com/42905003/73689037-3d598500-46c5-11ea-9e2f-55ff3156f48c.gif)

Attached is a level for testing purposes
[Tape Crash Level.zip](https://github.com/opentoonz/opentoonz/files/4150195/Tape.Crash.Level.zip)

Edit:
OS: Win 10
OT Ver: Jan 24th Nightly

**Comment by beeheemooth** [comment] 2020-02-04 00:41
@WolfInABowl I downloaded your level, but I could not reproduce the crash, no matter how I tried.
Do you use a stylus or mouse? What are the settings of the Tape Tool? You did not specify your OS.

**Comment by gab3d** [comment] 2020-02-04 02:52
Well I have to say that: 
- I cannot make the Tape tool work in a "visible manner" in Toonz Raster levels
I mean, the Tape does close the gaps, but it doesn't show anything at all. The drawing seems to be open, but you can fill it.
- The Gap Check option doesn't show anything either; the only way to use it is to activate the Fill Check and see when it turns "fillable".
Gap Check activated, and Distance high enough to show the closing line:
![imagen](https://user-images.githubusercontent.com/18104091/73709052-d0eb7f80-46de-11ea-8f19-dae22c8e4480.png)
Fill Check & Gap Check activated, same conditions:
![imagen](https://user-images.githubusercontent.com/18104091/73709091-e82a6d00-46de-11ea-98fc-c3a4b0293f8c.png)
Tape Tool has filled the gap (but it isn't showing at all):
![imagen](https://user-images.githubusercontent.com/18104091/73709452-e614de00-46df-11ea-8fcb-1024278c91f2.png)
Tape Tool options used:
![imagen](https://user-images.githubusercontent.com/18104091/73709550-283e1f80-46e0-11ea-92ef-6849683ca5f7.png)


- Gap Check does show a very thin line in vector levels, but I think it should be much more notiecable also.
Gap Check activated, and Distance is high enough to show the closing line:
![imagen](https://user-images.githubusercontent.com/18104091/73708967-9255c500-46de-11ea-93b0-551dc7044909.png)

System: Windows 10 + GeForce 650M
OpenToonz: 1.4 (from the official web page).

**Comment by gab3d** [comment] 2020-02-04 02:53
I could not reproduce the crash.

**Comment by beeheemooth** [comment] 2020-02-04 10:43
@gab3d Increase Opacity

**Comment by WolfInABowl** [comment] 2020-02-04 12:53
I've included my OS and OT version above.
I am able to trigger the crash with both mouse and stylus.
Increasing the Tape Tools Distance setting may affect the likelihood of crashing, in the two above examples, I have it 85.

**Comment by RodneyBaker** [comment] 2020-02-04 16:42
I can't repeat the crash but I do recall having to adjust the Angle setting in order to get the think line of 'tape' to appear.  Although now that approach to seeing the line doesn't seem to be the case.

Interestingly...
If I select the gap via rectangle... TWICE... the line appears on the second pass!

**Comment by gab3d** [comment] 2020-02-04 17:32
@beeheemooth 
> @gab3d Increase Opacity

haha  thanks for pointing it out! 
well... I'm ashamed now 😸  I didn't even looked at the value of Opacity, as I assumed it wouldn't have anything to do with the problem. 😅

It's good to know the tool is working, still, perhaps the Opacity option should be set at 255 by default? So users (specially new or distracted ones like me) could see the tool is working...?

**Comment by gab3d** [comment] 2020-02-04 21:14
For the time being I've added a couple of Notes to the Manual warning users about the Opacity setting [effects on the tool](https://opentoonz.readthedocs.io/en/latest/painting_animation_levels.html#closing-gaps-in-drawing-outline) and in [Gap Check behavior](https://opentoonz.readthedocs.io/en/latest/painting_animation_levels.html#checking-gaps-in-the-drawing-outline).

**Comment by beeheemooth** [comment] 2020-02-05 00:32
On the contrary, it seems reasonable to me that this straight, thin and terrible line is not visible, because we cannot influence its thickness and cannot bend it. The objective of this line is purely technical - to close the gap to fill was possible

**Comment by RodneyBaker** [comment] 2021-02-02 14:20
Posting a note to point to the section of code where this issue can be addresssed:

https://github.com/opentoonz/opentoonz/blob/86e8a1aec9025e923b54d09386ff6d85ef87a5ed/toonz/sources/tnztools/rastertapetool.cpp

**Comment by shun-iwasawa** [comment] 2022-02-24 10:14
Hmm I could not reproduce the crash so far.

**Comment by RodneyBaker** [comment] 2022-09-07 09:35
Attempting to reproduce this again I could not... UNTIL... I downloaded the file @WolfInABowl posted and tried that again.

Attached is the crash report I got:
[TapeToolCrash.txt](https://github.com/opentoonz/opentoonz/files/9504807/TapeToolCrash.txt)

**Comment by RodneyBaker** [comment] 2023-05-27 11:32
@WolfInABowl Are you still seeing this crash in latest releases.
I'm no longer able to reproduce the crash.

**Comment by RodneyBaker** [comment] 2023-06-21 18:01
Closing as a stale report but...

@WolfInABowl please let us know if you are still experiencing this problem with Tape Tool.
As others have had a hard time reproducing this crash it will be good to know more about your the system being used as well.

**Closed by RodneyBaker** 2023-06-21 18:01 UTC
Labels: bug, crash
