### ISSUE TITLE
Crash drawing brush preset

### ISSUE THREAD

**Issue by JaviAledo** [opentoonz/opentoonz#3575] opened 2020-10-31 11:17 UTC
**Describe the bug**
Drawing on raster layer, when I change custom preset brush to a saved preset, and then drawing a new frame or on existing frame, it crashes and close.

**To Reproduce**
List steps to reproduce the behavior.
1. New raster layer
2. Modified brush (custom preset)
3. Select a saved brush preset
4. Draw new raster frame
(sometimes crash, and sometimes no)

**Expected behavior**
No crash

**Screenshots**

**Device Information:**
 - OS: Windows 7 64-bits pro and Windows 10 64-bits pro
 - OpenToonz Version: 1.4
 - GPU: AMD FirePro M4170 (on laptop), Nvidia Quadro M5000 (on workstation)
 - GPU Driver Version: 
Laptop
Direct3D 9.14.10.01261
OpenGL	 6.14.10.13476

Workstation
R450 U5 (452.57)

**Comment by RattusaurusRex** [comment] 2020-11-01 03:03
Here is the crash I get:

![preset_crash](https://user-images.githubusercontent.com/60277069/97794197-111b5800-1bb4-11eb-98b8-6aec17ca8e9d.gif)

**Comment by beeheemooth** [comment] 2020-11-01 11:13
In 8.1 this work fine

**Comment by RodneyBaker** [comment] 2021-01-07 21:32
This should be resolved in current nightlies. ([LINK](https://github.com/opentoonz/opentoonz_nightlies/releases))
@JaviAledo Can you confirm the problem is still present in current nightly releases? 
Closing pending confirmation this is still a problem.

**Closed by RodneyBaker** 2021-01-07 21:32 UTC
