### ISSUE TITLE
Texture Settings don't work

### ISSUE THREAD

**Issue by bencresty** [opentoonz/opentoonz#4541] opened 2022-09-19 09:47 UTC
### Description

When changing the settings of a texture (like a custom texture) nothing changes in the actual texture used in the viewport. It doesn't matter if this is a preset texture or a custom one.

The texture settings DO work internally and the texture preview in the styles panel DOES show the actual result after changing the settings and so get updated as expected. But the update doesn't reach the actual usage of the texture. When using the texture (or looking in the viewport to see an already used texture on a vector layer in action) nothing has changed. It doesn't matter if we're in preview mode or not.

The only setting that does work, at least here, is 'Load from File' to load a custom texture from image. But unless I'm missing something here, textures are pretty useless when it's impossible to change things like scale, repeat etc.

I would find it hard to believe no one ever tried textures in OpenToonz and found out it's not working. So am I missing something here or is this really not working after so many years?

### Steps to Reproduce

1. Create a vector level
2. Draw something to fill
3. Go to texture-tab in the styles panel --> click a texture
4. Go to the Settings tab in the styles panel --> Try changing any setting, like scale, rotation...
5. Look in the little preview in the styles panel to see the style changes after changing settings
6. look in the viewport to see that nothing changed in the actual usage of the texture
7. to be sure: just draw something new and apply this texture to it; same result; the changed settings are ignored

### Expected Behavior

I would expect this to work. So changes in the settings should be reflected in the actual usage of the texture.

### Screenshots, Video & Crash Logs

![image](https://user-images.githubusercontent.com/69322733/190991447-f3dabc42-1ac7-4bfb-af97-ce7e53c7b057.png)

![image](https://user-images.githubusercontent.com/69322733/190991565-5b5f9538-abe7-4758-981c-923748ebc559.png)

![image](https://user-images.githubusercontent.com/69322733/190991699-f1fd22c2-5244-43d8-86f9-ff99d16341fa.png)

### OpenToonz Version

1.6

### OpenToonz Version Information

built Apr 4 2022 10:30:14

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment] 2022-09-19 12:39
Yes, this was identified early on as an area that fell short and needs improvement.

By all means feel free to continue the discussion however as it rarely good for a user to be surprised (in a negative way that is!).  There are however many issues that simply haven't gotten on a developers 'must address' list.  This can especially be true of processes that have reasonable work arounds where a feature can still be used in some other way.  Textures are one of those.


Will close this as a duplicate of #603.
We use to have a duplicate tag but after years only a very few actual duplicate reports existed so the label was removed.
In some cases those issues were addressed or rewritten to form more unique views on similar but sufficiently different aspects of a feature.  In those cases we might tag the report with "relates to #603" and leave the report open until the matter can sufficiently be addressed in the other report(s).

Aside:  As you can see from the number of reports there are more than a few 'little things' that developers can cut their teetch on whilte getting familiar with the Opentoonz code.  There certainly is no lack of things to update/fix/improve!  :)

**Closed by RodneyBaker** 2022-09-19 12:39 UTC
Labels: bug

**Comment by bencresty** [comment] 2022-09-19 13:46
@RodneyBaker  tbh I wouldn't even know what to discuss in this case. It's clearly not working at all on vector layers. Solution seems simple to me; 1) hide non-working stuff from the user (if 'vectorlayer' than hide = 2 minutes programming for a dev knowing this code base?), 2) throw a warning to the user this isn't working on vector layers (if vectorlayer than show warning = 2 minutes programming for a dev knowing this code base?) or 3) make it work on vector layers (I understand that takes way more time and can be really complicated as you have to deal with some things like adding raster textures to vector or even vector inside vector). 

That the UI should tell the user it's currently not possible to use textures on vector layers doesn't really seem rocket science to me and a no brainer. It boggles me why you don't do things like that, especially when thinking UX and user-focussed and obviously many people were confused by this and put time and effort in trying to make this work.

Sure there are a lot of issues open. And I'm sure you're working hard on them and thanks for that. But at the same time the software crashes a lot and has a lot of these kind of weird things we don't expect from animation software in 2022. So you could say the list of issues explains the long awaiting of fixes, but at the same time you could also ask yourself why all these issues are (still) open and why there are (still) so many crashes and issues. No judgeing at all because I don't know you guys, I don't know how much time you spent and I don't know the state of the software when it was open sourced in 2016, and again, I'm sure you guys work very hard and probably are with way too little people to do things. 
Just an observation. Because this software has great potential, but it's pretty difficult to use when things like this aren't working. 
That said; Thanks for all your hard work and I understand this is probably a side project and you have your day jobs too. Keep it up.

**Comment by RodneyBaker** [comment] 2022-09-19 14:05
The solution is always simple right?  Most solutions are.
That doesn't explain why obvious (and not so obvious issues) they don't get implemented though.  ;)

The important thing (for us as users to do) is to identify the shortfall which is exactly what you (and others) have done.
My own personal belief is that a generation of user/developers will likely have to arise that know enough about the code base to adjust the source to the expected outcome.

@manongjohn (who manages and maintains the Tahoma2D fork of Opentoonz has stated how he as a developer tends to approach such problems (and I paraphrase here): "As a developer I work on two kinds of issue:  1) Things that interest me 2) Things that bother me to the point where I have to address it."

Given that (useful) description it then becomes our task to present issues in a way that potential developers can easily recognize one of those two aspects.  Then it's largely a matter of being comfortable enough with the code to dive in.  This and having the time to devote to that of course.

It can help that while a developer is in the code working on some other issue they are aware of related issues.  Then it becomes easier to also address those issues.

Although many issues have been addressed... vector related issues have never quite had a dedicated champion attached to Opentoonz source code.   

As for why issues don't get addressed... and how they have been addressed in the past... that has been discussed at length in many venues.  If you've posted a report of an observed issue (and you have!) then you've done your job as a user to get the information/feedback flowing.

And... a belated welcome to the Opentoonz community.  :)

**Comment by openanim** [comment] 2022-09-19 18:56
@bencresty . The parameters and its animation is only available for tlv levels ( toonz rasters levels). There are also a Texture Fx  for the toonz levels if need, It's something you can find on manual guide also.

**Comment by RodneyBaker** [comment] 2022-09-19 21:59
As a follow up to @openanim's information...
@DarrenTAnims has a youtube video that covers most of the differences that exist when using textures in the various level types.

https://www.youtube.com/watch?v=jhK5G6XWrqY

**Comment by bencresty** [comment] 2022-09-19 23:25
@openanim @RodneyBaker  thanks for the responses and welcome message!

**Comment by manongjohn** [comment] 2022-09-20 02:34
> @manongjohn (who manages and maintains the Tahoma2D fork of Opentoonz has stated how he as a developer tends to approach such problems (and I paraphrase here): "As a developer I work on two kinds of issue: 1) Things that interest me 2) Things that bother me to the point where I have to address it."

Just to clarify something as this kind of makes me out to be somewhat self-centered (I don't think it wasn't intentional)...while it is true that I have stated the above, it was mostly as a joke.  I have always tried to address stability, user's pain points and quick quality of life enhancements above any personal interests of mine. I picked stuff I knew I could handle or do in the limited time  I have to work on stuff. It wasn't just because it interested me or bothered me enough to fix it...though it did certainly help me focus on it more. :)

**Comment by RodneyBaker** [comment] 2022-09-20 14:05
I definitely didn't/don't see you as self centered @manongjohn.  Quite the opposite.  Github history itself attests to that more than I could ever capture.  The main reason I 'quoted' you is because I liked the way you stated your development approach (even if it was mostly as a joke when you wrote it) as it read as a developer being practical (especially given limited amount of time to devote to development) and presents a fairly clear way forward when posting feature requests;   find ways to document the requested feature so that it is of compelling interest to potential developers.  Illustrate why this particular request should reasonably be of a higher priority than other requests.  As you suggest... where the pain points are that make the request truly compelling and of obvious necessity.   Etc. etc.   :)

With some 600+ reports open at present (and more on the way every day) I was mostly expressing why requests that surely should only take two minutes to implement can be expected to take more time than that.  My apologies where I've failed in adequately stating that.  ;)
