### ISSUE TITLE
[Feature Request] Implement OpenFX compatibility

### ISSUE THREAD

**Issue by tushantin** [opentoonz/opentoonz#2137] opened 2018-07-04 11:32 UTC
While researching OpenFX plugins that I could use for Natron it occurred to me that plenty of other OpenFX plugins can also be used with Toon Boom Harmony, and now that I think about it, it can actually be pretty useful to expand the possibilities that can be achieved in a 2D Animation software and perhaps even skipping the Compositing the process in an external software. 

OpenToonz already has an FX Schematics, and I believe -- once integrated with OFX compatibility -- it can be extended to include FXs from a variety of different people who produce it and not just be reliant on OpenToonz developers to create similar variants of them in the software itself. (Then again, I only say this because I do not know how difficult it is to create an OpenToonz FX plugin compared to an OpenFX plugin that is platform dependant, and that platform dependency is what makes it a bit uncomfortable for me). 

Anywho, I just thought I'd post this to encourage further discussion on this, and whether the software may benefit from the feature / compatibility.

**Comment by artisteacher** [comment] 2018-07-04 12:56
I think it's important to get the current FX to be much more stable first.

**Comment by RodneyBaker** [comment] 2018-07-04 13:42
This is a duplicate of https://github.com/opentoonz/opentoonz/issues/419 but development in the direction of OpenFX is certainly to be encouraged.

Having said that I am slightly opposed to the idea of duplicating features found in other freely available software for a number of reasons and I'll list a few.  I realize the benefits of doing everything inside one program but with limited resources and such, practical goals must always be considered

where other programs enjoy considerable development the duplication of effort can be unfortunate and while the effort may include many positive outcomes some negative outcomes also occur.

The nature of competition in open source software is still something being worked out and there aren't a lot of case studies describing it's variables.  Where other software freely available is also taken into account things can get even more complicated. 

Some of the pros and cons include:
- Number and support of programmers
- Dispersion of users
- Duplicated code and effort
- Competing brands and user bases
- Waiting for or Demanding features that already exist in other products
etc.

Those are the subjects that immediately come to mind.
Before going on let me reiterate that I do think OpenToonz would be a much better program with OpenFX plugins incorporated.  We can also say this about almost any other feature though.  So how best to chart a path forward?

We can guess the number of users and that of programmers is rising across the board for creative software such as OpenToonz.  There is some competition for these users and programmers because of diversity of product, personal interests, sense of community, financial backing, etc.  

Competition is generally good for products but does splinter the larger base of users and programmers.  I suppose a question to ask would be whether the competitors are 1) aware of their competing natures 2) aware of how their product fits into that larger scheme of competition. 3) able to communicate with competitors to benefit of all parties involved.  The nature of competition suggests that at the end of the day only one must win and that certainly need not be the case.

One of the reasons communication with competitors is important is to reduce potential waste in duplicating code and to support programmers.  The support I mention here is not only that of well seasoned and knowledgeable programmers but to encourage new programmers and supply educational opportunity.

Reduction of duplication of code is one of the reasons why OpenFX was created.  Where these specialized processes are maintained expertise can focus on one area of code shared by all.  This is likely the primary advantage of incorporating OpenFX into Opentoonz. 

The last item I listed was that of waiting for features that already exist in other progams and this would appear to be the stage where we live.  It may be that in order to move beyond this stage we have to examine the other things in the list as well starting with drawing and publishing the paths to products that already supply the desired feature set.  Then a proper path forward can be established that more specifically addresses OpenToonz capabilities and feature set.

**Comment by gab3d** [comment] 2018-07-04 16:09
I think there are currently two main aspects of OT FXs that need to be considered:

1. FXs that work with Toonz levels and data.
2. FX slow rendering perfirmance. (and that could lead to GPU rendering as a solution)

If OpenFX is to be implemented inside OT I think it should be capable to address these to issues. i.e.
1. OpenFXs be able to access and work directly with Toonz levels data (and any other relevant OT data in the rendering pipeline).
2. Improve rendering speed of FX, be though GPU or CPU rendering.

If that is not the case, then we will face constant duplication of efforts and possible incompatibility between the current architecture and the OpenFX one, when users try to mix several FX in the schematic.

**Comment by RodneyBaker** [comment] 2018-12-03 21:32
Closing this as a feature request duplicate of #419 pending more research and development.

**Closed by RodneyBaker** 2018-12-03 21:32 UTC
Labels: Duplicate, Feature Request
