### ISSUE TITLE
OPENTOONZ CRASHED WHEN IM EDITING, NOW OPENTOONZ IS CRASHING WHEN I OPEN THE SCENE

### ISSUE THREAD

**Issue by GRACEanims729** [opentoonz/opentoonz#3536] opened 2020-10-16 05:57 UTC
I am currently working on an animation when i insert an image, opentoonz suddenly crashed. now, when i open my scene, it crashes but when i try to load another scene, i can still open my file.

I hope that you can help me solve this problem. i know that i can still recover my files because when i try another scene, opentoonz doesn't crash except for one specific scene.

this is another scene that i can still open
![image](https://user-images.githubusercontent.com/72960710/96218016-a70a7e00-0f38-11eb-8209-09bd865e532d.png)
 
this is the scene that kept on crashing. i'm afraid i lose all my files
![image](https://user-images.githubusercontent.com/72960710/96218157-08cae800-0f39-11eb-8a9a-3799d98820dc.png)

**Device Information:**
 - OS: Windows
 - OpenToonz Version: 1.4
 - GPU:  Intel(R) HD Graphics 5300

**Comment by RodneyBaker** [comment] 2020-10-16 17:37
Please do not use all CAPS in your titles @GRACEanims729 as that implies screaming/yelling.
Thanks!

This sounds like a problem that has been fixed in current nightly releases.
https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by RodneyBaker** [comment] 2020-10-16 17:38
Closing as a duplicate of https://github.com/opentoonz/opentoonz/issues/3535

**Closed by RodneyBaker** 2020-10-16 17:38 UTC
