### ISSUE TITLE
Feature: Hand-drawn Animation Auto-Complete

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#926] opened 2016-11-18 16:55 UTC
In my graduation project me and my team are going to implement the Hand-drawn Animation Auto-Complete research: [click here to see video](https://www.youtube.com/watch?v=w0YmWiy6sA4).
This research is based on this one: [click here to see video](https://www.youtube.com/watch?v=m7MEAw46Ojo).

I think it would be easier if we start it from scratch so that the code base would be smaller and more manageable. But at the same time it would be kind of a waste. So we were thinking maybe we could add this feature to opentoonz. Opentoonz has a wonderful qt5 code base. But it's huge and we will spend so much time trying to be consistent with the rest of the code.

The question is: Would you guys be willing to merge this into the master branch if we do it, or would that be against any of the design philosophies of the program?
If you would be willing to merge it then we will definitely start to work on it.
If not then I guess we'll just start from scratch.

Also if you guys have any ideas, comments or critics we would love to hear them.

PS: we're big fans of opentoonz. Thank you for the masterpiece software.

**Comment by turtletooth** [comment] 2016-11-18 17:23
This looks great.  I think it would be awesome to integrate this into an existing product rather than creating a separate piece of software.  I am one of developers here, but I don't have the power to make the big decisions, but I don't see why something like this wouldn't be accepted and merged.  It would only make the program more functional and capable.  

I would love to see this implemented.  I don't think it competes with the design philosophies since OpenToonz is designed to work with many animation workflows.

Thanks for sharing the possibility and I'm excited to see what happens.

**Comment by lordadamson** [comment] 2016-11-18 17:57
That sounds encouraging, thank you :D.
So do you advice we start working on it right away or should we let one of the decision makers know first?

**Comment by blurymind** [comment] 2016-11-18 18:17
I'd say get it started :)
But it would be of course good to study the code base of some of the
relevant tools where this could be integrated. Opentoonz has for example a
basic tweening capability.

If you manage to get a functional prototype of this running in opentoonz
the likelyhood of merging it to trunk is high- as it is a valuable feature
indeed. @shun-iwasawa is one of the core devs and has merged other
contributed features in the past- sometimes with some refactoring after the
functional prototype

**Comment by lordadamson** [comment] 2016-11-18 18:22
Yes indeed. If we want to get it merged we'll have to have you guys see what we're doing and constantly get your feedback. Because I know we are going to get things wrong at the beginning, especially because we're not familiar with the code base. And this is the first time we code anything similar.

So what parts of the code would you recommend we start looking? @blurymind

**Comment by turtletooth** [comment] 2016-11-18 18:52
I think it should be safe to start working on it.  The other developers have been very open to adding useful functionality to the program.  There has already been strong interest in adding some of the guided drawing features and your solution seems quite powerful.

As @blurymind mentioned - OpenToonz has basic tweening (as shown in this video: https://youtu.be/eFcXj90vWNw )

I think that the system you are working on is more powerful than the current system, and gives the user more control, but keeping the two or maybe even integrating them would be good.

OpenToonz has three different layer types- vector, Toonz Raster and normal raster.  The inbetweening I mentioned works in vector layers by analyzing strokes (and the order they were drawn) and determining in betweens.  

The ToonzRaster layer is a powerful raster layer that has the freedom of raster drawing but keeps color information separate.  This allows everything painted with a certain color to be changed easily in the style editor.

Raster level is a basic raster level without the easy color changing ability but greater control over brush softness and blending.

I can see arguments for adding your system to each of these levels, but I think that either vector or toonz raster make the most sense as I think these are the levels that are used most.  There was a brush smoothing option PR that was adding during the summer that was added to these two level types.  It was made by  @walkerka #432 .  Looking at that PR might give you a place to start looking for where to hook in.

Thanks again for considering adding this in.

**Comment by turtletooth** [comment] 2016-11-18 19:04
I think I would recommend starting with whatever type of drawing you research is based on.  If it is vector based, I would start there.  If raster, I think ToonzRaster would be a good place.

**Comment by lordadamson** [comment] 2016-11-18 19:58
The researches I'm implementing are independent of layer types. It can even be applied to 3D stuff. So it is up to me to choose whether we implement it to the toonz raster or to the vector layers.
But I'd love to hear your opinions on this.

**Comment by turtletooth** [comment] 2016-11-18 20:23
I think that a lot of inking work is done using raster layers while it seems that Toonz Raster is often used for scanned traditional work.  It seems that your tool could help make inking and/or digital frame by frame go faster, so I think vector might make sense, but I would also love to hear from other users. @rayek @konero @blurymind @adamearle What do you think?

**Comment by blurymind** [comment] 2016-11-18 20:37
It will have to be vector. Tweening does not work for any of the other
level types

**Comment by shun-iwasawa** [comment] 2016-11-21 02:22
@lordadamson
Our major aim to launch OpenToonz project was to develop a new platform for connecting the academic research into front-line of animation production. (As noted in [OpenToonz Website](https://opentoonz.github.io/e/).)
Your proposal is highly welcomed and I hope you would utilize this software to get feedback from users to improve your research.

**Comment by lordadamson** [comment] 2016-11-21 07:02
That's amazing and indeed a very encouraging beginning. We've already started crawling the source code. I hope we'll get good results. I'll close my issue now since all of my concerns and questions were answered. Thank you all :))

**Comment by blurymind** [comment] 2016-11-21 12:51
@lordadamson You could keep it open and use it to present progress reports and get feedback from developers and users.

Keeping it up will also increase the chance of having more developers see it and be able to help you implement it.

We usually close an issue when it is not being worked on, it is confirmed to be a duplicate or it has been solved and merged (when feature request)

**Comment by lordadamson** [comment] 2016-11-23 10:26
Okay then, sounds like a plan :D I'll reopen the issue and update you guys with our progress.

**Comment by artisteacher** [comment] 2016-12-08 19:11
This would be an amazing enhancement! It would really speed up the animating process for my students.

**Comment by dadoprom** [comment] 2016-12-21 22:16
Yes please, yes, would be cool to have this!

**Comment by hedayasamy** [comment] 2016-12-25 16:14
Hello, I'm on the same team as @lordadamson, and based on the researches, our project is hugely based on extracting sample points from users' operations (i.e strokes, hatches,.. etc)... And after reading and understanding the code a bit, we've stumbled upon the function "extractStrokeControlPoints" in the tstroke.cpp file, so our question is what do "ControlPoints" represent when the user draws for example a curve? we've gathered that they are of type "TThickPoint" but that brings another question why aren't they of type "TThickQuadratic"?... Thanks in advance.

**Comment by lordadamson** [comment] 2016-12-27 13:48
@turtletooth @blurymind @shun-iwasawa We'd appreciate it someone would clarify the difference between TThickPoint and TThickQuadratic.

**Comment by turtletooth** [comment] 2016-12-30 05:58
I think that @shun-iwasawa or @ideasman42 might be your best bet for this.  I don't know the details about how drawing is done in OpenToonz

**Comment by blurymind** [comment] 2017-01-03 14:06
I think yes, @turtletooth is correct. Those two know the internals the most to my knowledge

**Comment by ideasman42** [comment] 2017-01-03 17:12
@lordadamson, these kinds of questions you can find the answer from 5-10min reading over the classes and see how they're used.

If there is some aspect thats not clear, its fine to ask about of course - but asking how 2 classes differ... you're really better off reading the source then waiting a day or more for an answer.

Further, if you plan an advanced project like this - you're going to have to read a lot of code to properly integrate your changes.

This is not to be rude or tell you not to work on this, just that explaining code internals is very inefficient in this format. Unless you need to ask about some big-picture stuff thats not clear.

**Comment by turtletooth** [comment] 2017-01-15 03:53
I wanted to check in and see how this was going.  Were you able to get your questions figured out?

**Comment by lordadamson** [comment] 2017-01-15 08:42
@turtletooth Hey man thanks for your concern :D Being college students me and my team are currently going through exams, that's why we're temporarily halting work on this project and will be back again as soon as we're finished with our exams (well maybe we'll take a short break after exams so as not to get a mental breakdown haha). Soooo, no we did not figure this out yet, but will definitely do soon God's willing :D

**Comment by beeheemooth** [comment] 2017-02-15 00:45
This is a super brilliant thing !!! You are best!!!

 It looks like a more functional Plastic Tool!

  I would like to ask a question. How will behave shape that's just intersects itself repeatedly? For example a snake?

**Comment by lordadamson** [comment] 2017-02-15 07:19
Hi @beeheemooth I'm glad you find it interesting as we do :grinning:
The algorithm is stroke oriented and not object oriented. meaning that an object like a snake will contain multiple strokes, so the prediction will analyze each one of these strokes and how it relates to its surroundings and predict your next stroke/frame accordingly.

To answer your question. I honestly don't know how well it's going to behave. At this point we're not sure if it is practical at all. All we've got is a research and a few flashy videos showing only the best results. So until we produce testable outputs and real artists test this thing out and provide us with feedback, we may never know for real.

**Comment by artisteacher** [comment] 2017-02-15 21:16
When you are ready for feedback, I'd be happy to test it out on a mac. I'm rooting for you!

**Comment by lordadamson** [comment] 2017-02-18 22:14
Thank you! will definitely let you know.

**Comment by morevnaproject** [comment] 2017-02-20 16:18
> So it is up to me to choose whether we implement it to the toonz raster or to the vector layers. But I'd love to hear your opinions on this.

Lot of people in our studio loves raster painting. It would be awesome to have this thing in raster (since OT already have some basic vector tweening). Also, I am aware that some my friend devs are already working on point-based morphing system for OT (similar to Synfig system).

**Comment by lordadamson** [comment] 2017-02-20 17:58
I'm afraid we've already started implementation on the vector layer. I hope we could port this to raster at some point.

**Comment by beeheemooth** [comment] 2017-02-20 18:17
> I'm afraid we've already started implementation on the vector layer.
Yesss!

**Comment by blurymind** [comment] 2017-02-20 18:59
I have a couple of suggestions that can improve tweening workflow and are related to this feature very much:
https://github.com/opentoonz/opentoonz/issues/565  
https://github.com/opentoonz/opentoonz/issues/570
https://github.com/opentoonz/opentoonz/issues/611

I have worked on traditional animation as an inbetweener for a living and believe that these improvements will make a huge difference and save a lot of time!
 @morevnaproject  if you set up a fundme campaign for ivan to implement them, you got $$ from me ;)

**Comment by hedayasamy** [comment] 2017-02-21 12:00
Hi :D 
We're facing a weird issue in our implementation, I know this might not be the best place but it would be very appreciated if someone could help us out:
http://stackoverflow.com/questions/42366640/pushing-a-pointer-to-a-vector-no-matching-function-for-call-to-stdvectortype

**Comment by morevnaproject** [comment] 2017-02-25 15:26
> @morevnaproject if you set up a fundme campaign for ivan to implement them, you got $$ from me ;)

Just to make it clear: do you explicitly mean gofundme platform, or any other crowdfunding platform would work for you as well?

**Comment by blurymind** [comment] 2017-02-25 19:07
Anything that supports paypal really. The one you used for the mypaint
brushlib implementation looks good too! :D

**Comment by morevnaproject** [comment] 2017-02-26 12:18
> Anything that supports paypal really. The one you used for the mypaint brushlib implementation looks good too! :dagger: 

Great, that's good to know!

Regarding the platform we used for MyPaint brushes feature, I would like to mention, that anyone can use it to start a bounty (actually, in the original platform concept it is supposed that bounties are initiated by _users_ ). ^__^

**Comment by lordadamson** [comment] 2017-03-06 20:31
@morevnaproject wait, are you one of the team that created the mypaint brush engine?

**Comment by morevnaproject** [comment] 2017-03-07 03:09
@lordadamson No, I am not one of creators of MyPaint brush engine. But one of my developers is working on integrating MyPaint brush engine into OpenToonz.

**Comment by lordadamson** [comment] 2017-03-07 19:42
oh well... good luck <3 :D

**Comment by lordadamson** [comment] 2017-03-21 17:35
Hi, quick update. We produced our very first output a couple of days ago. It's really immature and quircky but it's a step in the right direction :smile: 
Wish us luck :heart: 
![First Output](https://media.giphy.com/media/KxkH83LEnJRVm/giphy.gif)

**Comment by turtletooth** [comment] 2017-03-21 17:37
That's awesome!  Thanks for working on this.  It's exciting to see progress.

**Comment by artisteacher** [comment] 2017-03-21 18:04
So exciting!

**Comment by beeheemooth** [comment] 2017-03-22 10:29
Great ! Will this thing have any settings?

**Comment by lordadamson** [comment] 2017-03-22 10:51
well there are a few variables in the code that are kind of magic numbers and constants that we set according to what behaves best. Exposing these numbers as settings would not be very user-friendly because the user would understand for example what a "sample point neighbourhood space vicinity" number means.
However we could expose some end user preferences like the enable/disable prediction and maybe the color of the prediction stroke?
That's what I can think of for now, let me know if you have other ideas!

**Comment by artisteacher** [comment] 2017-03-22 11:26
It would be great to have a checkbox for enabling/disabling prediction in the tool option bar for the brush tool. For the default prediction stroke color, red may not be the best choice, as it is used for onionskin on previous frames. When using onionskin, green shows forward frames. If this feature is completely separate from onionskin, perhaps a 3rd color would be best so that onionskin & prediction are not confused with each other.

**Comment by lordadamson** [comment] 2017-03-22 20:16
well that's a good note @artisteacher suggest a color please? preferably an exact rgba that is not irritating to the eyes on the long run? :smile:

**Comment by turtletooth** [comment] 2017-03-22 20:20
What about some sort of blue (160, 210, 255 perhaps).

**Comment by lordadamson** [comment] 2017-03-22 20:39
I'm no artist but that looks pretty good! I set the alpha to 105. Does anyone have a better suggestion or should we settle for this one?
![screenshot from 2017-03-22 22-37-23](https://cloud.githubusercontent.com/assets/6195060/24219625/25b3eec2-0f50-11e7-9c19-e78a0f1ca089.png)

**Comment by artisteacher** [comment] 2017-03-22 22:03
You can never go wrong with blue! Looks good.

**Comment by lordadamson** [comment] 2017-03-22 22:21
yeah! blue it is :smile:

**Comment by beeheemooth** [comment] 2017-03-22 23:21
Maybe it would be useful if it was possible to take into account the degree of perspective reduction, for precise detailing
![2017-03-23_011708](https://cloud.githubusercontent.com/assets/25724133/24224980/d3856196-0f66-11e7-8b2e-24eb32cce153.jpg)

**Comment by lordadamson** [comment] 2017-03-23 05:36
In theory it should do that because it doesn't just randomly duplicate past strokes, it adapts them to new environment. While the algorithm won't really understand what perspective is, but it should by analysing the similarities in neighbouring strokes provide a fair suggestion.
Examples can be found in their [painting repetition video](https://www.youtube.com/watch?v=m7MEAw46Ojo).

**Comment by blurymind** [comment] 2017-03-24 09:20
for onion skinning - I tend to use green or blue for forward frames and red or yellow for past frames

**Comment by Number0001** [comment] 2017-04-15 06:35
We are waiting for new news. 🥇

**Comment by lordadamson** [comment] 2017-04-15 10:45
Hi @Number0001  I really appreciate you taking interest in our little project.

We're working on it, taking good steps but we're stuck in a few points that are not clear in the research papers and we still don't know how to get around them. Jun Xing -the man who wrote the papers- has been kind enough to send us a demo code for the animation autocomplete (across frames) which definitely should help but could not send us the painting repetitions autocomplete (within frames) due to copyright concerns. And he hasn't been very responsive to our questions; he's super busy I guess.

So yeah we're working on it, struggling and taking small steps, but we'll get there God willing.

**Comment by Number0001** [comment] 2017-04-28 13:33
Can there be new results?🥇 If you recorded a video about the current as it now looks, we were happy.

**Comment by Number0001** [comment] 2017-04-28 13:34
Can there be new results?🥇 If you recorded a video about how it looks now, we were happy.

**Comment by lordadamson** [comment] 2017-04-29 08:53
Well currently the output is just not that good. it's lame and unoptimized; so I'd rather wait until I have something actually cool/exciting to show. Sooo yeah, we're happily working hard on it; until then just sit tight :D

**Comment by lordadamson** [comment] 2017-05-06 19:48
Hi :D 
Here's an update gif

![giphy](https://cloud.githubusercontent.com/assets/6195060/25775424/9baf6b3a-32ad-11e7-93af-82c33787b856.gif)

So this is what we got so far. Quirky as it looks, it's actually quirkier than that in practice lol
It still has a lot of way to go. But we're definitely on the right direction.

So what happens behind the scene is:
Similarity analysis algorithms matches the old branch with the new one, then gets the neighbour of the both branches and predicts those who exist in the old one but has no matching pairs in the new one (the two strokes representing the leaf).
Hope that makes sense :D

**Comment by turtletooth** [comment] 2017-05-07 05:27
Thanks for sharing this.  It's really neat to see the progress- I can't imagine the work that has to go into this.

**Comment by UpgradeOpenToonz** [comment] 2017-05-07 12:36
Very cool, we closely follow the news.

**Comment by beeheemooth** [comment] 2017-05-07 17:14
Fantastic !!! We are all here waiting for the floating fish ^______^

**Comment by Number0001** [comment] 2017-05-23 14:15
Any news?

**Comment by AntonWern** [comment] 2017-05-27 14:19
@lordadamson Any news on this?

**Comment by lordadamson** [comment] 2017-05-27 15:23
Hi guys :D no news. going through exams and will get back to work right after God's willing.

**Comment by lordadamson** [comment] 2017-06-24 15:38
![giphy](https://user-images.githubusercontent.com/6195060/27509735-17ad1820-590c-11e7-9883-522f8f6476bc.gif)
Hi :D I know it is not big news but the system now works recursively. It uses the last prediction as input to the system as if it's the last drawn stroke so that the system would do the whole similarity analysis and produces another synthesized stroke accordingly which becomes input again... I guess you get the idea.

**Comment by lordadamson** [comment] 2017-06-24 15:40
We're trying to make it context aware now. Like for example have it stop at the end of the ladder in the gif above all we're getting is these satanic symbols 😢 
![screenshot from 2017-06-11 00-54-45](https://user-images.githubusercontent.com/6195060/27509752-6d3e72fc-590c-11e7-9b17-c2325132dd3e.png)

**Comment by artisteacher** [comment] 2017-06-24 19:15
Thanks for the update! It's exciting to see progress.

**Comment by blurymind** [comment] 2017-06-25 10:54
Very cool!! :D

**Comment by MaxMixBug** [comment] 2017-07-13 10:15
@lordadamson Any news on this?

**Comment by MaxMixBug** [comment] 2017-07-28 10:24
@lordadamson Are you in a general chat? https://discord.gg/4V7Yk9m

**Comment by lordadamson** [comment] 2017-07-28 10:47
Hi all,
I have some bad news. I've had a full time job for a while now and it's taking all my time. I haven't been able to find the time to work on this project for a while now and I really don't know what to do about it. I even tried to gather a team of my coworkers, and in the beginning they seemed interested but then working an extra hour for a non-profit project does not appeal to everybody.

My team are in a very similar situation.

Let me know guys if any of you has been in a similar situation and what did you do about it. For now there's one thing I'm sure I'll do. I'll document all of our research and development to make it easier for others to pick up and continue building on it.

@MaxMixBug I am not. But I doubt I'll be active if I were.

**Comment by MaxMixBug** [comment] 2017-07-28 13:27
@lordadamson  You can lay out the project, can someone else will be able to continue it for you.
Could you complete the project? @turtletooth @morevnaproject @manongjohn @blackwarthog

**Comment by beeheemooth** [comment] 2017-07-28 14:05
@lordadamson Your development is unique. We all would like to see its implementation in OpenToonz. Please do not quit your job halfway!

**Comment by artisteacher** [comment] 2017-07-28 19:17
Congrats on your job! Thanks for being willing to document your work. Maybe making a WIP pull request would be a way to start? I hope someone can take over because this would be a valuable addition.

**Comment by lordadamson** [comment] 2017-07-29 01:21
@beeheemooth Believe me I do not want to quit :cry: But if I don't work I won't be able to feed myself.
@artisteacher Your idea is wonderful, I have created the PR and I'll start documenting things there :))

**Comment by Agnyy** [comment] 2017-07-29 17:03
@lordadamson Thanks for your work!

**Comment by jpturcotte** [comment] 2017-09-09 20:27
@lordadamson If we started a bounty for this, would you be ready to resume your work?

**Comment by lordadamson** [comment] 2017-09-15 14:00
Hi @jpturcotte Thank you for your interest man. I'm afraid I could not. I do not have the luxury of time.

**Comment by RodneyBaker** [comment] 2018-12-17 10:44
Closing as slipping to future development and tagged as 'on hiatus'.

A question:  With the original contributor now a ghost how much of the code for this feature was preserved and/or is available for use by others wishing to continue development?  I do note the referenced video is still available on youtube.

**Closed by RodneyBaker** 2018-12-17 10:44 UTC
Labels: Enhancement, Help Wanted, Hiatus

**Comment by RodneyBaker** [comment] 2023-09-11 02:08
Just a note to suggest there are some (minor) aspects of this proposal that are implemented via PR #5069.

**Comment by beeheemooth** [comment] 2023-09-11 11:47
@RodneyBaker In my opinion, these two PRs have nothing in common.
