### ISSUE TITLE
Failure to read pointParam when instancing certain Macro FX

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2424] opened 2018-12-16 18:26 UTC
### Issue Summary
Attempting to instance a certain Macro FX causes OT to crash.
Attached are two similar MacroFX that exhibit this issue.
[macroFx.zip](https://github.com/opentoonz/opentoonz/files/2683833/macroFx.zip)

### Screenshot or Video Reference

![image](https://user-images.githubusercontent.com/42905003/50057203-148fcc80-015f-11e9-9369-25ce0bbc3b39.png)

EDIT:
This is an image from an unrelated issue, you can see the original version of the Outline Macro that presented no issue.
![image](https://user-images.githubusercontent.com/42905003/50057317-96ccc080-0160-11e9-832c-07c4dc698dcc.png)

### Steps to Reproduce
1. Create the nodes and link them up as shown in the reference image.
2. Select all of the nodes shown in the red box and create a Macro from them.
3. Save the Macro, the name doesn't matter.
4. Attempt to create an instance of the Macro FX in the Schematic window.

### Expected Results
The Macro FX is instanced in the Schematic and can be used.

### Actual Results
OpenToonz crashes as soon as the Macro is selected from the drop-down list.

### System Information
1.2.1 (Dec 15 2018 Appveyor build)
Windows 10
I7 5820k
16GB DDR 4
GTX 980

**Comment by manongjohn** [comment] 2018-12-17 03:32
Narrowed the issue down to the Curve node.  The way it is written out and then read back in causes it to get stuck in an infinite loop.

**Comment by Wolfinabowl** [comment] 2018-12-17 16:30
Just tried the AppVeyor build and can confirm that the issue is fixed.
Thanks manongjohn!

**Comment by manongjohn** [comment] 2019-07-14 16:37
I'm reopening this as the issue is back again but somehow with a different cause than originally discovered.  It is still an issue with loading the CurveFx when it's in a MacroFx.

The problem is when a CurveFX is in a MacroFx and is written out as a Preset, the curve information written out under the `<super>` tag does not contain pointParam details that the CurveFx has. 

>   <super>
    <params>
	   <curve>
        <tonecurve>
          <redgreenbluealphachannel>
            <point>
              <pointParam id='3'/>
            </point>

Later when the MacroFx is loaded, the curve information in the `<super>` section is read in and crashes because it is expecting pointParam details to load but there aren't any.

Writing the data out does not fix the problem. Actually causes the macrofx not to load.  Loading default pointParam may not crash when loading, but will crash when rendering/previewing. 

Not sure the best way to fix this.

**Comment by RodneyBaker** [comment] 2019-09-20 14:59
@shun-iwasawa We could use your insight on best way to proceed for this one.

**Comment by RodneyBaker** [comment] 2019-09-21 19:06
@WolfInABowl  
@shun-iwasawa has submitted a fix for this that tests out good for me.
Having your verdict on this will help seal the deal.

Here's a link to the appveyor release (fix):  [LINK](https://ci.appveyor.com/api/buildjobs/p266idh700c0q0lv/artifacts/toonz%2Fx64%2FOpenToonz.zip)
Just extract the zip file, rename the stuff directory to 'portablestuff', and drop it into Opentoonz directory to creating a working portable release of the fix.

**Closed** 2019-10-14 09:13 UTC
Labels: Crash, Known Issue
