### ISSUE TITLE
Bug expanding the .tnz scene file to the point it becomes unusable

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#1819] opened 2018-02-20 20:46 UTC
I've been working on a small project. It has a sub-xsheet, some auto-animations (using the animate tool) and a few effects (glow and invisibility). The whole animation lasts 30 seconds or so. It got to the point where everytime I tried to do anything (like change rooms to the effects room or start the preview) OpenToonz would freeze. Sometimes it would come back after a few minutes, sometimes not. It's like I've hit some kind of wall with it, by adding the last couple of levels. It's not using many resources either: 17% cpu, total 28% memory (inc my other apps, mostly used by Chrome).

I don't understand the problem fully yet, but I keep backups as I work, so I rolled back a few versions to one that worked ok, then started working for 2 mins. Then, when I looked at the scene file (.tnz) it had grown from 620k to 18,119kb. Quite an increase. Looking at the difference between them showed that the new file had tons of new empty fx nodes toward the end.
<fxnode>
          <STD_fadeFx id='17782'/>
        </fxnode>
        <fxnode>
          <STD_fadeFx id='17783'/>
        </fxnode>
        <fxnode>
          <STD_fadeFx id='17784'/>
        </fxnode>
...

I'll keep looking to see if I can pin down the problem, but it seems that I can no longer edit this project.

**Comment by DarrenTAnims** [comment] 2018-02-20 20:51
Even loading the old version, then hitting save changes the .tnz file; changing the id inside "Toonz_columnFx" nodes, which seems strange.

**Comment by DarrenTAnims** [comment] 2018-02-20 21:11
This is crazy. So, I've rolled back to an earlier version. In the timeline view, I clicked the "New Vector Level" button, but as it's in the timeline view it adds a single frame in a current layer, so I drag the frame up above the others which creates a few new layers (it should only ever create 1, which is a separate issue, but could be part of the cause of this). So I click on each blank layer header and press the delete key to remove them. And then hit save. That's all I do and the problem starts.

If I then go to either the function editor or the Fx schematic I can see an extra 80 or so Transparency effects! I suspect it just keeps adding them for some reason. Maybe because the previous layer had an effect attached to it possibly?

**Comment by jpturcotte** [comment] 2018-02-20 22:17
This is really weird. Maybe the developers have a clue. Tell us if you find anything else. Thanks for reporting this!

**Comment by manongjohn** [comment] 2018-02-20 22:43
I'm wondering if this would also happen in Xsheet mode, if you mimic the same steps in Xsheet mode.

The reason I say that is because both modes use the same code but there is extra logic for dealing with how to display and or grab the column you're working with in Timeline mode.  

The one difference that you are not seeing between the two different modes is how the empty layers are being created. In Timeline mode it's very obvious but because the xsheet mode has an "infinite" amount of empty columns you're not actually seeing the actual empty columns being created in its place when you drag a level to the far right.

Based on my work with the timeline I would actually expect this bug to be present in both modes.

**Comment by DarrenTAnims** [comment] 2018-02-21 09:18
I rolled back to a previous version and noticed that I already had a dozen or so unlinked effects, so I deleted these and carried on working only using the xsheet. I think the problem may have happened when I created the new level. Because clicking the new vector level button creates it in the already created layer, you then have to drag it above all the other layers to get to a new one and it when you get above them you often find it's created 10 more blank layers because of the scroll speed. This is really wrong. Firstly you should be able to create a blank layer with a new level. And secondly if you drag a cell to create a new layer it should only ever create 1. There's no reason to keep creating dozens of new layers. But I'm guessing this will be fixed soon. Also, when I created the new level and dragged it up to a new layer, I had a copy of the keys from the old layer on the new one, so I had to delete these too!

Incidentally, in the xsheet there's always a single blank layer (column) to the right, so you can always create a new level in that. Personally, I think that when you click one of the new level buttons, it should create a new column/layer, but I guess it's historically what the program has always done so is unlikely to change, but this is another one of those things that will confuse new people. (Plus an old conversation that I gave up on a while back is that typing in a name for the new level should use the same name for the new layer).

**Comment by RodneyBaker** [comment] 2018-02-21 16:29
> when you click one of the new level buttons, it should create a new column/layer


You lose me here.  New Level Buttons?
If you mean New Vector, New Toonz Raster or New Raster buttons it does create a new column/layer so I'm obviously misunderstanding something here.

**Comment by DarrenTAnims** [comment] 2018-02-21 16:33
Sorry, when I say the New Level buttons. Yes, I mean the 3 buttons on the timeline toolbar: New Vector Level, New Raster Level & New Toonz Raster Level. I've just experimented before replying here. They don't create a new column/layer if you're in a cell. It creates the 1st drawing in that cell You have to click out of all cells before clicking the button, which is nice to find out now.

**Comment by RodneyBaker** [comment] 2018-02-21 16:43
Yes, I think I see what you mean now.
If the cell/cells we have selected are empty OT assumes we wish to create the new level there.
If the cell we have selected is already occupied it will create a entirely new column to house the new level.

There are some cool things here that I haven't yet looked into to include taking the time to look at the options available in the popup that appears upon creating the new level.  I usually ignore that popup but see where I might not want to do that.  For instance, if I want a specific number of empty frames to be created (in the Level Strip) upon creating the new level we can enter that in the popup and we are ahead of the game.

Sorry to go off topic... but I thank you for realize the importance of how and why this works in the way that it does.

**Comment by DarrenTAnims** [comment] 2018-02-21 17:04
No I'm glad you asked Rodney. I hadn't realised that it could create a column/layer automatically if I clicked off a selected cell first. It's a shame that there's not a couple more options in that dialog, one specifically to set the name of the new layer (probably copied from the level name).

**Comment by RodneyBaker** [comment] 2018-02-21 19:29
>  one specifically to set the name of the new layer (probably copied from the level name).

Someone made that suggestion but it never gained traction.
The issue is how Levels and columns are rarely the same thing in animation of any complexity.
A column/layer consists of as many levels as required (i.e. arbitary)
It would be interesting to see what adding that option to the dialog would do.
I suspect it would create more trouble than less.
I do understand the desire though... so we should investigate that thoroughly.

**Comment by artisteacher** [comment] 2018-02-21 21:57
Some of this looks to be related to #1797. If you right-click on the layer name, you can select "Remove Empty Columns" so that you do not need to manually delete the extra layers one by one. I also would prefer only one new empty layer being created from dragging layers. At least there could be a preference to limit the number of layers ie. choosing between "Drag to create multiple empty layers" or "Drag to create single empty layer" with single layer being the default.

I think that naming the column/layer based on the level name would be fine if it was a preference to be enabled - or perhaps a setting that could be checked in the new level dialog. If in preferences, it could be something like "set the column/layer name the same as its first created level". If an additional setting in the new level dialog, perhaps "Set this level name as the column/layer name (this setting will override a pre-existing column/layer name)". In that case, a new level added to an existing column/layer would rename the column/layer.

@RodneyBaker you can change the default level type in Preferences -> Drawing. Afterwards, whenever you start drawing in a new column (or a cell not contiguous with another level), a new level will be created with that level type. If you wanted something for going back and forth, between level types more quickly, you could set shortcuts for making each level type.

**Comment by RodneyBaker** [comment] 2018-02-21 22:08
> @RodneyBaker you can change the default level type in Preferences -> Drawing. Afterwards, whenever you start drawing in a new column (or a cell not contiguous with another level), a new level will be created with that level type. If you wanted something for going back and forth, between level types more quickly, you could set shortcuts for making each level type.

Yes, I've done that and more.
But the benefit I'm leaning toward pluses that up one more step.
I would likely need to demonstrate but basicially it would be gaining the power of autolevels created of the desired type with one press of a button and then being able to press on without repressing that button (because it's auto generated).  We wouldn't need to press another shortcut until such a time as we wanted to transition to auto using other auto levels.

**Comment by manongjohn** [comment] 2018-02-22 06:35
Bringing this back on topic... :)

Unless what I found is different, I can repeat this issue in both Timeline and Xsheet under 2 conditions:

1) it's an fx that takes in a "Source" like Blur
2) There is no source connected to it in schematic view.  Either its floating solo or its output is connected to something, but nothing going into it.

Under this condition, the fx is duplicated for every empty column that is created while dragging a level to an empty column and remains there even if the empty column are deleted.

If however, the fx is tied to a column (a source is connected to it in schematic view), then it only duplicates when a non-empty column is created.  The duplicate fx is tied to the new column with the level in it.

Normally, for me, when I add an fx to a column, it will automatically link to it if there are levels in that column.  In a few rare occasions that's hard for me to duplicate, it doesn't establish that link and creates a floating fx (in schematic).  How/why that happens, I'm not sure but would definitely start causing that issue when that 1st happens.

The fix for this is to not duplicate any fx that takes in a "Source" and has no source linked to it when dragging levels to other columns.

**Comment by shun-iwasawa** [comment] 2018-02-22 06:59
@DarrenTAnims @manongjohn 
I think I don't get properly the procedure, but am not able to reproduce this issue yet.
Can you please post detailed steps or some movie which I can follow?

**Comment by manongjohn** [comment] 2018-02-22 11:06
Here are steps that may not make any sense, but illustrates the issue

1) Add a new level to Col1
2) Open a Schematic window and switch to FX Schematic view
3) Right-click Schematic window and then "Add FX" -> "Blur" -> "Blur"
- This will create an unconnected "Blur" Fx in the Schematic window
4) Drag the level in Col1 to Col 5
- Watch as the "Blur" is duplicated for each empty level you cross over.

**Comment by manongjohn** [comment] 2018-02-22 11:11
I should note that my steps can be done in either Timeline or Xsheet.  In either case, it happens with the creation of a real empty column instead of an empty virtual column. It's just more obvious in Timeline since you can actually see the empty column creation when dragging levels up or down

**Comment by shun-iwasawa** [comment] 2018-02-23 06:42
@manongjohn Thank you for the steps. I tried them on the current master build.

![duplicate_bug_trial](https://user-images.githubusercontent.com/17974955/36581220-4113980c-18af-11e8-9330-74557ad59588.gif)
 
Hmm, I couldn't find any problem. Did I miss something..?

**Comment by manongjohn** [comment] 2018-02-23 09:50
@shun-iwasawa After dragging column, try zooming out in the schematic window in case it is creating it where you cannot see it.

**Comment by NoahFarron** [comment] 2018-02-23 10:37
I've replicated this, following @manongjohn's instructions.

![tz-blur-error](https://user-images.githubusercontent.com/36535462/36590076-56e9eb56-1885-11e8-91d9-4fcea36e2f2d.gif)

**Comment by shun-iwasawa** [comment] 2018-02-23 10:50
@manongjohn  I couldn't find any extra fx nodes in the schematic. 

@NoahFarron  Thank you for sharing the video. I'm curious about the condition of occurrence of this bug. Can you please upload your preference file ( `OpenToonz 1.2 Stuff\profiles\layouts\settings.username\preferences.ini` ) for reference?

**Comment by manongjohn** [comment] 2018-02-23 11:03
@shun-iwasawa  After you mentioned preferences, I discovered this happens only when you have "Cell and Column Data" dragging behavior set.

**Comment by shun-iwasawa** [comment] 2018-02-23 11:19
Great. Now I could reproduce the problem. Thanks!

**Comment by NoahFarron** [comment] 2018-02-23 12:51
@shun-iwasawa Looks like you've caught it, but here's the pref file anyway just in case.

[preferences.zip](https://github.com/opentoonz/opentoonz/files/1751669/preferences.zip)

**Closed** 2018-03-14 03:04 UTC
