### ISSUE TITLE
OpenToonz crashes upon cleanup

### ISSUE THREAD

**Issue by diegoh42** [opentoonz/opentoonz#661] opened 2016-07-20 15:30 UTC
Whenever I attempt to cleanup a .TIFF file, OpenToonz crashes. Similarly, whenever I attempt to save a file, the program crashes aswell. Any Suggestions?
![screen shot 2016-07-19 at 8 42 17 pm](https://cloud.githubusercontent.com/assets/20549895/16992416/0fe0beee-4e54-11e6-8950-55f5f5bde32b.png)

I am using an IMac
I am trying to save TLZ, TNZ, and TIFF files
I am using V1.0

**Comment by turtletooth** [comment] 2016-08-01 05:12
Duplicate of #654

**Closed** 2017-01-18 22:19 UTC
Labels: Duplicate
