### ISSUE TITLE
Network Lag while running OpenToonz (Caused by new-version check?)

### ISSUE THREAD

**Issue by automated-reckoning** [opentoonz/opentoonz#877] opened 2016-10-21 01:35 UTC
I would like somebody to try and replicate this. While OpenToonz 1.1 (commit 50d5306afc17325f015db97ae09911445991b475) is running I experience network latency of almost 3 seconds, every ten or twenty seconds. This is despite the fact that as far as I can tell, A) Opentoonz shouldn't be connecting to the internet. B) my firewall settings shouldn't allow it to touch the network anyway. If I close the program, network goes back to normal. This was discovered while running Skype, and I have not been able to test it yet without skype running. Will update ticket when I can. 

Ping Log:
Reply from 2607:f8b0:4009:80e::200e: time=2948ms
Reply from 2607:f8b0:4009:80e::200e: time=207ms
Reply from 2607:f8b0:4009:80e::200e: time=34ms
Reply from 2607:f8b0:4009:80e::200e: time=38ms
Reply from 2607:f8b0:4009:80e::200e: time=37ms
Reply from 2607:f8b0:4009:80e::200e: time=29ms
Reply from 2607:f8b0:4009:80e::200e: time=40ms
Reply from 2607:f8b0:4009:80e::200e: time=38ms
Reply from 2607:f8b0:4009:80e::200e: time=2984ms

Network adapter is D-Link DWA-182 USB wifi dongle. Windows 10. Intel i5.

**Comment by automated-reckoning** [comment] 2016-10-21 13:22
Confirmed that this issue is present at all times. Inspection with Process Monitor shows that OpenToonz is constantly querying the registry for network information, so it's doing _something._ 

Further investigation shows that OT has the Qt5Network module loaded, possibly for things like the farm functionality or network storage? 

It's just occurred to me that if OT is regularly trying to poll the network my router might be the issue as well. Unfortunately I can't really check on this possibility with my network setup.

**Comment by automated-reckoning** [comment] 2016-10-22 18:36
Tested with ethernet instead of my USB wifi adapter and the problem goes away, so it looks like the wifi or adapter is the issue. Blocked OT completely from the internet with Windows Firewall rules, but the issue persists.

**Comment by automated-reckoning** [comment] 2016-10-23 23:17
@ideasman42 This is less a question and more an observation. I'm not sure if it qualifies as an OT bug, but OT is the only software I've observed the behaviour with. I'd love input from anybody with ideas on what could be interacting to produce this.

**Comment by jabarrera** [comment] 2016-11-26 16:50
I have seen "today" that Opentoonz connects to net for checking new software updates and I remembered this issue. It shows now a popup information window about a new version.

I have not seen the code, but it's probably that if your firewall reject the connection, Opentoonz maybe try to connect in a infinite loop and dry the WIFI connection (wired connection are more stable for lot of tries). I don't know if it has a timeout (probably not).

**Comment by jabarrera** [comment] 2016-11-29 17:30
@automated-reckoning , I've been looking at this. I found a small error in the **check update** function that could be reach in some circunstances (a firewalled connection, for example).

I think that it is not enough to lag your connection, but strange things happens. :)

As I can't reproduce your exactly issue, please, could you test the fix?

You only need to apply this branch (https://github.com/jabarrera/opentoonz/tree/fix/check-update)  to your forked _Opentoonz master branch_ compile and execute Opentoonz with the same configuration when your connection get lagged.

In Opentoonz, open the **Message Center** (Window/MessageCenter). About 10 seconds since the init, you must see a message warning that the connection finished with a timeout.

After that, check the life of your connection.


Additionaly, I've been looking the connection mantained for Opentoonz. Farm server gets open in TCP:51005. But it is not managed by QT. It use basic net.

There is, too, a (I think) basic chat system (port 10545). This use QT plastform, but it is used nowhere, so...

**Comment by jpturcotte** [comment] 2018-05-29 11:44
@jabarrera Has your fix been committed?

**Comment by RodneyBaker** [comment] 2018-12-11 23:36
Tagging this as known issue and note that a fix was suggested but perhaps not directly implemented.
Subsequent changes may have resolved the problem as no similar report has been posted for over two years.  Closing.

**Closed by RodneyBaker** 2018-12-11 23:36 UTC
Labels: Known Issue, OS: Windows, Question
