### ISSUE TITLE
No canvas at all?

### ISSUE THREAD

**Issue by connorsucks** [opentoonz/opentoonz#1750] opened 2018-01-23 02:57 UTC
Idk whats going on. I started up the program and its just grey? I've tried setting the background to white and changing the size. Anything i could think of. I really need help because i cant see where I'm drawing. Maybe its default to the program but it doesn't seem this way, so like any help would be fantastic ;v;
![capture](https://user-images.githubusercontent.com/35715006/35255843-ac971200-ffb6-11e7-91a9-ffe274600a16.PNG)

**Comment by artisteacher** [comment] 2018-01-23 03:14
This is a duplicate of #1674. For now, you should try installing the Morevna release or turtletooth’s OTX.

**Closed** 2018-01-25 15:30 UTC
