### ISSUE TITLE
Logitech DLL crash

### ISSUE THREAD

**Issue by SuvenduNayak09** [opentoonz/opentoonz#5426] opened 2024-04-25 06:40 UTC
### Description

software is crashing again and again

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Other

**Comment by DarrenTAnims** [comment] 2024-04-25 12:30
Please fill out the bug report form when you post an issue.
Without it, nothing can be done and your report will just be closed.

**Comment by Tess-svk** [comment] 2024-04-25 14:12
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-04-25 15:10:33
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 24


Crash File: C:\...\OpenToonz\OpenToonz\crash\Crash-20240425-151033.log
Mini Dump File: C:\...\OpenToonz\OpenToonz\crash\Crash-20240425-151033.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvmdi.inf_amd64_1e678564fff99713\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\SYSTEM32\gpapi.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvmdi.inf_amd64_1e678564fff99713\nvgpucomp64.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\ApplicationTargetedFeatureDatabase.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffe1da87a7a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffe1da2e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffe1dab33fe] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ffdc841413e] <MSVFW32.dll>
  6> ICOpen [0x7ffdc8413da4] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ffd7c686212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ffd7c684478] <image.dll>
  9> initImageIo [0x7ffd7c627ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff780fa0dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff780fa2d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7813ceab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7813ce092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ffe1d62257d] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ffe1da6aa48] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment] 2024-04-25 14:53
The good news...

That file.
On your computer.
lvcod64.dll is a logitech webcam driver that conflicts with Opentoonz (and many other programs).
It is a driver no longer supported by Logitec.
Renaming or removing/deleting the file should resolve the problem.
C:\WINDOWS\SYSTEM32\lvcod64.dll

REF:  #5360 (and other reports)

**Comment by RodneyBaker** [comment] 2024-04-26 15:06
Closing as a duplicate of similar reports.

**Closed by RodneyBaker** 2024-04-26 15:06 UTC
Labels: duplicate
