### ISSUE TITLE
Audio tracks muted by default, and have no sound in preview

### ISSUE THREAD

**Issue by Lantau42** [opentoonz/opentoonz#4638] opened 2022-12-08 02:39 UTC
### Description

I use Opentoonz for Mac Monterey 12.5, and every time I upload audio files, they appear muted by default. Each time I try to unmute them (using the 'click to play the soundtrack back' button) to play sound in the animation preview, there's no sound whatsoever. Even stranger, that track's mute button gets muted on its own again after a few seconds, even when I'm not pressing anything.
But for some bizarre reason, the sound does come out in the rendered video. It's just in the preview that's the problem, which makes it extremely difficult to make proper lip-sync animations. 

I've tested this using the official Opentoonz 1.6 build (from August, I think), and the nightly build from December 5 2022. 
I have ffmpeg installed (with the files in the ffmpeg folder all opened in terminal before opening Opentoonz), and I've tested this with both mp3 and wav files (both 8 bit and 16 bit). Even with multiple different audio files, the bug's still there. 

I've used Opentoonz for the previous version of Mac's OS (Mac Big Sur), and the audio tracks did work back then. So I don't know if it's just a problem with my OS. 
 
Frankly, I'm tearing my hair out, and I'm begging for a solution. Thank you.

### Screenshots, Video & Crash Logs

This is what the audio file looks by default. Note that the 'sound' icon in the toolbar is on, and I've tried turning it on-and-off several times to see if there's any difference (no change)
<img width="1026" alt="Screenshot 2022-12-08 at 2 27 24 AM" src="https://user-images.githubusercontent.com/120071891/206341478-bdd33e96-6244-4c63-9044-0c2cbc33eb4e.png">

How it looks when I try to unmute the audio track. There is no sound, even when scrubbing through. 
<img width="808" alt="Screenshot 2022-12-08 at 2 17 05 AM" src="https://user-images.githubusercontent.com/120071891/206341087-3d93c555-014c-4df3-bac2-38b40277bb6f.png">

Volume is completely at 100% the whole time. 
<img width="869" alt="Screenshot 2022-12-08 at 2 40 38 AM" src="https://user-images.githubusercontent.com/120071891/206342967-14dd4355-4f57-40ef-a6fc-2d0fa711457a.png">

How it looks seconds later. This can happen while I'm still playing the audio, and haven't even clicked anything. 
<img width="872" alt="Screenshot 2022-12-08 at 2 30 02 AM" src="https://user-images.githubusercontent.com/120071891/206341784-f1b545b6-550b-4f91-896d-892f4be2e845.png">

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

December 5 2022

### Operating System

macOS

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by artisteacher** [comment] 2022-12-08 03:18
I can confirm this is an issue on macOS - even with audio recorded directly in OT. I don't have this problem in T2D.

**Comment by RodneyBaker** [comment] 2023-03-20 10:46
@Lantau42 With recent fixes to audio you might want to try the latest nightly release to see if that address some of your reported issues.

**Comment by shun-iwasawa** [comment] 2023-03-31 04:28
To clarify, the speaker icon in the column header is not the mute/unmute button. It's for preview-playing the single sound column.
Activating the `Soundtrack` button in the Viewer / Flipbook console should unmute the soundtrack in the camstand view or in the preview. This is the actual glitch, and it seems to be specific to macOS.

**Comment by gab3d** [comment] 2023-03-31 14:46
@shun-iwasawa 
Perhaps for audio tracks the mute icon could be changed to a speaker? (and the audio play icon to the standard play icon).
I've always found this speaker icon for playing to be confusing.

**Comment by RodneyBaker** [comment] 2023-10-15 14:23
Closing as likely resolved and/or abandoned by original reporter.

**Closed by RodneyBaker** 2023-10-15 14:23 UTC
Labels: bug, troubleshooting

**Comment by JPJammin** [comment] 2023-10-30 22:01
Hello. I am now having the same issue, except I am on OS Big Sur.

**Comment by elimisa** [comment] 2023-11-09 08:21
My problem is that the program closes when I play audios, even those recorded within the same program, and I have tried in every way, always complying with the requirements requested by the program.

**Comment by RodneyBaker** [comment] 2023-11-09 17:31
@elimisa You might try downloading a fresh compy of FFMPEG if you haven't already.
Other than that about all I can recommend is to consider (and perhaps share) one of the audio files here for purpose of testing.
I suspect however that it may play for other users which would suggest turning and looking further at your current system.
FFMPEG is a good starting place as most audio files will be processed through that.
