### ISSUE TITLE
Crash with Plastic tool rendering in mp4

### ISSUE THREAD

**Issue by bosko2020** [opentoonz/opentoonz#3576] opened 2020-11-01 19:41 UTC
Describe the bug:
Crash during rendering in mp4. Found the cause of the error, this is a plastic tool. After using this tool, there are crashes during rendering. Other instruments are fine

To Reproduce
List steps to reproduce the behavior.
1. Used the Plastic tool in the picture
2. after finishing the work I pressed rendering in mp4
3. the program crashed.

Found an error using the exception method. There were no errors when using other tools. I would be glad if this helps in solving the problem.

**Comment by RodneyBaker** [comment] 2021-01-07 21:28
Closing as a duplicate of #3595 although technically that report is a duplicate of this  one.

**Closed by RodneyBaker** 2021-01-07 21:28 UTC
Labels: bug, crash, duplicate
