### ISSUE TITLE
Cintiq Pen Registration is off screen

### ISSUE THREAD

**Issue by JaredSellers** [opentoonz/opentoonz#1686] opened 2017-12-15 01:48 UTC
After updating to 1.2, when I make a mark in a scene with my tablet pen, it will make the mark far above the canvas, off screen. The cursor for the pen appears in the correct place on the screen, right underneath the stylus tip, but then the mark each stroke makes is severely displaced. If I make a stroke with the mouse, it appears fine and in place. If I turn my Cintiq to tablet mode (so that there is technically one monitor, my main monitor), then the pen begins to work properly again. It is only an issue when I have two monitors running. I tried downgrading to 1.1.3 and the problem stopped, so it is unique to 1.2. The problem also happens with the 12-5-17 portable build. I hope this is enough information, I can replicate it very consistently.

**Comment by turtletooth** [comment] 2017-12-15 02:05
Can you please try the modified version I posted on gumroad today: https://gumroad.com/l/ZgxH
It has all the new features of 1.2 except the ability to use shader fx, but I think some of the under the hood changes might make for a better drawing experience for you.

**Comment by JaredSellers** [comment] 2017-12-15 03:24
Thanks for the quick reply. The problem is still there, even with both new versions of the portable build. I found there is no issue if I set the Cintiq as my primary monitor.

**Comment by turtletooth** [comment] 2017-12-15 03:26
If your cintiq and the other monitor don't have the same display scaling, that might be part of the issue.  I have run into issues with running multiple monitors at different scaling.

**Comment by RodneyBaker** [comment] 2018-12-15 05:30
Closing this as a duplicate of known issue with multiple monitors of different scales/resolution.

**Closed by RodneyBaker** 2018-12-15 05:30 UTC
