### ISSUE TITLE
When you call up the "Inbetweens" window, you can continue to draw.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2778] opened 2019-09-17 22:38 UTC
### Screenshot or Video Reference

![ezgif-2-4d9a7c272066](https://user-images.githubusercontent.com/25724133/65084678-9e9de780-d9b4-11e9-8b2a-151ff5684928.gif)

### Steps to Reproduce

1. Call "Inbetweens" window.
2. Draw a flower.

**Comment by beeheemooth** [comment] 2019-09-17 22:45
Eraser is also possible

**Comment by RodneyBaker** [comment] 2019-09-18 04:27
That's not a bug... that's a feature!  :)

**Comment by RodneyBaker** [comment] 2019-11-20 13:10
In looking at this report it seems to me the capability to draw and erase on the first frame of a level while the inbetweening menu is activated is one of those 'it's a feature not a bug' issues.

Rationale:  It can be useful to quickly alter one (or more) of the frames that will be autoinbetweened in order to produce different results without deselecting the frames that will be processed.

The point of interest here might well be to enhance the feature further so that it is easier to select and alter frames while Autoinbetweening is activated.

@beeheemooth Can you provide any additional detail on why drawing and erasing while Autotrace activated is a issue?

**Comment by RodneyBaker** [comment] 2020-01-06 01:41
Closing pending additional explanation of why being able to draw while Auto-inbetweening is active is not a good thing.

**Closed by RodneyBaker** 2020-01-06 01:41 UTC
Labels: UI
