### ISSUE TITLE
reporte

### ISSUE THREAD

**Issue by jhonatannina** [opentoonz/opentoonz#5568] opened 2024-08-17 01:39 UTC
### Ask a question related to OpenToonz

no puedo terminar mi dibujo con los errores que aparecen espero que se solucione pronto del problema

**Comment by RodneyBaker** [comment] 2024-08-17 01:47
Thanks for the report.  We are hopeful the problems will be solved soon as well.
Can you describe the problem you are currently experiencing?

If you are interesting in chat to help in resolving your problem there are venues like the Opentoonz discord.
Here's an invite:  https://discord.gg/hvVj44K4ee

**Comment by RodneyBaker** [comment] 2024-08-17 01:48
Closing as a duplicate of #5569/

**Closed by RodneyBaker** 2024-08-17 01:48 UTC
Labels: troubleshooting
