### ISSUE TITLE
Locked / Hidden Drawing Problem

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#1066] opened 2017-02-27 19:22 UTC
When you hide a drawing it can still be edited without you realizing it. This runs counter to the purpose of hiding of hiding it. It would be better if it were not possible to modify a hidden drawing.

![hidden](https://cloud.githubusercontent.com/assets/18170954/23375833/7effec72-fd32-11e6-8076-0a5e59fd9f71.gif)

**Comment by turtletooth** [comment] 2017-05-22 04:08
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by turtletooth** [comment] 2017-05-22 04:09
Reopening since this behavior is counter to expected behavior.

**Comment by MisterABK** [comment] 2018-03-05 19:27
Hello,

I'd like to add that this problem is particularly troublesome because hiding a level causes that level to be selected. This doesn't make a lot of sense to me, as a new user. So I am repeatedly hiding levels, and trying to draw (expecting to continue drawing on the level I had selected previously) and finding myself drawing on the level I just hid.

**Comment by artisteacher** [comment] 2018-03-05 22:51
@MisterABK, this has been fixed in the nightly builds. Hiding a level will still select it, but accidentally drawing on the hidden level is no longer an issue.

**Comment by MisterABK** [comment] 2018-03-06 09:52
That's great to know!

Would it be worth me reporting the hiding/selecting issue? It's not exactly a bug, but it is unexpected behaviour.

**Comment by gab3d** [comment] 2018-03-06 13:36
@MisterABK 
I think you're right about the workflow disruption caused by unexpectedly selecting a column while hiding it.
Besides, there's obviously no use in having that column selected while at the same time hiding it.

**Comment by RodneyBaker** [comment] 2018-11-05 12:44
#2323 Appears to relate to this issue.

**Comment by manongjohn** [comment] 2018-11-06 05:29
Recommend closing this.  It was an issue with the column buttons in 1.1.3. Back then we didn't even have a popup warning the column as hidden or locked and it didn't block the tool if they were.  This was fixed by version 1.2 which now gives  a popup warning and blocks the tool correctly.

We can treat #2323 as a somewhat separate issue because it deals with shortcuts.

**Comment by RodneyBaker** [comment] 2018-12-12 22:03
Closing based on @manongjohn recommendation.
Please advise if issues suggest the report needs to be reopened.

**Closed by RodneyBaker** 2018-12-12 22:03 UTC
Labels: Bug
