### ISSUE TITLE
Vector Fill Maximum Gap Slider.

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#4395] opened 2022-04-15 15:46 UTC
This problem exist both in OpenToonz and Tahoma2D since  OT PR #1317 and occurs when you try to fill an open shape with the Maximum Gap all the way up when u go to the next frame the maximum gap slider will reset back down and then u have to turn it back up and so on with every next frame.

https://user-images.githubusercontent.com/74626650/163591693-82ab408c-b118-4bc7-bfec-41778343c692.mp4

**Comment by manongjohn** [comment] 2022-04-15 16:00
This is technically not a bug.  The change was to make each frame have its own Max Gap setting.  Naturally this would cause the max gap setting change from 1 frame to the next.

I would suggest converting this to a `Feature Request` to add a toolbar option to `Apply Max Gap to Level`.

When checked it would change and write out only the level based max gap value, as it does now, but discard any frame-based max gap values that might have been previously set when this option was off. The setting would then apply to the entire level and can be different for each vector level.

NOTE: when loading an existing PLI file into the scene, it should somehow detect if any frame-based max gap values are recorded in the file and update the toolbar option appropriately.

**Comment by JPUser1** [comment] 2022-04-15 17:27
@manongjohn  ok.

**Comment by gab3d** [comment] 2022-04-16 23:42
@manongjohn 
...just a note on that new option's name:
the term "Apply" makes me think of an action that is to be executed one time (like a button that you press to make something happen).
Perhaps the new option could be called something along the lines of "Use Global Gap" or just "Global Gap", much like we currently have the "Global Key" option in Animate Tool, to make the inserted key to be applied to all transformation parameters?

**Comment by manongjohn** [comment] 2022-04-16 23:48
However it needs to be labeled is fine, though reading through the comments between Jeremy and Shun-iwasawa in 1317, it sounds like changing the level based autogap treats it as the new format instead of the old one and is no longer backwards compatible? A bit confused.

Needs more discussion/clarification one way or another.

**Comment by RodneyBaker** [comment] 2022-09-25 05:12
One other possible approach might be to have the Maximum Gap Slider value be sticky (as in overwritten) by Default Settings and subject to being saved as a new default when the value is modified.  If the user never modifies the slider then the default would remain zero.  If the user spent some time with the slider at greater than zero and saved Defaults it would save that value as the new default that would appear each time Fill Tool was activated.  To return the default back the user could set the slider to zero and then save default settings.

There are definitely issues with this approach as a user is not likely to know they have locked in that new default and without knowing it made the current levels incompatible with releases prior to the addition of the Max Gap Slider.

Granted... this would be a little hard to discover beyond reading the (presumedly updated) documentation.

**Comment by RodneyBaker** [comment] 2022-12-23 04:54
Closing as abandoned by ghost
There are aspects of the original request that still should be addressed.

**Closed by RodneyBaker** 2022-12-23 04:54 UTC
Labels: needs info
