### ISSUE TITLE
Opentoonz 1.7 crashes when I open it

### ISSUE THREAD

**Issue by Dolendin** [opentoonz/opentoonz#4876] opened 2023-05-09 10:18 UTC
### Description

The software crashes when I open it since I installed the 1.7 release.
Here is the crash log:

OpenToonz 1.7  (Build Mar 14 2023)

Report Date: 2023-05-09 12:15:45
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19044
CPU Threads: 12

Crash File: C:\Users\theju\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230509-121545.log
Mini Dump File: C:\Users\theju\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230509-121545.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\WINTRUST.DLL
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d1bd230cd08e7436\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffddb5e8b4c] <ntdll.dll>
  2> RtlRaiseException [0x7ffddb5c12c6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffddb610f0e] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ffdb33c2b9c] <MSVFW32.dll>
  6> ICOpen [0x7ffdb33c2d64] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ffd9cf96212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ffd9cf94478] <image.dll>
  9> initImageIo [0x7ffd9cf37ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff61f2a0dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff61f2a2d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61f6ceab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61f6ce092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ffdd98d7604] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ffddb5c26a1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. Open the software

### OpenToonz Version

Other (Specify below)

### OpenToonz Version Information

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by justburner** [comment] 2023-05-11 05:39
Exact problem found in #4883

**Comment by RodneyBaker** [comment] 2023-05-11 11:11
Will close this as s duplicate of #4883 but please let us know if the problem persists.

**Closed by RodneyBaker** 2023-05-11 11:11 UTC
Labels: needs info, crash

**Comment by Catrina-Brando** [comment] 2023-12-18 00:13
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-12-18 08:02:22
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 16

GPU Vendor: Intel
GPU Model: Intel(R) UHD Graphics
GPU Version: 4.6.0 - Build 31.0.101.4255

Crash File: C:\Users\Lean Hailie\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231218-080222.log
Mini Dump File: C:\Users\Lean Hailie\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231218-080222.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: KISAME SCENE 1
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\KISAME SCENE 1.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\shcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\bcrypt.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9741ef1f4093481f\igc64.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9741ef1f4093481f\igxelpicd64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9741ef1f4093481f\igdml64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9741ef1f4093481f\igdgmm64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.2506_none_270c5ae97388e100\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffb8f8c7a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffb8f86e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffb8f8f340e] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6fb4361c9] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6fb41d75d] <OpenToonz.exe>
  6> QWidget::event [0x7ffb1ff3807c] <Qt5Widgets.dll>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6fb41b13b] <OpenToonz.exe>
  8> QApplicationPrivate::notify_helper [0x7ffb1ff155c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7ffb1ff134e0] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7ffb1bd2318a] <Qt5Core.dll>
 11> QApplicationPrivate::sendMouseEvent [0x7ffb1ff167c5] <Qt5Widgets.dll>
 12> QDesktopWidget::workAreaResized [0x7ffb1ff609d2] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7ffb1ff5e96e] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7ffb1ff155c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7ffb1ff14643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7ffb1bd2318a] <Qt5Core.dll>
 17> QGuiApplicationPrivate::processMouseEvent [0x7ffb1f8c47c3] <Qt5Gui.dll>
 18> QWindowSystemInterface::sendWindowSystemEvents [0x7ffb1f8af030] <Qt5Gui.dll>
 19> QEventDispatcherWin32::processEvents [0x7ffb1bd6bcfa] <Qt5Core.dll>
 20> qt_plugin_query_metadata [0x7ffb23aa28d9] <qwindows.dll>
 21> QEventLoop::exec [0x7ffb1bd1f64c] <Qt5Core.dll>
 22> QCoreApplication::exec [0x7ffb1bd22164] <Qt5Core.dll>
 23> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6fb375219] <OpenToonz.exe>
 24> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6fb79eab7] <OpenToonz.exe>
 25> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6fb79e092] <OpenToonz.exe>
 26> BaseThreadInitThunk [0x7ffb8da3257d] <KERNEL32.DLL>
 27> RtlUserThreadStart [0x7ffb8f8aaa58] <ntdll.dll>
==== End ====
