### ISSUE TITLE
Tablet:  Hovering not recognized

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1796] opened 2018-02-12 14:49 UTC
--- 
Status
---
- [x] Known Issue
- [x] Documented Workaround(s)
- [x] Documented Code Location(s) / Upstream depencies
- [ ] Drivers confirmed
- [ ] Priority Established
- [ ] Bounty Attached
- [ ] Developer Assigned

---
Report
---

The small yellow dot that appears with hover before we set an onionskin point doesn't appear anymore after I start to paint in the Viewer. It seems like the pen tablet hovering is not properly recognised. I'm on OSX 10.12.6, Wacom Tablet and OT 1.2.

It happens with the Timeline and also with the Xsheet. I have attached a small screen recording.

Thanks!

[Issue.mov.zip](https://github.com/opentoonz/opentoonz/files/1716650/Issue.mov.zip)

**Comment by DotSilva** [comment] 2018-03-08 11:39
Strangely enough, if I change the Wacom Tablet Settings 'Tip Feel' and open Open Toonz, it momentarily works before returning to the described issue.

**Comment by artisteacher** [comment] 2018-06-13 03:03
I’ve been having the same problem in 10.11.6 and 10.13.5. It seems that if OpenToonz is already open and a tablet is connected, it doesn’t register hover events. If the tablet is connected before OT opens, then hovering seems to work as expected - but only temporarily. For example, if the stylus leaves the proximity of the tablet, once the stylus is back in range, hovering no longer works. Disconnecting & reconnecting the tablet also stops hovering from working. If the tablet is connected before OT opens and the stylus does not leave the range of the tablet, all of the hover functionality and tool tip changes register as expected.

**Comment by manongjohn** [comment] 2019-01-13 21:57
Just an FYI,

This is not an OT issue. There is actually an open QT bug reported (QTBUG-65559) that is related to this issue.  It's an issue with pen and mouse tracking not working.

The problem is pen moments typically send 2 events, tablet and mouse events but now it's only receiving tablet events.  Tablet events are where we get pressure data from, but the mouse events are used for a number of things and can help to trigger cursor changes, mouse over button highlights, tooltip display and other mouse over effects.

I will go further and say I don't believe this is a QT version issue, but rather a macOS issue.  I've compiled OT using 5.9.2 and 5.9.7 on  macOS 10.11 (El Capitan) and the problem persists, only tablet events are generated.  I'm guessing it might have started with El Capitan.

Funny thing is, you can make it generate mouse or tablet events by doing the following:
1) Start OT with the pen close to tablet.  OT will generate mouse tracking events and things like tooltips, cursor changes, button highlights, etc, will work. However, when drawing there is no pressure.
2) Pull pen away or keep pen away from tablet when starting OT and it will only generate tablet events. You'll have pen pressure for drawing (ideal) but will not have the other stuff as you are seeing now.

One way to force the switch from tablet events to mouse events is to switch window focus to a window on your mac with your mouse/trackpad, but then touch the OT window with your pen.

**Comment by artisteacher** [comment] 2019-01-14 04:00
Interesting. How can you track whether it's a mouse or tablet event? Will the [changes to QT in 5.12](https://wiki.qt.io/New_Features_in_Qt_5.12) for input make any difference? 
> Replaced the handling of tablet/touchscreen/touchpad/mouse input with a unified implementation

If the problem were solely a macOS issue, I'd expect to have similar tablet issues with more programs.

**Comment by manongjohn** [comment] 2019-01-14 04:31
I put in qDebug() statements in the Tapp::eventFilter() to print out the events its getting.  Debugging in macOS is kind of painful for me since I'm not sure how to do that and ofcourse qDebug doesn't really print to consol or anything in macs, so I hacked it to throw the messages to OT's Message Center. :)

I checked Krita because I know they use QT and I did notice it appears to have some hovering issues on the mac also.  I haven't tested with a non-Wacom tablet. I have one but can't connect it to the macbook I am using because I don't have an hdmi to mini-dvi adapter.  Depending on the application, the hovering issue may largely go unnoticed. We have stuff that relies on mouse overs so it becomes readily apparent.

It's just odd that I can compile with older QT versions on El Capitan and get the same issue. If it was a QT version issue, it wouldn't happen with 5.9.2/7.  So either it's macOS or Wacom+macOS. It would be curious to see if more recent builds of OT would have issues on Mavericks or Yosemite.

As for 5.12:

>Replaced the handling of tablet/touchscreen/touchpad/mouse input with a unified implementation **based on the Windows Pointer Input Messages on Windows 8 and newer**. Hardware like the screen digitizer in the MS Surface line is now supported without special drivers.

Not sure how this impacts macOS though since it seems more Windows related.. But it does seem like they might have Windows Ink finally supported in Qt!  Might have to undo the Windows Ink stuff I implemented, if that's the case.

**Comment by artisteacher** [comment] 2020-01-15 17:12
Based on #2703, it sounds like the hover/focus issue is not strictly a macOS issue - Linux is impacted as well.

It would be interesting to see how much Krita's approach helps.
> Indeed, applying this patch here:
https://github.com/KDE/krita/blob/master/3rdparty/ext_qt/0012-Synthesize-Enter-LeaveEvent-for-accepted-QTabletEven.patch
Fixed most of it

**Comment by coreyryanhanson** [comment] 2020-07-07 17:24
I can confirm that I experience this on Linux too. Using the v1.4 flatpak on Centos8. Right clicking with the stylus also does not work on the canvas.

**Comment by jombo1** [comment] 2021-06-12 02:19
Writing here to say I am experiencing this as well. Running Manjaro Linux, Opentoonz 1.5, XP-Pen 22R. Unable to right click on canvas with stylus, cursor not updating. Seems to be a symptom of the hovering issue.

**Comment by RodneyBaker** [comment] 2023-11-06 13:26
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.

**Closed by RodneyBaker** 2023-11-06 13:26 UTC
Labels: os-linux, os-mac, known issue
