### ISSUE TITLE
surface ui size

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#1339] opened 2017-07-24 10:17 UTC
Hello,

on my surface 3 the OpenToonz  UI is too big to work.

i attached a picture with the ui in comparison with my desktop screen (here the size is ok)
both are 1920 x 1080

i already changed the QT environment variables  = 1

that did not work

any ideas?
![1920x1080surface3](https://user-images.githubusercontent.com/29300971/28518856-c1106e52-7069-11e7-8816-557d2995323e.jpg)
 (OpenToonz 1.1.3)

**Comment by artisteacher** [comment] 2017-07-24 14:30
Did you already have the environment variable changed before upgrading to 1.1.3? If so, you might want to try putting it back to the default.

**Comment by manongjohn** [comment] 2017-07-24 14:58
Was it fine before 1.1.3 or is this the 1st time you're trying it on the surface 3?

Doesn't the surface 3 resolution go higher than 1920x1080? Try going to a higher resolution on the surface 3?  I know someone reported issues with the UI being too small on a surface 3, but I think they were on a higher resolution than what you are using. The issue of the UI being too small was fixed, I believe.

**Comment by shun-iwasawa** [comment] 2017-07-25 03:10
It seems that the Surface 3 has high dpi monitor and OpenToonz automatically adapts it.
Please try the following:

- Select `Control Panel > Display > Screen Resolution` .
- Click `Make text and other items larger or smaller` .
- Select smaller value from `Change the size of all items` options.
- Sign out and sign in again.
- Launch OpenToonz

Please note in advance that OpenToonz UI will become too small to operate  in such settings.

**Comment by bobbybutterfly** [comment] 2017-07-25 06:02
Ok, thanks @shun-iwasawa 
switching the screensize from recommended 150% to 125% fixed it and the UI is now exactly the size like on my desktop.
Back to 150% and the UI doubles again.
Its a workaround for now:)

**Comment by bobbybutterfly** [comment] 2017-07-25 06:20
![screenshift](https://user-images.githubusercontent.com/29300971/28558393-07a2c2fe-7112-11e7-9ad1-af5c450e8ea6.jpg)

**Comment by shun-iwasawa** [comment] 2017-07-25 07:15
Good!
The high-dpi monitor support is not a bug, but a new feature in v1.1.3. In most cases it can obtain an optimum UI size but may become quite large in some monitors.

Closing the issue.

**Closed by shun-iwasawa** 2017-07-25 07:15 UTC
