### ISSUE TITLE
Help!Why is it like this?

### ISSUE THREAD

**Issue by anhle111** [opentoonz/opentoonz#5458] opened 2024-05-14 05:45 UTC
### Description

How to restore original settings and interface? I accidentally ruined everything.
![OpenToonz 1 6 5_14_2024 12_38_14 PM](https://github.com/opentoonz/opentoonz/assets/169647825/63fe4a9e-82cd-4834-83a4-925c1d4c5238)

### Steps to Reproduce

1. 
2. 

### Expected Behavior

I hope there will be a button to restore settings and interface

### Screenshots, Video & Crash Logs

![OpenToonz 1 6 5_14_2024 12_37_55 PM](https://github.com/opentoonz/opentoonz/assets/169647825/bca974c4-3cf1-413f-ba23-3d763579f0ba)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by JParks123** [comment] 2024-05-14 06:19
just double click the timeline header where it says Scene Untitled.

**Comment by RodneyBaker** [comment] 2024-05-16 04:44
Any update @anhle111 ?

**Comment by RodneyBaker** [comment] 2024-05-16 04:47
Closing as a duplicate of #5456

**Closed by RodneyBaker** 2024-05-16 04:47 UTC
