### ISSUE TITLE
Crash related to multiple monitors

### ISSUE THREAD

**Issue by scardario** [opentoonz/opentoonz#109] opened 2016-03-30 05:25 UTC
Hi, I have a crash every time I try to open the program and I think it's because multiple monitors

The only way I can start opentoonz is by deleting all the configuration files created in some subfolders of "open toonz stuff" folder during the start of the application, that's about 27 files. I just make a search for all the files in that folder, organize the search by modification date and delete all of those that were created last.

The crash seems to happen when I have a window in other monitor and that configuration is saved in some file.

If I don't move a window to another monitor the software seems to start again without problems, if I move a window, like say, the combo window, to other monitor, the software will crash the next time I try to start it.

I use 3 monitors (2 monitors and a cintiq), changing a single window to any of the non-primary monitors will crash the application next time I start it.

I'm running win10 pro, no monitor managers installed. Please let me know if you need additional information.

**Comment by tomByrer** [comment] 2016-03-30 11:22
Tried with your 2 monitors & not your cintiq?

**Comment by moonracer191** [comment] 2016-03-31 01:34
I use 2 monitors and a cintiq also. I haven't had any trouble with moving windows but if I try to load opentoonz with the cintiq it crashes on startup. But if I load opentoonz and then plug in my cintiq I have no trouble moving any panels to it. idk what the problem is but for me at least as long as I unplug my cintiq when i load its perfectly fine so you could try that

**Comment by artintime** [comment] 2016-03-31 12:28
Hi,
I am also using a cintiq and two monitors and Toonz worked everytime as long as I keep it on the main monitor, but as soon as i drag it to my Cintiq to work the program remembers the location and crashes the next time i open it. However, it did work when I dragged it back to the main monitor. so maybe just bring the program back after you finish your work is simple as that before they fix the issue?
Thought to share this observation and hope it'll come handy to some.
Cheers.

**Comment by 3Rton** [comment] 2016-03-31 14:08
I can confirm Artintime, this also occurs to me in Windows 10 64-bit OTz 1.0.1 version.
I didn't notice before because my work monitor is my main monitor, but if I start the program, drag it to secondary screen and close it, next time opening it gives the error.

**Comment by tomByrer** [comment] 2016-03-31 14:55
I wonder if this is pertaining to USB monitors, & not exclusive to cintiq?

**Comment by Nyrdbrain** [comment] 2016-03-31 15:52
scardario, can you list the files you had to delete to get it to start again?
I'm having a similar issue with dual monitors, but nothing I've deleted seems to allow it to restart.
If anyone knows where it saves window location data I'd like to know that.

**Comment by Nyrdbrain** [comment] 2016-03-31 16:52
Actually found where it is.

C:\OpenToonz 1.0 stuff\profiles\layouts\OpenToonz.*YOURNAME*  The files are Maindwindow. Popups. Room 1. Room 2. Room 3. Room 4. Room 5. Room 6.

I guess it could be 27 files if you figured out how to scatter and configure 27 individual elements from the program. I only had to delete 4, which get recreated when you start the program again.

Still pretty bad to not be able to save window locations across multi-monitor set ups.

**Comment by artintime** [comment] 2016-03-31 16:53
Nyrdbrain, I'd assume it'd be more useful if you can use Visual studio to debug and track the actual file. Every workstation has different causes and might not work on yours. 
Good luck.

**Comment by Nyrdbrain** [comment] 2016-03-31 17:01
I'm just trying to be helpful. I'm not a debugger.

I tested it out. Opened the program, moved the combo viewer screen onto my portrait mode second monitor, and then closed the program and the same error happened. It wouldn't open.

I deleted those same 8 files and restarted, and it opened just fine and works.

So for simple minded folks like me who just want to use the program after they moved a window around. Try searching for those file names, delete them, then start the program again.

Hope that is helps.

**Comment by walkerka** [comment] 2016-04-01 15:19
Same issue. I'm using Cintiq 13HD on win7 x64 and it works well for the first running. It crashed when exiting on the Cintiq and keeps crashing after that. The workaround is temp disconnecting Cintiq before startup to force it run at main screen. 
I have not compiled code by myself yet. Maybe I can find the reason if the build works.

**Comment by walkerka** [comment] 2016-04-02 04:23
I made a local build with vs2013 32bits/Qt 5.3. And I run with debugger, it no longer crashes even startup from the cintiq screen. It still crashed everytime when I exited but it looks like another issue. Has it been fixed on master branch? Or it's a 64 bits build only issue?

I updated boost library from 55 to 56, not sure if it matters.

**Comment by AyameLee** [comment] 2016-04-04 07:53
Could it be to do with PNG files using an older color profile? For example the PNG files for the theme. Is it worth looking at removing ICC data from those images located in **OpenToonz 1.0 stuff\config\qss\**?

This could probably be tested by just renaming the OpenToonz 1.0 stuff directory, that way OpenToonz 1.0 won't be able to find it, error out but it should still start up. I just tried it and the GUI is completely broken, but the point is to see if it starts up.

Try adding some ICC Profiles under Windows Color Management and see if that helps.

Open Color Management, tick the box "Use my settings for this device", then click "Add..." button, choose **sRGB IEC61966-2.1** then click the button "Set as Default Profile", then "Close". Does that make any difference? **Do it to all your monitors**.

Try it on a freshly installed Windows to rule out any conflicts with other software or drivers. With Toon Boom Harmony, it won't run with Intel HD3000 iGPU drivers installed unless I uninstall OpenCL.

#77

**Comment by mkalte666** [comment] 2016-04-04 11:30
Im running into the same error.

> Is it worth looking at removing ICC data from those images located in OpenToonz 1.0 stuff\config\qss\?

It does not start for me doing that, and crashes at the same point.

> Try adding some ICC Profiles under Windows Color Management and see if that helps.

Did that for all my monitors. Even rebooted. Still does not start.

Strange thing is that directly after the installation i had no problem running the program but after firing my computer up this morning it dosnt start.

**Comment by kusano** [comment] 2016-04-05 20:28
By debugging with Qt DLLs having debug informations, I found that OpenToonz crashes at isFullScreen_sys().
QTBUG-48288 should be related:
[QTBUG-48288] Windows: Crash in the isFullScreen_sys method. - Qt Bug Tracker
https://bugreports.qt.io/browse/QTBUG-48288

**Comment by kusano** [comment] 2016-04-05 20:39
I also found that the following patch prevent the crash.
I could not figure out the reason and the correctness :confused:

```diff
diff --git a/toonz/sources/toonz/comboviewerpane.cpp b/toonz/sources/toonz/comboviewerpane.cpp
index b2cce3c..9aedcac 100644
--- a/toonz/sources/toonz/comboviewerpane.cpp
+++ b/toonz/sources/toonz/comboviewerpane.cpp
@@ -135,7 +135,7 @@ ComboViewerPanel::ComboViewerPanel(QWidget *parent, Qt::WFlags flags)
 		{
 			viewerL->addWidget(m_vRuler, 1, 0);
 			viewerL->addWidget(m_hRuler, 0, 1);
-			viewerL->addWidget(fsWidget, 1, 1);
+			viewerL->addWidget(m_sceneViewer, 1, 1);
 		}
 		mainLayout->addLayout(viewerL, 1);
 		m_flipConsole = new FlipConsole(mainLayout, buttons, false, m_keyFrameButton, "SceneViewerConsole", this, true);
```

**Comment by bigbooteh** [comment] 2016-04-09 00:49
Here's what I found has worked for me.
I'm running Windows 10 64bit with a 2 monitor setup. My secondary monitor is a Cintiq.
When I launched the program the first time I moved it to my Cintiq monitor (because I want to draw)
Then I closed it and attempting to relaunch I'd get the crash at start.
What seems to happen is that it doesn't like to relaunch from a secondary monitor if that's where you closed it from. It remembers that and will fail on relaunching.

So here's my workaround:

Launch Toonz from primary monitor
Drag Toonz to Cintiq to work if I want to draw.
DO NOT CLOSE TOONZ FROM CINTIQ MONITOR
Drag Toonz back to primary monitor and exit So far this is working (pain in the ass but working)
If you do forget and close on a Cintiq or secondary monitor simply delete the mainwindow.ini file
that's found here:
C:\OpenToonz 1.0 stuff\profiles\layouts\OpenToonz.(youcomputersname)
This will relaunch Toonz on the primary monitor again but retain your setup of menus I believe.

Seems like a relatively simple fix.
Hope this helps someone.

**Comment by 3Rton** [comment] 2016-04-09 11:14
@bigbooteh For me the above doesn't work. Just removing the mainwindow.ini isn't enough albeit removing the whole folder works. Albeit this is still the best fix imo since most people probably don't have extensively customized layouts yet anyhow. still would be nice if they could fix the multimonitor issues.

**Comment by artintime** [comment] 2016-04-09 12:43
@bigbooteh The same solution is posted above and I am glad the workaround has worked for you also. 
cheers

**Comment by ryan50505** [comment] 2016-04-12 01:09
OK!  I have been having this issue from the get go. The only solution was to delete a folder in profiles that has my username, but every time the program will run the folder will re-spawn... so I had to delete the folder every time i wanted to use the program. So open  netplwiz in the run window and changed all my accounts to admin level, i also set them to login without entering a  password... IT WORKED!!!

**Comment by kogaki** [comment] 2016-04-19 06:58
Hi all, thank you for your trying some workarounds. Now we merged #174 and it already bundled in `nightly release`. Could anyone test that this build fixed this issue or not? Thanks.

**Comment by scardario** [comment] 2016-04-20 14:58
I just tested it, it doesn't crash anymore, but it doesn't save windows position and sizes when they are in other monitors. Still it's great it's working without crashing.

Thanks!!

**Comment by kogaki** [comment] 2016-04-22 05:15
Great!

**Closed by kogaki** 2016-04-22 05:15 UTC
Labels: Bug, Windows
