### ISSUE TITLE
SVG:  Some objects from import don't have fill

### ISSUE THREAD

**Issue by LifeWatcher123** [opentoonz/opentoonz#3932] opened 2021-04-29 07:00 UTC
**Description**
I have an SVG file from Inkscape and I want to animate it using OpenToonz. Unfortunately, some objects don't have fill in them. I can see the outlines of the object in question when I select it. But, I can't get their fill with the Fill tool. This also occurs in the latest nightly installation.

**To Reproduce**
1. Fresh installation of OpenToonz
2. Import the SVG file attached

**Expected behavior**
All the objects of the SVG, including the left leg, should have a brown fill color.

**Screenshots**
This is the original SVG preview from Inkscape:
![In Inkscape](https://user-images.githubusercontent.com/43345572/116512305-6a154000-a8fa-11eb-8a06-49529b9ba620.png)
This is the result of the import to OpenToonz:
![In OpenToonz](https://user-images.githubusercontent.com/43345572/116512418-9466fd80-a8fa-11eb-9421-2feed6eddad5.png)

**File Attached**
[SVG File](https://drive.google.com/file/d/1NLrTka_AiQIg2tpTF4XyxZ_SKPS-Uy-n/view?usp=sharing)

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: Stable 1.5
 - GPU: NVIDIA GeForce GT 1030
 - GPU Driver Version: 466.11

**Comment by RodneyBaker** [comment] 2021-04-29 11:01
There are a number of known issues with SVG import/conversion and this is one.
It will take some time before all of those are addressed but there are some things that can be done to obtain the best results possible.

For instance, in the case of a character made of different parts that will be leveraged for cutout animation... separating the parts prior to import and then reassembling the parts as groups will usually allow for the best filling results.  The missing leg of your character is a good example of this case.

While your report is a duplicate of prior SVG related reports we'll keep it open for now in order to better draft a path forward to address the more direct requirements of SVG import as well as the larger requirements of fuller SVG support.

Note that in some cases making sure the parts are grouped in the external software can assist greatly in having those groups make the transition from SVG to PLI format... which is what Opentoonz converts SVG images into automatically upon import.   

Since you are using Inkscape you likely have one of the best tools for SVG currently available.
You might experiment with the export settings to make sure those settings are not pushing too far into elements of SVG not supported by older programs... which applies to Opentoonz with regard to SVG processing.

**Comment by RodneyBaker** [comment] 2021-05-07 12:48
I'm going to tag this as a duplicate with intent to close this report in lieu of other similar reports... perhaps especially this one:  https://github.com/opentoonz/opentoonz/issues/1795

If there is something unique in this report over and above the original report that will be good to know.

**Comment by LifeWatcher123** [comment] 2022-05-28 12:17
First of all, thanks again to you and to all that are involved in this project. Pardon my lack of interaction, as school has been rough lately.

To the best of my abilities, I couldn't find an issue where parts of the SVG have specifically no fill. That may be irrelevant, but to my inexperienced junior dev monkey brain, I hope keeping this issue open helps, even in the slightest.

Thank you again for all the hard work. I hope I can contribute soon.

**Comment by artisteacher** [comment] 2022-06-01 02:14
I think this is the first report: https://github.com/opentoonz/opentoonz/issues/119

**Comment by RodneyBaker** [comment] 2022-09-25 06:56
Delayed closure as a duplicate as observered by @artisteacher
Every day we get just a little bit closer to seeing a clear path forward for use of SVG images with Opentoonz...

**Closed by RodneyBaker** 2022-09-25 06:56 UTC
