### ISSUE TITLE
Crash When Editing Lineart using Control Point Editor tool

### ISSUE THREAD

**Issue by tghart** [opentoonz/opentoonz#1242] opened 2017-05-31 10:12 UTC
Hello, I have Problem

This problem always happen when i editing lineart using control point editor tool . Opentoonz will be crash and My project always lost :( , I Use Opentoonz 1.1.2 (Built May 26 2017).

For Example :
![giphy 3](https://cloud.githubusercontent.com/assets/25517443/26627258/0789a242-4624-11e7-8491-ba90677bea4b.gif)

Thanks you

**Comment by turtletooth** [comment] 2017-05-31 19:13
Would you mind sharing the level file this happens on?

**Comment by beeheemooth** [comment] 2017-05-31 20:02
Just make a vector level, select the Line Tool, and click.
![ezgif-1-8de99790be](https://cloud.githubusercontent.com/assets/25724133/26651389/31bb60ba-4655-11e7-8f4d-e2c464b1d423.gif)

**Comment by tghart** [comment] 2017-05-31 21:23
this my level file
https://drive.google.com/open?id=0ByaxsBi8eeBDOGRZQmNibHZHU0U

**Comment by turtletooth** [comment] 2017-05-31 23:43
@beeheemooth I can't reproduce your example.

**Comment by beeheemooth** [comment] 2017-06-01 03:51
Strange. This is from the current opentoonz_nightlies.
There used to be no such problem. Probably at me the program was incorrectly established.

**Comment by shun-iwasawa** [comment] 2017-06-01 04:19
@tghart Thank you for reporting the problem. It seems that you uploaded the scene file, not the level file. Can you please re-upload the file `+drawings\BZ.pli`?

@beeheemooth I tried to reproduce the crash with the current nightly build but I couldn't, neither...

**Comment by tghart** [comment] 2017-06-01 04:48
@shun-iwasawa This https://drive.google.com/open?id=0ByaxsBi8eeBDNUJJQ1J2eHpOWVE

**Comment by beeheemooth** [comment] 2017-06-01 08:46
Hm.. I installed 2017-06-01 05:42:24 UTC opentoonz_nightlies, but the crash still happens.
To reproduce the error, I do the following:
1. Run OpenToonz.
2. Create Vector Level.
3. Select Geometry Tool > Line.
4. Click on canvas. ( and release, no drag )
An error occurs stably only when the layer is empty. If it already contains a vector, then there is no error.
If you can not reproduce the error, tell me, is it possible that this is due to any problems in the system? (windows 8.1)

**Comment by shun-iwasawa** [comment] 2017-06-01 10:19
I could reproduce the crash with the sample data from @tghart .

**Comment by RodneyBaker** [comment] 2018-12-04 03:50
Not sure of the status of this issue.
Any updates?

**Comment by RodneyBaker** [comment] 2019-08-05 17:03
As this issue is over two years old it should be revalidated via current releases.
I can not reproduce @beeheemooth crash which may be a separate issue.
I'm not sure of the exact steps @shun-iwasawa used to reproduce the crash with @tghart supplied Level file.

Recommend review of this issue to determine status.

**Comment by beeheemooth** [comment] 2019-08-06 10:49
@RodneyBaker The crash that I described earlier is no longer observed in recent versions of OT.

**Comment by RodneyBaker** [comment] 2019-08-06 13:35
Good to hear @beeheemooth.
We'll wait a little while to see if there are any updates from @tghart or @shun-iwasawa before closing the original report.

Review continues...

**Comment by RodneyBaker** [comment] 2019-09-20 20:50
Closing as likely resolved and abandoned or resolved by original reporter and others.
@tghart @shun-iwasawa If you still experience any problems please let us know.

**Closed by RodneyBaker** 2019-09-20 20:50 UTC
Labels: Bug, Crash, Needs Info
