### ISSUE TITLE
Load WAV level -> Get creepy sound.

### ISSUE THREAD

**Issue by jabarrera** [opentoonz/opentoonz#863] opened 2016-10-15 11:56 UTC
Hi!

When I load a **WAV sound**, I always get a continuous creepy very loud sound (for example, when I play it from the level in the x-sheet).

I suppose that it must be related with the **frequency** or something related (maybe only happens in GNU/Linux), but I don't get one good WAV (and I think that must be accepted all of them).

I am using Opentoonz and ffmpeg in GNU/Linux.

One I tried was this: https://dl.dropboxusercontent.com/u/58974111/11SecClub_May_Competition.wav

Thanks and greetings.

**Comment by turtletooth** [comment] 2016-10-20 19:10
I think it may be linux specific - I tried the wav you included and it worked fine one Windows.

**Comment by DaveJeffery** [comment] 2016-10-24 12:36
I also get this issue on Linux; I'm on Manjaro KDE 64-bit. I've never managed to get distortion-free audio in OpenToonz. I've tried various audio formats and both 48000 and 44100 sample rates and had no luck with any file I've tried.

**Comment by ideasman42** [comment] 2016-11-27 00:19
Committed fix 7c1be800e990c5b29299c75794e29331c143d291

**Closed by ideasman42** 2016-11-27 00:19 UTC
Labels: Bug, Linux

**Comment by DaveJeffery** [comment] 2016-11-27 15:57
I've just cloned the repo and built it - I can confirm it works beautifully. Many, many thanks.

**Comment by 2xdwolfishdx2** [comment] 2018-11-05 15:15
hola , tengo un problema igual pero en WINDOWS , los audios me con estática  al importarlos y exportarlos con el OPENTOONZ , aqui les dejo una muestra de los audios al exportarlos con el programa

**Comment by 2xdwolfishdx2** [comment] 2018-11-05 15:18
hello, I have an equal problem but in WINDOWS, the audios I statically import and export them with the OPENTOONZ, here I leave a sample of the audios to export them with the program:
https://mega.nz/#!QgRURKLB!Cd8exHOGvD6qxdw5q9wGj1o5891JKVHSWAifl7hRloA

**Comment by gab3d** [comment] 2018-11-07 18:17
@2xdwolfishdx2 's problem might seem related to the original audio file being normalized to a somewhat high level. I've seen his original file and even if it's at a high level it doen't clip in a normal audio player, but when loaded into OT it sunds like what he uploaded above.

A solution I've found was to lower the general volume of the audio in Audacity prior to load it into OT, and that improved the situation.
Nevertheless there seems to be some kind of a problem in OT with audio files which volume levels are near the clipping point.

Attached I leave the original audio that causes the problem, in case someone could test it to see if a possible cause can be found.

[AUDIO DE PRUEBA QUE ME DA FALLAS.zip](https://github.com/opentoonz/opentoonz/files/2558629/AUDIO.DE.PRUEBA.QUE.ME.DA.FALLAS.zip)

**Comment by 2xdwolfishdx2** [comment] 2018-11-08 23:18
> @2xdwolfishdx2 's problem might seem related to the original audio file being normalized to a somewhat high level. I've seen his original file and even if it's at a high level it doen't clip in a normal audio player, but when loaded into OT it sunds like what he uploaded above.
> 
> A solution I've found was to lower the general volume of the audio in Audacity prior to load it into OT, and that improved the situation.
> Nevertheless there seems to be some kind of a problem in OT with audio files which volume levels are near the clipping point.
> 
> Attached I leave the original audio that causes the problem, in case someone could test it to see if a possible cause can be found.
> 
> [AUDIO DE PRUEBA QUE ME DA FALLAS.zip](https://github.com/opentoonz/opentoonz/files/2558629/AUDIO.DE.PRUEBA.QUE.ME.DA.FALLAS.zip)

thanks for the help, really this problem with the opentoonz, makes that I can only use audio with 16bit 32000z quality to work normally

**Comment by 2xdwolfishdx2** [comment] 2018-11-08 23:19
> @2xdwolfishdx2 's problem might seem related to the original audio file being normalized to a somewhat high level. I've seen his original file and even if it's at a high level it doen't clip in a normal audio player, but when loaded into OT it sunds like what he uploaded above.
> 
> A solution I've found was to lower the general volume of the audio in Audacity prior to load it into OT, and that improved the situation.
> Nevertheless there seems to be some kind of a problem in OT with audio files which volume levels are near the clipping point.
> 
> Attached I leave the original audio that causes the problem, in case someone could test it to see if a possible cause can be found.
> 
> [AUDIO DE PRUEBA QUE ME DA FALLAS.zip](https://github.com/opentoonz/opentoonz/files/2558629/AUDIO.DE.PRUEBA.QUE.ME.DA.FALLAS.zip)

thanks for the help, really this problem with the opentoonz, makes that I can only use audio with 16bit 32000z quality to work normally, which is a somewhat low quality for quality work
