### ISSUE TITLE
Plastic Mesh:  Premultiplied alpha / white border

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#1934] opened 2018-04-27 01:33 UTC
Hi. I tried every combination in the level settings to get rid of the white border that appears when I parent a drawing made in an external editor to a mesh made in the plastic tool. How do I get rid of this white border?
![2018-04-26 2](https://user-images.githubusercontent.com/920153/39339970-05e93de6-4991-11e8-85ca-f0b89ea300e7.png)

**Comment by shun-iwasawa** [comment] 2018-04-27 02:01
Thank you for the report, I could reproduce the problem.

The white border usually appears when you import non-premultiplied image. You can get rid of it by checking `Premultiply` option in the level settings.
However, for now such option seems not to effect when you connect the column to the mesh.
Note that the borders seems to appear only in the camstand mode. There seems to be no problem when you preview or render the scene.

**Comment by oladitan** [comment] 2018-04-27 15:13
Thank you for investigating this. When I render the border is subtle but still visible.

**Comment by RodneyBaker** [comment] 2018-05-25 14:08
This issue relates to a broader class of observations all relating to premultipilication and (possibly) antialiasing).

At some point we need to map out the premultiplication process throughout OpenToonz to make determination on what can be done to address the problem and in cases where OpenToonz can't remedy to inform the user of available options.

**Comment by RodneyBaker** [comment] 2018-12-03 22:10
This issue should be resolved.
@oladitan can you confirm?

**Comment by RodneyBaker** [comment] 2019-10-26 03:40
Closing as likely resolved and/or abandoned.
@oladitan Please let us know if you are still experiencing the problem.

Reference also (not yet merged as of the time of this post):  #2854

**Closed** 2019-11-11 02:01 UTC
