### ISSUE TITLE
What can be a possible reason why "Edit cell numbers" - "Reverse" doesn't work in Opentoonz? The cells are normally selected, but Reverse doesn't do anything.

### ISSUE THREAD

**Issue by marekbrich** [opentoonz/opentoonz#3691] opened 2021-01-21 16:22 UTC
**Question**
Ask a question related to OpenToonz.

**Comment by KaseyFarron** [comment] 2021-01-21 16:28
Works fine for me.

![CellEdit](https://user-images.githubusercontent.com/55353161/105380262-963b6980-5c05-11eb-9cfc-6d12611e0981.gif)

**Comment by RodneyBaker** [comment] 2021-01-21 20:17
Can you share any more information about what content you have in your levels?
A screen shot if possible.

**Comment by marekbrich** [comment] 2021-01-22 10:17
https://user-images.githubusercontent.com/68535140/105478136-15cb4600-5ca3-11eb-9223-95c1d6055bee.mp4

Here is the simplest demonstration. I expected the opposite movement after reversing i.e. from bottom right to top left, but nothing changes.

**Comment by RodneyBaker** [comment] 2021-01-22 11:39
The problem is that the Reverse command being used is for reversing image exposures and not keyframes.
You have only one image exposed over the whole set of frames... so... with only one image... there is nothing to reverse with.

Hope that makes sense.

**Comment by marekbrich** [comment] 2021-01-22 13:53
Thanks a lot for the tips. I tried both, replicating the steps in the video, and they work. The workaround I was using was to copy the initial keyframe to the end frame, which gives more or less the same effect i.e. the same movement extended in the opposite direction. Still, I can't say I properly understand the purpose of Level strip and why certain things can only be done there and not in frames. Similar thing happens (another issue here on github) when we try to copy a frame into a new column - the new column mimics all the parameters of the one it was copied from, unless we copy from one column's level strip into another level strip to create an independent object. I believe these two issues are based on the same misunderstanding of the Level strip drawings. Hopefully I'll figure it out, cause otherwise I'm afraid similar issues might get in my way in the future related to Level strip.

**Comment by KaseyFarron** [comment] 2021-01-22 14:57
> Still, I can't say I properly understand the purpose of Level strip and why certain things can only be done there and not in frames. 

The level strip is your drawings, the xsheet controls how those drawings are exposed to the camera, it's really simple, just like the same workflow on paper. It works this way in Clip Studio too, where the layer panel acts like the level strip.

If you copy/paste in the xsheet, you're just copying the text "A 1" or "A 2" etc. as if it were a spreadsheet.

**Comment by marekbrich** [comment] 2021-01-22 18:52
Aha. Then I think the point of "You have only one image exposed over the whole set of frames" (in RodneyBaker's comment) actually means that I have only one drawing in Level strip. When I expand the column frames and animate it, I don't change the drawing as such. If I now get it right, I should understand Level strip as a series of independent drawings (images, objects). So, even the statement "The object is moving (animated) in Level strip" is technically not correct - it is a series of different drawings that give an impression of movement in a right sequence. While the Xsheet is a place for animation; it really doesn't matter if I use one single object/image or more; animation is "blind" and keys apply to whichever drawing happens to be exposed in a frame, irrespective of weather it is one object or multiple across frames. If this is right, further implication would be: this is the reason why I don't see keyframes immediately in images exposed in Xsheet, even though, seemingly, I can see the change in position - because technically there is no change of parameters in one object, no animation, but just different images. these don't have animation parameters at all. And that is also why I can't animate a drawing.

**Comment by artisteacher** [comment] 2021-01-22 18:53
> when we try to copy a frame into a new column - the new column mimics all the parameters of the one it was copied from

That's true - it's just the same drawings in a new location. Instead, try selecting all the cells you want a copy of from the column and then use the clone cells command. This will create a new level with the same drawings but in it's own column. You can make changes to either level without impacting the other.
<img width="235" alt="Screen Shot 2021-01-22 at 1 50 47 PM" src="https://user-images.githubusercontent.com/21159116/105532636-153daa00-5cb9-11eb-8a95-a789ae42ccc5.png">

**Comment by artisteacher** [comment] 2021-01-22 18:55
> And that is also why I can't animate a drawing.

You totally can - using the plastic tool.
[https://opentoonz.readthedocs.io/en/latest/create_animations_using_plastic_tool.html?highlight=plastic](https://opentoonz.readthedocs.io/en/latest/create_animations_using_plastic_tool.html?highlight=plastic)

**Comment by marekbrich** [comment] 2021-01-22 19:11
1   Clone cells - cool! so I don't have to do it in 8 steps as before.
2   Plastic tool, right. still in a frame. I meant I can't animate a drawing in level strip.

**Comment by RodneyBaker** [comment] 2021-03-22 01:59
Closing this but feel free to continue discussion as necessary.

**Closed by RodneyBaker** 2021-03-22 01:59 UTC
Labels: question, troubleshooting
