### ISSUE TITLE
1.7 Release Candidate Build Appears Broken on Linux

### ISSUE THREAD

**Issue by deathchimera** [opentoonz/opentoonz#4840] opened 2023-04-20 04:38 UTC
### Description

On trying to build Opentoonz on Linux, I get the following error after running the "cmake ../sources" command. The same thing happens when building from the AUR with the opentoonz-git package. This message repeats 8 times for each file seen in the middle of the error. I just copy-pasted each file listed into one spot, where it normally would display the info. Example Image below.

-,,,
CMake Error at /usr/lib/cmake/Qt5LinguistTools/Qt5LinguistToolsMacros.cmake:99 (add_custom_command):
  Attempt to add a custom rule to output

    /home/ghost/apps/opentoonz-1.7.0rc/toonz/build/toonz/.lupdate/toonz.ts.stamp.rule
    /home/ghost/apps/opentoonz-1.7.0rc/toonz/build/tnztools/.lupdate/tnztools.ts.stamp.rule
    /home/ghost/apps/opentoonz-1.7.0rc/toonz/build/toonzqt/.lupdate/toonzqt.ts.stamp.rule
    /home/ghost/apps/opentoonz-1.7.0rc/toonz/build/image/.lupdate/image.ts.stamp.rule
    /home/ghost/apps/opentoonz-1.7.0rc/toonz/build/colorfx/.lupdate/colorfx.ts.stamp.rule
    /home/ghost/apps/opentoonz-1.7.0rc/toonz/build/toonzlib/.lupdate/toonzlib.ts.stamp.rule
    /home/ghost/apps/opentoonz-1.7.0rc/toonz/build/tnzcore/.lupdate/tnzcore.ts.stamp.rule

  which already has a custom rule.
Call Stack (most recent call first):
  CMakeLists.txt:604 (qt5_create_translation)
  toonz/CMakeLists.txt:418 (add_translation)
-,,,

### Steps to Reproduce

1. Follow build instructions until you reach Cmake sources step.
2. Attempt to Cmake the sources.

### Expected Behavior

To build

### Screenshots, Video & Crash Logs

![temp-screenshot](https://user-images.githubusercontent.com/77942602/233259444-eff49097-e80c-4e1c-a9e6-7f6bf9ef8932.jpg)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

1.7rc

### Operating System

Linux

### GPU

Intel

### Graphics Tablet

None

**Comment by deathchimera** [comment] 2023-04-20 20:57
The errors disappeared. Trying to build it completely now to see if any other errors occur, but don't imagine they would.

**Comment by deathchimera** [comment] 2023-04-23 23:35
Not sure why I get this issue when building locally. Finally figured out how to capture error output into a file, so this should be useful. Something to do with opencv or how OT calls for it.
[error.log](https://github.com/opentoonz/opentoonz/files/11305247/error.log)

**Comment by Vogtinator** [comment] 2023-04-24 09:06
Duplicate of https://github.com/opentoonz/opentoonz/issues/4831?

**Comment by deathchimera** [comment] 2023-04-25 03:08
Sorry for the late reply. Wasn't aware of vtk at all, thought it was a part of opencv. I don't think I've ever installed it on my system, yet OT builds both in stable and AUR repositories have no mention of it as far as I can tell (and they function well, save for the AUR one currently, as it doesn't disable 'WITH_TRANSLATION'). 
Yes, I believe the AUR works as you described, as do the official repositories. The only difference between the two being AUR is less regulated. 

Installed the vtk library, and OT finished compiling without error. Do builds of OT depend on this? Not sure how builds have worked up until now without listing it as a dependency, but somehow they've worked. I've mainly been referring to builds from official and AUR repos because the difference between local and these builds were confusing me, though that may be because of my lack of literacy with build instructions and tooling.

Here is a link to the Official Community Repo build and the AUR build for those who wish to compare.
https://github.com/archlinux/svntogit-community/blob/packages/opentoonz/trunk/PKGBUILD
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opentoonz-git

**Comment by Vogtinator** [comment] 2023-04-25 06:30
AFAICT the commit https://invent.kde.org/qt/qt/qttools/-/commit/a100f74851afc596b828c67f9eb402d95081e907 in 5.15.9 is just bad.

**Comment by deathchimera** [comment] 2023-04-25 08:52
Well, a mystery for another day, I say. Looking through the issues, I'll have to bump mvoltz's request on #3824. Otherwise, it seems QT is stirring trouble for builds. Issue closing etiquette isn't my forte, so, safe to close?

**Comment by krop** [comment] 2023-04-25 09:41
> I don't have Linux environment at hand so I cannot reproduce the problem, but as a quick workaround, could you try running cmake with the `WITH_TRANSLATION` option turned off?
> 
> `cmake ../sources -DWITH_TRANSLATION=OFF`

This is unrelated to linux. Anyone trying to build opentoonz with Qt 5.15.9 will get the same error. See the comments in #4831

**Comment by RodneyBaker** [comment] 2024-05-30 20:18
Closing with deference to #4831

**Closed by RodneyBaker** 2024-05-30 20:18 UTC
Labels: bug, os-linux, refactor / build, referral / thirdparty
