### ISSUE TITLE
New scene not saved upon creation

### ISSUE THREAD

**Issue by MisterABK** [opentoonz/opentoonz#1777] opened 2018-01-30 11:28 UTC
--- 
Status
---
- [x] Known Issue
- [x] Documented Workaround(s)
- [x] Documented Code Location(s)
- [ ] Priority Established
- [ ] Bounty Attached
- [ ] Developer Assigned

---
Report
---

The fact that there is a "Save In:" field in the Startup window implies that a newly created scene will be saved automatically upon creation. However, it seems that the scene isn't saved.

**Comment by RodneyBaker** [comment] 2018-01-30 14:40
Yes, that's mostly just an indication of where all assets will be saved.  At that point there is little to save because the user hasn't created anything.  

I do agree that it should save a token/generic/empty scene at that time of Scene creation.  I've been caught off guard a few times where I thought my new Scene was saved only to find out (usually through autosave) that it wasn't and therefore had to be named and saved.  

Because I create test Scenes often at one time Isuggested a date + time stamp might work well as a temp file until something was officially saved.  You make me think otherwise and that the Scene itself should be saved at the time 'Create Scene' is executed.  

I *think* what is happening at the time the user pushes that "Create Scene" button is that the directory structure that will hold all of the assets is created.  What you are seeing is that the Level files are not being created so it may be equivalent to a "Save Scene with (empty) Level".

If I understand correctly the problem is that a Scene and a Level are not the same thing and 'Create Scene' is only creating the Scene.  This is presented as "Save In:" because that is where (by default) all associated assets will be saved at the time they are created and saved.

Hope that makes sense.

**Comment by DarrenTea** [comment] 2018-01-31 11:33
I always hit Ctrl+S after starting a new scene, so I don't forget. But I don't use auto-save and regularly manually save. Saving it on creation wouldn't bother me, but I have been know to start a scene for testing a feature/bug or to try a drawing technique and then I close OT without saving, so it works for me in these situations. I wouldn't want a project saved.

But that aside, I think it's common practice for applications to allow you create a new project (without a name and without saving anything) and then when you hit save, it asks for a name. I'd like that feature. The only application I can think of that asks me for a name is Visual Studio and that saves the project on creation, so I agree, by typing a name, this should save it.

**Comment by DarrenTAnims** [comment] 2019-01-08 12:19
Why's this closed? Has this feature request been added elsewhere?

**Comment by RodneyBaker** [comment] 2019-01-08 14:44
As a feature request this report can't live on github per current guidance.
It's not dead though... just closed and in the realm of research and development awaiting a champion to take on the task of coding it into Opentoonz.  I reported this elsewhere so this one is near and dear to my heart.

We should look to see if we can plus up the methodology for feature requests and workflow enhancement as they are highly important and we don't want to miss the opportunities.

There is a fine line between feature, UX enhancement and bug but one question to ask to assist in that determination is; is the current feature in question operating as originally designed?  If not then it's a bug.  If 'yes' then a feature request/enhancement awaiting further development.

**Comment by DarrenTAnims** [comment] 2019-01-08 14:48
I agree. It's probably more of a feature request than a bug. So is there a feature request listed on the Google groups features list?

**Comment by RodneyBaker** [comment] 2019-01-08 14:56
There is a Feature Request forum and a Feature Request (Closed) forum.
Once resolved feature requests there can be recategorized as closed.

https://groups.google.com/forum/#!categories/opentoonz_en/feature-requests

Aside:  I'm confident we can improve the development process and in particular plus up the feature request process in the coming year.  It may take some time but the wheels are already turning and 2019 looks to be a great year for new features and enhancements.  

One thing we do by keeping features and enhancement requests that haven't been fully vetted and championed off of github is allow developers to concentrate on the critical issues that and bugs which keep Opentoonz from being highly stable on all platforms.

**Comment by DarrenTAnims** [comment] 2019-01-08 15:00
I agree that feature requests shouldn't be on github. That's what the google group is for. But I'm concerned that when feature requests in here are closed, that the issue isn't lost. They should really have a feature request opened on the google group at the same time (and maybe a link to it added to the, now closed, bug report).

But in short, I think you're saying that this issue hasn't got a feature request on that group. Is that right? If so, shouldn't we add one?

**Comment by RodneyBaker** [comment] 2019-01-08 15:00
Keep in mind also that a feature request posted here to github can be closed and still developed.
This may be a preferred method for those that really want to see a feature or enhancement implemented and especially for those that don't think posting on the OT Forum will garner enough attention.

In those cases where the line is blurry and it's not entirely clear how a request might positively impact stability... maybe even fix a known error... post the report here on github and then Close it.  Then add new posts as necessarily to update the status.

**Comment by RodneyBaker** [comment] 2019-01-08 15:04
It is my understanding that developers who are looking for features to champion will look to the Opentoonz forum for areas of interest to champion.   This is per what has been stated here when the decision was made not to allow feature requests on github.  It should be noted that many of those decision makers don't frequent here as often as they did in the past.  If no one (besides Shun... I know he monitors the forum closely!) is watching the OT Forum and reviewing those requests then we may need to revisit that decision.

**Comment by DarrenTAnims** [comment] 2019-01-08 15:13
OK, I'll add it to the forum. However, There could be other feature requests being lost if they're just being closed on here and the OP doesn't know about the forum. Shouldn't it be a principal that if you close a feature request from there, that you also add a note suggesting the OP adds the feature request to avoid losing the request? I assumed that you'd be adding them as you closed them. I'll try and add the requests with mine or ones I've been involved with.

**Comment by RodneyBaker** [comment] 2019-01-08 15:17
If a feature request gets lost that is a pretty good indicator that it wasn't all that important to begin with...  ;)

**Comment by DarrenTAnims** [comment] 2019-01-08 15:21
But if the only message they get is that the request has been closed they might think it's being worked on or fixed, so will assume it's in the next release, which was why I was suggesting that when you close them, you add words to the effect of:

This isn't a bug. It's a feature request. If you want to keep this request, please report it at:
https://groups.google.com/forum/#!categories/opentoonz_en/feature-requests

**Comment by RodneyBaker** [comment] 2019-10-26 20:32
Reopening as it is part of the UI Scrub.
It will be good to at least determine if this presents an opportunity to save files early in the production rather than later, risking potential loss of unsaved data.

**Comment by RodneyBaker** [comment] 2019-11-13 21:19
Looks to be resolved by #2875

**Comment by RodneyBaker** [comment] 2020-01-04 16:37
Tagging as known issue.

As it is generally not good practice to leave code in the source in anticipation of some future development a decision needs to be made on whether to implement the code commented out 'as is', to remove/replace it with another approach or to remove altogether.

**Comment by RodneyBaker** [comment] 2020-01-30 00:22
Good news.  This issue has been resolved by #3064.

**Closed by RodneyBaker** 2020-01-30 00:22 UTC
Labels: UI, bug, enhancement, known issue
