### ISSUE TITLE
Frame Range for Vectors with wacom doesn't work

### ISSUE THREAD

**Issue by Toybulldog** [opentoonz/opentoonz#1677] opened 2017-12-12 06:41 UTC
hey,

Yesterday I installed the latest Github master 1.2
Unfortunately I have problems with the range function when I use my Wacom CTH-680.
![my system](https://user-images.githubusercontent.com/11164330/33870739-94610f0a-df0f-11e7-8905-06ef9f24bff2.png)

A few days ago the github version works perfectly. (I still use it, all ok).
Please have a look at the video there you can see what I mean

https://vimeo.com/246918640

Thank you for your good work on OpenToonz I think the development is going very fast.

lg peter

**Comment by artisteacher** [comment] 2017-12-12 17:26
I'm not having any issues with vector frame range with a Wacom Intuos or a Wacom Bamboo on OS X 10.11.6.

**Comment by shun-iwasawa** [comment] 2017-12-13 02:38
I couldn't reproduce the problem either with my CTH-690 both on Win and on OSX.
It may related to Linux, but still need more info.

**Comment by Toybulldog** [comment] 2017-12-13 06:32
I did a video again and tried to describe the problem better
if you can take your time, look at it.
thank you for your effort
https://vimeo.com/247096413

**Comment by shun-iwasawa** [comment] 2017-12-13 06:52
Thank you for the video.
Please let me know the commit id for the version which works properly in the latter half of the video.
Is it possible for you to detect from which commit the problem appears?

**Comment by Orphanlast** [comment] 2017-12-13 07:08
Yo... I have the same problem. My stylus has a button that has an assigned shortcut to (shift+space)... it draws on the screen when I zoom. Or it selects stuff. Or it animates, moves stuff with the animate tool. It all depends on what tool I'm using... so annoying.

I use a week old version of OTX. It's a safe backup. And it's pretty much 1.2.

**Comment by Toybulldog** [comment] 2017-12-13 07:19
gitHub that works
I hope that the right number
![op that works](https://user-images.githubusercontent.com/11164330/33926404-47729c84-dfde-11e7-921a-500b9c807360.png)
![github thats work](https://user-images.githubusercontent.com/11164330/33926416-51a251cc-dfde-11e7-9d6f-56dd60b37e12.png)

**Comment by Toybulldog** [comment] 2017-12-13 07:37
As far as I know, that was before "fix raster selection"
(commit : 75b93877c0abd6a5a005a039d134a584eec7ec8c ) ????

**Comment by Orphanlast** [comment] 2017-12-13 07:56
I'm sure it is. My release said it came out 12/5/2040. It works good.

**Comment by Orphanlast** [comment] 2017-12-13 07:57
*2010... lol

**Comment by Orphanlast** [comment] 2017-12-13 07:57
damnts *2017 (butter fingers... typing wrong digits on a phote)

**Comment by RodneyBaker** [comment] 2017-12-13 08:00
@Orphalast   Don't forget... you can edit your post to correct typos.  ;)

**Comment by Orphanlast** [comment] 2017-12-13 15:11
Yeah, looks like I needeto request the desktop version on my phone

**Comment by RodneyBaker** [comment] 2019-10-26 23:27
@Toybulldog are you still experiencing this issue?
Thanks!

**Comment by RodneyBaker** [comment] 2019-11-03 15:53
Closing as likely resolved and/or abandoned.

**Closed by RodneyBaker** 2019-11-03 15:53 UTC
Labels: Linux, Needs Info
