### ISSUE TITLE
Corrupted data in scene file

### ISSUE THREAD

**Issue by Tartarin8** [opentoonz/opentoonz#3290] opened 2020-05-18 14:26 UTC
**Describe the bug**
For some reason, some values in the function editor seem to be incoherent and impossible to change without creating problems elsewhere. It seem to be a bug with interpolation.

**To Reproduce**
Open the attached scene in OT (no need for dependencies). In the function editor, col3 (souris), between frames 279 and 287, you see several 0 values in columns Scale H, Scale V and Scale, which shouldn't be there. If you look the interpolation tab, it shows "from = 1" instead of the last keyframe, which should be impossible. It seem to be tricky to change those values without moving the problem elsewhere.

At the moment, my file seem to be broken.
**Device Information:**
 - OS: Windows 8.1
 - OpenToonz Version: 4.3
 - GPU: GTX 660
[Une souris verte debug.zip](https://github.com/opentoonz/opentoonz/files/4644626/Une.souris.verte.debug.zip)

**Comment by gab3d** [comment] 2020-05-18 20:35
the problem seems to be in the stored data:
![imagen](https://user-images.githubusercontent.com/18104091/82257091-d2f3ea00-992d-11ea-933e-1b86ec762501.png)

**Comment by Tartarin8** [comment] 2020-05-18 20:40
Could you please give me a hint of:
- where to show those values?
- what value seem wrong (I don't understand)?
- what may have cause that?
- how to change those values to uncorrupt my file?
Thanks!

**Comment by gab3d** [comment] 2020-05-18 20:44
this is the scene file read with a text editor.

I think the problem is the **<n>** just following the 280 keyframe data
perhaps you can try to remove it and loading it back to see if it solves the problem

I updated the image above to show the problem

**Comment by manongjohn** [comment] 2020-05-18 20:55
The problem is the <n>...</n> data. Remove it.

**Comment by gab3d** [comment] 2020-05-18 21:22
but the <prev> data is ok to be there.

i think you should restore the general format you see in previous frames:
`<E>`
`    <prev>`
`       *some data*`
`    </prev>`
`    frame number   *some data*`
`</E>`

**Comment by Tartarin8** [comment] 2020-05-18 21:23
Thanks. I've managed to repair the ScaleH and ScaleV by removing those parts. Haven't found the "Scale" buggy part but I will (it seems buggy in other parameters too, though).
What could possibly cause that? (and what means <n></n>?) I've done no complicated tweeking, it's my first project, I think I just played around with the scaling with the "all" animate tool.

**Comment by manongjohn** [comment] 2020-05-18 21:33
I'm assuming you removed the `<n>...</n>` to fix the file?

The data in `<n>...</n>` is somehow being generated and saved to the file.  I'm not sure what it is.  My guess is when keyframes are added/removed somehow.  It clears something internally which is represented by an `<n>`.  I don't think it was meant to be written out.  The problem is when it's written out, OT doesn't know what to do with it when loading the scene. I've also seen it where it creates `<>....</>` and that also appears to cause similar problems.

This issue appears to be more of an issue lately.

**Comment by manongjohn** [comment] 2020-05-18 21:35
FYI, this is related to #3168

**Comment by Tartarin8** [comment] 2020-05-18 21:40
Ok, thanks for taking care of this problem! By the way, what text editor should I use to easily navigate in the file and finish my tidying? I tried notepad++ but it doesn't allow to open/close parts to navigate faster in hierarchy.

**Comment by Tartarin8** [comment] 2020-05-18 22:20
I've managed to repair the <sc> (scale) data list too, to get the frame interpolation working back, between 175 and 182. I had to remove a bunch of weird things that hadn't the general keyframe structure (not only `<n></n>` this time). Maybe take a look at this column too, if it could give some hints to correct the bug.
Thanks!

**Comment by RodneyBaker** [comment] 2020-05-18 22:35
Notepad++ will allow closing of tags but we have to make sure we've set the format to XML so that the formatting will be recognized.

I recommend Notepad++.

**Comment by manongjohn** [comment] 2020-05-18 23:00
Out of curiosity, do you recall how you were manipulating keyframes and interpolation in the OT session just before you found out your file couldn't load?  Trying to see if it's coming from a particular area.

**Comment by Tartarin8** [comment] 2020-05-18 23:51
My file always could load. It simply had bugs. I think it appeared when I manually set some values in the toolbar option (animate, all, scale) until my main character disappeared and value couldn't by changed anymore. Not really sure though...

**Comment by RodneyBaker** [comment] 2020-10-18 06:27
This issue should be resolved now.
@Tartarin8 Please let us know if you still experience any issues using current releases.

**Closed by RodneyBaker** 2020-10-18 06:27 UTC
