### ISSUE TITLE
Timeline issues while reordering layers OSX

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1797] opened 2018-02-12 14:55 UTC
I am having a strange issue with the Timeline. When I try to move a layer up or down, clicking on the rectangle on top of each layer name, it sometimes selects the other layers instead of moving the desired layer.
As I've said, I am clicking on the top rectangle of each layer's/level name, not on its main rectangle.

I've tried with the pen and with a mouse and the behaviour is the same. I have the latest 1.2 and OSX 10.12.6.

When doing the same thing with the Xsheet, everything works as expected. 

Besides that, another user reported that 'it’s really easy to accidentally add a large number of empty columns when reordering'. It also happens to me too.

Thanks for your attention!

[Timeline Issue.mov.zip](https://github.com/opentoonz/opentoonz/files/1716672/Timeline.Issue.mov.zip)

**Comment by artisteacher** [comment] 2018-02-13 03:45
For both the timeline & the Xsheet, reordering columns beyond the visible area can add an excessive number of empty columns. Dragging back to the intended placement works as expected in the Xsheet but can result in other layers shifting unexpectedly in the Timeline - particularly if the drag towards Col1 lasts too long.

Maybe a workaround should be expanding the timeline/Xsheet window when reordering.

**Comment by DotSilva** [comment] 2018-02-13 14:26
That is one of the issues. I have a shortcut assigned to Remove Empty Columns as my workaround (still not perfect, but it works).

The other issue (for me more problematic) is when I try to move a layer up or down (in the timeline). It selects the other layers most of the times instead of moving the desired layer. I am clicking on the top rectangle of each layer's/level name, not on its main rectangle.

**Comment by artisteacher** [comment] 2018-02-13 14:43
I don't usually have that problem. Are you using multiple displays, by chance?

**Comment by manongjohn** [comment] 2018-02-13 15:17
I can reproduce that selection issue in Windows with a mouse, but I have to basically click and move very quickly to reproduce it. I can even reproduce something like it, sometimes in Xsheet mode, if I start the action close to the border of then column next to it. In that case, it moves the wrong column.

It's like by the time the click is fully registered, the pointer is no longer in the rectangle when it determines what action to do. In timeline, you're likely in the name area and begins selection. In xsheet, you're in the next column and it grabs the wrong column.

If I don't click and move so fast it doesn't happen. Have to try with my tablet.

**Comment by DotSilva** [comment] 2018-02-13 15:44
Not using multiple displays. I've tried clicking and moving fast and slow, as Manong said, but the result is always the same.

**Comment by artisteacher** [comment] 2018-05-25 23:30
This has been resolved in the nightly build. Recommend closing.

**Closed** 2018-10-24 04:15 UTC
Labels: OS: MacOS
