### ISSUE TITLE
Type Tool crash

### ISSUE THREAD

**Issue by CorginautCreations** [opentoonz/opentoonz#3805] opened 2021-03-22 18:34 UTC
**Describe the bug**
Using the writingtool in OT, either writing in the viewer mode or ctrl+V a text will make it automaticly crash the program.
It only worked once, while pasting )ctrl+V) in japenese characters. Then when I opened another window to write in, with alphabetical characters it started to crash.
Opened a new project, tried to handwrite the alphabetical characters, and it crashed again.

**Expected behavior**
To be able to write with my keyboard.

**Screenshots**
[this is the tool that is having issues.](https://media.discordapp.net/attachments/313439701505933313/823617953878245417/unknown.png) 
**Device Information:**
 - OS: [ Windows]
 - OpenToonz Version: [OpenToonz 1.5 (built Mar 21 2021 12:58:10]
 - GPU: AMD Ryzen 5 3600 6-Core Processor 3.59 GHz
 - GPU Driver Version: 2020.1113.1501.27036

**Comment by shun-iwasawa** [comment] 2021-03-23 01:42
Unfortunately I couldn't reproduce the crash with Type tool yet.
Which type of level (Toonz Raster / Toonz Vector / Raster) did you use the tool to?
If possible, uploading a screen captured video showing the crash moment would be helpful.

**Comment by RodneyBaker** [comment] 2021-12-09 20:00
@CorginautCreations Are you still experiencing this problem?

**Comment by RodneyBaker** [comment] 2022-01-20 16:28
Closing this as a duplicate of #4221 
Keeping that report open instead of this one as it has updates to the problem.

**Comment by shun-iwasawa** [comment] 2022-01-21 03:19
I'm not sure why I couldn't reproduce the crash the other day, but now I could reproduce it. I think it seems to be a separate problem from #4221 .

**Closed** 2022-01-21 07:09 UTC
Labels: crash
