### ISSUE TITLE
Crash on start up with Camtasia screen capture drivers

### ISSUE THREAD

**Issue by ajethridge** [opentoonz/opentoonz#180] opened 2016-04-14 23:48 UTC
Sorry if this is an old issue, Opentoonz was crashing on start up. found out that opentoonz didn't like the screen capture drivers for Camtasia 8 specifically DLLfiles " tsc2_codec64.dll" and "tsccvid64.dll". 

I uninstalled Camtasia, since I don't use it anymore and deleted the files from the C:/Windows/SysWOW64/ directory.

Opentoonz now loads up.

**Comment by fthamura** [comment] 2016-04-20 04:23
me also. crash .. in win10

**Comment by RodneyBaker** [comment] 2018-05-26 02:28
**I'm running Camtasia 8.6 and the current OpenToonz nightlies without and crashing on Win10. 
This makes me more than curious about whether the crash issue has also been resolved for other users.**

I'm not crashing with this reported issue while running Camtasia but (initially) I am running into another issue that appears to be triggered by use of Camtasia and OpenToonz running simultaneously.  The good news is that it appears to be resolved in today's PR #2005.

The new issue seemingly caused by the line dot issue that PR #2005 fixes appears to resolve this pressure/stroke issue as well.

**Comment by RodneyBaker** [comment] 2018-12-12 21:58
Original reporter is not continuing to have this issue and current testing with Camtasia isn't reproducing the problem.  (See first post)

Closing this as known issue for older installations of Opentoonz on systems with Camtasia although it would be good to have at least one other confirmation.

The crash report by @fthamura does not appear to be related.
Can you confirm @fthamura that your issue relates to use of Camtasia?

**Closed by RodneyBaker** 2018-12-12 21:58 UTC
Labels: Bug, Crash, Known Issue, OS: Windows
