### ISSUE TITLE
Some cool mypaint resources worth considering to add to opentoonz' library

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#1414] opened 2017-08-18 23:47 UTC
Here are some of the best brush sets that imo should be included with opentoonz,.but they arent

Mojo- https://saegerverse.wordpress.com/mypaint-mojo/
![brushes](https://user-images.githubusercontent.com/6495061/29481084-95262db6-8475-11e7-8b81-3ef10c621ac5.png)

David Revoy's - http://www.davidrevoy.com/article142/ressource-mypaint-brushes
![mypaint-brushkit6_net](https://user-images.githubusercontent.com/6495061/29481132-d545ed3c-8475-11e7-9531-5e3f66b10ed3.jpg)

**Comment by RodneyBaker** [comment] 2017-08-19 12:47
Hmmm... I'm not sure what you are talking about...  not being included.  ;)

Let's see.
You posted this.
I downloaded and unzipped into MyPaint brush folder.
Now I have them.  :)

Thank you.  Those are great.

You need to post things like this to the main forum so other can have them too.  :)

**Comment by blurymind** [comment] 2017-08-19 13:06
My request is to have them included with the install :)
Have some of the best mypaint brushes in OT, not just a bunch of the oldest
default sets

**Comment by RodneyBaker** [comment] 2017-08-19 13:17
Sorry, I know.  I was just being me.
Speaking of being me... and not you...
When I use that one pen... the one you can draw for hours and hours with... my drawings do NOT turn out that nice.  There is something obviously wrong with that brush on my end.

**Comment by blurymind** [comment] 2017-08-19 13:20
It's a low hanging fruit that would improve the mypaint feature out of the
box - with  very little effort for the devs
Just download and unzip a bunch of files
:)

**Comment by RodneyBaker** [comment] 2017-08-19 13:33
This does raise a fairly significant point.
How can we implement things like this ourselves without resorting to the primary developers involvement.
To attempt to answer my own question I'll suggest some possibilities:
Perhaps we could create a methodology for users to Update brushes from right inside OpenToonz without resorting to creating a new build.  This may relate to @turtletooth 's recent work on granting OpenToonz builds the ability to be portable.  I digress a little.  The point here being that if a way to update the brushes from a specific location could be implemented then all someone would have to do to enable that would be:  1) To upload new brushes to that location 2) reset the pointer to point to a different location.  

Aside:  I like that David Levoy's brush set is released to the public domain.  Nice!  (and Thanks to David Levoy for those brushes!)



P.S.  Lately I've found that I really like the basic 'brush' in MyPaint.  This has much to do with the fact that I like the look of brush inking it produces.  When using it I find myself thinking I need better pencil work underneath to ink on top of because I realize I've become lazy (that and I'm not really that good an inker).

**Comment by blurymind** [comment] 2017-08-19 13:38
@RodneyBaker implementing a system to get resources from a shared repository would require much more work for the developers. Krita used to have it, but i think it got discontinued due to the other requirement of continued service to the repository - hosting, moderation, etc

My suggestion is to include a bunch of the best brushes atm with the install, then let the users find more brushes

Another lower hanging fruit could be to add a 'import mypaint brush set' command that simply copies a selected by the user mypaint brush set to the brush folder. And maybe a command to open the folder where mypaint brushes are - to make it easier for the user to discover it. Or a command that opens a web page where more brushes can be downloaded

**Comment by RodneyBaker** [comment] 2017-08-19 13:51
Understood.  One of the first things I did after using MyPaint in OpenToonz is go out on the internet, locate and download a few other brushes.  I need to remove and reinstall so that I know which are the default and which are the ones I added.  As your intent is to improve the default set of brushes that area of recognition of what is default versus what has been might be an area for opportunity and for developer involvement.   

One thing I'm anticipating is that other users might think similarly and want a particular brush or set to be added to the default.  How do we best determine what should be default versus what should not?  
I know this is outside of your issue but consider... that is the reason Feature Requests aren't dropped into github.  ;)

As for adding the brushes you want to add to the default, I think I can do that.
Is there some kind of vetting process I need to go through before I implement this and submit a PR?
Obviously once I do submit a PR the powers that be don't have to merge it but... as you say it should be easy to at least get the brushes to the point of a PR so they can add it if they want.

**Comment by RodneyBaker** [comment] 2017-08-19 14:43
Okay, I see where the license are maintained.
We just have to add this set to the license.txt file in the MyPaint brush folder.
David Levoy already has one set listed there.


See:  
https://github.com/opentoonz/opentoonz/blob/master/stuff/library/mypaint%20brushes/Licenses.txt

**Comment by RodneyBaker** [comment] 2017-08-19 14:59
Initial PR has been submitted to add the Mojo set of MyPaint brushes to OpenToonz
What has been done thus far:
 - Corrected spelling word 'experimental' at the top of license.txt document
- Added license information and attribution to author of Mojo brushes (Saeger Ryman) to license.txt  I'm not sure why I thought the author was David Levoy before.  Perhaps the Mojo set is based on the Levoy set?  Regardless both are licensed CC0 1.0.
  Please disregard that reference and I'll edit that post to be more accurate.

To Do:  
- Add the directory and the brushes

**Comment by konero** [comment] 2017-08-19 16:26
Work with branches. I know it seems complicated at first but you'll get the hang of it, and if you're using Git Desktop its really simple.

https://guides.github.com/introduction/flow/
https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

You can practice by forking the Spoon-Knife repo and pushing branches to it.
https://guides.github.com/activities/forking/

**Comment by RodneyBaker** [comment] 2017-08-19 16:35
@Kite  Thanks!   Initially I thought I was working with branches.  Then
apparently I wasn't.
I seem to went off track when I tried to create the directory to store the
brushes in.
I forgot how to do that.

The good news is that the content of the things I've worked on thus far is
simple (no math!) so there may still be hope for me.

**Comment by adamearle** [comment] 2017-08-21 03:04
Simple remove, add, import and export buttons of presets in opentoonz is
really lacking and would be the most professional oriented fix.

Considering also what professional artist/ animators and studios need to do
from a day to day, week to week and project to project basis why this isn't
already made abailable shows a clear lack of understanding of modern
workflow for current animation.

This is actually to be honest actually something that is really really a
pressing issue for alot of practicing animators and studios because of the
lack of versatility and will continue to make opentoonz the last choice and
slow down development because of the lack of people/ studios wanting to
pick it up.

This is seriously worth having a conversation about over the water cooler
and then getting on with it and just doing it and making it happen.

I could go on

Ad  ;D

**Comment by turtletooth** [comment] 2017-08-21 05:02
> why this isn't already made abailable shows a clear lack of understanding of modern workflow for current animation.

It more likely shows a lack of manpower and funding.  We all know these features would be great to have, but not everything can be tackled all at once.

**Comment by gab3d** [comment] 2017-08-21 06:03
@adamearle, if you'd like to fund a special development of your choice,
it'd probably be done sooner. ;)
Otherwise, you better expose your points in the best way you can and hope
for some cool volunteer developer to decide and use his free time to do it.

El ago. 21, 2017 2:02 AM, "Jeremy Bullock" <notifications@github.com>
escribió:

why this isn't already made abailable shows a clear lack of understanding
of modern workflow for current animation.

It more likely shows a lack of manpower and funding. We all know these
features would be great to have, but not everything can be tackled all at
once.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opentoonz/opentoonz/issues/1414#issuecomment-323646910>,
or mute the thread

**Comment by jpturcotte** [comment] 2017-08-21 15:53
Exactly. @adamearle, this is a case of [Bountysource](https://www.bountysource.com/teams/opentoonz)! You really should create a thread for this in the Google Group.

**Comment by RodneyBaker** [comment] 2017-08-21 17:12
My response should be in the forum but I place it here because this is
where the original thoughts were given.

@AdamEarl said:

> professional artist/ animators and studios


I agree that it is good that professional artists and animators conduct
themselves in a professional manner.
It is also important to remember that Professional artists/animators often
have an IT savvy person on call dedicated to ironing out the rough spots in
their particular workflow.
It's that dedication (assignment) that can prove troublesome when faced
with limited resources and especially under the weight of production.
Hence the need for prioritization.

The OpenToonz community has a methodology for fast turn around of bug
reports (the priority) and feature requests (very important but of a lesser
priority).
Keep in mind that new features produce new bugs that must then also be
prioritized so the process is cyclic.

Here an overview of the current methodology:

Bug Reports (Priority)
- Report reproducible bugs to github were they can be fixed.

Feature Requests (Prioritized upon acceptance by/assignment to developer
otherwise in varying states of development)
- Submit Feature Requests to the OpenToonz forum placing the post in the
Feature Requests category.  Once addressed it will be moved to Feature
Requests (Closed).  If necessary the request can be refined and reopened or
used as the basis for a new request.
- Feature Requests assigned to a developer should be added to github where
they can be referenced by a Pull Request (PR) upon completion.
In effect, the issue is a 'work order' which tasks someone (often the same
person that issued the request) with the work.

Ideas that fall into other categories can be discussed and explored and
psuedo-coded while they await a programmer to champion.
Discussion and user development will improve the ideas chance of adoption.

Things that fall outside of these two areas such as general exploration of
a feature or workflow are discussed in the OpenToonz forum 'Discussion'
category.  Potential bug reports that cannot be replicated or demonstrated
should be posted to the OpenToonz forum under the "Troubleshooting"
category.  Often an issue can be resolved quickly at the user level and
(importantly) user error can be ruled out.

The final two categories in the OpenToonz forum are "Announcements" and
"Share your work".
Announcements is where matters related to OpenToonz should be highlighted
and news shared about significant events and milestones.
'Share your Work" is similar to that but more for placing the spotlight on
things not directly related to OpenToonz.
There can be a fine line between these two categories but it can help to
think of 'Announcements' as speaking on behalf of those that bring us
OpenToonz.  If they would post the announcement there then... Announce!
'Share your Work' is perhaps the arena with the most promise because as
OpenToonz user begin to produce animation those efforts will need to be
placed in the spotlight.
This category also includes Works in Progress so forum members should be
continuously posting updates to their projects.

@AdamEarl Are you familar with the term 'hyperbole
<https://www.google.com/search?q=define+hyperbole&oq=define+hyperbole&gs_l=psy-ab.3...25668.27003.0.27194.0.0.0.0.0.0.0.0..0.0....0...1.1.64.psy-ab..0.0.0.pUjbczHcoOE>'?
 ;)

If everything is a priority nothing is a priority.
Let's start a discussion in the OpenToonz forum (or two or three) where we
can further define and express your priorities.
Let's refine them to the point where they appear as full blown features,
tiny tweaks that meet your criteria and everything else necessary.  :)

**Comment by blurymind** [comment] 2017-08-22 18:51
pull request here:
https://github.com/opentoonz/opentoonz/pull/1417
and
https://github.com/opentoonz/opentoonz/pull/1416
@RodneyBaker Thank you! 👍

**Closed** 2017-11-14 05:49 UTC
Labels: Feature Request
