### ISSUE TITLE
Strange  crash when copy-pasting (gif, zip)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1711] opened 2017-12-28 21:16 UTC
One of my Toonz Raster drawings crashed the program when copying and pasting into the Vector Level. With the exception method, having lost many time, I determined the problem area of the drawing (see zip). This fragment can be copied and pasted only in parts, if you insert the entire fragment, the program will crash. Why is this happening?

[ED.zip](https://github.com/opentoonz/opentoonz/files/1592128/ED.zip)

![ezgif-3-3ecfb5c37c](https://user-images.githubusercontent.com/25724133/34423489-0120492c-ec25-11e7-948b-3e2ee9f34cab.gif)

**Comment by beeheemooth** [comment] 2018-02-03 21:53
I was able to figure out the fact that one of the reasons for the crash of the program when converting Toonz Raster Levels in Vector Levels is probably the "Treshold" parameter. This drawing, one of the many in one level, resulted in crash of the program at one value of the "Treshold" parameter, and at another value the conversion was successful.

![ezgif-3-7f459d9ffb](https://user-images.githubusercontent.com/25724133/35771914-515d9856-093d-11e8-90ec-9d0455669942.gif)

**Comment by RodneyBaker** [comment] 2018-10-13 03:09
I'm unable to reproduce this problem.

**Comment by RodneyBaker** [comment] 2019-10-24 07:18
I no longer get a crash with with the provided file (nor other files) when Threshold isset to 100% during Convert to Vector.

@beeheemooth  Can you confirm?

**Comment by RodneyBaker** [comment] 2019-11-10 16:08
Closing pending confirmation of the issue persisting.

**Closed by RodneyBaker** 2019-11-10 16:08 UTC
Labels: Bug, Crash
