### ISSUE TITLE
Trouble with SVG image import

### ISSUE THREAD

**Issue by GrishGautam** [opentoonz/opentoonz#4018] opened 2021-07-20 05:54 UTC
**Describe the bug**
Importing problem.

**To Reproduce**
List steps to reproduce the behavior.
1. And fill tool is not working properly in vector mode.
2.
3.

**Expected behavior**
can you please make fill tool work as good as in raster mode.please. (❁´◡`❁)༼ つ ◕_◕ ༽つ༼ つ ◕_◕ ༽つ☜(ﾟヮﾟ☜)
**Screenshots**

https://user-images.githubusercontent.com/85336666/126268667-f916dd82-1706-4f83-a348-c5ce7506a05f.mp4

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by artisteacher** [comment] 2021-07-20 12:28
SVG import has several known issues - #3171, #1009, #1795, #3677

**Comment by RodneyBaker** [comment] 2021-07-20 12:35
As @artisteacher has indicated, there are many known problems with SVG import and so will close this as a duplicate of those other open reports.

Until such a time as those issues are championed and (eventually) resolved there are a number of workarounds one of which works quite well but is not optimal especially if trying to maintain the original vector lines.  The best results I've seen have actually been to render the vector artwork out as PNG... import that PNG into Opentoonz... and then convert that image to vectors (usually using outline rather than centerline).   Told you it was not optimal!  ;)
Perhaps the one thing I personally avoid more than anything when importing SVG images is gradient fills...  just not worth the effort.  Interestingly, gradient fills export out of Opentoonz rather nicely and if nothing messes with the process while the file is external maintains those gradient fills when reopened in Opentoonz.  Go figure.

I do recommend reading up on those other issues as each report does discuss the various problems.
Hopefully we can start a master report soon and perhaps even do a fundraiser to encourage a developer to take on the variouis tasks releated to SVG import/export.

There have been a few users that have found optimal ways to work with SVG but that is mostly by avoiding the known issues.  One thing that can help tremendously is to output to SVG 1.0 format... and without any fancy fills or linework.

One thing you can do to assist the effort to resolve SVG import/export is to share one of the SVG images you are trying to import without success.  That SVG image can then be used as a example of what works... does not work... may someday work... and likely will never work except in the far flung future.

Will keep this report open for now as any file you contribute might add something to the mix that is unique beyond those other reports.

Also, with regard to color fills 'coming up'...
It might be good to consider how palette styles/color swatches work in Opentoonz.
The assignment of colors can break the fills of an external SVG being imported because of how that works.
If carefully considered however, fills can import quite nicely.

**Comment by GrishGautam** [comment] 2021-07-20 13:44
Thanks for concern.❤😁😁
but i can't upload svg file. 
here is the image i downloaded from site:
https://face.co/

**Comment by RodneyBaker** [comment] 2021-07-20 14:29
Yes, with Github we either have to link to the SVG source or compress the image into a .zip file and upload that.

As far as embarking on the path to being a developer (specifically of Opentoonz) I'd say the first thing to do is build Opentoonz from the source code.  Being able to build from source (and edited/changed code) is about as basic as it gets and it's just complex enough that it will let you know whether or not development is something you want to pursue.  Build instructions can be found here:  

https://github.com/opentoonz/opentoonz#how-to-build-locally

**Comment by RodneyBaker** [comment] 2021-07-20 14:52
A problem with the SVG images created from that site is with how shapes overlap each other in complex ways.
This suggests to me that grabbing the image as a PNG raster/bitmap first, importing that into Opentoonz and then converting from raster to vector is going to work best.

This assumes that you wouldn't take the SVG into another program such as Inkscape and optimize it for use with Opentoonz.

Here is a quick test of a conversion from a screen grab of the face (raster) into vector.
At this point the vector lines are not optimally connected.  Running the option to Simply Vectors in Opentoonz can often remedy that.

![image](https://user-images.githubusercontent.com/2576432/126345675-240fcc4c-df26-48d3-8e76-deba5cabae87.png)

**Comment by RodneyBaker** [comment] 2021-07-20 15:22
Here's me messing around a little more and adding a gradient fill once the image is converted from PNG to vector inside Opentoonz:

![image](https://user-images.githubusercontent.com/2576432/126350804-d5fcfa77-4976-4ae6-9910-b4e8a84db6db.png)

**Comment by artisteacher** [comment] 2021-07-20 16:29
Just an FYI, any gradients are going to have issues on import. You are more likely to have a successful import with solid fills. Also, the more complex the SVG, the more likely there is to be issues on import.

**Comment by RodneyBaker** [comment] 2021-07-20 19:33
Will close this report as it does not appear to add any new issues not addressed in the other referenced reports.
Feel free to continue the discussion here of course.

**Closed by RodneyBaker** 2021-07-20 19:33 UTC
Labels: duplicate, known issue

**Comment by GrishGautam** [comment] 2021-07-21 09:16
Thanks everyone.
