### ISSUE TITLE
Brush tool problem on HUION Graphic tablet..

### ISSUE THREAD

**Issue by digimikeh** [opentoonz/opentoonz#586] opened 2016-07-06 03:37 UTC
Hi all..

Today i bought a Huion H610 Pro graphic tablet, i have installed latest drivers (Mac OS X El Capitan) and after that i opened OpenToonZ...  everything is fine till now...

When i select Brush Tool (b) and then try to draw with the pen, it won't draw at all no matter if i check or un check the option boxes : "selective", "pencil" and "pressure" .. none of them make the tool work with the pen..  curiously works with mouse..

The only way i can work is using paint brush tool, but i think its purpose is not for drawing because they are not used as lines...

if this is solved, please forget me... if not.. well.. the issue is on.

Thanks!

**Comment by digimikeh** [comment] 2016-07-07 04:16
Bought another one, Genius 608, getting the same problem in mac... on windows works fine..
looks like is a mac version problem.

**Comment by digimikeh** [comment] 2016-07-08 23:37
looks like no one is using mac and a graphic Tablet here?...

I have noticed that none of graphic Tablet Works with pencil brush on mac systems... 
consider it please?, as a low priority of course.. but take in mind 

Thanks.

**Comment by digimikeh** [comment] 2016-07-09 04:41
today i was tested using different levels (Preferences -> Drawing)...
Vector Toonz Level and Raster Toonz Level are not working with graphic tablet on Mac..
Raster Level is working....

**Comment by samirosman** [comment] 2016-07-12 23:33
I can confirm this issue on OSX when using the huion h610pro tablet and the huion GT-190 monitor. I can draw one or two strokes then it stops. Other tools such as the selection and vector deform tools work normally but I am unable to make any new strokes.

**Comment by digimikeh** [comment] 2016-07-13 02:40
good to read that (for me) so i can assume is not a problem of my system else a compilation one.

lets wait so... :)

**Comment by jpturcotte** [comment] 2017-08-21 20:58
Is this still occurring with the latest nightly: https://github.com/opentoonz/opentoonz/releases? The devs are working on tablet issues on Mac right now, so it would be really useful to know. Thank you!

**Comment by samirosman** [comment] 2017-08-22 03:05
@jpturcotte works on the Huion H610 haven't tested on the GT-190.

**Comment by jpturcotte** [comment] 2017-08-22 12:08
@samirosman So the issues seem fixed? Great! Tell us if you get to try it on the GT-190. Thank you very much!
@digimikeh Can you please check if it works for you?

**Comment by samirosman** [comment] 2017-08-22 16:52
@jpturcotte yes the issue seems to be fixed on both the GT-190 and the H610!!
Thank you Devs for the fix!

**Comment by jpturcotte** [comment] 2017-08-22 17:19
Hurray!
@turtletooth Smells like a close!

**Comment by RodneyBaker** [comment] 2018-10-13 03:00
Multiple users have reported driver updates resolving Huion problems.
@digimikeh If this issue is resolved for you recommend closing the issue.
If not please let us know.

**Closed** 2018-10-24 04:08 UTC
Labels: Bug, OS: MacOS
