### ISSUE TITLE
all 500+ of my frames are gone after opentoonz crashed, how do i restore them? (mac)

### ISSUE THREAD

**Issue by bes-ang-lala** [opentoonz/opentoonz#3361] opened 2020-06-22 18:00 UTC
I was animating until the application suddenly closed and crashed. This has happened before, so I was not that worried about it, but when I opened OpenToonz again, all of the frames had gone missing. All the frames all had no icon and was coloured red instead of white. 
![Screen Shot 2020-06-23 at 12 11 05 AM](https://user-images.githubusercontent.com/67286530/85319957-ed088580-b4f4-11ea-8c4a-458916cd60f7.png)
![Screen Shot 2020-06-23 at 12 11 11 AM](https://user-images.githubusercontent.com/67286530/85319974-f85bb100-b4f4-11ea-9da1-40a443cf379f.png)

I watched this method: https://www.youtube.com/watch?v=5npFPB2VuWc but he was a windows user, and I don't think it worked out well. 
I have tried uninstalling the application and reinstalling it.
I went to sandbox -> drawings -> and tried copy pasting the level back. 
I have tried getting the save file and removed the bak on tnz.bak, loaded it up as tnz, but it still came out the same. 

I would really love (am dying) to know how to get my frames back. I worked six hours straight on an animation software I didn't know how to use, and might have had a breakdown after this incident. Please help :^(

**Comment by artisteacher** [comment] 2020-06-23 01:31
This is likely related to #2581. There are always a couple things worth checking when a level is missing. First, I like to make sure there's not a path issue.

To check if the problem is a path issue, right-click on a cell from the level in the Xsheet/Timeline and select "Level Settings". At the top you can see the name of the file and the expected path. The end of the path should be identical to the level name + the level ending. If the names don't match, the level won't load.
<img width="367" alt="Screen Shot 2020-06-22 at 9 12 52 PM" src="https://user-images.githubusercontent.com/21159116/85349988-e4e91f80-b4cd-11ea-8cfb-271a863d7e62.png">

If there's not an obvious path issue, I'll take a look in Finder & see if I can find the level there. If the correct level is visible in the drawings or extras folder (or a custom location), I'll open the scene's backup to see if that helps. In the scene folder, I'll rename the scene backup to something new & remove .bak from the name. Then I'll load the renamed backup in OT.

Otherwise, if I looked for the level in Finder & it was missing but the backup is there, then I'll rename the backup level (as you tried). After renaming the backup file to use the exact same name as the original, I'll restart OT and try opening the scene again.

If none of that works, I'll try restoring the project from the most recent Time Machine backup. Time Machine running automatically is a life saver.

**Comment by bes-ang-lala** [comment] 2020-06-23 06:08
Hello, first of all thank you so much for responding back to help me out :^(

I went to check the paths as you told me to, and it looks like the end actually is identical to the level name.
<img width="359" alt="Screen Shot 2020-06-23 at 1 57 00 PM" src="https://user-images.githubusercontent.com/67286530/85366653-61294480-b55a-11ea-9114-a15bee8eb462.png">

And to my surprise, it was, in fact, still inside the drawings folder.
<img width="204" alt="Screen Shot 2020-06-23 at 2 00 12 PM" src="https://user-images.githubusercontent.com/67286530/85366710-7dc57c80-b55a-11ea-9aaf-9a6fc42949a8.png">

This baffles me since nothing looks out of place at all, only frustrating me even more :^( And I unfortunately don't have Time Machine running, so I wasn't able to use that to help me out. 

If you need a visual for how my scenes folder look:
<img width="193" alt="Screen Shot 2020-06-23 at 2 02 16 PM" src="https://user-images.githubusercontent.com/67286530/85366869-c4b37200-b55a-11ea-9206-e089d179cfdf.png">
The copy was the renamed .bak file, but as I've said earlier, none of the icons still came out hgngh

Did it really crash that bad? I really, really don't want to give up my animation :^(((

**Comment by artisteacher** [comment] 2020-06-23 06:46
If you look at the drawings folder in the Browser room (with icon view), does the level show up? It might be worth trying to load it in a new scene or project.

**Comment by bes-ang-lala** [comment] 2020-06-23 07:53
ahhhh shucks it still doesn't work,,,loading it into an entirely new project still has the all frames corrupted :^((( it's nice to see that my files are still there and it recognizes the amount of frames i have, but it really just won't load

thanks so much for the help, but unfortunately it looks like i'll have to just redo this some other time hhhhh,,,

is there a way to avoid this in the future?

**Comment by artisteacher** [comment] 2020-06-23 15:29
Personally, I've set the number of backups to 2 in Preferences in case something like this happens. It won't necessarily fix things every time but if the level itself & the first backup are corrupted or missing, maybe there's a chance the 2nd one won't be.

I do highly recommend turning on Time Machine. It'll save backups locally on the computer if there's not an external drive setup. If a crash in OpenToonz corrupts or removes something, it wouldn't have any impact on a Time Machine backup.

Do you remember exactly what you were doing before the crash? If you can share the crash report, it might help developers figure out what went wrong.

**Comment by RodneyBaker** [comment] 2023-09-17 04:58
Closing as sufficient time has passed to discover whether or not the original frames of animation could be restored.
Feel free to continue the discusstion as necessary.

**Closed by RodneyBaker** 2023-09-17 04:58 UTC
Labels: os-mac
