### ISSUE TITLE
Optional horizontal xsheet layout

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#503] opened 2016-06-23 04:15 UTC
It would be nice to have an option to orient the Xsheet in a horizontal layout instead of the vertical one.  Keep both, but allow the horizontal layout as a different xsheet window that can be chosen, much like the Tool bar can be selected in vertical or horizontal layouts.

Here is an example of a current vertical layout and a mocked up horizontal layout with the same information:

![xsheet-horizontal](https://cloud.githubusercontent.com/assets/19245851/16291290/2e715742-38d3-11e6-97c4-4decff5edd44.png)

It is a bit more intuitive because it looks more like a timeline.  This looks and feels similar to timelines in other animation software making it easier to understand.  It also feels more natural to view the timeline from left-right instead of up-down.

Most screens/videos are wider than taller so a horizontal layout could work out better when placed at the top or bottom of the screen like in the Cleanup, Animation or Pltedit rooms.  Docking it on the right or left and squeezing it to just show icons and visibility/lock buttons would make it appear similar to "Layers" panes in other animation software which could be useful in the Basics or Drawing room.

Might also want to consider adding a horizontal layout for the Function Editor if this one is done.

**Comment by Rayek** [comment] 2016-06-23 07:50
Although I disagree that a horizontal Xsheet or timeline would feel more natural (to professional paper-based animators the Xsheet is a tool of their trade, and I actually prefer the vertical Xsheet layout myself), I do agree that it would be very handy for many users and screens that a horizontal option is available in OT.

However, I am unsure how much work and effort that would take.

**Comment by blurymind** [comment] 2016-06-23 11:46
I personally would never use a horizontal  xsheet on a single monitor setup.

Tvpaint uses that style and while it gives a lot of extra horizontal space for cells, it takes away almost half the vertical space of the actual drawing area. When you animate biped characters vertical space is super precious, while horizontal space tends to be white canvas. That is why the current setup is actually really good!
One way tvpaint gets around the problem is having the software autohide the horizontal x-sheet while the mouse cursor is not over it's panel. This is something that can be toggled on/off on most panels - they have autohide mode.

But tvpaint's design is different to the one in toonz.We dont have that autohide panel behavior

**Comment by Juls3000** [comment] 2016-06-24 18:54
IMO vertical Xsheet gives to OpenToonz his unique personality, which means integration of both, step by step and interpolated animation, me too I prefer it. This solution comes from many hours of integrated work of coders and animators.

**Comment by manongjohn** [comment] 2016-06-24 19:51
You make it sound like I am suggesting a replacement. I just want the option of using either one. :) Default can remain the vertical one. Use horizontal only if you want to. No one says you have to. Adjust and use the tool as it fits your own workstyle/flow best, but without options, that's sometimes difficult.

Not everyone has big monitors, multiple monitors or large drawing tablets. I have a small cintiq so i try what i can to maximize the drawing/viewing space while keeping the appropriate tools easily accessible. I believe a horitzonal layout would help me out a little more in that regard with how i use OT and it may also help others as well.

I'm sure it's probably a lot of work, so not expecting to see it any time soon since there are many other things that need work.

**Comment by automated-reckoning** [comment] 2016-10-20 20:21
But a timeline with layers and an Xsheet aren't the same thing, are they? As far as I can tell they don't work the same, certainly. I'm not sure that they could be easily translated back and forth.

**Comment by manongjohn** [comment] 2016-10-20 20:51
The way i see it, an Xsheet is just a timeline with layers oriented in a verticle layout and has more functionality/flexibility.  It may not be exactly the same.

I wonder if it would just be better to have a straight up timeline with layers like other animation software (i.e. animate cc) which automatically maps itself to an Xsheet where additional things can be done. Then you can view even more of the timeline on the screen and then rightclick or something to jump to where it would be on the Xsheet to do more stuff.

**Comment by turtletooth** [comment] 2017-02-09 03:41
Here is a portable version of the timeline feature currently in development.  There is a button in the corner of the xsheet to toggle between the two views.

**Comment by turtletooth** [comment] 2017-02-13 19:14
I'm going to close this here since we have an active PR.  We can keep discussing it there.

**Closed by turtletooth** 2017-02-13 19:14 UTC
Labels: Feature Request
