### ISSUE TITLE
Android or iOS app support ???

### ISSUE THREAD

**Issue by BabluKumar17** [opentoonz/opentoonz#781] opened 2016-09-02 06:28 UTC
Hi there, I want to build an interactive story-telling Android and iOS app. Can I use OpenToonz software to make animations and then use those animated pictures or videos in my Android app?

**Is there any tool or Android or iOS library support available which can be used to animate an Android or iOS apps?**

Thank you so much. Looking forward to your response.

**Comment by blurymind** [comment] 2016-09-07 07:33
this is a duplicate of
https://github.com/opentoonz/opentoonz/issues/755

if you are asking for a way to use opentoonz created animations in the creation of ios and android apps, then what you really want to have is this:
https://github.com/opentoonz/opentoonz/issues/173

The main reason is that the export of of raw keyframe data rather than individual image frames will greatly reduce the size of the game/application. Most mobile games nowadays use spine2d/dragonbones/spriter or other animation software that is paired with a runtime for the game engine that interprets the raw keyframe data (json file) to drive the body parts of the character.

My suggestion for opentoonz is to adopt the dragonbones json file structure in order to be able to use the runtime that is already available for unity and other major game engines. It is a mature format whose runtimes are not constrained by ridiculous licensing limitations like spine2d for example

**Comment by blurymind** [comment] 2016-09-07 09:31
In Fact dragonbones has an editor that is used for the exact thing that you are requesting!
http://dragonbones.com/en/comic.html

**Comment by turtletooth** [comment] 2016-09-30 18:38
Duplicate.  Closing.

**Closed by turtletooth** 2016-09-30 18:38 UTC
Labels: Feature Request
