### ISSUE TITLE
SVG:  Imports have unwanted fills and parts of path are offset

### ISSUE THREAD

**Issue by jsharer** [opentoonz/opentoonz#3171] opened 2020-03-23 12:11 UTC
### Issue Summary
SVG containing a single path with no fill, loaded into OpenToonz 1.4, has portions filled, and portions of the path offset (drastically).

Note that this SVG has many loops in the path. These are intentional.

### Screenshot or Video Reference
How it looks in Inkscape:
![GraphicInInkscape](https://user-images.githubusercontent.com/4711203/77314740-9f556480-6cdc-11ea-8062-5c3d5513b27c.PNG)

How it looks in OpenToonz:
![GraphicInOpenToonz1 4](https://user-images.githubusercontent.com/4711203/77314780-b2683480-6cdc-11ea-9137-0c576e724f3f.PNG)

### Steps to Reproduce
Using the OpenToonz Browser, select the file jugglers.svg that is in this zip file:
[Jugglers.zip](https://github.com/opentoonz/opentoonz/files/4369187/Jugglers.zip)
Load the file, choosing to Import into the current project.

### Expected Results
The fill and relative position of the points on the path are similar to the original.

### Actual Results
The imported vector drawing contains numerous filled regions, and many portions of the path are offset from their original locations.

### System Information
* **OpenToonz Version**: 1.4
* **Operating System**: Windows 10
* **CPU**: Intel Core-I5
* **Memory**: 8GB
* **Graphics Card**: NA
* **Graphics Tablet**: NA

**Comment by artisteacher** [comment] 2020-03-24 03:55
Likely related to #1795, #1009, and #119. Also might be related to #2321.

SVG actually get converted to PLI when they are loaded in OT. PLI clearly have some fill/region issues that have been a problem for a while.

**Comment by RodneyBaker** [comment] 2020-03-26 16:25
We need to scout for an SVG expert to assist in tackling the various issues with SVG import.
Importing appears to be the main source of problems in this area.

While somewhat out of the focus of this issue I'm very curious to know what results you find if doing something similar inside Opentoonz and then exporting to your program of choice.  In my tests thus far exporting/converting PLI to SVG has worked well with some known issues verified such as maintaining gradient fills, etc.

I note in testing your Jugglers SVG that one possible workaround for the color fill is to leave the fill as is and then make the #1 black color swatch 100% transparent.  Then create a new black color swatch... assuming such a black color fill is even needed.

The offsetting of parts of the path is very odd.
My initial thought is that this might relate to groups in the original application but I haven't investigated that far yet.

**Comment by RodneyBaker** [comment] 2020-03-26 23:55
Here's a rework of the supplied SVG file (altered in Opentoonz) just for reference sake.
It is renamed with .txt extension so needs to have the extension renamed .svg:
[reworkA.txt](https://github.com/opentoonz/opentoonz/files/4390669/reworkA.txt)

**Comment by RodneyBaker** [comment] 2022-09-25 06:58
Closing as a duplicate of #119 although there may be additional information captured in this report and others related to issues with SVG.

**Closed by RodneyBaker** 2022-09-25 06:58 UTC
Labels: bug, known issue
