### ISSUE TITLE
Crash on building skeleton via Plastic Tool (version 1.2.0.1, Linux)

### ISSUE THREAD

**Issue by tushantin** [opentoonz/opentoonz#1718] opened 2018-01-05 14:45 UTC
Using Ubuntu LTS, latest OT Morevna build. For some reason using the Plastic Tool crashes now. Well, creating a mesh isn't a problem, but building the skeleton then switching to anything else — whether a tool or switching to animate mode — definitely crashes.

**Comment by tushantin** [comment] 2018-01-05 14:54
Update: It seems I can build a skeleton and animate the mesh just fine if it's NOT a parent to any layer. If I parent it to the vector layer I need, especially after building the skeleton, it crashes.

**Comment by howlsrv** [comment] 2018-01-10 04:27
I have the same problem with crash when trying to animate skeleton on vector level.  No problem with raster or toonz raster levels.  I build the skeleton, and choose animate, then program locks up after any mouse click.  I'm using OTX modified version because of slowdown issue with regular OT 1.2. Same crash issue with Morevna 1.2 version.  This issue is not present with OT 1.1.3.   I'm using Windows 10. Nvidia GTX 680

**Comment by synk-a-dynka** [comment] 2019-05-13 08:55
Same issue here.
Doing anything after building skeleton, changing tool or trying to save, etc., crashes Open Toonz.
Terminal says "Illegal instruction (core dumped)"

OpenToonz 1.3.0 (Morevna, feb 2 2019)
Ubuntu 18.04.2 LTS 64-bit
Intel i7, 12core 24Gb RAM.

**Comment by synk-a-dynka** [comment] 2019-05-20 09:16
duplicate of #1473

**Comment by synk-a-dynka** [comment] 2019-05-20 12:12
The Snap build, https://snapcraft.io/opentoonz, does work, but have other problems.

GeForce GTX 1060 6GB
driver=nvidia
QMake version 3.1
Using Qt version 5.8.0 in /usr/local/bin/qt/qt580/5.8/gcc_64/lib

**Comment by RodneyBaker** [comment] 2020-12-23 21:12
@animationista @tushantin @howlsrv You may be interested in the current Linux ubuntu builds created by Github Actions:
https://github.com/opentoonz/opentoonz/actions/runs/440819992#artifacts

**Comment by RodneyBaker** [comment] 2020-12-23 21:41
Closing as a duplicate of #1473

**Closed by RodneyBaker** 2020-12-23 21:41 UTC
Labels: crash, linux
