### ISSUE TITLE
Crash OpenToonz

### ISSUE THREAD

**Issue by LeDegenere** [opentoonz/opentoonz#4997] opened 2023-07-06 17:30 UTC
### Description

I'm drawing my character's eyes in Vector on a different layer than the head, and the Crash Software

### Steps to Reproduce

1. I d'ont no
2. I d'ont no
I d'ont no

### Expected Behavior

I d'ont no

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-07-06 19:24:57
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1650/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 536.23

Crash File: C:\Users\33659\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230706-192457.log
Mini Dump File: C:\Users\33659\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230706-192457.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: walk
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\walk.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvmoi.inf_amd64_1bb7a846c06ba721\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffca99a8b9c] <ntdll.dll>
  2> RtlRaiseException [0x7ffca9981316] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffca99d0f8e] <ntdll.dll>
  4> TStroke::getMaxThickness [0x7ffc4ba8e4e3] <tnzcore.dll>
  5> TRegion::addEdge [0x7ffc4ba828c3] <tnzcore.dll>
  6> computeRegionFeature [0x7ffc4ba7b5a2] <tnzcore.dll>
  7> TVectorImage::moveStrokes [0x7ffc4baa8cb4] <tnzcore.dll>
  8> TVectorImage::notifyChangedStrokes [0x7ffc4baa8f82] <tnzcore.dll>
  9> ToolOptions::showEvent [0x7ffc57ae55e0] <tnztools.dll>
 10> ToolOptions::showEvent [0x7ffc57ae8048] <tnztools.dll>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60f7cb4bd] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60f7cc4eb] <OpenToonz.exe>
 13> QWidget::event [0x7ffc4fba80f7] <Qt5Widgets.dll>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60f7c942b] <OpenToonz.exe>
 15> QApplicationPrivate::notify_helper [0x7ffc4fb855c0] <Qt5Widgets.dll>
 16> QApplication::notify [0x7ffc4fb83e73] <Qt5Widgets.dll>
 17> QCoreApplication::notifyInternal2 [0x7ffc5028318a] <Qt5Core.dll>
 18> QDesktopWidget::workAreaResized [0x7ffc4fbd1284] <Qt5Widgets.dll>
 19> QDesktopWidget::workAreaResized [0x7ffc4fbceb59] <Qt5Widgets.dll>
 20> QApplicationPrivate::notify_helper [0x7ffc4fb855c0] <Qt5Widgets.dll>
 21> QApplication::notify [0x7ffc4fb84643] <Qt5Widgets.dll>
 22> QCoreApplication::notifyInternal2 [0x7ffc5028318a] <Qt5Core.dll>
 23> QGuiApplicationPrivate::processTabletEvent [0x7ffc4b1656b7] <Qt5Gui.dll>
 24> QWindowSystemInterface::sendWindowSystemEvents [0x7ffc4b14f030] <Qt5Gui.dll>
 25> QEventDispatcherWin32::processEvents [0x7ffc502cbcfa] <Qt5Core.dll>
 26> qt_plugin_query_metadata [0x7ffc4ab228d9] <qwindows.dll>
 27> QEventLoop::exec [0x7ffc5027f64c] <Qt5Core.dll>
 28> QCoreApplication::exec [0x7ffc50282164] <Qt5Core.dll>
 29> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff60f6e5219] <OpenToonz.exe>
 30> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60fb0eab7] <OpenToonz.exe>
 31> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60fb0e092] <OpenToonz.exe>
 32> BaseThreadInitThunk [0x7ffca9637614] <KERNEL32.DLL>
 33> RtlUserThreadStart [0x7ffca99826f1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

Build Mar 14 2023

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by LeDegenere** [comment] 2023-07-06 18:09
Steps to Reproduce
1 . Draw
2 . Draw

**Comment by RodneyBaker** [comment] 2023-07-06 18:21
Closing as a duplicate of #4998

**Closed by RodneyBaker** 2023-07-06 18:21 UTC
Labels: incomplete report
