### ISSUE TITLE
Strange Behavior Vector Styles

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#1954] opened 2018-05-08 13:41 UTC
https://www.youtube.com/watch?v=-h4xFDrYahU&feature=youtu.be

Hello. Please watch the video to see the issues I am experiencing:

vector styles will not respond in the style editor
style previews will not show up unless I click around
style editor window scales weird.
and more...

Is there a way to fix this?

This is the latest nightly build of opentoonz

Open Toonz 1.2

Windows 10

**Comment by shun-iwasawa** [comment] 2018-05-08 14:31
In the video there seems to be two unexpected behaviors.

- You seem to click the arabesque texture style but the bottom thumbnail does not update. ([0:38](https://youtu.be/-h4xFDrYahU?t=38))
- Style Editor UI shrinks. Interestingly, it seems to be back to normal when you select the Color tab. ([4:06](https://youtu.be/-h4xFDrYahU?t=246) - it's very strange.)

Unfortunately I couldn't reproduce none of them with my Win8 PC.
Does the problem occur on the docked (= not floating) style editor as well ?

By the way, actually I didn't know that painting vectors can be done by selecting the vectors with the Selection tool then select a style in the palette. Thank you for letting me know the tip!

**Comment by oladitan** [comment] 2018-05-08 15:54
The issues seem to be solved by changing the preferred graphics processor for Opentoonz to auto-select:integrated instead of high-performance NVIDIA processor in my NVIDA control panel. Is Opentoonz optimized for NVIDIA GPU?

**Comment by RodneyBaker** [comment] 2018-12-02 23:34
Closing based on @oladitan 's report the problem has been resolved.
Addition issues with Nvidia Graphics cards are occasionally reported so the solution of "changing the preferred graphics processor for Opentoonz to auto-select:integrated instead of high-performance NVIDIA processor in my NVIDA control panel" should be noted.

**Closed by RodneyBaker** 2018-12-02 23:34 UTC
