### ISSUE TITLE
OpenToonz Crashed and Drawings are gone

### ISSUE THREAD

**Issue by paperfood** [opentoonz/opentoonz#3442] opened 2020-08-14 05:00 UTC
I've seen #3361 and tried looking at the level settings, but it seems that my drawings weren't saved in the drawings folder.
![image](https://user-images.githubusercontent.com/69664122/90215296-14baf200-ddb0-11ea-9086-cfc6b112515e.png)
(This level is "I" and another layer that I have is "H", but neither can be found in the drawings folder)
![image](https://user-images.githubusercontent.com/69664122/90215344-3ae09200-ddb0-11ea-9e3f-d245990e75ed.png)

Is there another place that my frames might have been stored? Also, the audio is fine.
I should also mention that OpenToonz crashed twice while I was working today. It happened unexpectedly both times. The first time I forgot to save. The screenshots are the result of the second one. No pop-up window showed up when it crashed.

**Comment by artisteacher** [comment] 2020-08-14 13:16
Duplicate of #2581.

You can see if the backups of the levels still exist - using Finder (macOS) or File/Windows Explorer (Windows).

**Comment by RodneyBaker** [comment] 2020-10-18 06:24
Closing as a duplicate.

**Closed by RodneyBaker** 2020-10-18 06:24 UTC
Labels: question
