### ISSUE TITLE
Huge latency on brush

### ISSUE THREAD

**Issue by deanmoriart** [opentoonz/opentoonz#1173] opened 2017-04-26 12:34 UTC
Hello,

I was using Mybrush appimage since I know about opentoonz. Yesterday I want to give a shot from this master build to maybe fix vector antialising problem. (I started another thread for that) And I have this extreme latency on brush right now on this build. I tried all levels both vector and rasters. I am on xubuntu. I don't have this problem on Mybrush implemented version.

https://youtu.be/uZic7Q93NBk

**Comment by deanmoriart** [comment] 2017-05-10 15:26
Guys I can't be the only one having this issue right ? or am I ? I tried nightly build as well ended up with same result. What can cause something like that ? That red cursor does exactly what I m doing with the pen with 3-4 seconds delay.

**Comment by adamearle** [comment] 2017-05-12 06:28
No I get as well with my Cintiq and other computers I have tested it on that all run windows 7 

I'm running gtx 960 or something and 32 gigs of ram with loads of virtual space and disk space.

soo errrrrm something to look into.

Also the animation team has been using OpenToonz for the last two weeks and have loads of notes from everyone in the studio that is using it and we are wondering to post all of these notes and bugs which are an epic amount from the team.

OT seems to be a huge hot topic in the studio at the moment and the artist are going to great lengths to give good notes so we would love for them to be reviewed.

Thank guys 

Adam Earle  : )

**Comment by artisteacher** [comment] 2017-05-15 02:56
With vector levels, I have the most lag when smooth in enabled. The higher the smooth value, the more lag. This is on OS X.

**Comment by ideasman42** [comment] 2017-05-15 03:00
Mostly likely this is just poor OpenGL performance.

**Comment by artisteacher** [comment] 2017-05-15 03:17
@ideasman42, for those of us that experience the issue, are there any steps we can take to help find the cause?

**Comment by ideasman42** [comment] 2017-05-15 03:28
Ideally you could try swapping out your graphics cards with different brands/models - to confirm this is an issue between OT and the graphics drivers/hardware.

**Comment by adamearle** [comment] 2017-05-15 05:57
Hey mate something here with my cintq and im running 32 gigs of ram nvidia
gtx960 windows 7

**Comment by deanmoriart** [comment] 2017-05-15 22:51
@artisteacher Actually lag comes from smoothing is not lag. That's how smoothing works, delays the movement to help smooth the line. This one is different tho. It follows the cursor with delay no matter what tool or settings is on.

**Comment by artisteacher** [comment] 2017-05-19 13:43
One of my students has been working on a scene that is ridiculously laggy to the point where it's not possible to make any progress and I'm pretty sure it's an extreme version of this issue. I narrowed it down to a specific vector level. It's not a particularly complex level to look at, though it looks like the student used the brush alone when they probably should have used the fill bucket - or perhaps a raster level. 
![screen shot 2017-05-19 at 8 48 02 am](https://cloud.githubusercontent.com/assets/21159116/26248342/fb5258b0-3c6f-11e7-833a-6acfed867e23.png)
There is no problem with selecting, using the geometric tool, or etc. The lag occurs when the brush or eraser is used. It also lags when adjusting the strokes - like with the control point editor. The file size is unexpectedly large for a single frame - 2.9MB. 

It looks like there are a huge number of control/anchor points...
![screen shot 2017-05-19 at 9 02 11 am](https://cloud.githubusercontent.com/assets/21159116/26249045/bf9be50e-3c72-11e7-9358-a22f7c389913.png)

@ideasman42 - this level should make the issue reproducible. 
[CB.pli.zip](https://github.com/opentoonz/opentoonz/files/1014315/CB.pli.zip)

**Comment by turtletooth** [comment] 2017-05-19 14:14
I'm not sure if that is a bug or simply using the tool differently than it was designed.  I have also had students use the vector brush for sketch style or filling and destroyed their performance too.  With that said, if any sort of optimization can be done to handle hundreds/thousands of vector points better, I am all for it.

**Comment by adamearle** [comment] 2017-05-19 23:45
Something like "illustrators blob brush" is best for that kind of 
drawing where you might colour the space  as a fill. You will have to 
trial "illustrators Blob brush" to see what I mean. The eraser that 
accompanies the "blob brush" is really good as well. We use the "blob 
brush" in the studio everyday.

Just an idea but it might be best to bring the "raster to vector" tool 
set to the "view & Xsheet window. This might offer another way of 
working. That said I haven't used it, but could work really well if it 
was pimped out for todays users.

Adam Earle

**Comment by turtletooth** [comment] 2017-05-25 21:00
This seems to be a duplicate of #144

**Closed by turtletooth** 2017-05-25 21:00 UTC
Labels: Bug
