### ISSUE TITLE
wrong cursor showing

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#2583] opened 2019-04-01 18:02 UTC
### Issue Summary

cursor stuck on... this one when i change monitors, to hover the cursor to the othet opentoonz window
### Screenshot or Video Reference

https://i.imgur.com/Xf4kFkM.png
### Steps to Reproduce

have 2 windows, 1 on each monitor, pass the mouse between them
### Expected Results

show normal cursor or equivalent to the right cursor
### Actual Results

annoyingly this cursor prevails, and its not a precise cursor, that means, when you click on the spot you want, it does not actually click where you want
### System Information
* **OpenToonz Version**:
1.3 
* **Operating System**: 
windows 10 version 1083
* **CPU**: 
amd ryzen 1600
* **Memory**: 
crucial ballistix 8gb 2666MHz
* **Graphics Card**: 
radeon hd 6870
* **Graphics Tablet**: 
NaN

**Comment by artisteacher** [comment] 2019-04-01 22:35
This looks like it's related to #1951.

**Comment by RodneyBaker** [comment] 2020-01-15 21:12
Closing as a duplicate of #1951.

**Closed by RodneyBaker** 2020-01-15 21:12 UTC
Labels: UI
