### ISSUE TITLE
FFmpeg not found, please set the location in the Preferences and restart. MacOS ventura - opentoonz 1.7.1

### ISSUE THREAD

**Issue by conseld** [opentoonz/opentoonz#4882] opened 2023-05-10 03:43 UTC
### Description

Hello everyone after I updated opentonnz 1.7 and 1.7.1 I can't render to .gif and .mp4
I redid the process of the path /Applications/OpenToonz/FFmpeg in macOS maybe I need to do something else or I have a problem. Is anyone having this problem?

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

<img width="505" alt="Captura de Tela 2023-05-09 às 23 47 39" src="https://github.com/opentoonz/opentoonz/assets/7719738/80b94cfa-66fe-4d91-988b-74becfeae598">

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by PBL2023** [comment] 2023-05-13 22:19
conseld. I am also having this same problem. Once opentoonz was updated ffmpeg is not visible to the software. does anyone have a solution to export vid from opentoonz 1.7?

**Comment by gelatinbomb** [comment] 2023-05-24 01:56
Have the same problem here with Opentoonz **1.7.1** packaged as a **flatpak** on **Fedora Linux 37**. I tried messing around with the flatpak permisions and trying adding some shortcuts to the ffmpeg binary but nothing helped. 

The flatpak edition bundles a ffmpeg executable but is unable to use it.

**Comment by artisteacher** [comment] 2023-05-24 02:42
Might be the same problem that was recently fixed in T2D https://github.com/tahoma2d/tahoma2d/pull/1155

**Comment by YukihoYT** [comment] 2023-05-31 21:40
I also had problems with the export. I followed the exact instructions on what to do when the animation needs to be converted into a MP4 file or something like that. Wasn't recognised by the program.
I tried to update my program since there happend to be a newer version available so I gave it a try.
That's when everything stopped working altogether. Every attempt to open the program resulted in a crash.
So I got rid of it.
The good news: As I reinstalled it on my computer I can now normally open the program again like I did before.
The bad news: I'm at the exact same problem I started out with.
If there is a solution already posted in this or one of the other threads I missed out on, sorry for the repeat and if not, thank you in advance.
PS: English is not my first language (in case it sounded weird)

**Comment by JackHack96** [comment] 2023-07-23 11:22
I'm having the same issue using the Flatpak version, no matter the setting I use

**Comment by snapai** [comment] 2023-08-14 02:36
Running into the same issue on Windows 11 Pro 64-bit 22H2, both 1.7.1 release, and the most recent nightly, b3a690b
The path setting was imported from 1.6 where it was working fine.

This effectively prevents "Fast render to MP4" from working in up to date versions, as well as other mp4 outputs.

![OpenToonz_sCzFNHdumF](https://github.com/opentoonz/opentoonz/assets/5098372/560fb307-130d-4d9c-8c25-89a26a022c2c)

@RodneyBaker since this issue is crossplatform (Mac/Windows/Linux-via-flatpak), should the tags be reconsidered?

**Comment by RodneyBaker** [comment] 2023-08-14 02:54
If you haven't updated FFMPEG recently I would try that first especially if both FFMPEG *and* Opentoonz haven't been updated in awhile.

Rationale:  v1.7 introduced some (major) changes to FFMPEG that likely require the latest release of FFMPEG.
(I'll try to locate the exact info on this but in the meantime if this update status applies please consider updating FFMPEG).
This was likely a breaking change from v1.6 that should have been emphasized during release.

It is not clear to me that OP is having issues with Fast Render so much as not connecting to FFMPEG which in turn would cause issue with Fast Render.  Connecting to proper FFMPEG should at least be confirmed first.

At any rate, at first glance this appears to potentially unrelated to the Mac fix that reportedly resolves the problem.

Aside:  The commit linked goes to a change that was entirely textual (copyright year updated) so perhaps that was a typo?

**Comment by snapai** [comment] 2023-08-14 03:15
@RodneyBaker this fixed the issue for me. Though the bundled version of ffmpeg that ships with the latest update to ImageMagick is still the old 2020 4.2.3 version.

Got the latest Gyan build of ffmpeg (post 6.0 8-10 d9d5695390 ) and it seems to have worked.
Might be a good idea to patch that dialog with different text, instead of just not found "A recent (>version) build of ffmpeg was not found" - to give a breadcrumb that there's a version requirement.

**Comment by gab3d** [comment] 2024-03-21 20:05
Hi there,
There's one user suffering from this on a Mac, OT v1.7.1
In the end what was the solution to this problem? So I can help him... (I am on Windows, so cannot check it myself)

Thanks!

**Comment by RodneyBaker** [comment] 2024-09-27 09:11
Going to guess this was resolved at some point although users do still run into simialr problems from time to time.

**Comment by RodneyBaker** [comment] 2024-11-24 21:18
Since the original issue reported was with Windows...
Request anyone having issues with FFMPEG on Linux open a new report as the original problem reported here is likely resolved.

FFMPEG has some specific requirements (and some fringe issues) that must be navigated so the ideal approach will be to join one of the Opentoonz venues such as discord where the problems can be sorted in real time.

**Closed by RodneyBaker** 2024-11-24 21:18 UTC
Labels: troubleshooting
