### ISSUE TITLE
Loss of highlight frame 

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2683] opened 2019-07-31 11:35 UTC
### Issue Summary

To optimize the workflow in OpenToonz, I use a program to record macros (a sequence of commands entered from the keyboard). 

Most of the macros I recorded are focused on working in Xsheet and they significantly speed up the routine work with frames and save time. However, sometimes there is a problem with the loss of focus frame, resulting in a macro does not work correctly. 

I noticed that this happens in two tools: the Selection Tool (when the tool is activated) and the Control Point Editor (when editing).
### Steps to Reproduce

Here is an example:

![ezgif-1-512f36c88b70](https://user-images.githubusercontent.com/25724133/62206880-6e19d400-b39b-11e9-8d6f-8609f462f8dc.gif)
Suppose we have written the following sequence of operations into a macro: "Next Frame", "Duplicate Drawing", "Autorenumber". These commands will be executed correctly as many times as you like, until we call one of the tools listed above (Selection Tool, Control Point Editor) using hot keys. When they are called, the focus frame is lost, and the macro performs only the first operation ("Next Frame").

Why do frames stop being highlighted when these tools are activated? Can this be somehow avoided to be able to use macros?

**Comment by RodneyBaker** [comment] 2019-08-01 04:21
What is the name of the macro recorder you are using

**Comment by beeheemooth** [comment] 2019-08-01 08:14
Tiny Task. 
I linked the generated .exe files to the buttons on my tablet.

**Comment by RodneyBaker** [comment] 2019-08-01 08:35
Ah.  Thanks.
Tiny Task is one of my favorite little programs.
It does have some issues however with tracking (or at least did) and I'll have to refresh my memory on exactly what those were.  From memory I'd say that the issue is that Tiny Task uses positioning data so that whatever is below the mouse/pen at the clicking time gets activated.
I'm not entirely sure about the keystroking capabilities of Tiny Task so I'm off to check... especially if it has been updated.

There are other macro recorders available and those should be more robust than Tiny Task.

**Comment by beeheemooth** [comment] 2019-08-01 09:14
Yes, I learned from you about this program. It is really very useful.

I tried other programs for recording macros, but they all have no connection with the OpenToonz interface. Loss of frame focus occurs in Xsheet.
 
A solution to the problem could be duplicating not the selected frame, but the current frame in the current column (but this is a feature request).

Probably, I could come up with some kind of "macros-trick" that positions the Xsheet so that I can highlight the desired frame, but it is so tricky and I'm so tired of solving such technical problems (although this is very interesting). I want to finally do my animation. ^_^

**Comment by RodneyBaker** [comment] 2019-08-02 13:57
Hmmmm...

I'm trying to figured out a way to troubleshoot this issue but it will be difficult because even if you were to share the macro... my screen would need to be set up exactly the same in order for it to execute properly.

Can you share the saved macro file?  (The executable likely won't be of much help)

Here's what I would suggest to 'fix' the macro:
In your steps make sure you add steps that click back into the main canvas and then selects the area of interest (for instance rectangling all contents in the frame or Select All after a mouse click into the canvas.  

The issue here is not with focus of Opentoonz as much as it it the macro recorder/player not having enough data to execute properly (in the right screen location).  As such the shortcut key is simply executing where the last keystroke placed the focus.  The macro has shifted the focus when the shortcut key activated the other area.  The fix therefore is to force the focus to return to the desired location.  In most cases this would be initiated via a mouse click but there may be some shortcut keys that allow for that also.

Recommend closing and continuing the discussion in the OT Forum Troubleshooting category.

**Comment by beeheemooth** [comment] 2019-08-02 14:39
@RodneyBaker Wait a moment.

 It seems to me that you did not quite understand the essence of the problem (judging by how you changed the name of the topic).

It's not about macros or macros programs at all (in this case, you can remove the word "macros"). Is the problem that the frame highlight is lost under the conditions that I described earlier (Selection Tool, Control Point Editor), and this happens exactly in OT, and is not connected with the use of any other auxiliary program.
You can reproduce the problem manually, without macros. To do this, go to full-screen mode and try to duplicate drawings (as I described above) only with the help of hotkeys. You will be able to do this until you activate the above tools. After that, you will not be able to create duplicate drawings, for this you will need to open the Xsheet window and manually highlight the frame with the cursor - this is the essence of the problem.

The frame highlight disappears when using the Selection Tool and Control Point Editor. One of the limitations of this is the inability to create macros (including).

**Comment by RodneyBaker** [comment] 2019-08-02 22:19
I'm tracking you, just trying to hone in on the essence of the problem and to discuss it fully so that the problem can be reproduced... or restated...  and fixed.
You've stated:

Steps to reproduce:
1.  Go to Full Screen Mode **
2.  Duplicate drawings using hot keys

3.  While duplicating drawings note that activating Selection and/or Control Point Editor tools will cause loss of ability to duplicate drawings.

(Issue) Focus is lost (or not returned) upon using Selection and/or Control Point Editor

** Regarding the Full Screen mode, there are/were some known issues with Full Screen which we should review and rule out.

As for the reason I emphasize the use of TinyTask, it is my understanding that other than the use of shortcut keys TinyTask is fully dependent upon screen space.  It is the keystrokes that require the focus of any given window to be maintained because when the focus shifts to a different window the shortcut key is executed in that context instead.

There are several issues open that relate to Opentoonz losing focus while and it will be good to identify those and deal with them as best we can.  The underlying issue seems to be that when some Tools are activated the current state is not recorded so that state cannot be returned to easily thereafter.  For instance, if the user is doing pretty much anything and then switches to the Selector Tool how does it know to shift the focus back again and at what point in time does it accomplish that change.  Similarly with Control Point Editor tool.  If the user is drawing and invokes the CPE tool Opentoonz shifts into that editing mode.  How the tool would know to return to the previous mode and when to effect the change must be considered.  With a macro recorder, the steps are fairly clear; the user must add each step to the record so that those steps can be replayed.

Aside:  For title editing I occasionally adjust titles to help others identify and manage issues and to assist with categorization.  The originator of the report is always free to change the titles again to refine, restate and further hone in on the problem.

**Comment by RodneyBaker** [comment] 2019-08-06 22:04
Some additional information for general discussion...
I played with TinyTask and Opentoonz for quite awhile yesterday and as much as I like TinyTask it isn't quite up to the task although I did have a good time using it with Opentoonz in general.  It would be nice to find another option for recording and playing back macros similar to TinyTask but more robust.  The ultimate 'fix' of course would be an internal macro recording feature but obviously that would be a major piece of work.

Regarding the loss of focus in Opentoonz it will be good to review previous issues both open and closed related to that.  It's nice to have a fluid interface... OT's highly customizable UI is one of it's strengths... but it is important to be able to fully lock it down and keep the focus as constant as possible.

Largely unrelated:  
Something that may also be of interest to you @beeheemooth with regard to automation will be PR #2659 by @blackwarthog which grants ability to run Opentoonz scripts from the command line.

**Comment by shun-iwasawa** [comment] 2020-01-09 08:37
Here is a reason of the issue:

- Currently the `Duplicate Drawing` command is applied to the selected cell, thus it is enabled only when the cell selection is active.
- Once you switch to the selection tool or the control point editor tool, another type of selection becomes active. (It is why these tools can select. copy, and paste something unlike other tools.)
- The software can have only one active selection at once. So the cell selection is released when another selection becomes active. The command becomes disabled accordingly.

One possibility for enhancing this function in the future would be to make the command available even if the cell selection is not active. Making it to create the drawing into a cell at the current column / current frame in such case.

**Comment by beeheemooth** [comment] 2020-01-09 10:36
@shun-iwasawa thank you for the explanation.

**Closed** 2020-01-09 13:41 UTC
Labels: Feature / Request, UI
