### ISSUE TITLE
Toonz Raster Level glitch

### ISSUE THREAD

**Issue by Orphanlast** [opentoonz/opentoonz#1452] opened 2017-09-02 06:50 UTC
If you freehand erase a fill on a toonz raster level and turn selective mode on the fill brush and fill with freehand, it'll allow fills to rest next to fills. Sometimes it'll glitch out and reshape the erased areas or recolor everything and no amount of pressing ctrl+z will revert it back, so your stuck remakind your shadows and highlights over and over again.

I know this is just ONE technique for shadows and highlights. But the eraser has a frame range option. So it COULD be a time saver... if you could just press ctrl+z and revert it back if a fill doesn't work out as it should.

**Comment by beeheemooth** [comment] 2017-09-02 16:58
I will supplement the theme created by Orphanlast by comparing the work of the Fill Tool in CSP and Toonz Raster Levels.

![ezgif-2-0982be4e9b](https://user-images.githubusercontent.com/25724133/29997251-44d9d83c-9017-11e7-820e-592018aea349.gif)

I noticed that the Fill Tool in Freehand mode works the same in closed loop shapes, where there are voids. The Fill Tool fills the entire shape with the color on which the click was made (from which the tool started moving). However, it ignores other colors, even if the Selective mode is enabled. Canceling an action returns only a rectangular slice where there are all the colors that the tool has grasped. At first I thought it was a glitch, but later it seemed to me that there was some unknown meaning hidden here (OpenToonz is full of mysteries).
The question is: is this a glitch? If this is not a glitch, but some unknown feature, then I would like to see an illustrative example using this feature.

![ezgif-2-e700b5ad49](https://user-images.githubusercontent.com/25724133/29997334-07db2ed4-9019-11e7-855e-95d73b16502c.gif)

**Comment by Orphanlast** [comment] 2017-09-02 17:10
@Beeheemooth, thank you for this detailed expansion of this glitch. I REALLY appreciate it. And you're the one who's experienced it more than I have because it's YOUR workflow. 

If anyone needs any other examples I made a tutorial on this type of workflow and I sugges possible ways this glitch is triggered and what to avoid... but... we're human.

https://youtu.be/kit18lu7fxM

**Comment by konero** [comment] 2017-09-02 19:57
I can't make heads or tails of this issue, I'm not sure why you're erasing, doesn't seem like a very effective method. I'm just going to assume Toonz Raster wants some line logic to create color boundaries between shadow, base and light shapes. Since you don't have any, its getting confused.

That's why I suggest you use and research the color trace line method used in Japanese productions. IMO you should have your shadow shapes drawn with line.

![clrtrc](https://user-images.githubusercontent.com/19820721/29997711-6acfe96e-9012-11e7-8e89-05d01705dafe.gif)

Sorry if I'm not understanding the issue.

**Comment by artisteacher** [comment] 2017-09-02 20:20
@konero I may be wrong but it looks like the eraser tool is being used instead of the brush or geometric tool because it can be used for a range of frames instead of just one frame at a time. 

So for the desired workflow, frame range could be added to the brush and geometric tools for Toonz Raster levels and/or the undo history could be improved.

**Comment by beeheemooth** [comment] 2017-09-02 21:28
@artisteacher You're right. Using the Eraser Tool in this way, you can quickly and easily draw and edit shadows, highlights and colors, without lines. 
The most interesting thing in this workflow is that the more colors you have, the easier it is to work with them.
[https://www.youtube.com/watch?v=ZQXLVeRiVlY](url)

**Comment by openanim** [comment] 2017-09-02 22:13
@beeheemooth 
I could not shade this way, in any case the result is there, really good work. One question, since you seem to have used a tweening process for your character why not tweener also the color separation lines as in the kanero's exemple and use the frame range with fill tool or tweener with your drawings keys already colored and create, then the inbetweening ? it's slower than with the gum? I do not really realize

**Comment by beeheemooth** [comment] 2017-09-02 22:50
@openanim I did so. But the thing is that Autopaint lines created in the vector level and transferred to Toonz Raster are always _IN FRONT_ of the contour lines and no matter how hard I tried, I could not find a solution to this problem. Autopaint lines always have to be drawn manually in the Toonz Raster brush with the Selective mode turned on (so that the lines are under the contour).

Can you advise how to transfer Autopaint lines to Toonz Raster?

**Comment by konero** [comment] 2017-09-03 00:50
@beeheemooth Sorry I don't work with vectors.

But can't you draw black inks on one level, color trace lines on a separate level? That could allow you to sort out the stacking, like typical layers.

**Comment by openanim** [comment] 2017-09-03 01:51
@beeheemooth 

Sorry, I don't quite understand . I don't do my process on toonz raster levels so I unfortunately do not understand your problem. Can you post an example in the forum to avoid polluting the discussion for exemple  here in your topic : https://groups.google.com/forum/#!category-topic/opentoonz_en/feature-requests/TF7j1U_LcuA .

I will continue the discussion directly there

**Comment by Orphanlast** [comment] 2017-09-03 01:53
Plenty of examples by Beeheemooth and I have been supplied.

**Comment by beeheemooth** [comment] 2017-09-03 08:00
@openanim Well, I will continue this on the forum. There are many more questions about this.

But in this thread Orphanlast and I want to know the answer to the question: _is this behavior Fill Tool a feature of OpenToonz or is it still a bug?_

**Comment by shun-iwasawa** [comment] 2017-09-04 03:37
@beeheemooth 
Unfortunately, as @konero pointed, for now OpenToonz assumes all the fill regions are separated by lines or image borders in Toonz Raster Levels. Filling on the areas with no line borders may cause unexpected behavior, but it is not a bug.
I saw your great work posted in the forum done by "clipping" black region with eraser tool like wood-block print -  It's very unique and I was amazed at & loved it. Hope you could find some workaround to achieve your style.

**Comment by Orphanlast** [comment] 2017-09-04 04:07
To me, it doesn't matter if it's a bug or glitch. In the end, this workflow exists. It does work. So whatever you'd call it, it's semantics for something that stands as a stumbling block. Maybe toonz rasters need an auto-stroke option to the eraser tool that you can tick like the selective mode ticker. 

where the eraser tool has an automated stroke around the border of the erased zone with the color of the selected style.

**Comment by turtletooth** [comment] 2017-09-04 04:26
@Orphanlast I understand your frustration, but there are more gentle approaches to voicing you opinion.

**Comment by Orphanlast** [comment] 2017-09-04 04:35
Just seems like Beeheemooth came up with something cool is all.

**Comment by beeheemooth** [comment] 2017-09-04 11:25
@shun-iwasawa Thanks for the answer!

Well, let's take into account this feature of OpenToonz.
I will continue to develop this method, although I do not think I have discovered something new. It was probably invented by the one who decided to connect the Eraser Tool and Frame Range.

@Orphanlast If you have no more questions, I think you can close the topic.

**Closed** 2017-09-06 04:59 UTC
