### ISSUE TITLE
Report bug：Opentoonz1.3 import png image display exception.

### ISSUE THREAD

**Issue by vpaintanimation** [opentoonz/opentoonz#2533] opened 2019-02-24 15:51 UTC
I using windows7-64 bit system.  Open opentoonz1.3.  Drag from the desktop  png image to opentoonz,  The image is not displayed, I opened the software preview and didn't see the image.  I originally wanted to make a picture warp animation using a plastic tool.  Plastic tool preview also does not display images.  I tried the historical version.  It was found that only versions prior to 1.0.3 did not have this problem.

**Comment by vpaintanimation** [comment] 2019-02-24 16:45
![1](https://user-images.githubusercontent.com/25269197/53302191-3a9db100-3821-11e9-9a56-8adf4e9ba8cb.gif)

**Comment by manongjohn** [comment] 2019-02-24 17:14
It appears your file is named '1' and OT is likely treating it like a sequenced file. Without a real name before it, it can't properly load the file.

Rename the file to something else to get around this issue for now.

**Comment by vpaintanimation** [comment] 2019-02-24 17:45
Other names I used before, The result is the same, This png image named 1 is my quick edit to reproduce the bug.

**Comment by beeheemooth** [comment] 2019-02-24 18:14
@vpaintanimation Try first to put these images into the "Extras" folder of the current project, and load them into the scene from there. I had a similar problem and this advice helped me.

 Btw, where did you find VPaint 1.7 Alpha 2 ?... ^_^

**Comment by vpaintanimation** [comment] 2019-02-24 19:11
@beeheemooth I requested vpaint developer Mr. Boris. Let him develop the layer function in vpaint：https://www.dropbox.com/s/s4x35cx2e5lh14p/vpaint-1.7-alpha-2-64bit.msi?dl=0
  I think opentoonz is very suitable for adding vpaint production concept. 2D vertices, lines, faces Time-varying topology animate.

**Comment by manongjohn** [comment] 2019-02-24 19:31
Fyi, I confirmed in 1.3 that if the file name is named as 1.png, it won't load properly. If i change it to X1.png, it loads it as X1 (not a sequence). i believe loading files with just numbers is a known issue.

If renaming it still doesn't work, please attach the png file so i can see if it's an issue with something in the png file preventing it from loading properly.

**Comment by vpaintanimation** [comment] 2019-02-24 19:33
I am not a developer, but I feel, Letting opentoonz support 2D topological animations is too demanding for developers. Many 2D animation software are now improving production efficiency. But there are very few software that can solve inbetween frame work. The opentoonz plastic tools are very powerful, but I still hope that it will become even more powerful. 🙂

**Comment by vpaintanimation** [comment] 2019-02-24 19:38
@manongjohn Thank you, the problem has been solved, yes, you are right! The name of the picture cannot contain numbers. E.g：free 1.png    line2.png   111.png

**Comment by gab3d** [comment] 2019-02-25 00:18
@vpaintanimation 
I've tried to clarify in the OT Manual the valid naming rules for images, you can read them here:
https://opentoonz.readthedocs.io/en/latest/working_in_xsheet.html#loading-levels

**Comment by artisteacher** [comment] 2019-02-26 17:22
On a related note, screenshots on a Mac have the same issue unless they are renamed. I think the default screenshot name format has issues due to the placement/number of periods (ie. Screen Shot 2019-02-26 at 8.49.23 AM.png)

**Comment by gab3d** [comment] 2019-02-26 19:32
@artisteacher 
I can reproduce it on Windows too.
I've tried several combinations that didn't work:
- Screen_Shot_2019-02-26_at_8.49.23_AM.png
- ScreenShot2019-02-26at8.49.23AM.png
- Screen_Shot_20190226_at_8.49.23_AM.png
- ScreenShot20190226at8.49.23AM.png
- ScreenShot20190226at849.23AM.png
- Screen.23AM.png

...so I guess the problem is the **.23AM.** part which causes the trouble (basically what appears to be a *frame number* followed by two letters) 

**Screen_23AM.png** works, though.

**Comment by RodneyBaker** [comment] 2019-10-26 04:33
Closing as @vpaintanimation reported the issue resolved.

**Closed by RodneyBaker** 2019-10-26 04:33 UTC
