### ISSUE TITLE
Cursor and Brush offset

### ISSUE THREAD

**Issue by Shemmet** [opentoonz/opentoonz#1295] opened 2017-06-22 15:36 UTC
Whenever I go to draw something, there's a space between where my cursor is, and where the brush is. The space changes in size too, based on where I move the cursor. I don't know how to fix this, and it's really getting in the way of me doing my work. 
![error](https://user-images.githubusercontent.com/29632864/27442728-06c4a7d6-573f-11e7-8837-5b6ea2832b1b.PNG)

**Comment by artisteacher** [comment] 2017-06-23 02:36
What level type are you using? Smoothing usually causes that gap for me in vector and toonz raster levels. Setting the smooth value to 0 might help but it will probably also impact the line quality.

**Comment by Shemmet** [comment] 2017-06-23 14:49
My smooth value is already at 0, and the issue persists.

**Comment by artisteacher** [comment] 2017-06-24 15:38
This could be related to #1212. What is your operating system and version of OpenToonz? Is your monitor high-dpi?

**Comment by turtletooth** [comment] 2017-06-25 02:46
Closing as a duplicate.  @Shemmet If you could give more information about your os etc in #1212, that would be helpful.

**Comment by UAAartist** [comment] 2017-07-07 17:09
Having the same problem, but it's only associated with my Wacom Cintiq.  I've seen this happen before with ToonBoom Animate.  The solution there was to turn the tablet to mouse mode... which is a feature that was removed from Wacom Cintiq.  I currently don't know how to fix this.  Could this be due to an OpenToonz update?  Because I didn't have this problem last year.

**Comment by UAAartist** [comment] 2017-07-07 17:42
JUST  SOLVED  THE ISSUE.
The problem was that the Windows 10 Display Scaling needs to be set to "recommended," which for me was 150%.  Now the problem is completely gone!

**Comment by turtletooth** [comment] 2017-07-07 19:36
@Shemmet Could you try @UAAartist solution and let us know if it worked?

**Comment by Shemmet** [comment] 2017-07-07 22:20
I would love to try if I knew how to change the Windows 10 Display Scaling.

**Comment by UAAartist** [comment] 2017-07-07 22:53
Right-click the desktop, then go to Display Settings, scroll down to "Scale and Layout," change the size to recommended (for me that was 150%).

**Comment by Shemmet** [comment] 2017-07-07 23:48
Nope, it didn't work, that's what my settings were already at.

**Comment by Rojuinex** [comment] 2017-07-23 21:02
I notice that this happens to me when I have my ultrawides plugged in and OpenToonz on the ultrawide.

**Comment by Shemmet** [comment] 2017-07-26 05:05
My issue was solved!

**Comment by openanim** [comment] 2017-07-28 01:22
hi @Shemmet , Can you explain how you solved this issue ?

**Closed** 2017-08-26 00:44 UTC
Labels: Bug
