### ISSUE TITLE
Undo:  Ctrl-Z removes second most recent stroke

### ISSUE THREAD

**Issue by MisterABK** [opentoonz/opentoonz#1735] opened 2018-01-15 11:29 UTC
I'm drawing on a toonz raster layer. If I hit Ctrl-Z very shortly after drawing a stroke (or while drawing) the previously drawn line will be erased. Pressing Ctrl-Z again removes the line before that one, leaving the most recent stroke untouched

(Opentoonz 1.2, Win 10)

**Comment by artisteacher** [comment] 2018-12-03 03:56
I’ve run into this on MacOS when undoing while I haven’t completed the current stroke. Usually because an unintended stroke was triggered somehow after moving the cursor out of the viewer & back. Trying to undo the random stroke without clicking to complete it, results in the behavior described by @MisterABK.

**Comment by RodneyBaker** [comment] 2018-12-03 04:04
This appears to relate to several other reports including:  #1700 undo in raster level happens in different order.  Not sure it's a duplicate at this point in time but very likely.

**Comment by artisteacher** [comment] 2018-12-03 04:07
They definitely could be related, though I’ve run into this in vector levels.

**Comment by LWheaton1990** [comment] 2018-12-18 19:39
I'm experiencing this as well, but mine crashes when this happens. I am drawing, everything's fine, but then I ctrl+z and the wrong stroke is undone, the GUP usage peaks out, and OT closes. :(

**Comment by RodneyBaker** [comment] 2020-01-03 22:49
I cannot seem to reproduce this issue any more.
I'm currently testing/focused on the original report with toonz raster levels.

@MisterABK Can you confirm this is still an issue for you with toonz raster levels?

@artisteacher with vector levels this might tangentially relate to another PR that might be merged soon (#2914).  If not and we have reproduceable steps it might be good to break this out into a separate report.

@LWheaton1990 Same for standard raster levels.  Yours being particularly of interest because you've stated the problem produces a crash.  If still an issue it would be good to open up a new report referencing this issue.

**Comment by RodneyBaker** [comment] 2022-02-19 10:51
Closing as likely resolved and/or abandoned.

**Closed by RodneyBaker** 2022-02-19 10:51 UTC
Labels: bug
