### ISSUE TITLE
Opentoonz crashes when typing space in text tool

### ISSUE THREAD

**Issue by cardcraft** [opentoonz/opentoonz#3604] opened 2020-11-26 21:26 UTC
**Describe the bug**
When using the text tool and type space in the text EX. "Hello World" the program crashes instantly 

**To Reproduce**
List steps to reproduce the behavior.
Create a new project
Use the text tool
Type something with a space

**Expected behavior**
i expected text with a space in it that can be animated with all the normal tools

**Screenshots**

**Device Information:**
 - OS: Fedora 32
 - OpenToonz Version: 1.4.0 Flatpak install
 - GPU: NVIDIA RTX 750 TI
 - GPU Driver Version: latest

**Comment by RodneyBaker** [comment] 2020-12-14 02:03
I cannot reproduce this on Windows.
Perhaps it relates only to Linux?

**Comment by artisteacher** [comment] 2020-12-14 03:11
Not an issue on macOS either.

**Comment by le-dragon-dev** [comment] 2021-02-20 11:23
Hello! I tested on Linux (Yep, it's the Type Tool) and I have an exception: TException "bad QImage format" (tfont_qt.cpp l.173)

**Comment by orrin-ahola** [comment] 2021-03-11 17:38
I don't know if this redundant but I am experiencing this behavior as well.

5.7.4-arch1-1
opentoonz 1.4.0-2
NVIDIA GeForce GTX 1050 Ti

**Comment by le-dragon-dev** [comment] 2021-03-11 17:59
> I don't know if this redundant but I am experiencing this behavior as well.
> 
> 5.7.4-arch1-1
> opentoonz 1.4.0-2
> NVIDIA GeForce GTX 1050 Ti
> 
> (Also happens on my Manjaro laptop)

Hello!

A fix has been made for this, can you try the following appimage?
https://github.com/opentoonz/opentoonz/suites/2190932894/artifacts/45181417

It will be release with the next version of OpenToonz ;)

**Comment by orrin-ahola** [comment] 2021-03-11 18:40
> > I don't know if this redundant but I am experiencing this behavior as well.
> > 5.7.4-arch1-1
> > opentoonz 1.4.0-2
> > NVIDIA GeForce GTX 1050 Ti
> > (Also happens on my Manjaro laptop)
> 
> Hello!
> 
> A fix has been made for this, can you try the following appimage?
> https://github.com/opentoonz/opentoonz/suites/2190932894/artifacts/45181417
> 
> It will be release with the next version of OpenToonz ;)

Yup, that worked!  I was able to push the space bar without ill effect.

**Comment by RodneyBaker** [comment] 2021-03-11 18:54
Closing this as fixed but tagging as 'known issue' in order to assist with those that might not be able to find the information.

**Closed by RodneyBaker** 2021-03-11 18:54 UTC
Labels: known issue, linux
