### ISSUE TITLE
Linux version repo

### ISSUE THREAD

**Issue by fthamura** [opentoonz/opentoonz#72] opened 2016-03-27 15:21 UTC
where will be the tags for linux version,

or will opentoonz under 1 repo, but follow the operating system to compile the code

**Comment by blurymind** [comment] 2016-03-27 15:35
read before posting :)
https://github.com/opentoonz/opentoonz/issues/34
https://github.com/opentoonz/opentoonz/issues/49

This is being worked on at the moment

**Comment by odysseywestra** [comment] 2016-03-28 17:15
Closing since this is a duplicate of #34 and #49 like @blurymind mentioned.

**Closed by odysseywestra** 2016-03-28 17:15 UTC
Labels: duplicate
