### ISSUE TITLE
Constant crashing in the middle of work

### ISSUE THREAD

**Issue by Therippersart** [opentoonz/opentoonz#2408] opened 2018-12-09 18:19 UTC
Opentoonz version 1.2.1
So I decided to start over with my project. Its fine I guess, but the program crashed CONSTANTLY. Constantly to the point where i've set it to autosave every minute. I'm using Raster levels and drawing with a stylized pencil tool, the project has been created in sandbox, but i've tried importing the scene into another foler.

**Comment by artisteacher** [comment] 2018-12-09 18:30
It would be helpful to have more information. What is your operating system? Are there any specific steps that always cause a crash? You might want to give the [latest nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly) a try - there have been a lot of fixes & I find it a lot more stable.

**Comment by manongjohn** [comment] 2018-12-09 18:41
With the corrupted scene file you had in the other issue, I'm wondering if one of the levels you are reusing (i'm assuming) is also partially corrupted and causing you to crash constantly somehow.

Is it like this on a new project with new scenes and levels?  If it seems specific to your current project, it might help us to find out what is going on if you could provide the entire project.  If you don't wish to include it here, you can arrange to send directly to a developer for review.

**Comment by RodneyBaker** [comment] 2018-12-10 01:40
> Constantly to the point where i've set it to autosave every minute.

It's important to address the primary issues rather than medicate with things that cover up the core problems.  Setting autosave to every minute is pretty crazy... and in my estimation is going to create even move problems because the process will constantly interrupt other processes.

The primary issue appears related to working with standard raster levels so that would be a good place to focus attention.  For a test, try Toonz raster levels with the brush Smooth setting lowered so that it doesn't slow things down adversely.

There have been a few people that have reported consistent issues with standard raster (which is displayed via the blue color in xsheet/timeline.  To me this seems like a graphics card issue but it is likely a combination of different things.

I would also examine your antivirus to make sure it isn't being overly protective and interrupting writes to disk from an application it has deemed to be problematic.  Sometimes this can be as simple as a program that is unsigned.. which is currently the case with OpenToonz releases.

There are a number of things that load in memory that ideally should not be in memory while working with OpenToonz... excessive autosaving and antivirus protection are two areas I would examine if those issues where happening to me personally.  I would also look at other programs that are running at the same time as OpenToonz and limit use of those where possible.

If you are drawing on top of an image you have imported that will be less stable than one you create from scratch in opentoonz.  The recommendation there would be to create a new level and then immediately save your Scene and Level(s) so that they are solidly grounded on the harddrive.   If using an external drive or USB... consider not using those until the problem is better understood.   The additional time it takes for the operating system to query and write to USB or external drive might be causing problems.

Concerning graphics cards... I'd say especially Nvidia.. double/triple check to make sure you are running the current (or best) drivers for your card.  Best might not be the latest driver.

When a program is constantly crashing and yet there isn't a obvious reason for the problem that in and of itself is a clue that will help us discover what is causing the problem.  One thing we don't want to do is make the problem worse by increasing things like autosave to interrupt every minute... that's inviting more problems.  Autosave is great.  It has a purpose. But... Rule #1 in saving should be "Never rely on  autosave to solve your problems."  ;)

**Comment by artisteacher** [comment] 2018-12-10 02:00
Also, if you happen to be copying from a cell and pasting into the next empty cell, that causes a crash with Raster levels. A fix is waiting to be merged & should be in the next release. In the meantime, only paste onto existing frames.

**Comment by RodneyBaker** [comment] 2018-12-17 09:57
Closing as unable to reproduce specific conditions or steps leading to crash.
Several similar reports suggest areas of interest to examine in the future to include users working with standard raster levels.  If encountering this issue please consider using a recent release with a fresh stuff directly and new Project in order to eliminate the possibility of corrupt file from the past continuing to be problematic.

**Closed by RodneyBaker** 2018-12-17 09:57 UTC
Labels: Crash, Needs Info
