### ISSUE TITLE
Paint Brush Random Scribbling Glitch

### ISSUE THREAD

**Issue by jamesalexanderdickerson** [opentoonz/opentoonz#960] opened 2016-12-12 06:10 UTC
When drawing with the paintbrush on either a vecter layer or a raster layer, the cursor will jump and scribble to random places all over my drawing causing me to have to periodically undo to get rid of the random scribbling. This is with 1.1.2, on OSX El Capitan Version 10.11.4.

**Comment by artisteacher** [comment] 2016-12-12 13:45
This is most common for my students when they are using a wacom bamboo tablet with opentoonz and occurred with 1.1.1 and 1.1.2 on OS X 10.11.4 and 10.11.6. This does happen without a tablet, but much less frequently.

**Comment by jamesalexanderdickerson** [comment] 2016-12-12 19:34
I'm using a wacom cintiq 22hd. Thank you. Will I be unable to utilize the pressure sensitivity? Or can I just uncheck it and check it back to rid myself of the glitch?

**Comment by thebaconbaron** [comment] 2016-12-14 17:10
I'm using a Cintiq 13HD on macOS Sierra 10.12.1 and I have OpenToonz 1.1.2 installed.  This problem seems to be related to moving the pen completely away from the tablet after drawing with the brush.  If it remains hovering over the tablet (moving the cursor),  I don't get this issue.  When I pull the pen completely away from the tablet after drawing a line and then return to drawing, it is very easy to recreate this issue.  Disabling pressure sensitivity does not solve this for me.

**Comment by artisteacher** [comment] 2016-12-14 19:24
Oh well, it was an idea. I think auto-save may also contribute.

**Comment by jamesalexanderdickerson** [comment] 2016-12-14 20:59
Yes, it didn't fix the issue and thebaconbaron, you appear to be correct.

**Comment by mcjadski** [comment] 2017-02-13 01:32
This is a duplicate of #756.

**Comment by turtletooth** [comment] 2017-02-13 01:39
Closing as a duplicate.  If it is somehow different, we can reopen.

**Closed by turtletooth** 2017-02-13 01:39 UTC
Labels: Bug, Duplicate, OS: MacOS

**Comment by gsibrian** [comment] 2017-10-19 14:46
Hello, I downloaded the build, downloaded all the required program and its failing at the boost part... should I use something other then terminal to do this successfully?
