### ISSUE TITLE
Output Settings is gone

### ISSUE THREAD

**Issue by brunotribst** [opentoonz/opentoonz#1556] opened 2017-11-06 14:40 UTC
I can't open anymore my Output Settings window... I tried to install the software again, but when I click there nothing happens...

**Comment by gab3d** [comment] 2017-11-06 18:34
before reinstalling, try removing the "OpenToonz 1.1 stuff" directory, so
you get a fresh install

2017-11-06 11:40 GMT-03:00 brunotribst <notifications@github.com>:

**Comment by shun-iwasawa** [comment] 2017-11-07 02:35
@brunotribst 
Can you please let me know the value of `OutputSettingsDialogGeometry` in
`OpenToonz 1.1 stuff\profiles\layouts\settings.username\popups.ini` ?
`popups.ini` is storing the latest popup geometries in order to reproduce the same position & size of popups on next launch.
As far as I know, there is a safety mechanism to make sure to display the popup even when the saved geometry is invalid (= out of the screen, it will happen when you previously used multiple monitors), but I may miss something.
Also please try removing `popups.ini` and check if the popup opens then. Thanks!

**Comment by brunotribst** [comment] 2017-11-07 15:01
now is:

> [General]
> StartupPopupDialogGeometry=613 402 710 451
> OutputSettingsDialogGeometry=706 262 444 678

but since I deleted the stuff folder to reinstall, my Output Settings is back!! Thank you guys

**Comment by shun-iwasawa** [comment] 2017-11-09 10:00
Hmm, the values seems to be OK in `popups.ini` .
Anyway, I'll close this issue as we can't investigate it further for now.
Please reopen when the same problem occurs again.

**Closed by shun-iwasawa** 2017-11-09 10:00 UTC
