### ISSUE TITLE
Crash after used one of parameters from animate tool

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3609] opened 2020-11-28 02:53 UTC
**Describe the bug**
I obtain a crash in my environment after used one of parameter from animate tool as position, rotation etc. on a empty cell.

**To Reproduce**
List steps to reproduce the behavior.
1.go to an empty cell
2.change the parameter for another one.
3.crash

**Expected behavior**
No crash

**Device Information:**
 - OS: [10]
 - OpenToonz Version: [e.g. Nightly built nov 15 2020 10.17.38)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by RodneyBaker** [comment] 2020-12-24 06:34
This should be fixed by a recent PR.
I can't reproduce with current nightly build.

**Comment by openanim** [comment] 2020-12-25 23:01
I confirm that this seems to have been fixed with the last nb.. I can't reproduce it anymore, thank you.

**Closed** 2020-12-26 03:03 UTC
Labels: crash, needs info
