### ISSUE TITLE
Open toonz not opening at all 

### ISSUE THREAD

**Issue by Parziaval** [opentoonz/opentoonz#5253] opened 2024-01-04 18:11 UTC
### Ask a question related to OpenToonz

I am having trouble in opening Open tooz Software, when i click on the software it does not open at all, instead it shows error, i have attached the screenshot for more information, Please help me to solve this problem.
![Screenshot (134)](https://github.com/opentoonz/opentoonz/assets/134164734/5d36192e-32a3-4b78-9020-65535f11e185)
![Screenshot (135)](https://github.com/opentoonz/opentoonz/assets/134164734/70ee0b90-4818-4bf7-80b1-505a775c564f)
![Screenshot (136)](https://github.com/opentoonz/opentoonz/assets/134164734/491daab2-5c44-4955-80b5-e59d41988033)

**Comment by RodneyBaker** [comment] 2024-01-04 19:41
@Parziaval Sorry to hear you are having problems.
We really need solid information to go on here although I personally do appreciate your attempt to supply at least some.

You may want to read some of the recent reports as many of those have intentionally been left open so that users can more easily find solutions to those problems.  Perhaps better yet you might look at the closed reports as those tend to be verfied solutions.

The only guess I can make at this point would be that you might have run into the Logitech webcam driver issue that has been plaguing users for the past year or so.  The solution to that is to rename or remove that particular driver.

You can find more information on that particular solution here and in similar reports:  #5236

You didn't post the actual crash report so I can't confirm that to be your specific problem.

**Comment by Parziaval** [comment] 2024-01-05 06:46
Thank You For Your Answer But I can't find lvco64dll File. And For More Information I am Writing Problem Again
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-01-05 11:46:38
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 12


Crash File: C:\Users\Chavan\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240105-114638.log
Mini Dump File: C:\Users\Chavan\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240105-114638.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\sechost.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\WS2_32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_1d7bca28ac3cf032\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\lagarith.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff9659c8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff9659a12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff9659f0ebe] <ntdll.dll>
  4> DriverProc [0x25613a056d8] <lagarith.dll>
  5> DriverProc [0x25613a04430] <lagarith.dll>
  6> ICSendMessage [0x7ff90b7e2b9c] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ff9129e7498] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ff9129e4bb6] <image.dll>
  9> initImageIo [0x7ff912987ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7d47b0dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7d47b2d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d4bdeab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d4bde092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ff964647344] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ff9659a26b1] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment] 2024-01-08 05:47
Yes, the good news here (or bad news depending on POV) is that the problem is not with the Logitech webcam driver.

The best I think I can do at this point with the information we have is quote @konero who has suggested in the past:

> Might be due to your system then, you can open a cmd prompt (as administrator) and type this: sfc /scannow, it will scan your system for corrupt system files and try fix them, if it fixes anything restart your PC and run it again, keep repeating it until it can't find anything else
> If you use anything like registry cleaners/ccleaner etc. that tinker with the system, OpenToonz is really sensitive to the changes they make

**Comment by RodneyBaker** [comment] 2024-03-22 11:50
Closing as likely resolved and/or abandoned.
@Parziaval Please let us know if you are still experiencing problems.

**Closed by RodneyBaker** 2024-03-22 11:50 UTC
Labels: needs info, incomplete report
