### ISSUE TITLE
MacroFX Not Working

### ISSUE THREAD

**Issue by MitchWoodin** [opentoonz/opentoonz#4953] opened 2023-06-15 22:53 UTC
### Description

Hi,

I've been trying to create a macrofx node but I don't seem to be able to do it. I found #4159 but that doesn't seem to have a solution? The node I'm trying to create contains just four Matte Out nodes.

### Steps to Reproduce

1.  Create a New Scene
2.  Create multiple nodes in FX schematic (mine was four matte out nodes)
3. Right click and choose `Make Macro FX` 
4. Nothing happens

### Expected Behavior

I'm expecting the nodes to collapse into a single Macro FX node. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment] 2023-06-15 23:18
My initial test cannot reproduce your steps not working but I may be missing something.
Can you create a simple scene and export it (via File > Export Scene).. zip that up and share it here?

I'm attaching one of the test scenes I created just to see if something really obvious wasn't working:
[SimpleMacroTest.zip](https://github.com/opentoonz/opentoonz/files/11763904/SimpleMacroTest.zip)

**Comment by shun-iwasawa** [comment] 2023-06-16 01:17
Please make sure that the four Matte Out Fxs are connected to each other before turing them into macro Fx.
There must be only one root node among the selected nodes.

**Comment by RodneyBaker** [comment] 2024-08-12 14:25
Closing as likely resolved.

**Closed by RodneyBaker** 2024-08-12 14:25 UTC
Labels: troubleshooting
