### ISSUE TITLE
Crashes Upon Initializing Toonz environment.

### ISSUE THREAD

**Issue by HyperGamer28** [opentoonz/opentoonz#50] opened 2016-03-26 15:12 UTC
I could use some help. I tried to run, even use Admin Privileges and Windows 8 Compatibility, but it ends up crashing. I am using the HDMI cable for my TV cause my Laptop Monitor Broke. Here are my Computer Specs:

Processor: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
Video Card 1: NVIDIA GeForce GT 730M
Video Card 2: Intel(R) HD Graphics Family
Memory: 8.0 GB
Operating System: Microsoft Windows 8.1 (build 9600), 64-bit

**Comment by rioforce** [comment] 2016-03-27 22:14
This happens for me too, I have a Windows 10 laptop. My computer specs are:

Processor: AMD A6-4400M APU with Radeon HD Graphics 2.70 GHz
Ram: 4 GB
OS: Windows 10 Home, 64 bit
Monitor: 1366 x 768

I realize that my graphics card is not an Intel, it's an AMD, and my screen resolution is too small for the recommended requirements. I wonder, though, is it crashing because of this, or is it another reason? I'm going to test it on another computer later on and give my results.

**Comment by AmEv7Fam** [comment] 2016-03-28 00:36
Mentioned in #46: Do either of you happen to have a Logitech webcam?

**Comment by rioforce** [comment] 2016-03-28 00:40
I do, in fact, have two Logitech webcam, though neither is plugged in right now (and haven't been for over a month).

I did test the program on a desktop computer (I don't have the specs with me right now) that I know has never had a Logitech webcam attached, and it works, though, it has higher specs so that may be a completely different reason why it's working there and not here. Just thought I'd mention that.

**Comment by odysseywestra** [comment] 2016-03-28 19:36
Closing since this is a duplicate of #46.

**Closed by odysseywestra** 2016-03-28 19:36 UTC
