### ISSUE TITLE
brush strokes become red even if have selected the black colour

### ISSUE THREAD

**Issue by Rajkumar0swain** [opentoonz/opentoonz#5181] opened 2023-11-19 08:03 UTC
### Ask a question related to OpenToonz

brush strokes become red even if have selected the black colour. and also there is some glitch in undo after copying anything well I'm attaching the video of red stroke problem, right now I don't have the video of undo problem, but I will attach that soon
[2023-11-15 21-28-49.zip](https://github.com/opentoonz/opentoonz/files/13402638/2023-11-15.21-28-49.zip)

**Comment by RodneyBaker** [comment] 2023-11-19 08:57
Removing as a duplicate of #5180

**Closed by RodneyBaker** 2023-11-19 08:57 UTC
Labels: question, duplicate
