### ISSUE TITLE
Suggestions/Hints on how to start meddling with opentoonz code.

### ISSUE THREAD

**Issue by GabrielCambe** [opentoonz/opentoonz#3701] opened 2021-01-30 15:51 UTC
I have a bit of experience with c++ programming and i really want to start changing opentoonz and contributiong code, but i am experiencing a hard time trying to make sense of all the code, specially the "front-end" part of opentoonz (if we can call it that), i do not have experience with QT and get really insecure going through the code.

I would like to change the way opentoonz handles the numbers shortcuts to the colors in the Level Pallete.
![image](https://user-images.githubusercontent.com/30998470/106360609-23fb1100-62f8-11eb-9ea7-de085fca12a5.png)

Basically, when we are in the first pallete we get shortcuts to the colors, from 1 to 0, but as soon as we change through the pallete's window tabs, we do not have the shortcuts anymore.
![image](https://user-images.githubusercontent.com/30998470/106360670-8227f400-62f8-11eb-8c61-0e3f85ab390b.png)

I found that this is really damaging to productivity and i would like to make the shortcuts present in all windows and maybe add a shortcut to change through the tabs as well.

I looked at the code but i am really lost, can you give me a hint where to begin?

And also, sorry if i am asking too much... Is there  some guide or book that will help me with opentoonz programming?

(Sorry if this seems like a feature request, but, because i want to actually implement it, i thought that it should be posted as a question)

**Comment by RodneyBaker** [comment] 2021-01-31 00:18
It's a good question @GabrielCambe 
There isn't a lot of information on coding for Opentoonz although there is a lot of information out there scattered about.
The more specific information relates to building Opentoonz from source as well as creating plugins and such.

Having said this, I believe in time we'll see more of what you are looking for appear especially as programmers share their insights.

I would suggest that the current 'book' on programming in opentoonz can be found in the Pull Requessts (PR) where for each PR there is a link to the files that were changed.  This is a great place to review the changes developers have made to the code and get a good sense of the historical changes of the source code.   Additionally, I would suggest looking for PRs of those areas of interest to you... Issues and PRs that relate to the Palettes and Style Editor for instance as those will provide entry points to code specifically addressing code related to those areas of interest and related workflow.

Perhaps the first thing I would do as an aspiring programmer of Opentoonz is build the program from source.
I'll suggest doing that if you haven't already done so.
Getting familiar with github is also something of a prerequisite as that will be essential moving forward.

Others will have suggestions for how to approach the specific area of interest with Palettes and Shortcut Keys but the Opentoonz source code is broken up pretty well into the various processes.  As such exposing yourself to the code related to Palettes and Shortcuts seems appropriate. 

Something to always consider is how the current implementation is being used.
How will adjusting the shortcut key operations impact current workflow.
For example, from my experience the shortcut keys do in fact work via additional palette pages... they still refer to the original 10 colors on page 1 even when we are on other pages.  In this way we can easily move back to those colors when we need them.

Additional considerations arise as well in how we can improve upon this without adversely effecting those who currently rely heavily on that workflow.  This suggests that any major changes should also should have a means to opt in or out of the change... say for instance... through Preferences.  Then there is the ever present (and pesky!) matter of Undo... and anticipating when users don't use the change for its intended purpose but innovate beyond.  Will that result in a crash or unexpected behavior?  

All this to say, "Welcome aboard @GabrielCambe!".
Here's to many years of successful development in the future.

I'll give a look at the code and see if anything in particular stands out as a good starting place to explore for your current point of interest.

**Comment by RodneyBaker** [comment] 2021-01-31 00:35
Here is the broader view of palette related code:

https://github.com/opentoonz/opentoonz/search?q=tpalette

**Comment by RodneyBaker** [comment] 2021-01-31 00:46
Not all code will adhere to ideal C++ standards.
For instances there is this message in tpalette.h:

> Syntax
>     A palette is supposedly created <B>on the heap</B>, to the point that, <I>in
> current
>     implementation</I>, copy and assignment are \a forbidden. This behavior is
> somewhat
>     inconsitent since a palette \b is currently \a clonable and \a assignable
> with the
>     appropriate functions. Normalization to common C++ syntax should be enforced
> ASAP.

This suggests much of the current source code is still very much a work in progress.

**Comment by RodneyBaker** [comment] 2021-01-31 00:53
It looks to me as if this is a good place to start exploring the actual code related to palette shortcuts:

https://github.com/opentoonz/opentoonz/blob/45bac5a15c26f3cdd0ff4e624a3722d2cc063715/toonz/sources/include/tpalette.h#L397

**Comment by GabrielCambe** [comment] 2021-01-31 06:27
Thank you really much Rodney! I didnt thought about the pull request history but this is a perfect hands-on option to learn about the code!
Fortunatelly i have already built the code on Debian Stretch and after that on Ubuntu 18.04 so i am familiar with the process, though i do not understand yet how the dependencies are used within the program. But i think reading the pull requests and diving heads on will be a shocking improvement.

Thanks again!

**Comment by RodneyBaker** [comment] 2021-03-17 19:27
Will close this but we always are interested in discussing how best to dive into the Opentoonz code.
Thanks for asking the question @GabrielCambe and...

If you have time we'd love to hear more about what you discover.

**Closed by RodneyBaker** 2021-03-17 19:27 UTC
Labels: question
