### ISSUE TITLE
New Experimental Version

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1329] opened 2017-07-14 06:06 UTC
https://gum.co/TZmmM

This is an experimental version of OpenToonz containing many new features that aren't yet part of the main version. 

Developing these features takes a great deal of time and effort.  If you can afford it, please consider paying something for the download.

This is a list of the features included in this version:

Timeline

Notelevel

Soundtrack Export

Down Arrow for New Frame in Level Strip

Geometry Tool - Enter to Finish Polyline

New Preference Option to allow New Levels to Default to Camera Size

Fix Spritesheet Padding

Sound in Combo Viewer Fixed

Fix New Level Default Name for Vector Levels

Autosave Options Included in Startup Popup

Drawing Substitution works on Subxsheet Levels

Fix Popup Locations

Fix Maximized Grayed Out Windows

Lip Sync Popup (Papagayo Import)

Guided Drawing Feature

Preference Option - Imported Images Can Use Camera DPI

Vector Brush - Shift for Straight Line

Fill Tool- Vector Change Maximum Gap Size 

Vector Brush Frame Range Option

Vector Brush Snapping

Geometry Tool Vector Snapping

**Comment by Rayek** [comment] 2017-07-14 07:02
Many thanks for your hard work, Jeremy! I sponsored you a bit - not that much (money is tight in the summer), but enough for dinner :-)

Soundtrack export is essential for me, and this portable version is so useful when teaching.

**Comment by RodneyBaker** [comment] 2017-07-14 12:04
OTX... hey, I like the sound of that.

Contributed.
...with thanks and appreciation for all you have done and do.

**Comment by openanim** [comment] 2017-07-14 12:34
@turtletooth , it's a dream day !! 

Downloaded and contributed.

My thanks again to all those who have given theses features possible. And a big thank you especially to turtletooth.

**Comment by turtletooth** [comment] 2017-07-14 19:16
Thank you all for your words and contributions.  I really appreciate it.  I have already found a big bug and will release a new version shortly.

**Comment by Rayek** [comment] 2017-07-14 19:21
Any chance of integrating the Mypaint stuff as well?

**Comment by turtletooth** [comment] 2017-07-14 19:22
As soon as they make it possible to build it with Visual Studio, I will add it.

**Comment by turtletooth** [comment] 2017-07-14 19:26
> Soundtrack export is essential for me, and this portable version is so useful when teaching.
I'm not sure why soundtrack is still not reviewed.  I wish there were either more reviewers or a faster review process.

**Comment by turtletooth** [comment] 2017-07-14 20:18
New version posted.

**Comment by turtletooth** [comment] 2017-07-14 20:36
I should note - vector levels created in this version are not compatible with previous versions.

**Comment by turtletooth** [comment] 2017-07-15 17:05
For those who have played with this.  The brush options work fine on a hd monitor, but get cramped on less.  I'm not sure what to do with this.  I really like having all the options, but it needs to be usable.  Thoughts?

**Comment by openanim** [comment] 2017-07-15 19:05
Right about that I also like having all the options available ... and on my cintiq companion 2, the accuracy and smooth option are not visible correctly. Maybe consider extending the options bar. I do not really have any idea, sorry. I noticed, the cursor of my stylus is not well positioned where I want to draw in this version (its works perfectly in stable version). Look at the video attached.

https://1drv.ms/v/s!AspsYffPSwbdhuIMoPrOFyAimd-f9g

**Comment by turtletooth** [comment] 2017-07-15 19:23
So I'm moving the guided drawing feature to the right click menu where you activate onion skin.  That will allow it to be used for more than just brush and geometry tools.  I am also going to play with changing "Frame Range" to Range

**Comment by turtletooth** [comment] 2017-07-15 20:29
I'm still not sure what is causing the offset.

But I did some changes to give a little more room in the options bar.

**Comment by openanim** [comment] 2017-07-15 20:49
The offset does not exist in the stable version, so it is rather reassuring. Man theses new features leaves me speechless. The guided drawing, also works with vector files made with other software, like cacani does. Very pleasant.

**Comment by turtletooth** [comment] 2017-07-15 21:11
New version is posted 7/15/17

**Comment by openanim** [comment] 2017-07-15 21:44
How can i download it? The link above gives me version 7/14/17

**Comment by turtletooth** [comment] 2017-07-15 21:47
When did you last check?  I just checked and the link should be otx7-15-172.zip

**Comment by openanim** [comment] 2017-07-15 21:50
@turtletooth Nice that's works :D

**Comment by RodneyBaker** [comment] 2017-07-15 22:48
Nice.  With the addition of Snap as well as other tweaks that complement Fill, fill issue appear to be a thing of the past.

**Comment by openanim** [comment] 2017-07-16 13:05
The offset seems to be specific to my cintiq tablet. I dont know where the issue comes from with this version, but I don't have this issue on a classic computer connected with a wacom bamboo tablet for exemple. It seems to be a problem specific to my cintiq configuration for this version (the stable version doesn't have this issue.)

**Comment by blurymind** [comment] 2017-07-23 20:41
I had a play with it for a bit and just love all of the new features! Absolutely fantastic and they address the software's biggest weaknesses in such elegant ways.

Dont know if its any worth, you might already know about these, btu will report them anyway:
Found a gui bug in this version - the inbetween button stops appearing, but is still clickable.
The drawing thumbnails are not working - 'no icon'

![capture](https://user-images.githubusercontent.com/6495061/28502675-504031d2-6fef-11e7-85c0-a7f6ec60352c.PNG)
'
I will try to find out the steps to reproduce this problem.

**Comment by blurymind** [comment] 2017-07-23 20:44
Oh, I found another bug! The application doesnt close them you close its window or with file>quit!

That doesnt crash it either. It just closes the scene, but the application doesnt quit at all. Not matter 
how many times you try to quit it.

**Comment by artisteacher** [comment] 2017-07-24 00:52
There are so many great features coming. I can't wait to give them a try in OS X.

**Comment by turtletooth** [comment] 2017-07-24 01:47
@blurymind It may have to do with how the portable version initializes folders and preferences.  I haven't actually experienced them myself, but I haven't looked for them on a clean unzip of the software.  

@artisteacher I can't wait for them to get merged either.  I personally love using the snapping for drawing.

**Comment by bobbybutterfly** [comment] 2017-07-26 09:58
OT crashes, when loading papagayo file in the new popupwindow but no column is selected

**Comment by turtletooth** [comment] 2017-07-27 06:14
New build with MyPaint brushes in raster levels is here: https://gum.co/TZmmM

**Comment by Rayek** [comment] 2017-07-27 06:23
THANK YOU SO MUCH!!! It works brilliantly! And being portable is really the icing on the cake.

**Comment by Rayek** [comment] 2017-07-27 06:47
Btw, is it possible to draw with the mouse with the MyPaint brushes? Works with my Wacom, but no response when I tried the mouse.

**Comment by blurymind** [comment] 2017-07-27 08:17
@turtletooth 
https://gum.co/TZmmM
fails to load for me. Windows 7 x64
![capture](https://user-images.githubusercontent.com/6495061/28660824-75a60da6-72ac-11e7-9554-dfd9af114483.PNG)

**Comment by RodneyBaker** [comment] 2017-07-28 14:18
![no xsheet icons](https://user-images.githubusercontent.com/2576432/28721361-ad217ce2-7375-11e7-8510-0cc05f0fe183.png)
I haven't been seeing the new SVG icons in the experimental version.
I'm exploring to see if I can manually download and put it in the correct location.

They don't appear for me in the timeline mode either.

**Comment by manongjohn** [comment] 2017-07-30 02:00
@RodneyBaker Odd that no icons are loading for you? Even the note one under the Xsheet button is missing. That was not touched and is a PNG, I believe.

I'll be incorporating the new icons soon and will commit my changes which can then be merged into next experimental.

**Comment by turtletooth** [comment] 2017-07-30 02:06
@RodneyBaker What platform are you on?  7 or 10?

**Comment by RodneyBaker** [comment] 2017-07-30 12:05
I'm running Windows 10, creators update.
I have icons in the official and morevna releases... just not in the experimental.


I've done a lot of different things to test with the exception (and it's an important exception) of shutting down my computer and starting again.  I'll try that when I next get a chance to do so.

**Comment by Rayek** [comment] 2017-08-01 05:44
I found this version to be extremely buggy when working with the "Mozart" cutout IK bone tools. Very crash-prone, and parts of the rigged characters have a tendency to disappear when I use the IK mode - and then crash. It is unusable in its current state, unfortunately.

Test this for yourself with the files here:
http://www.toonz.com/htm/support/suppw.htm

Open the "Mozart Final" scene, and switch to the IK mode of the Skeleton tool. Move his coat a bit, for example - it disappears, and OT crashes. OT also crashes often when right-mouse clicking levels in the Xsheet.

The disappearing act occurs in the official latest builds as well, but does not crash OT. I will post a bug in its own thread.

I wish someone would work on improving the cutout IK bone animation tools in OT - they are extremely primitive - up to the point of being unusable in production, and in dire need of an update. It is the weakest part of the application, in my opinion. Compare Moho for inspiration. Or any 3d application's IK rigging with proper constraints, mesh weighting, pose libraries, non-linear animation tools to mix and blend poses, and so on. 

The Futurama creators depend on Moho for IK-based rigging and animation. And it is very understandable why!

**Comment by bobbybutterfly** [comment] 2017-08-02 10:10
OpenToonz is a highly professional tool in my opinion.

When i drag a PSD-layered Character in 500dpi into the xsheet OT takes it flawlessly (in the 1.1.3 stable version).
In Moho 12.2 it crashes.
The viewport interaction and play animation speed in OT is fantastic,

I have some crashes in the experimental version when scrubbing animation, when starting rendering and when loading, importing large psd files.

**Comment by turtletooth** [comment] 2017-08-06 06:13
New version available with updates to frame range, lip sync, and including flip viewer over, drag on numeric values to change and more.
https://gum.co/TZmmM

**Comment by bobbybutterfly** [comment] 2017-08-06 10:35
-"camera stand visibility toggle" is switched on, when clicking the "additional level settings" button
maybe this is on purpose
- the eye-symbol with dark grey outline is a kind of a continuty break of the original design, which is white on yellow for a reason

**Comment by openanim** [comment] 2017-08-06 11:48
@turtletooth, i love this flip feature, new contribution, ty for that.

**Comment by bobbybutterfly** [comment] 2017-08-06 14:28
@turtletooth, i have a warning now instead of a crash, when using lipsync window while no column selected, thanks:)

**Comment by konero** [comment] 2017-08-06 14:37
@bobbybutterfly I'm dealing with the lock icon already. I'll submit the PR soon.

**Comment by bobbybutterfly** [comment] 2017-08-06 14:41
@konero cool, looking Forward to that!

**Comment by openanim** [comment] 2017-08-06 15:06
@bobbybutterfly you need to create a shortcut from the visualization menu

**Comment by bobbybutterfly** [comment] 2017-08-06 15:11
@openanim ok,thanks!

**Comment by manongjohn** [comment] 2017-08-07 18:50
@bobbybutterfly When clicking  "additional level settings" button, the "camera stand visibility toggle" always toggles back on. This also happens in the current release when you click-hold to get to the opacity setting.  I guess the question is, should it continue to do that when there is a button to get to it?

**Comment by bobbybutterfly** [comment] 2017-08-07 19:45
@manongjohn i think its unusual to activate buttons by clicking other ones.
i would do it the other way around: block the gearwheel button, if the "camera stand visibility toggle" is not highlighted.
I find the gearwheel not the best idea for "additional" settings, especially transparency settings.
The gear wheel would be cool as "general" level settings symbol
Autodesk Maya has two overlapping rectangles for viewport transparency, which i find more appropriate (just my 2 cents)
![transparencemaya](https://user-images.githubusercontent.com/29300971/29042955-72aa5ede-7bb9-11e7-853d-63d47f385792.jpg)

**Comment by gab3d** [comment] 2017-08-08 05:01
I'd tend to look more to applications like Krita, Photoshop, TV Paint,
ToonBoom, etc. to see what kind of icons they use for Opacity controls.
These are probably more "common knoledge" to an average OpenToonz user,
than a 3D program. But that's just my opinion...

El ago. 7, 2017 4:45 PM, "bobbybutterfly" <notifications@github.com>
escribió:

@manongjohn <https://github.com/manongjohn> i think its unusual to activate
buttons by clicking other ones.
i would do it the other way around: block the gearwheel button, if the
"camera stand visibility toggle" is not highlighted.
I find the gearwheel not the best idea for "additional" settings,
especially transparency settings.
The gear wheel would be cool as "general" level settings symbol
Autodesk Maya has two overlapping rectangles for viewport transparency,
which i find more appropriate (just my 2 cents)
[image: transparencemaya]
<https://user-images.githubusercontent.com/29300971/29042955-72aa5ede-7bb9-11e7-853d-63d47f385792.jpg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opentoonz/opentoonz/issues/1329#issuecomment-320761266>,
or mute the thread

**Comment by sergiofrias** [comment] 2017-08-09 12:16
@turtletooth ,I created a issue  here : 
https://github.com/opentoonz/opentoonz/issues/1385 
The hook tool don't display numbers,tested on Morevna and your latest OTX.
thank you.

**Closed** 2017-08-25 22:14 UTC

**Comment by ctgpro** [comment] 2017-12-02 23:00
when opening OTX, I do not get the drawing sheet

**Comment by ctgpro** [comment] 2017-12-02 23:01
![desktop 02-12-2017 06-57-22 p m -605](https://user-images.githubusercontent.com/34084037/33520531-290782da-d793-11e7-9d67-a4d95731329a.png)
