### ISSUE TITLE
Plugins are not loaded on Linux

### ISSUE THREAD

**Issue by nzinov** [opentoonz/opentoonz#1331] opened 2017-07-17 07:24 UTC
I am running opentoonz 1.1.3 on Arch Linux. I've built some plugins and put into stuff/plugins. On startup the following is printed into terminal:
```
plugin search directory:/home/nikolay/.config/OpenToonz/stuff/plugins
walkDirectory_: /home/nikolay/.config/OpenToonz/stuff/plugins
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_BlurChromaticAberration.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_BlurConvolution.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_BlurCurlNoise.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_BlurMaskedC.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_BlurMaskedD.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_BlurMaskedR.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_CoherentNoise.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_ComposeAdd.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_ComposeMul.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_ComposeOptical.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_Drip.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_ImageQuilting.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_Kaleidoscope.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_LightBloom.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_LightGlare.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_LightIncident.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_NeuralStyle.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_Paraffin.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_PencilHatching.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_Tiling.plugin
doLoad handle:(nil) path:/home/nikolay/.config/OpenToonz/stuff/plugins/DWANGO_WaveGlass.plugin
walkDirectory_: /home/nikolay/.config/OpenToonz/stuff/plugins/neural_style_synthesizer
===== PluginLoadController::finished() =====
```
However, nothing is changed in FX selection window and Plugins folder is shown as empty. What could be wrong?

**Comment by RodneyBaker** [comment] 2018-12-15 05:15
@nzinov Are you still experiencing this issue?

We likely need to confer with others who have successfully got plugins to work on Linux.

**Comment by RodneyBaker** [comment] 2019-09-21 17:17
Untagging as bug as there is no identified error in the code as of yet.
Additional information required to resolve the issue.

**Comment by manongjohn** [comment] 2019-09-21 17:23
It's not working as designed. It's a bug

**Comment by RodneyBaker** [comment] 2019-09-21 17:55
What part is not working?

**Comment by RodneyBaker** [comment] 2019-09-21 18:14
Question:  Are plugins cross compatible across Win, Mac and Linux?
Or do they need to be rebuilt for each operating system?

**Comment by manongjohn** [comment] 2019-09-21 18:22
There is obviously a problem if it should be loading but its not showing up. Not all bugs in code are obvious, even to the trained eye. Could it be a user issue? Maybe. Need another Linux user to confirm this. Until otherwise proven, its a potential Linux bug.

**Comment by RodneyBaker** [comment] 2019-09-21 18:37
Feel free to tag as bug.
It doesn't meet the criteria for me.
Perhaps @turtletooth can shed some light on the reasons he tagged it as bug so that the issue can be properly addressed.

**Comment by gab3d** [comment] 2019-09-21 19:13
what I see regarding plugins is that:
- they require an old version of the library OpenCV (3.1.0). that's no problem, because it can be downloaded anyway, but it's not too clear from the instructions that you should look for that specific (old) version of the library for the plugins to work. 
- the install instructions are outdated (they refer to paths from the OpenToonz 1.0 release)
https://github.com/opentoonz/dwango_opentoonz_plugins
it would be nice to at least update that instructions, so a user that wants to try the plugins, don't have the feeling (while going through the install steps) that perhaps it'll never work, because of a lack of maintenance.

**Comment by b4zz4** [comment] 2020-07-23 13:28
In the case of OpenToonz-XXX-morevna-XXX.appimage.

I think this does not work because the application uses a different glib and qt than the operating system. The one inside the **appImage**.

But I don't know how to solve this

**Comment by b4zz4** [comment] 2020-07-24 20:51
Could it be because of this?
```
extern "C" {
TOONZ_PLUGIN_PROBE_BEGIN(TOONZ_IF_VER(1, 0))
...
```
maybe the numbering changed but not in the examples

**Comment by RodneyBaker** [comment] 2022-09-02 11:30
@nzinov Were you ever able to load plugins on linux?

Other linux users, have you been able to load plugins?

Inquiring minds would like to know.

**Comment by RodneyBaker** [comment] 2022-12-29 13:47
Linux users?
Again the question:  Can you confirm loading of plugins is (still) an issue?

Closing for now as likely resolved and/or abandoned.

**Closed by RodneyBaker** 2022-12-29 13:47 UTC
Labels: question, os-linux, needs info

**Comment by agnathnitt** [comment] 2023-11-13 16:45
how to add DWANGO OpenToonz Plugins in linux or Ubuntu?
