### ISSUE TITLE
Paint Brush Tool and Mouse Cursor

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1212] opened 2017-05-22 16:29 UTC
I want to try animate pixel art with OT. I create Toonz Raster Level and use Paint Brush Tool, But problem is mouse cursor.

When brush size is big, cursor is in center. But when i change brush size to 1 pixel,
cursor is not center. it is hard to drawing.
![mousr cursor](https://cloud.githubusercontent.com/assets/16509592/26318754/b9ad2996-3f0b-11e7-875f-4f2817b91a32.jpeg)

**Comment by turtletooth** [comment] 2017-05-24 04:43
What OS, device and OT release are you using?

**Comment by 2dvision** [comment] 2017-05-24 11:03
OS: Windows 7, OT: v1.1.2 and nightly build
and
OS: Ubuntu 16.04 64bit, OT: Appimage by morevnaproject

![mouse cursor](https://cloud.githubusercontent.com/assets/16509592/26400410/4ec775d0-4070-11e7-88e6-4b00943ab56f.gif)

**Comment by turtletooth** [comment] 2017-05-24 16:23
Is your screen a high dpi screen?

**Comment by 2dvision** [comment] 2017-05-24 19:29
> Is your screen a high dpi screen?

No, My resolution is 1280x1024 (17" CRT Monitor).

**Comment by artisteacher** [comment] 2019-01-25 00:10
On my high resolution screen (MacOS), I get the cursor locked to the bottom left corner instead of the middle - no matter how much I am zoomed in/out. The larger the brush size gets, the closer the cursor moves to the center. If the size is at least 15, then the cursor is placed properly.

**Comment by RodneyBaker** [comment] 2019-12-07 03:36
Closing as this issue is likely resolved and/or abandoned.
@2dvision Please let us know if you are still experiencing similar problems.

**Comment by artisteacher** [comment] 2019-12-07 03:49
@RodneyBaker - I still get the offset on macOS.

**Comment by RodneyBaker** [comment] 2019-12-07 03:56
Ah yes.  I forgot that the fix worked for PCs but not MacOS.
Thanks for the feedback.
Reopening and tagging with MacOS.
(This may be a duplicate report... not sure)

**Comment by 2dvision** [comment] 2019-12-07 12:16
Dear @RodneyBaker  , I have still this issue in OT nightlies `6f36231`, Windows 7 and LED monitor 18.5" with resolution 1360 x 768.

**Comment by RodneyBaker** [comment] 2019-12-08 00:04
Thanks for the feedback.
It seems we've still got a ways to go on this one.

**Comment by RodneyBaker** [comment] 2019-12-08 23:54
The fix for #2749 may related to similar fix here.

**Comment by turtletooth** [comment] 2020-05-12 03:32
How about if we hide the black dot?  Just use the red?

**Closed** 2020-05-12 21:52 UTC
Labels: bug

**Comment by fdkubba** [comment] 2020-12-10 03:26
hey guys, getting the same issue, resetting my tablet settings fixed it until it broke again:

OS: Windows 10 64-bit (10.0 Build 18363)
Display: Cintiq 22 1920 x1080
![image](https://user-images.githubusercontent.com/75768844/101717578-8c9edd80-3a6d-11eb-9092-5dd52d5eb24c.png)
(added cursor in snipping tool to show)

**Comment by Dingbat1991** [comment] 2020-12-15 04:31
I'm having the same issues as well. Operating on a Gaomon PD1560 display. Tablet works as intended when using Photoshop or Illustrator.
