### ISSUE TITLE
DWANGO OpenToonz Plugins not working

### ISSUE THREAD

**Issue by DoomDesigner** [opentoonz/opentoonz#1582] opened 2017-11-18 11:09 UTC
Plugins do not work. 
https://github.com/opentoonz/dwango_opentoonz_plugins

**Comment by shun-iwasawa** [comment] 2017-11-20 04:02
Could you please post more information regarding your OS, version, etc.? The plugins seem to work on my Win7 environment.

**Comment by DoomDesigner** [comment] 2017-11-21 13:04
Windows 10 @shun-iwasawa

**Comment by DoomDesigner** [comment] 2017-11-21 13:06
Not only I have such a problem. 
I know a lot of people who came across this.

**Comment by shun-iwasawa** [comment] 2017-11-22 03:14
Confirmed that the plugins work on my Windows10 MobileStudioPro.
Please read carefully again the [README](https://github.com/opentoonz/dwango_opentoonz_plugins/blob/master/README.md) and follow the instruction. 
Especially, please make sure to install Visual C++ Redistributable Packages for Visual Studio **2013** and OpenCV version **3.1**.

**Comment by turtletooth** [comment] 2017-11-22 03:16
I'll make a video on this soon to help clarify this.

**Comment by shun-iwasawa** [comment] 2017-11-22 03:27
@turtletooth Thanks! I'll put a link to the video on README once it is released.

**Comment by turtletooth** [comment] 2017-11-22 03:28
I'm traveling right now, but I should be able to get to it within a week.

**Comment by turtletooth** [comment] 2017-11-27 05:15
@shun-iwasawa What do you think about including the single dll from opencv that is needed for the plugins to work in the windows installation along with the license text found at https://opencv.org/license.html

This would make installing as simple as moving the plugins to the folder.

**Comment by turtletooth** [comment] 2017-12-06 23:12
Here is a link to the video: https://www.youtube.com/watch?v=Ltp261kJEto

**Comment by RodneyBaker** [comment] 2018-12-02 23:15
Here's an annual update to this one... 
The plugins in question are confirmed to work.
The issue at hand is what the best approach to making the required DLL file available might be.
When last I checked the DLL file in question is 40+MB in size.

The question at hand is whether a download might be made available so that the larger process of locating and extracting the DLL from the other files will not be required.

**Comment by RodneyBaker** [comment] 2018-12-12 22:58
Closing this as the plugins are confirmed to work.  
At some point it would be good to migrate related information into documentation and other venues.

**Comment by RodneyBaker** [comment] 2020-09-05 21:41
Reviving this issue because now that the required DLL is included in the Opentoonz distros there is an opportunity to include the DWANGO plugins in the official release.

@shun-iwasawa For general review and consideration of inclusion in the v1.5 release.
This especially as the plugins themselves are very small in size.

**Comment by RodneyBaker** [comment] 2020-10-23 14:46
Adding a note to notify that the DWANGO plugins are currently released with Tahoma.
I have not tested but... we should be able to simply copy over the plugins as well as the required DLL file from Tahoma to use with Opentoonz.

I'm not sure but perhaps we can specify via INI file where the plugins are located but this would not take care of the required DLL file.

Will test copying the plugins over and report back...

**Comment by RodneyBaker** [comment] 2020-10-23 14:56
Yes, I confirm that if the plugins are copied over from Tahoma2D plugin folder to Opentoonz plugin folder... AND... the opencv_world440.dll file is copied from Tahoma2D application folder to Opentoonz application folder... the plugins appear.
The same goes for @WolfinaBowl's plugins as well.

Note that I have not confirmed that all of the plugins actually work... but they should.

![image](https://user-images.githubusercontent.com/2576432/97019540-0c9cd280-1516-11eb-9d8e-d0d06ffd68fd.png)

**Comment by RodneyBaker** [comment] 2021-12-09 19:04
A note moving into v1.6...
It certainly would be nice to have some or all of the present plugins available with the installer.

There is a bit of maintenance associated with plugins in that they need to be either updated periodically or multiple DLL files have to be included to ensure the plugins compiled with different versions of OpenCV will run.  As such it might not be practical to include plugins with the primary release of Opentoonz.

If we can find a way to make this work with minimal need for maintenance there would be little reason not to include as many plugins as possible.  The plugins themselves are small in size.

It would be good to at least have one plugin in the stuff directory to aid in users knowing where to place additional plugins.  At present the directory itself does not exist which makes it harder to discover and successfully execute the plugin process.

**Comment by RodneyBaker** [comment] 2021-12-09 19:08
As Jeremy (ghost) mentioned above it might be appropriate to have an inactive directory inside the plugins folder to keep plugins from automatically loading upon startup of Opentoonz.  Then the user could move plugins from the inactive directory into the main plugins directory to enable them upon restart of Opentoonz.

**Comment by RodneyBaker** [comment] 2022-11-05 18:26
@DoomDesigner Can you confirm that your initial problem (Dwango Plugins not working on WIndows) is still present for you?

I had renamed this report but probably should change it back to focus on the plugins working (or not) and leave the decision of including the plugins to another request.

**Comment by RodneyBaker** [comment] 2022-12-29 13:56
Closing as likely resolved and/or abandoned.

Note there is still an open ended question on whether the Dwango plugins could/should be added to the Opentoonz release.  There are a number of pros/cons to adding them to include:

Pros
- Plugins are generally small files and don't take up much space
- Having a number of plugins in the core distribution would be encourage usage and further development of plugins
- A few more minor pros not itemized here

Cons
- Plugin maintenance requires that they be rebuilt when supporting files are updated
- Plugins load at startup and will slow that startup 
- Other cons not explored fully enough to itemize

A mitigation to the slow down at startup might be a means to place the plugins as 'inactive' where OT would ignore them upon startup.  Making the plugins active would then allow those plugins to work upon restart of OT.  In simplest form this could be simply providing the plugins as a zip file in the plugins directory or having an 'inactive' directory where users could place plugins they do not wish to load.

For continuing discussion please see other reports about OpenCV and plugins.

**Closed by RodneyBaker** 2022-12-29 13:56 UTC
Labels: question, feature request, workaround, roadmap
