### ISSUE TITLE
opentoonz ui too THICK(big)

### ISSUE THREAD

**Issue by SOMEONERANDO1** [opentoonz/opentoonz#4725] opened 2023-01-25 01:23 UTC
### Ask a question related to OpenToonz

My ui on opentoonz is too big, thus I would like to know if you can change the size of the ui or just to make it smaller. IF you can make the ui smaller please explain explain it too me.  

question : how do you change the size of ui?

**Comment by DarrenTAnims** [comment] 2023-01-25 10:44
You have to change your scaling in Windows to 100%, in the settings.

**Comment by RodneyBaker** [comment] 2023-02-04 21:45
WIll close as a duplicate of #4710 
@SOMEONERANDO1 Please let us know if you still need assistance.

**Closed by RodneyBaker** 2023-02-04 21:45 UTC
Labels: question, UI, troubleshooting
