### ISSUE TITLE
Scanner Not Responding

### ISSUE THREAD

**Issue by montypig** [opentoonz/opentoonz#3633] opened 2020-12-11 16:49 UTC
**Describe the bug**
Opentoonz seems to be having trouble communicating with my scanner's driver. When I try to scasn, test the scanner, set the driver, or create a crop box, the program crashes. I'm working on a canon mx320. 
**To Reproduce**
List steps to reproduce the behavior.
1.Open program
2.Open any scanning dialog
3. The program freezes

**Expected behavior**
There is no image from the scanner bed!

**Screenshots**

**Device Information:**
 - OS: windows 10
 - OpenToonz Version: 1.4
 - GPU: Intel R HD Graphics 4600
 - GPU Driver Version: 20.19.15.5126

**Comment by gab3d** [comment] 2020-12-16 21:10
@montypig 
Please read the first two Notes in [this page of the OpenToonz Manual](https://opentoonz.readthedocs.io/en/latest/scanning_paper_drawings.html).
Thanks!

**Comment by RodneyBaker** [comment] 2020-12-24 16:28
Closing this as a duplicate of #3225.
Scanner support directly via Opentoonz is definitely something that needs to be looked into and if not directly supported should be removed from the menu so as not to confuse users.

Perhaps in time a tighter integration between Opentoonz and GTS might be developed where GTS can be launched and manipulated more directly via Opentoonz interface.

**Closed by RodneyBaker** 2020-12-24 16:28 UTC
Labels: needs info
