### ISSUE TITLE
Rendering causes crashs

### ISSUE THREAD

**Issue by BuntNuggets** [opentoonz/opentoonz#1548] opened 2017-10-31 22:22 UTC
about 75% of the time i render an animation (really short, 600 frames and no intensive movements) opentoonz crashes while rendering. Also, after rendering, the video is completely fucked. pls help.

**Comment by shun-iwasawa** [comment] 2017-11-01 02:30
Thank you for posting the problem. I think I need more information to detect the cause of crash.

- Is the problem peculiar to the specific output format?
  - Which format did you try to output?
  - Does the problem occur on another movie format / sequential images format as well?

If you can render with another format, then the problem seems to be related to the output procedure of the specific format.

- Is the problem is related to the frame length? Or triggered with rendering the specific frame?
  - Does the problem occur constantly at always 75% of the time, or irregularly?
  - Does the problem still occur if you split the range of output?

If the problem occurs quite irregularly and you can finish the rendering by splitting the scene, then the problem seems to be related to shortage of memory.
If OpenToonz fails to render with some specific chunk of frames, then the problem seems to be related to the levels/fxs/parameters used in such frames.  

Information about which OS and OT version you are using would be also helpful.

**Comment by BuntNuggets** [comment] 2017-11-01 23:24
rendering to MP4 worked fine, got it resolved

**Comment by damies13** [comment] 2017-11-24 01:05
@BuntNuggets Great you got a workaround with MP4 but can you answer shun-iwasawa's questions so we can under stand what caused your crash? Specifically:

- Which format did you try to output?
- Does the problem occur on another movie format / sequential images format as well?
- Which OS are you using Windows 7 / 8 / 10? Mac OSX 10.??
- Which version of OpenToonz? 1.1.3?

**Comment by BrundleThwaite** [comment] 2017-12-17 19:49
I get regular crashed when I render to .png (Windows 10). The scenes contain up to three .png backgrounds and a couple of raster levels the resolution is 4096 X 2160 (DCI 4K).

The render only crashed when using all CPU's when I use a single CPU the render is fine.

**Comment by RodneyBaker** [comment] 2018-12-12 03:47
Closing this report as the original OPR states the issue was resolved.
For those with unresolved issues please open a separate report.
Thanks!

**Closed by RodneyBaker** 2018-12-12 03:47 UTC
Labels: Crash, Needs Info
