### ISSUE TITLE
Crash on hidden column

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2311] opened 2018-10-01 22:46 UTC
### Issue Summary

When inadvertently I draw on a hidden column, after several strokes or sometimes only one is enough, OT crash.

### Steps to Reproduce

- Create severals columns
- Hide 1 column
- then try to draw something on hidden column

### Expected Results

no crash

OT Last NB

Windows 10 8g

**Comment by artisteacher** [comment] 2018-10-02 14:15
Preview or the camera stand visibility - or folding the column? Does this happen just with the Xsheet active? On MacOS and the latest nightly, I'm not getting this crash on any level type with preview and/or camera stand visibility off. Drawing on a folded column also works just fine.

**Comment by openanim** [comment] 2018-10-03 13:31
Sorry, i thought these steps were enough but it seems to be random. But oddly, it happens to me quite often on projects. When by mistake, I hide a column and draw on it. I will close this issue and I will edit it if I can find a way to reproduce it.

It was about camera stand visibility btw.

**Comment by manongjohn** [comment] 2018-10-03 14:02
Which level type does this mostly happen in or does it not matter? If it's Toonz Raster or standard Raster, are you using MyPaint brushes or the standard brush?

Normally when you attempt to draw on a hidden column, it usually brings up a popup saying you can't edit a hidden column right away so I'm a little surprised you can attempt to draw 1 or more strokes on a hidden column before it crashes.

**Comment by artisteacher** [comment] 2018-10-03 14:36
If the level strip is active, you can actually draw on a level even if its column is hidden in the Xsheet. I was surprised at first but it does make sense - you are looking at the level without any regard to the scene.

If the Xsheet is active, you should definitely be getting that warning notification instead of crashing/being able to draw on a hidden level.

**Comment by openanim** [comment] 2018-10-03 16:36
Here is a gif, it crash at the end. I still do not know how to reproduce it but I have the impression that the repeated enable/ disable of the camera stand visibility can be the cause of the crash. Even if it seems strange to me because when it happened during my project, the frequency of use was less.
![crash hidden column](https://user-images.githubusercontent.com/29790512/46425053-17237e00-c73b-11e8-9a16-8e3fe50aae6e.gif)

**Comment by RodneyBaker** [comment] 2018-11-05 12:47
#2323 appears to relate to this issue.

**Comment by manongjohn** [comment] 2018-11-06 02:51
I was able to reliably and repeatedly reproduce this issue on the Official 1.2.1 release by doing the following:

1. Open new raster layer with frame in Cell 1
2. Turn OFF Camera Visibility, Tap frame in Cell 1, try to draw -> Popup w/ warning that column is hidden
3. Close popup
3. Turn ON Camera Visibility, Tap frame in Cell 1 again, try to draw -> Won't draw, crashes

I was **not** able to duplicate this in a 10/18 Nightly that I have.  It appears something fixed this.

If you can confirm it is fixed, we can close this.

**Comment by openanim** [comment] 2018-11-06 03:15
@manongjohn The problem is still there. I followed your steps and I had the crash 3 times. I use the latest NB.

**Comment by manongjohn** [comment] 2018-11-06 03:50
I downloaded the latest nightly. At first i couldn't get it to crash with my steps. I turned off my Windows Ink setting in OT and then i could reliably crash it again.

Will look more into it.

Btw, i could not reproduce this with a vector level or Toonz Raster level in official release. Seems like it is raster specific.

**Comment by openanim** [comment] 2018-11-06 12:13
I followed your instructions but opentoonz does not start, even after restarting ^^ Is there a special procedure to do?

**Comment by manongjohn** [comment] 2018-11-06 13:10
No. Should just be able to extract the dlls from the file i provided and drop into place. There should be 9 dlls in the same folder as the OpenTooonz_1.2.exe.

**Comment by manongjohn** [comment] 2018-11-06 15:45
@openanim @RodneyBaker was able to test if replacing the DLLs would work with the latest nightly.  Unfortunately it didn't work for him.  Why it worked for me is a mystery.  You can revert your system back to what it was.

I'll continue to look at this when I can.

**Comment by openanim** [comment] 2018-11-06 15:54
I did not understand a step. What does "Create a temporary directory in there (tmp)" mean? I created a folder "tmp" with my basic QTddl file inside. That's right ? I then put your QTddl but the launch does not work.

**Comment by manongjohn** [comment] 2018-11-06 16:12
It was just a place to backup the original QT*.dll files that were in `C:\Program Files\OpenToonz 1.2` so you could restore them after the test.  I wanted you to make a `C:\Program Files\OpenToonz 1.2\tmp` folder, and move all 9 QT*.dll files from `C:\Program Files\OpenToonz 1.2` to the `C:\Program Files\OpenToonz 1.2\tmp` folder.  Then you would have to uncompress the QT594dlls.zip file and take the 9 files from it and put them in `C:\Program Files\OpenToonz 1.2` folder.

I wouldn't worry about it unless you really want to try.  To get back to a running state, you can just reinstall the latest nightly again and it should put back everything back to normal.

**Comment by openanim** [comment] 2018-11-06 16:18
that's what I did the first time, but I still do not understand why I could not launch OT on my side. Yes when I put my basic ddl it works without problems but as soon as I replace yours nothing happens. No error message, just nothing.  But it's an other problem.

**Comment by RodneyBaker** [comment] 2018-12-03 03:10
I previously confirmed but just tried it again to make sure...
I confirm that PR #2369 (appveyor) does not crash when performing the following (as outlined by @manongjohn) :

1. Open new raster layer with frame in Cell 1
2. Turn OFF Camera Visibility, Tap frame in Cell 1, try to draw -> Popup w/ warning that column is hidden
3. Close popup
4. Turn ON Camera Visibility, Tap frame in Cell 1 again, try to draw -> Won't draw, crashes

These steps crash latest nightly but not the PR.

**Comment by openanim** [comment] 2018-12-12 23:47
Same on my side, it works too!

**Closed** 2018-12-20 01:52 UTC
Labels: Bug, PR Pending Review
