### ISSUE TITLE
Deleting a frame in the level strip doesn't actually delete it but cutting it does

### ISSUE THREAD

**Issue by Nukiloco** [opentoonz/opentoonz#3724] opened 2021-02-21 07:02 UTC
**Describe the bug**
In the level strip, when you right click a frame and press Delete, it doesn't remove it from the level strip. When you press Cut, it removes it from the level strip.

**To Reproduce**
1. Draw on a blank frame on a level strip.
2. Right click and press Delete, see that it doesn't remove it from the level strip.
3. Right click and press Cut, see that it removes it from the level strip.

**Expected behavior**
When right clicking and pressing Delete, it should remove it from the level strip like how cut removes it from the level strip.

**Screenshots**
https://user-images.githubusercontent.com/16618467/108618022-8020f480-73cf-11eb-9821-0b0559949462.mp4

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: v1.4
 - GPU: NVIDIA GTX 750 Ti
 - GPU Driver Version: 456.71

**Comment by RodneyBaker** [comment] 2022-02-18 11:36
While it's easy to understand the issue here the current approach of Cut and Delete in the Level Strip is intentional and by design.

It may help to think of the Level Strip as a film strip where CUTTING is like splicing or removing a section of film and DELETING is removing the contents of a frame or selection of frames.

It is unfortunate that the usage in the Level Strip is the opposite of usage of Cut and Delete in other locations of Opentoonz.

It isn't clear how we might best proceed.

**Comment by artisteacher** [comment] 2022-02-18 14:36
> It is unfortunate that the usage in the Level Strip is the opposite of usage of Cut and Delete in other locations of Opentoonz.

I don't agree that it's opposite.  Technically delete does delete, it's just deleting the drawing and leaving the frame. Which can be incredibly helpful. Cut behaves exactly the same everywhere - it copies and deletes at the same time.

 In T2D, the Level Strip's delete was changed from clear to the expected delete behavior - delete deletes the frame. Personally I miss having clear assigned a default shortcut. I don't really care if it's delete or something else though.

Making this even more complicated, on most Macs our delete key is the equivalent of backspace on most PC keyboards. So I can't use delete without a modifier anyway - unless I change the default delete shortcut to use my actual delete key. This makes many Mac users think they can't delete anything...

**Comment by artisteacher** [comment] 2022-02-18 14:39
Also, if you think about it, delete in the Timeline/Xsheet is just clearing out any exposed frames. It leaves the frames empty, but they still take up the same space.

**Comment by RodneyBaker** [comment] 2022-02-18 20:45
My apology for the length of this post... it delves a bit deeper than just his report...

I should have said behaves 'differently' rather than 'oppositely'.  When typing I knew that wasn't quite the right word.  ;)
Thanks for getting that corrected.  My main point was that users get accustomed to a specific result say of Cut removing everything selected and then sometimes when using Cut it doesn't remove everything.  This leads to users constantly wondering... should I choose Cut or Delete in this case?

This isn't much of a big deal but when reports hang on for years with no movement or consideration it may be a sign that more clarity is needed.  My aim here is to look deeper into the process and consider why there is confusion between the terms and processes of Cut and Delete.  It would be little surprise to find a new user confused by the terms but we also find more seasoned users wondering from time to time as well.

The original reporter here @Nukiloco called this a bug and while I personally wouldn't apply the term here as the processes are behaving exactly as originally intended it does demonstrate an inflection point where users continually read the process as confusing and perhaps even broken.

This report is ripe for closure and my hand is hovering the mouse over the 'close with comment' button as there is no bug involved.  But the point remains that a user took the time to report a problem and regardless of the report closing presumably that problem will remain.  I see my role in closing of a report as having confidence the original poster is satisfied with that decision.

All this to explain some of my approach in reviewing and closing reports... so thanks for sticking with me and reading.  ;)

I do think the idea of adding further clarity in the UI as @gab3d suggests might be a good move even if that was contained in a tooltip.  Tahoma 2D initiated the process of posting information about commands and processes to the status bar at bottom of screen and that would be another consideration.  It would represent a lot of work and maintenance... and translation as well.

I suppose more than anything this is actually me posting my intent to close this issue but trying to anticipate how additional reports will be opened relating to this in the future.


@Nukiloco We are always interested in the original reporter's thoughts.
The expectation you posted for Cut and Delete to behave the same in the Level Strip is not ideal as they are two intentionally different processes with differing goals in mind.

As we are at a year from original reporting and there is no actual proposal attached and all is working as intended I will recommend opening such a proposal as a new report so that others may consider that proposed change.  This proposal might simply be to provide better clarity on the differences in use between Cut and Delete.

**Comment by Nukiloco** [comment] 2022-02-24 04:37
I haven't used OpenToonz in a while though from reading your comment, yea I think it would about providing more information about differences between Cut and Delete.

**Closed** 2023-03-13 14:54 UTC
