### ISSUE TITLE
Toggle Main Window's Full Screen Mode (Black)

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#2796] opened 2019-09-20 16:50 UTC
### Issue Summary

Style Editor and Viewer become black, When I click on menus, I can't see the drop-down menu.

For back to the normal screen I need to use shortcut  Ctrl+` , In my case, When I back to the normal screen, Style Editor change size.

### Screenshot or Video Reference

When I click on "Toggle Main Window's ..." You see everything become black in gif (just in gif). When I click on menus you  just see drop-down menu. But I see OT windows and panels in my screen and I can't see the drop-down menu.

![Toggle Main Window's Full Screen Mode don't work good](https://user-images.githubusercontent.com/16509592/65343302-e78ab180-dbe9-11e9-8468-acf0e7aef66f.gif)

I don't know why Print Screen button and OBS can't capture ok in this OT screen mode. I take a photo with my phone from my monitor.

![Toggle Main Window's Full Screen Mode don't work good](https://user-images.githubusercontent.com/16509592/65343620-a6df6800-dbea-11e9-8cbe-0b58e5da721c.jpg)

### Steps to Reproduce

1. Go to Window > Toggle Main Window's Full Screen Mode (or use shortcut  Ctrl+` ).

2. Style Editor and Viewer become black, And menus don't work.

### System Information
* **OpenToonz Version**: 1.3 stable, NB `55a5931`
* **Operating System**: Windows 7
* **CPU**: Intel Core  2 Duo
* **Memory**: 4 GB
* **Graphics Card**: NVIDIA GeForce 9600 GT

**Comment by RodneyBaker** [comment] 2019-09-20 17:04
Thanks for the report and especially for the descriptions and detail.
This is likely a duplicate of previously reported issues:  #2215, #2109 and others

**Comment by RodneyBaker** [comment] 2019-09-21 17:40
There is a difference between Full Screen and a Maximized window:

(From online search):
```
Mainwindow w;
w.setWindowState(Qt::WindowMaximized);
w.show(); 
```
versus

```
Mainwindow w;
w.setWindowState(Qt::WindowFullScreen);
w.show();

```
This has me curious if this is a Full Screen problem or a Maximized Window problem.

**Closed** 2019-10-14 10:11 UTC
Labels: Bug, Known Issue
