### ISSUE TITLE
ZSpace Screw Up!

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1280] opened 2017-06-13 07:35 UTC
## **Parented columns seem to screw up in Zspace when having to animated in Zdepth (this can lead to other drastic problems with 3D space in OT)**

**Objects by default aren't drawn at zero Z depth but by a odd number ie "Z: 12.8fld on Computer Desktop 1" "Z: 16fld on Desktop Computer 2"; we also believe that zero space isn't represented when you click on a level cel, but only represented by the combo view/viewer window by the red X**

**Could Blender's 3D space be implemented In OT?**

**Comment by MikioKimura** [comment] 2017-06-13 07:35
This Bug appeared on these computers
 
**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz
 
**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz
 
**Surface Pro Computer specs:**
Operating System: Windows 7
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz
 
**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by shun-iwasawa** [comment] 2017-06-13 08:02
It is not a bug. 
OpenToonz handles Z depth in a "pseudo" 3D space - it doesn't consider the camera FOV and all layers(columns) are assumed as placed in parallel with the projection plane.
Under such condition, Z position of each layer is described as the "width of the camera cone" at the position of the layer. 
For instance, if you have a scene with 16 inch width camera, the initial Z position of columns with no Z translation will be same as the camera width (=16 fld). If you change the Z position to 8 fld, it means that the column is placed at the midpoint between the initial position and the camera position and it will be displayed twice the size of the original.

**Comment by adamearle** [comment] 2017-06-22 05:27
Is there a wat to make this friendlier for animators instead of remembering
some crazy number?

A design to keep animators animating not record keeping if you know what i
mean.

What would it take to get blender 3D space in here or something like that.
Like really what are we actually talking to bring this app out of the dark
ages?

Seriously


*Adam Earle*
<MrAdamEarle@Gmail.com>

**Comment by RodneyBaker** [comment] 2017-06-22 15:55
@adamearle 
Twice I started a bit longer discussion here but deleted both and started over.
There are some approaches that work but I'm contempating how best to present those approaches as well as how to best consider the strengths of OpenToonz as well as optimal ways forward with regard to focus,  workflow(s) and development cycles.

Using the Channel Editor in conjunction with the current 3D Camera view and the Stage Listing** is a good approach.  This is especially useful where we animate (translate, rotate, scale or otherwise manipulate) objects in a scene but especially with respect to leaving the camera view so we get a different sense of  how objects relate to one another.  Once a keyframe is established for the Z Order of any object it can easily be adjusted/manipulated in the Channel Editor by moving the keyframe up or down (up(whether animated or static).

BUT... that is the deeper stuff that should be delved into.
Easier and more likely to appeal to newbies would be the following:
  Enter the 3D Camera view
  With the Edit Tool selected...
  Select the Object you desire to move in depth (Z space)...
  Hold the Control Key down...
  Drag mouse to move object forward or backward in Z space...
  Smile/frown and adjust as necessary

This method has the advantage of not having to consider any numerical value assigned to the object.  It therefore keeps animators animating without requirement for record keeping which meets the design requirements (as specified by @adamearle).  Workflow is direct, tactile and visual.

Aside:  While this topic is best suited for discussion in the OpenToonz forum perhaps it can continue here because being 'Closed' it hopefully shouldn't distract developers from more pressing matters.  There are important elements of this topic that should have their trajectories observed with regard to development.

**These interface elements or their equivalents would likely be used in any 3D program as well so we might as well leverage them in OpenToonz too.  It is important to note however that they aren't required for optimal workflow but rather an alternative workflow.

**Comment by RodneyBaker** [comment] 2017-06-22 16:09
I had never tried to draw/paint in the 3D Camera view before... that's rather crazy cool.
I need to do more of that!

**Comment by RodneyBaker** [comment] 2019-09-24 02:27
Reopening so that it can properly be closed by PR #2180 
Thanks to @martinvanzijl for the PR and @MikioKimura for your patience.

**Comment by RodneyBaker** [comment] 2019-09-24 02:30
Reclosed... typo.

**Closed by RodneyBaker** 2019-09-24 02:30 UTC

**Comment by martinvanzijl** [comment] 2019-09-24 02:32
@RodneyBaker Yes, apologies, I referenced this issue by mistake. Have fixed my comment now. :-)

**Comment by RodneyBaker** [comment] 2019-09-24 02:50
No problem @martinvanzijl  I should allow the reference to cool down a little before reacting.
That and validate.  It LOOKED good though.  ;)
