### ISSUE TITLE
my opeentoonz crash and I don't know why 

### ISSUE THREAD

**Issue by Navi45Bomber** [opentoonz/opentoonz#5398] opened 2024-04-14 19:09 UTC
### Is your feature request related to a problem? Please describe

my animation crash and idk why

### Describe the solution you'd like

i don't why my animation is crash. not letting me work?

**Comment by RodneyBaker** [comment] 2024-04-18 21:03
Closing as a duplicate of #5409.

**Closed by RodneyBaker** 2024-04-18 21:03 UTC
Labels: needs info, incomplete report
