### ISSUE TITLE
Macro Preset Bug

### ISSUE THREAD

**Issue by Ecceptor** [opentoonz/opentoonz#1434] opened 2017-08-26 03:49 UTC
Each time I load my own built-in schematic macro preset Opentoonz crash.

**Comment by turtletooth** [comment] 2017-09-11 04:20
Can you share more information to give us reproducible steps.  I just created a macro and used it in another scene without any issues.

**Comment by Ecceptor** [comment] 2017-09-11 12:57
![blurfish](https://user-images.githubusercontent.com/20495731/30275188-17d56ba8-9733-11e7-8113-d0d132c77c3a.png)

These are my setup. It's for blurring 2 palette together.
 After this I select all the component(from Palette filter to Overfx) and choose Make Macro Fx. Then I saved as preset. When I loaded the preset Opentoonz crash.

**Comment by RodneyBaker** [comment] 2018-05-25 21:20
I've just gone through the basic steps of saving and reloading FX macros and am not getting this issue on WIn10 with any of the recent releases.

@Ecceptor 
Can you confirm this is still an issue with the most current nightly release?
A lot has changed since you last reported in on the problem.
If it is still occurring , can you share a copy of a macro that crashes as well as information about your system (which I assume to be Win 10)?

Thanks!

**Comment by RodneyBaker** [comment] 2019-12-08 21:31
As it's been over two years for this report the issue is likely resolved and/or abandoned.
@Ecceptor Can you confirm this is still a problem and if so share a copy of a MacroFX file that is problematic?

**Comment by RodneyBaker** [comment] 2019-12-18 13:21
Closing as likely closed and/or abandoned.

**Closed by RodneyBaker** 2019-12-18 13:21 UTC
Labels: Needs Info
