### ISSUE TITLE
Schematic:  Crash using Replace FX

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2177] opened 2018-07-20 21:38 UTC
### Issue Summary

When I use replace command on a node that has no input, OT crash.

### Screenshot or Video Reference

![replace no whitout input crash ot](https://user-images.githubusercontent.com/29790512/43026414-e1b6d654-8c75-11e8-8ca9-7ccf38299c2b.gif)

And change the value of cast shadow fx, also crash OT.

### Steps to Reproduce

Use replace command on node whitout input

w10 cintiq companion HD graphics OT 1.21

**Comment by RodneyBaker** [comment] 2018-12-03 21:41
I can't replicate this problem.  Did it get resolved in a recent Schematic update?

Whoops.  Spoke too soon.  I can reproduce the crash.
An easy way to test:
- Create a Color Card FX (it doesn't have an input)
- Use Replace FX and attempt to change it to Blur (or something similar)
This should produce a crash.

**Comment by manongjohn** [comment] 2018-12-08 16:47
@shun-iwasawa Can you take a look at this issue? There is at least one other path that I found to crash OT in the same place so it is not specific to replacing node.

It is crashing in `updateLink()` in fxschematicscene.cpp:

>for (int i = 0; i != inputPortsFx->getInputPortCount(); ++i) {
>      TFxPort *port = inputPortsFx->getInputPort(i);
>
>      if (TFx *linkedFx = port->getFx()) {

It fails on the `port->getFX()` line with the following error:

>Exception thrown: read access violation.
>port-> was 0xFFFFFFFFFFFFFFF7.

Some nodes work ok (motion blur) others don't.

I have tried to figure out how to fix this but having trouble finding the right solution.

My concern with this bug other than there is at least 2 ways to crash in the same place, but there are a number of places in our code where we do something like this:

>Tx *fx = port->getInputPort(x)->getFx();

This can potentially  cause crashes for the same reason above.

**Comment by artisteacher** [comment] 2018-12-08 19:38
I get a ton of crashes working with FX but they aren’t repeatable every time.

**Comment by manongjohn** [comment] 2018-12-12 20:33
@shun-iwasawa I think I figured out the underlying cause of this issue and will submit a PR shortly.

It boils down to how a ZeraryColumnFx  is being replaced with a normal fx.  The normal fx is being converted into a ZeraryColumnFx which I believe is incorrect.  Due to this conversion, there are issues accessing elements of the fx resulting in bad pointers.

**Closed** 2018-12-27 01:49 UTC
Labels: Bug
