### ISSUE TITLE
Select Whole Level tool options bar does not allow textual input of rotation

### ISSUE THREAD

**Issue by phillycheese007** [opentoonz/opentoonz#2351] opened 2018-10-29 21:41 UTC
### Issue Summary

Rotating a whole level at same time seems only posible by rotating in the viewer(rotating the shape bounding box).....try entering the rotation into the text input area and it only rotates one drawing from the level
### Screenshot or Video Reference

![whole](https://user-images.githubusercontent.com/25863731/47682043-8efd9080-dba1-11e8-8d1f-3ab69c41a8d2.gif)
### Steps to Reproduce

create level with more than 1 drawing> using select tool choose "whole level"  eneter in rotation in text input box
### Expected Results

all drawings rotate
.......I believe this problem does not only apply to rotation but to all options with text input ( i have not tested with other option besides whole level yet)
### Actual Results

only one drawing rotates
### System Information
* **OpenToonz Version**: nightly from sept
* **Operating System**: wind 10

* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by Orphanlast** [comment] 2018-10-30 01:30
Just sounds like you need to use the animate tool.

**Comment by artisteacher** [comment] 2018-10-30 02:29
I think it’s actually a deliberate choice to keep the behavior of the tool option bar values independent from how the viewer behaves - like in #1872. In some cases it can be helpful - ie. if you generally want to make changes to the whole level but find you want to tweak a single drawing independently...

Helpful when you understand how it works (in certain cases) but definitely not the expected behavior and can be disadvantageous for certain precision uses.

**Comment by artisteacher** [comment] 2018-10-30 14:51
You certainly could - but that requires more clicks to get into the dropdown. At least it's consistent with how the other tools work. I can see the use for this but as a whole though, I feel like it leads to misunderstandings and confusion. 

I would love to see a preference that makes modifying the tool option values behave like making those adjustments directly in the viewer. Or even better, a modifier key to override when desired - ie. in this case holding down on shift when modifying the rotation value would modify just the current drawing, while changing the value without shift would modify the entire level. I think it would be a ton of work for someone though...

**Comment by phillycheese007** [comment] 2018-10-30 22:08
I think im stiull a bit confused....
I think the clearest way for this is to keep single frame manipualtion to
"normal mode" and multiple frames (whole level) to "whole level mode"

u mention extra clicking but from my perspective i would never expect to be
able to target one drawing in "whole level" mode....I would click normal
mode....and i would not think of that as extra work really ...because the
functions would be exactly where id expect them to be

**Comment by phillycheese007** [comment] 2018-10-30 22:09
Also just to be clear.....this is not an animate tool issue.....stictly
drawing im talking about

**Comment by RodneyBaker** [comment] 2018-10-30 23:42
@phillycheese007 
As feature requests aren't generally opened for OT on github unless there is a dedicated developer attached to the request recommend closing this issue.  We can call it Feature Request #20181030A.  

The discussion can continue here in this topic even though the issue itself is closed.
In this way it won't interfere with develoers as they seek and destroy bug reports.
There is also the OpenToonz forum feature request category available to dive more deeply into development concerns ([LINK](https://groups.google.com/forum/#!categories/opentoonz_en/feature-requests) )

**Comment by phillycheese007** [comment] 2018-10-30 23:52
to be honest this still sounds like more of a bug than a feature request.....single drawing edits should not really be included in something called "whole level"...but i hear ya...i can reopen in google forums

**Comment by artisteacher** [comment] 2018-10-31 01:41
I know it is counter-intuitive but I am pretty sure it is a deliberate design choice rather than a bug. All of the individual value fields seem to work independently, ignoring other settings when you change them directly in the tool option bar - no matter what tool happens to be active. 

Looking at the animate tool rather than the select tool for a moment, if you are working with scale and set maintain to “mass”, changing the values directly in the tool option bar completely ignores maintain mass. Or if you lock the E/W position, you can still change it by editing the value directly in the tool option bar. It looks like only the animate tool and select tool have value fields + modes/locks, so they are the only tools where this behavior occurs.  The animate tool’s scale behaviors are a little more complex due to an additional modifier which actually enables certain tool options to apply (backwards from what I think is intuitive). I think if changes are made, it should happen to both tools to maintain consistency. 

It would be more user friendly and also expected for editing those values to take the other tool settings into account as the default behavior. However if this is a deliberate choice, there may be users that do rely on the existing behavior. Whether or not we see this as useful, obviously someone did. 

That said, I definitely see the value in changing the default behavior. Using a modifier key to make changes individually as needed (as happens currently when editing values) and letting normal changes behave as expected (taking modes & locks & etc. into account - without any modifier key) could work. Or perhaps an additional option in the tool option bar that could be checked/unchecked to enable/disable field override. Whatever change is made, it will need to allow us to keep the current flexibility while also adding additional precision capability & a more expected user experience.

**Comment by phillycheese007** [comment] 2018-10-31 01:52
yeah im a little mystified but ...and i hear ya bout this being intentional....i do think the option i talk about should be possible.. my hands are not steady enough to manually rotate a "whole level"  to exact numbers...repeatably

**Comment by artisteacher** [comment] 2018-10-31 02:07
As an alternative, you could rotate with the animate tool instead - like @Orphanlast suggested. It does add a keyframe, but if you have the first frame selected, your change will apply to the entire level without any tweening.

**Comment by Orphanlast** [comment] 2018-10-31 02:09
One plus of the animate tool is it's none destructive.

**Comment by phillycheese007** [comment] 2018-10-31 02:12
These are two different things...some overlap of course but we are talking
about different workflows.....for one example animate tool would rotate
hooks with it....selct tool on "whole level" does not

**Comment by RodneyBaker** [comment] 2018-10-31 03:37
Ok... getting caught up here....

When I draw multiple items/drawings in different frames of the level strip and then use Selector Tool with Whole Level selected.... and manually rotate.... all the drawings rotate.

You are wanting to add the ability to be able to enter said values in directly into the fields in the toolbar.

It's a useful feature request but not a bug.
If it were a bug then we might expect the developers to fix this so that the fields gray out so that nothing can be entered into them as that's likely what should be happening there.

**Closed** 2018-11-03 03:57 UTC
