### ISSUE TITLE
Crash using My paint brushes with geometry tool - SOLVED

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4296] opened 2022-03-04 12:16 UTC
This happens to me only with raster layers.

**Comment by RodneyBaker** [comment] 2022-03-04 18:53
You must be on Tahoma2D as use of mypaint brushes with Geometry Tool won't even work in Opentoonz.
If experiencing otherwise with Opentoonz recommend double checking that you are using current nightly release.

**Comment by artisteacher** [comment] 2022-03-04 19:21
I don't get a crash in T2D with the MyPaint brushes and geometry tool on macOS.

**Comment by F-Burning** [comment] 2022-03-04 19:34
It happens to me in Opentoonz too


https://user-images.githubusercontent.com/74098734/156829393-30e57be9-bd0a-4acd-a35b-c315776c5a15.mp4


As you can see, I'm using a "My paint brush pencil", but happens too without "My paint brushes". I think the bug is in the raster level.



> If experiencing otherwise with Opentoonz recommend double checking that you are using current nightly release.

Yes, it's a nightly version.

**Comment by RodneyBaker** [comment] 2022-03-04 19:49
Thanks for the video.
That's very strange and I can't reproduce it regardless of what I try.

A question:  When was the last time you installed with a clean install of both the program files and stuff directory?
I ask specifically because you seem to have a number of stability issues that others cannot reproduce and that is a good place to start.  Some of your instability sounds familiar but more related to issues of the past no longer experienced with current nightlies.  This suggests to me there must be some hardware difference that causes the problem.  To rule that out... If you have access to another computer running a clean install on that  would at least validate the issue isn't isolated to that specific computer.  Optimally, don't use the same pen/tablet on the other system to rule that out as well.


For other users:
I don't think this applies to you @F-Burning but I've noted that there are a few users who build their own nightlies and that is important information to know when troubleshooting... for those of you looking in that build from source... when posting a bug report please add that info and ideally test also using the latest nightly.

**Comment by F-Burning** [comment] 2022-03-04 20:19
Maybe that's it @RodneyBaker . I'm not used to cleaning when I install a new one nightly, although I don't understand what happens in Tahoma because it's portable and there are no pre-installed configurations that can generate errors. I'm going to try a clean and reinstall and see what happens. I hope that's it. Thank you.



PD: I have no idea about programming, so it's not my case 😋

**Comment by F-Burning** [comment] 2022-03-04 20:29
I installed the last nightly version after cleaning all and the crash continues in my pc.

I have Windows 10

**Comment by RodneyBaker** [comment] 2022-07-29 06:16
I missed the update that this problem was resolved via a reinstall.
Glad to hear!  Closing.

**Closed by RodneyBaker** 2022-07-29 06:16 UTC
