### ISSUE TITLE
OpenToonz 1.7 crashes upon opening

### ISSUE THREAD

**Issue by Kuebasu6204** [opentoonz/opentoonz#4886] opened 2023-05-10 23:33 UTC
**Description**
After downloading version 1.7, the program crashes upon trying to open the software. For reference, I had 1.6 installed beforehand. 

**Steps to Reproduce**

**Expected Behavior**
Expected the program to open normally.

**Screenshots, Video & Crash Logs**

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-05-10 19:30:17
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22000
CPU Threads: 8

Crash File: C:\Users\Miguel\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230510-193017.log
Mini Dump File: C:\Users\Miguel\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230510-193017.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\shcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22000.1_none_271a8fad6a2d1b1e\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\SYSTEM32\urlmon.dll
C:\Windows\System32\iertutil.dll
C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_fa58b8086803cc6e\ig9icd64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_fa58b8086803cc6e\igdml64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_fa58b8086803cc6e\igdgmm64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_fa58b8086803cc6e\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlAreLongPathsEnabled [0x7ffe63a9c49a] <ntdll.dll>
  2> RtlRestoreContext [0x7ffe63a559a2] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffe63ac7afe] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ffe41d33af6] <MSVFW32.dll>
  6> ICOpen [0x7ffe41d336f4] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ffe2f186212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ffe2f184478] <image.dll>
  9> initImageIo [0x7ffe2f127ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff76b230dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff76b232d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76b65eab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76b65e092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ffe62935590] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ffe63a2485b] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment] 2023-05-11 02:20
Please see #4883 as that appears to be the same problem.

**Comment by RodneyBaker** [comment] 2023-05-29 04:22
Closing as a duplicate of several other reports pointing to outdated and problematic logitec driver.
The file is located at:  C:\WINDOWS\SYSTEM32\lvcod64.dll

**Closed by RodneyBaker** 2023-05-29 04:22 UTC
Labels: crash, known issue, referral / thirdparty, duplicate
