### ISSUE TITLE
I cant use my drawing tablet with Opentoonz can someone plz help

### ISSUE THREAD

**Issue by YesMab** [opentoonz/opentoonz#3492] opened 2020-09-19 04:37 UTC
**Question**
     When ever I try to put my pen to my tablet a little circles around where I initially placed the pen on the tablet. after that a little drop down menu appears as if I right clicked.
     I would have posted this questions in the forums but I didn't have any permissions
     If I move my pen around a bit it creates this award line.

I don't believe this is a bug. I'm pretty sure this is just my bad

-Note I do not have the is problem in any other software's that I have tried
![Screenshot 2020-09-19 003647](https://user-images.githubusercontent.com/71538784/93659137-398a3100-fa10-11ea-8dcb-b037244f164f.png)

**Comment by YesMab** [comment] 2020-09-19 04:44
the circle in the middle is what forms around my curser when I keep my pen still

**Comment by RodneyBaker** [comment] 2020-09-19 04:48
Closing as an apparent duplicate of https://github.com/opentoonz/opentoonz/issues/3476

**Closed by RodneyBaker** 2020-09-19 04:48 UTC
Labels: question
