### ISSUE TITLE
Open Toonz crashing after switching navigation tools (OSX) 

### ISSUE THREAD

**Issue by NestorAntonio** [opentoonz/opentoonz#1979] opened 2018-05-16 17:38 UTC
Hello guys, I realized that when using the OSX version of OPT, it happens the same as #1913
 
At the moment of using the hand tool or the rotate tool, holding the button, If I release it and keep dragging with the stylus the software will crash. 

These are my specs:

MacOS Sierra 10.12.6
Processor 2.8 GHz Intel Core i5
Memory 8 GB 1600 MHz DDR3
Startup Disk Macintosh HD
Graphics Intel Iris 1536 MB
Cintiq 13HD

Thanks again for all your work and dedication.

**Comment by jpturcotte** [comment] 2018-05-16 17:47
If the issue is similar, please post there instead of opening a new issue. This is to keep things well organized for the developers. Thank you for your understanding!

Recommend close.

**Comment by NestorAntonio** [comment] 2018-05-24 13:52
Hello guys, you are right. I added a note to #1913, but it seems I can't close this thread.

**Comment by shun-iwasawa** [comment] 2018-06-13 08:42
I'll close this. Thanks!

**Closed by shun-iwasawa** 2018-06-13 08:42 UTC
