### ISSUE TITLE
opentoonz randomly crashes

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2054] opened 2018-06-11 00:46 UTC
when I use opentoonz it sometimes crashes I don't no why but the crash cause is:
ucrtbase.dll
it sometime crash and sometime not
my laptop specs:
nvidia gtx 630m
windows 7 64bit
i5

**Comment by shun-iwasawa** [comment] 2018-06-11 01:30
ucrtbase.dll stands for universal standard c run-time library and is associated with Microsoft Visual C++([MSDN](https://msdn.microsoft.com/en-us//library/abx4dbyh.aspx)). Since it is quite fundamental it is difficult for me to identify a specific cause of the crash.

Can you provide more information, such as what operation did you do just before you faced the crash?
If you can find reproducible step it would be very helpful. Thanks!

**Comment by animating-dino** [comment] 2018-06-11 18:13
I just open opentoonz and it crashes several times at the startup then I restart the computer and it work and when i am doing some work in opentoonz it just crashes I dont no why

**Comment by artisteacher** [comment] 2018-06-11 18:49
What version of OpenToonz are you using? If you haven't tried updating to the [RC/latest nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly), it's worth a try.

**Comment by animating-dino** [comment] 2018-06-11 23:02
I will download but it is so randomly to get this crash i can't tell it fixed or not

**Comment by animating-dino** [comment] 2018-06-13 15:57
![capture2](https://user-images.githubusercontent.com/39278532/41363016-2967a5e2-6f33-11e8-9d35-229d434a5b37.PNG)
![capture](https://user-images.githubusercontent.com/39278532/41363018-298af74a-6f33-11e8-8582-3d9750616941.PNG)

 I recive it again

**Comment by animating-dino** [comment] 2018-06-13 15:58
I just open it
it crash at startup

**Comment by artisteacher** [comment] 2018-06-13 18:43
This might be a duplicate of #1720 - there are a few options listed in the comments that you should try.

**Comment by animating-dino** [comment] 2018-06-14 00:33
but what he say not fixes my problem

**Comment by artisteacher** [comment] 2018-06-14 20:03
Too bad. I’m sure it’s frustrating but at least the more that’s ruled out, the closer we are to an answer. I see that the startup crash happened when you had the Browser room open. It’s possible that a corrupt or incompatible file that the Browser is accessing caused the crash - I’ve had that happen before. If you close OT with the Browser room active (and the same project selected - John Wick) and then reopen OT, do you get a repeatable crash?

**Closed** 2018-08-01 19:11 UTC
Labels: Needs Info
