### ISSUE TITLE
Magic Wand Tool

### ISSUE THREAD

**Issue by DreamBoi8** [opentoonz/opentoonz#4562] opened 2022-10-16 00:42 UTC
### Is your feature request related to a problem? Please describe

It's hard to shade drawing without this selection tool.

### Describe the solution you'd like

Add a magic wand tool.

**Comment by RodneyBaker** [comment] 2022-10-16 01:22
Thanks for the request @DreamBoi8 
Will close this as a duplicate of #4043 but please feel free to add any additional information about your request either here or in that request.

On a personal note, just the other day I was doing some work where a magic wand tool would have been quite useful.
That case would require that the magic wand actually create a mask however...

**Closed by RodneyBaker** 2022-10-16 01:22 UTC
Labels: feature request
