### ISSUE TITLE
Draw order options for the brush tool on vector levels (Discussion)

### ISSUE THREAD

**Issue by StonePerson2** [opentoonz/opentoonz#4503] opened 2022-08-15 17:25 UTC
### Is your feature request related to a problem? Please describe

You can set draw order on raster levels (over all, under all, palette order), but you can't do that on vector levels. 
You can move vector lines to front or to back manually by selecting them, right clicking and choosing a right option, but it's a lot of work and having it automated just like you can have with raster levels would really help.

### Describe the solution you'd like

Add an option to set draw order on vector levels

**Comment by RodneyBaker** [comment] 2022-08-15 19:34
Good news!  Draw order options for vector levels is currently available in the Tahoma2D fork.
As such all we need is to port that upstream to Opentoonz master.

There is no one currently working on this but at least the core code is in place and should the feature be needed in the meantime Tahoma2D and Opentoonz can both be used simultaneously.

**Comment by andeon** [comment] 2022-08-15 20:08
@RodneyBaker Recurrently, we have a lot of duplicate issues. If **Discussions** were enabled for the community, we could better manage things like this in unique threads.

How does this work now, it's hard to return or engage in old or closed issues. 

https://github.com/opentoonz/opentoonz/issues/3549

https://github.com/opentoonz/opentoonz/issues/3913

https://github.com/opentoonz/opentoonz/issues/4370

**Comment by RodneyBaker** [comment] 2022-08-15 20:14
@shun-iwasawa will have to decide if opening up Discussions is desireable.
I can see many reasons to add that.

I do wish that forks could be made to propogate issues.
Then we could create a mirror of Opentoonz master (read only) but also have Discussions enabled.

As for how this works now...
We identify duplicates and close them consolidating reports where we can.
The ones you point out could all likely be closed just by opening a new report that focuses on porting as those features have already been implemented in Tahoma2D but are waiting for someone to port them over.

**Comment by RodneyBaker** [comment] 2022-08-15 20:22
I will add an additonal personal observation.

I personally don't have issue with duplicate reports being opened.
This is a great indicator of the desire by users to have something addressed.

It does take some time to process those duplicates of course and I understand why that can be frustrating perhaps especially to those who originally opened a report that gets duplicated.

The important thing of course is for the underlying issue to be addressed and I would hope that more attention on an issue is always preferrable.

I recently suggested via discord that the Opentoonz community needs more testers and we do.
That helps stale issues get dusted off and information kept current.

**Comment by RodneyBaker** [comment] 2023-01-25 22:06
Closing this as a duplicate of #3549 as it is the original report.

**Closed by RodneyBaker** 2023-01-25 22:06 UTC
Labels: feature request
