### ISSUE TITLE
Add option to Auto-Duplicate Drawing On Paste Cell ($50)

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3241] opened 2020-04-18 04:44 UTC
### Issue Summary
I know many people like using the Level Strip, but I personally prefer how Adobe Animate lets you only use the Timeline. Probably the most important step to get there is to have a way to automatically duplicate the drawing a cell is using when the cell is copy/pasted, and having the pasted cell point to that duplicated drawing.

### Expected Results
If a cell is right clicked and "Paste Duplicate" is selected, or if Ctrl (Cmd on Mac) + V is pressed and a "Ctrl [Cmd on Mac] + V on Cell Duplicates Drawing" (there might be a better name for this setting) setting is enabled: The drawing the copied cell points to is duplicated automatically. The pasted cell points to this duplicate drawing, rather than the original drawing (I believe the same as pasting the cell, right clicking the duplicated cell, and selecting "Duplicate Drawing")

If a cell is right clicked and "Paste" is selected, or if Ctrl (Cmd on Mac) + V is pressed and the "Ctrl [Cmd on Mac] + V on Cell Duplicates Drawing" setting is disabled: Pasted cells point to the same drawing as the copied cell
(This all should also be done as expected if multiple cells are copied/pasted at once)

### Actual Results
Pasted cells always point to the same drawing as the copied cell

### System Information
* **OpenToonz Version**: Nightly
* **Operating System**: macOS Catalina 10.15.4
* **CPU**: Quad Core i5
* **Memory**: 8 GB LPDDR3
* **Graphics Card**: Intel Iris Plus Graphics 645

**Comment by gab3d** [comment] 2020-04-18 06:10
mmm... but you can do that by using the Cells -> Duplicate Drawing command ("D" shortcut).
it's even faster that using Ctrl+C then Ctrl+V

**Comment by beeheemooth** [comment] 2020-04-18 11:03
Add my five cents. The essence of the problem is that at the moment we can only duplicate the currently selected frame (frames). But practically in the workflow there is very often a situation when you need to use another drawing from Level Strip, **BUT** it needs to be edited. Naturally, you cannot edit it, as changes will also occur in other Xsheet cells (which contain the same drawing). Workarounds at the moment are quite cumbersome.

![ezgif-2-c35b9bef3a11](https://user-images.githubusercontent.com/25724133/79635969-056ac580-817d-11ea-8dfa-890d42735863.gif)

![ezgif-2-f11b966c3815](https://user-images.githubusercontent.com/25724133/79635971-08fe4c80-817d-11ea-80ef-fdc1ed9677d4.gif)

The copy-paste you are talking, @MrBlockCat,  about is only one side of the coin, as there are other ways to insert or replace cells (Drawing Substitution, drag'n'drop from Level Strip, Reverse, e.t.c.)

I think that the solution to this problem could be to duplicate the drawing directly in the cell with the number, as a result of which a duplicate of the current drawing is created in the cell, and the drawing itself is added to the end of the Level Strip (so as not to disrupt the frame order).

**Comment by DarrenTAnims** [comment] 2020-04-18 12:47
I can see that this is a really useful feature. I see users being surprised that doing a copy/paste then edit, changes the original drawing. But can we not add a "Paste Duplicate" option to the context menu to do this? Then if the user prefers, they can change their keyboard shortcuts so that this is what Ctrl+V does. It will also help with finding out there is this option - discoverability. Users tend not to look at the Prefs dialog until they're prompted to.

**Comment by MrBlockCat** [comment] 2020-04-18 16:58
@gab3d After a while I did figure that out, but as a beginner user copy/paste doesn’t work how I’d expect it to, so I think this would really help out other beginners as @DarrenTAnims said! I like @DarrenTAnims’s idea better than my original one for the reasons he described.

**Comment by MrBlockCat** [comment] 2020-04-18 18:59
The only other step I can think of towards optionally not using the Level Strip would be to have an option to automatically delete a drawing if the last cell that uses it is deleted. That might be useful to some people who use the Level Strip, too! But that can be a different issue.

**Comment by gab3d** [comment] 2020-04-18 19:21
@MrBlockCat 
I'm not against options, but please don't delete things automatically without a proper warning to the user, first.

**Comment by MrBlockCat** [comment] 2020-04-18 19:57
@gab3d Definitely! I’m thinking for that there could be a setting for the warning to ask if you want the drawing deleted, with the default being always ask (or maybe keep; This is of course all up for discussion!), and other choices being auto delete or keep. Ctrl/Cmd + Z should definitely also be able to undo the auto-deletion as a backup plan

**Comment by RodneyBaker** [comment] 2020-04-19 05:59
It seems this might be a lot of extra work just to adjust the current Duplicate methodology so that it duplicates and inserts in cases where it now errors out and says... 

![Unable to Replace](https://user-images.githubusercontent.com/2576432/79680728-8a36fd00-81d8-11ea-8a21-f66c4d59e756.png)

In allowing that duplication methodology to insert a copy of the currently exposed drawing it not only would place the new drawing but would also remove the need for the warning dialogue.

Aside:  There is a similar thing that could be done with cloned (unlinked) drawings which are created in their own level but that is sure to make the head spin.

**Comment by MrBlockCat** [comment] 2020-04-19 06:18
@RodneyBaker Interesting, I wasn't aware that warning message existed! What cases cause it to display?

**Comment by RodneyBaker** [comment] 2020-04-19 06:56
Duplication apparently requires a free space to be open in order for the duplicated frame to be inserted.  So at the end of a sequence... or if we say... adjust our exposure down or remove an exposure to clear up a cell... the duplicate will be created.

Perhaps the best way to see this is to attempt to duplicate (via D hotkey) a cell in the middle of a sequence versus one at the end of a sequence.

**Comment by RodneyBaker** [comment] 2020-04-19 07:00
Cloning could be used to achieve the same thing (although the duplicated frame/image would be in a new level as opposed to the same level).  Cloning currently puts the new exposure into a new column however so that would need to be updated in order for the new clone/level to be inserted into the current column at the desired location.  

I mention cloning because that is perhaps one of the surest ways to make sure the duplicated image is independent of the original.   Not only is it a new copy of the old drawing... but it is stored in an entirely different image file/level.

**Comment by beeheemooth** [comment] 2020-04-19 08:26
@RodneyBaker The logic of the "Duplicate Drawing" command should take into account the fact that the user wants to duplicate the drawing in the current frame. After all, if the user does not want this, he simply copies the number of the cell (or cells, Paste Numbers) and does not think about duplication.

**Comment by gab3d** [comment] 2020-04-19 17:40
> Perhaps the best way to see this is to attempt to duplicate (via D hotkey) a cell in the middle of a sequence versus one at the end of a sequence.

Just a note: that's valid in the context of the Xsheet, in the Level Strip the new duplicated drawings are always inserted correctly, and the existent ones are moved forward, if needed.

**Comment by MrBlockCat** [comment] 2020-04-20 00:14
@RodneyBaker I've added a $10 bounty to add this feature! https://www.bountysource.com/issues/91129354-add-option-to-auto-duplicate-drawing-on-paste-cell

**Comment by paulfishermedia** [comment] 2020-06-14 02:30
DUDE OH MY GOD. I can't believe I just read through this entire page and I have no solution. This is why this software sucks man it's counterintuitive AF. All I'm trying to do is copy and paste a drawing and use the eraser and make some changes on the next frame. Holy s**t. And duplicate doesn't do what I want either.

**Comment by jpturcotte** [comment] 2020-06-14 14:25
Bounty bumped to $50!

**Comment by turtletooth** [comment] 2020-06-14 16:18
I’ll do it.

**Comment by manongjohn** [comment] 2020-06-14 16:33
My suggestion for this is a new `Paste as Duplicate` option which users can assign (or reassign) a shortcut to so as not to impact existing users and workflows.

**Comment by turtletooth** [comment] 2020-06-14 17:02
I agree. I think ctrl-v and something like shift ctrl v

**Comment by turtletooth** [comment] 2020-06-30 04:55
PR submitted #3372

**Closed** 2020-07-06 05:00 UTC
Labels: bounty, feature request
