### ISSUE TITLE
Camera capture does not recognize any camera in Linux

### ISSUE THREAD

**Issue by charliemartinez** [opentoonz/opentoonz#2283] opened 2018-09-08 20:03 UTC
Hi! I'm very interested in using opentoonz for animations with stop motion technic.

But the software does not recognize any camera: neither the one that is incorporated in my laptop nor a new one I just bought, Logitech C922. Both cameras work without problems in other applications such as OBS and official opentoonz (from the AUR repositories of Manjaro).

But now that I'm using Debian, and I try morevna an flatpak.

Did it happen to someone else? Is there a solution?

Thank you very much from Buenos Aires, Argentina and congratulations for this excellent work.

**Comment by jpturcotte** [comment] 2018-09-08 20:09
Duplicate of #1834.

Hey Charlie! Please edit your post there to add this new bit of information, and close this issue. Thank you!

**Closed** 2018-09-11 18:26 UTC
