### ISSUE TITLE
Scene cannot be loaded, some files are missing

### ISSUE THREAD

**Issue by Therippersart** [opentoonz/opentoonz#2399] opened 2018-12-03 22:57 UTC
Opentoonz version 1.2.1

My amv I was working on open and closed just fine until today. Everytime I try to open my file, I get an error message telling me some files were missing, and it won't open my project. I've tried system restore, reinstalling the program, and digging through the files. Somewhat good news, my drawings are still there. (In the browser tab) but I want the full project back

I really just want my project back. This was WEEKS of work, and if I can't get it back, I won't be assed to start it again.

**Comment by manongjohn** [comment] 2018-12-03 23:30
Unforetantely, it sounds like the scene file is somehow corrupted/incomplete. Not sure what could have happened.

Can you provide the .tnz file so we can see how much of it is there?

**Comment by Therippersart** [comment] 2018-12-03 23:41
> Unforetantely, it sounds like the scene file is somehow corrupted/incomplete. Not sure what could have happened.
> 
> Can you provide the .tnz file so we can see how much of it is there?
> 
> Edit Oh. Its also possible that one of the levels may be messed up in such a way as to cause OT to not load the scene file properly giving that error.

I'm trying, but I seem to be unable to insert a toonz file.

**Comment by artisteacher** [comment] 2018-12-04 03:31
If you zip/conpress the file you should be able to upload it. In case the problem is a level and not your scene, you could try removing all the relevant levels and adding them back one at a time to find the problem file.

**Comment by gab3d** [comment] 2018-12-04 03:31
@Therippersart 
please zip it to be able to attach it

**Comment by Therippersart** [comment] 2018-12-04 11:30
> If you zip/conpress the file you should be able to upload it. In case the problem is a level and not your scene, you could try removing all the relevant levels and adding them back one at a time to find the problem file.


[Edgar.zip](https://github.com/opentoonz/opentoonz/files/2643738/Edgar.zip)

**Comment by Therippersart** [comment] 2018-12-04 13:00
Thanks. 80% is better than nothing...

**Comment by artisteacher** [comment] 2018-12-04 15:46
There are a few ways:
1. You could go to the Browser room and find the levels in the relevant folders in the old project (they are likely in the "drawing" and/or "extras" folders). Shift-click or Ctrl-click (CMD-click on MacOS) to select all the levels you need in the folder, then right-click and select "load". Then choose import or load - I would probably import 

2. In your new scene (in the new project), right-click on an empty cell in the Xsheet and select "Load Level". Then use the browser to find your levels and select all the needed levels in the folder to import.  Select either load or apply (apply is a better choice if you need to import from multiple folders as it will leave the loading window open). Then choose to load or import - repeat as necessary 

3. You can also drag and drop the levels into the Viewer or Xsheet/Timeline from your computer's file browser or etc.

**Comment by RodneyBaker** [comment] 2018-12-05 00:51
@Therippersart I think this is as far as we can take this.
Please let us know how things turn out.

Also, keep in mind that there other resources available to assist with troubleshooting.

The OpenToonz forum has a Troubleshooting area that can be used to explore problems.
Similarly there are several OpenToonz discords (chatrooms) where live assistance can be found and others OpenToonz users are able to assist in recovering data.

Links:
OpenToonz Troubleshooting forum:
https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting

OpenToonz Discords: https://discord.gg/xjZsAfu or https://discord.gg/JA292SR

Closing this issue.

**Closed by RodneyBaker** 2018-12-05 00:51 UTC

**Comment by madisomlok** [comment] 2021-03-06 14:49
i have the same problem with OpenToonz too Anyone can help?

**Comment by Ghanshan** [comment] 2022-01-30 19:41
me to

**Comment by RodneyBaker** [comment] 2022-01-30 21:25
@Ghanshan If you can provide additional information... project files etc. that will go a long way toward resolving your issue.
Short of that we are mostly limited to suggesting the standard remedies such as making sure you are using the latest nightly release and (assuming the image levels still remain) rebuilding the scene using those levels.
