### ISSUE TITLE
its coming again

### ISSUE THREAD

**Issue by TestTime3000** [opentoonz/opentoonz#4818] opened 2023-04-09 22:50 UTC
### Description

OpenToonz 1.6  (Build Mar 14 2023)

Report Date: 2023-04-10 01:47:22
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 528.24

Crash File: C:\Users\machi\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230410-014722.log
Mini Dump File: C:\Users\machi\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230410-014722.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: untitled16
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\Users\machi\AppData\Local\OpenToonz\OpenToonz\cache\temp\untitled16\untitled16.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\bcrypt.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\System32\CRYPT32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_d1bd230cd08e7436\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\system32\wintab32.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\System32\fwpuclnt.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7fff86a48b4c] <ntdll.dll>
  2> RtlRaiseException [0x7fff86a212c6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff86a70f4e] <ntdll.dll>
  4> QObject::isWidgetType [0x7fff56229a74] <Qt5Core.dll>
  5> QWidgetPrivate::showChildren [0x7fff55d29f9d] <Qt5Widgets.dll>
  6> QWidgetPrivate::show_helper [0x7fff55d2a2a4] <Qt5Widgets.dll>
  7> QWidgetPrivate::setVisible [0x7fff55d287b8] <Qt5Widgets.dll>
  8> QWidget::setVisible [0x7fff55d2855e] <Qt5Widgets.dll>
  9> QWidgetPrivate::showChildren [0x7fff55d2a0da] <Qt5Widgets.dll>
 10> QWidgetPrivate::show_helper [0x7fff55d2a2a4] <Qt5Widgets.dll>
 11> QWidgetPrivate::setVisible [0x7fff55d287b8] <Qt5Widgets.dll>
 12> QWidget::setVisible [0x7fff55d2855e] <Qt5Widgets.dll>
 13> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6c9ab4c62] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6c9ede4e7] <OpenToonz.exe>
 15> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6c9eddac2] <OpenToonz.exe>
 16> BaseThreadInitThunk [0x7fff84df7614] <KERNEL32.DLL>
 17> RtlUserThreadStart [0x7fff86a226a1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment] 2023-04-10 00:46
Closing as a duplicate of previous report.

**Closed by RodneyBaker** 2023-04-10 00:46 UTC
Labels: bug
