### ISSUE TITLE
Closed vector shape is unfillable

### ISSUE THREAD

**Issue by mcjadski** [opentoonz/opentoonz#1093] opened 2017-03-10 01:14 UTC
On Win 7, I did some experimenting with [unfillable.zip](https://github.com/opentoonz/opentoonz/files/816428/unfillable.zip) , courtesy of @shun-iwasawa.  For reference, here's the starting position.  The left region is indeed unfillable;  I left the fill-check off for the following screenshots, as it's quite interesting what happens.

![unfillable_start](https://cloud.githubusercontent.com/assets/25377429/23776461/1d95a764-04f4-11e7-8f45-f3287dd6d780.jpg)

If you adjust the angle of one of the handles like this, the fill swaps to the other region!  (The color is whatever color you had in the other region.)  

![unfillable_swap](https://cloud.githubusercontent.com/assets/25377429/23776547/9ccf494a-04f4-11e7-9bf6-030ec93d54e5.jpg)

If you adjust it to this position, the whole thing becomes unfillable:  

![unfillable_none](https://cloud.githubusercontent.com/assets/25377429/23776599/d5ed768e-04f4-11e7-819c-89db66179159.jpg)

Here, the whole thing becomes filled!  I didn't fill it, it just became all the one color:  

![unfillable_all](https://cloud.githubusercontent.com/assets/25377429/23776627/033b1dc6-04f5-11e7-8811-cfb7c64ce5f7.jpg)

You can color them differently then:  

![unfillable_different](https://cloud.githubusercontent.com/assets/25377429/23776637/141f25f6-04f5-11e7-9b79-273b6bb255dc.jpg)

As you tweek it slightly, the left region will sometimes flash between filled and not filled.  (NOTE:  If you color the left region red, then tweek it so the left region becomes unfilled, then tweek it so it becomes filled again, it will be black, not red.)  

![unfillable_near_all](https://cloud.githubusercontent.com/assets/25377429/23776685/63ea290a-04f5-11e7-9e99-e52df2016f22.jpg)

Making the image large using the Edit Tool has no effect:  

![unfillable_big_edit](https://cloud.githubusercontent.com/assets/25377429/23776694/7379a9fe-04f5-11e7-9bd9-5c7d69c937f6.jpg)

However, making it bigger with the Selection Tool makes the whole thing filled:  

![unfillable_big_selection](https://cloud.githubusercontent.com/assets/25377429/23776705/85fac4dc-04f5-11e7-9dc4-15049db91f59.jpg)

Moving it around with either tool seems to have no effect.

**Comment by shun-iwasawa** [comment] 2017-03-16 09:23
I have not yet solved this problem, but will write my findings so far.

Please try to build&run OpenToonz in debug mode. In only the debug mode, OpenToonz displays auto-closes for vector images with green lines. (It must be for checking purpose and is processed at [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/tvrender/tglregions.cpp#L582-L584) ) 

Looking at the unfillable example, you can find a tiny green line connecting the endpoints of the stroke.

<img src="https://cloud.githubusercontent.com/assets/17974955/23986024/6dfa739e-0a65-11e7-8293-1b50674529ef.png" width=500>

Now, select the Control Point Editor Tool and adjust the stroke. At some point, you can find that another green line suddenly appears at the intersection.

<img src="https://cloud.githubusercontent.com/assets/17974955/23986886/d6a5b13e-0a69-11e7-84cc-fb84d8f4d638.gif" width=500>

As you can guess, having this - the autoclose at intersection - is the condition to make the image properly-fillable.
 
<img src="https://cloud.githubusercontent.com/assets/17974955/23986814/770b013e-0a69-11e7-8c34-9074caa3c23a.gif" width=500>

This autoclose line seems to connect between specific points placed at regular intervals on the stroke.

<img src="https://cloud.githubusercontent.com/assets/17974955/23987389/bcdb0706-0a6c-11e7-8c85-6b5a84753c7c.gif" width=500>

The autoclosing procedure starts [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/tvectorimage/tcomputeregions.cpp#L1889) in `tcomputeregions.cpp`, and the interval between evenly-spaced points along the stroke is "5" for now, defined at [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/tvectorimage/tl2lautocloser.cpp#L110) in `tl2lautocloser.cpp`. The unit of this value is 1/53.33333 inch.

(@mcjadski found that making the shape bigger with the Selection tool  makes the whole thing filled. IMO this is because as the shape becomes bigger, the point distribution is changed and incidentally it could find the pair of points to autoclose.)

The autoclosing at the intersection is only needed if the intersection is made of the same segment of the same stroke. If you cut the stroke at some point with Cutter tool and make the intersection to two strokes, it becomes fillable without autoclosing.

<img src="https://cloud.githubusercontent.com/assets/17974955/23988113/2cdee5ba-0a70-11e7-8956-9d6e76cad8b3.gif" width=500>

Or even if you add a control point on the stroke and make the intersection to of different segments of the same stroke, it becomes fillable without autoclosing as well. (It seems that you need to change the shape slightly after adding the point in order to update region or something.)

<img src="https://cloud.githubusercontent.com/assets/17974955/23989173/db82328a-0a74-11e7-86e4-eafad126ec9c.gif" width=500>



SO, WHAT SHOULD WE DO TO FIX THIS?

I'm not yet find the best way to fix it. What we want is to separate the regions at intersections under any conditions somehow.
Changing the the interval of the "stroke points" to smaller value AND/OR changing the threshold between points to make the connection may gain the possibility to autoclose properly, but I'm not sure this can completely fix the problem and free of untoward effects.

**Comment by turtletooth** [comment] 2017-07-02 06:32
I played with it a bit and setting tl2lautocloser.cpp inc to 3 is enough to make this image work.  Do you see any downside to changing that value?

**Comment by turtletooth** [comment] 2017-07-05 19:32
#1317 Fixes this without changing the tl2autoclose value.

**Comment by mcjadski** [comment] 2017-07-13 23:14
Allowing users to choose the fillable gap size is a very helpful feature to have, but I'm not sure it completely solve the problem here. 

The frustration that arises with the vector fill issues results from the feeling that the program seems to be behaving in an arbitrary way.  If you have a 100% closed shape, you expect the shape to be fillable all the time, no matter what the gap size is set for.  

This shape, for instance, is completely closed, so a user will think the program is glitching out if it's unfillable, no matter what the settings:  

![unfillable_none](https://cloud.githubusercontent.com/assets/25377429/23776599/d5ed768e-04f4-11e7-819c-89db66179159.jpg)

It sounds like the real problem here is that OT doesn't know how to handle a single, unbroken stroke intersecting itself in a particular way.  The new feature @turtletooth added is a nice addition, but I think ultimately we'll have to find some way to fix the underlying problem.

**Comment by Orphanlast** [comment] 2018-01-14 09:30
I know the frustration you're having. But efforts have been made to fix this problem in the past. Such as "Convert to simplified vectors" -- and other meathods that @Turtletooth has has put into place. Although they do resolve coloring issues, the simplified vectors destroy "guided vector drawing" and ultimately they boil down to being a bandaid on a bigger problem. You adjust a vector that's been colored, and it'll recolor your entire frame. CTRL+Z only works something like 10% of the time, in order to fix the problem. So NOT being able to reproduce the desired effect makes it hard for developers to fix the problem.

Might I propose a new way to resolve this problem, and seeing as this bounty has recieved no donations, probably because developers see that resolving this problem head on is a lost cause, I think there's a way to side step the issue.

I know that on Toon Boom they have a color layer that you can link to your line work. It'd be interesting to have something like that. This way we don't make redundancy with a vector level for the line work, and a toonz raster level for the coloring that ALSO needs to include all of the line work in it. The reason why the current meathod is irritating is, suppose you realize, now that there's color, some lines need adjusting. You adjust you vector level, then you need to either restart completely with your toonz raster level, or redraw those adjustments onto your toonz raster level. So... you do the same task twice.

A linked color level would be great and here's why:

1.) If you create a toonz raster level and link it to your cleaned up vector line work, you can color it with ease and if the line work needs adjusting, you adjust the lines in one task. If the fill tool was used, the linked toonz raster level will record where the fill was placed and then adjust the fill automatically.

2.) If you use a vector level and link it to your vector line work, you gan get the crisp results of vector coloring. Although your vector line work level may not be simplified vectors, maybe the linked vector color level can interperate the lines as simplified vectors. When you use the fill tool, an indicator can show where you placed the fill (like the frame range indicator). This way, if you adjust lines, maybe it won't bug out. It'll remember the location the fill was placed. Your vector line work isn't simplified vectors, you can still use "vector guided drawing" on your vector line work, still, yet the linked vector level will INTERPERET the lines as simplified vectors.

Please keep in mind, I'm not suggesting making two new types of levels. I'm suggesting the ability to link.

I'm sorry, I can't find a toon boom link to illustate my point.

**Comment by tushantin** [comment] 2018-01-29 16:37
@Orphanlast I think I understand what you're saying, although I suppose Synfig does this far better IMO in the sense that it not only links to the Vector Regions layer with Vector Outlines layer, but it also links their respective nodes with each other in the exact position! So, if you move / edit / delete the node of one layer around you also move / edit / delete the node of the other layer. 

The only problem is that Synfig's vector system doesn't allow for tablet-drawing then Fill-Tooling in an organic fashion, which OT is meant to do, so you'd need to figure out how to code that in.

**Comment by jpturcotte** [comment] 2018-01-29 19:24
@Orphanlast & @tushantin Seeing that Synfig is also maintained by @morevnaproject & @blackwarthog, maybe they would be interested in a bounty?

**Closed** 2018-03-07 06:09 UTC
Labels: Bug
