### ISSUE TITLE
Insert Frame + Key.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2652] opened 2019-06-29 10:55 UTC
I think this is a bug.

### Actual Results

![ezgif-1-3310aee68f22](https://user-images.githubusercontent.com/25724133/60383073-1246ed00-9a75-11e9-9e23-3f3a1a230de5.gif)

### Expected Results

![ezgif-1-f6ef73b35667](https://user-images.githubusercontent.com/25724133/60383076-1b37be80-9a75-11e9-9359-784ec7b91c62.gif)

### System Information
* **OpenToonz Version**:  latest
* **Operating System**:  Windows 8.1

**Comment by manongjohn** [comment] 2019-09-24 18:11
Keep in mind that `Insert Frame` is a bit misleading because it is basically means `Insert "Scene" Frame`.  This would add a new frame on that row for every level in the xsheet (unless locked ofcourse). It's not inserting it after the selected row. It's essentially adding it above/before it.

Based on that, I would expect it to push everything down from that row forward, including the keys. otherwise it may mess up timing on other levels.

For this reason I don't consider this a bug.

I guess what makes it seem strange is that when the frame is inserted, the frame that was there just gets extended. Perhaps what should happen is it extends the previous frame if there is one or adds a blank frame if there isn't.  So in your example, if you are inserting at Scene Frame 1, it should have put a blank in there instead because there is no previous frame to extend, but when inserting later, then the previous frame, regardless if it's the same one or a different one should be extended.

My 2 cents.

**Comment by beeheemooth** [comment] 2019-09-24 19:56
@manongjohn If a direct solution to this problem is so complicated, can it simply indicate to the "Insert Frame" function that it should move the keys starting from the next frame (current frame +1)?

**Comment by RodneyBaker** [comment] 2019-11-20 13:40
Closing this as all appears to be working as designed.
Discussion of how to improve the current implementation of 'Insert Frame' and 'Remove Frame' can continue in this report.

**Closed by RodneyBaker** 2019-11-20 13:40 UTC
Labels: Enhancement
