### ISSUE TITLE
Error upon launch (Windows 10)

### ISSUE THREAD

**Issue by Tyrvde** [opentoonz/opentoonz#165] opened 2016-04-13 00:30 UTC
OpenToonz stopped working upon launch. It seems to be a common error, so I ran it through Visual Studio's debugger and this is what I've found. Hopefully it can shed a bit of light on the situation. 
![debug_opentoonz](https://cloud.githubusercontent.com/assets/16713353/14479514/1045155e-00e5-11e6-9b02-c6333bebdc71.PNG)

**Comment by Tyrvde** [comment] 2016-04-13 00:37
Also noted is that the error persists after running under Windows 7/8 compatability mode, both as an Administrator and without said privledges.

**Comment by ss23** [comment] 2016-04-14 21:58
@Tyrvde It's hard to tell exactly what the problem is just based on that, but since it's qt based, I've compiled a version of opentoonz with a newer version of qt.

Are you able to try downloading and running https://github.com/ss23/opentoonz/releases/download/qt56/OpenToonz-qt5.6.7z? It's a 7zip archive, but once extracted, you should be able to run it in place.

If it works, it may point to one of the issues that was fixed with Windows 10 on qt5.6.

**Comment by kogaki** [comment] 2016-05-19 07:39
Now we are building with Qt5.6 and this seems to be fixed

**Closed by kogaki** 2016-05-19 07:39 UTC
