### ISSUE TITLE
Plastic Tool:  Extra (fixed) bone

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#214] opened 2016-04-21 22:36 UTC
It's hard to explain, so here we go.

On the picture bellow I have 3 shapes. Middle one (BLUE) I want to turn into plastic and to connect with red and green shape. When I turn blue shape into plastic I get bone for that shape fixed in the center of the peg and it's staying there. If I detach that bone from the center, plastic mesh will detach as well from that shape. 
So, I can't re-position that bone which means it can not be deformed properly. In the next example it is more clear what I mean. 

![capture](https://cloud.githubusercontent.com/assets/18187104/14726061/d7ccb492-081f-11e6-9968-441980d43e1f.PNG)

---

In this scenario, first I create shapes and connect them with the bones, and that looks how it should.

![capture 2 1](https://cloud.githubusercontent.com/assets/18187104/14726157/842ab464-0820-11e6-82da-09fcd1069ed0.PNG)

After that, I select the blue shape and turn it to plastic. Here again I get extra bone which "belongs" to plastic shape but if you detach it, Plastic mesh will be separated from blue shape. This way you can't do proper forward kinemtic movement because pivot is fixed in the center.

![capture 2 1 1](https://cloud.githubusercontent.com/assets/18187104/14726226/fd1fb8f6-0820-11e6-97af-9e13080d20c2.PNG)

It's weird why this bone is even there with no option to be moved around without loosing the connection between plastic mesh and shape.

**Comment by BrundleThwaite** [comment] 2016-04-22 00:19
Sorry but this is not a bug

You make the bones for the plastic rig with the plastic tool after you have made the mesh the option to create a rig should become available under the plastic tool.

The skeleton tool is not used with the plastic tool at all.

**Comment by psychoanima** [comment] 2016-04-22 10:00
I know that plastic has it's own bones (rig), but it's on a separate layer, why is destroying bones on object (blue rectangle in my example) that is related with that mesh layer? This way I am loosing IK chain like on the last picture in my post.

In thought that plastic should serve as a muscle attached to regular bones, without destroying connection between them. 

I know how plastic linking is working, and this post is not about that. That feature works perfectly since they enable it.

**Comment by BrundleThwaite** [comment] 2016-04-22 10:31
Unfortunately it does not work that way in order to get that effect (The muscle effect) you would have to make the skeleton with Dummy and attach the column and plastic node to the Dummy column. I is not really workable the two do not work well together so you have to loose IK when you use plastic maybe at some point they will do IK chains and curves in the plastic toll but at the moment this is just a limitations that you have to live with.

![untitled-1](https://cloud.githubusercontent.com/assets/18170954/14739141/efd0e73c-0885-11e6-90d5-791b02a04f11.png)

If you want at some time in the future I could make a tutorial on how to get this working but it will only be in a couple of weeks time.

**Comment by psychoanima** [comment] 2016-04-22 10:46
I see. Thanks for your reply, it helped me a lot to understand how things are working here (I am Anime Studio Pro user, it takes time to swallow Toonz logic).

Well, then what I thought is a bug should be actually renamed into feature request.

**Comment by blurymind** [comment] 2016-04-22 13:11
not a bug. Here is how you can set it up:
![inheritrotationofbone](https://cloud.githubusercontent.com/assets/6495061/14742109/6d3339e4-0892-11e6-83e3-5dec87b5bed9.PNG)

However there is one thing that will cause you grief. The level that is parented to the mesh bone (hand) will not inherit the rotation of the bone. Instead it will only translate with it. In this case we would want it to translate and rotate, but opentoonz does not seem to have a way of setting it up that way.

Sorry for the crude drawing. Here I filed a feature request here:
https://github.com/opentoonz/opentoonz/issues/218

Please let me know if there already is a way to do this and I will close it.

**Comment by Juls3000** [comment] 2016-05-02 15:52
Now with v1.0.2 you can use expressions: 
https://drive.google.com/file/d/0B2HN_Ev_1daYd3hOeDRzbWtucnM/view?usp=sharing

explained here (video #3):
https://workflowy.com/s/JtI13Zub8a#/f9e62b0143ee

**Comment by blurymind** [comment] 2016-05-02 16:23
The expression to copy rotation will not be very useful in this case. I
explained why here:

https://github.com/opentoonz/opentoonz/issues/218#issuecomment-216224814

**Comment by Juls3000** [comment] 2016-05-02 18:29
I aswer there https://github.com/opentoonz/opentoonz/issues/218#issuecomment-216224814

**Comment by blurymind** [comment] 2016-05-02 20:01
Doesnt solve the problem - you still counter animate. The solution is not to attach to bones that way until someone improves it or comes up with a better expression. Copying rotations does not solve it.

**Comment by RodneyBaker** [comment] 2018-05-20 13:54
@psychoanima   As this issue is rather ancient, can you give us an update on the current status of this and if you are still experiencing the same issue?

**Comment by psychoanima** [comment] 2018-05-21 10:39
Hey @RodneyBaker ! Forward kinematic movement combined with plastic shape works OK now! 

However, that "extra" bone that belongs to plastic is now only making problems during Inverse kinematic movement - they can't be combined.

**Comment by RodneyBaker** [comment] 2018-11-06 02:37
I'm tempted to suggest this issue be given the 'Won't Fix' tag but perhaps that is too extreme.
Can this report be reviewed with an eye to make it less of a feature request?
There doesn't appear to be anything that isn't operating as designed here.

**Comment by RodneyBaker** [comment] 2018-12-17 22:43
Closing as any development/resolution of this will likely be in 2019 and beyond with a scrub of Plastic Tool workflow in its entirety.

**Closed by RodneyBaker** 2018-12-17 22:43 UTC
Labels: Bug, Enhancement
