### ISSUE TITLE
Randomly adds non-erasible black lines

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1869] opened 2018-03-13 14:23 UTC
Whenever I right click, it leaves random non erasable black lines. I'm on the newest Morevna Edition. Any help?

**Comment by artisteacher** [comment] 2018-03-13 18:19
Does this happen with every level type? Are you using a tablet or mouse?

**Comment by nisfinx** [comment] 2018-03-15 16:13
It happens with both, mouse and tablet. And I don't know about level types :P

**Comment by artisteacher** [comment] 2018-03-15 18:16
When you look at the level in the Xsheet or Timeline:
Vector = the mustard yellow color
Toonz Raster = green color
Raster = the blue color

**Comment by nisfinx** [comment] 2018-03-15 18:19
It's green. The Toonz Raster I guess then. Should it be on that?

**Comment by shun-iwasawa** [comment] 2018-03-16 02:48
> non erasable 

It sounds like that the problem is not due to unexpected behavior of drawing tools ( like #1781 ) but may be related to more fundamental graphics ( such as failure in refreshing the viewer ).
@nisfinx can you please post a screen snapshot showing the lines?

**Comment by nisfinx** [comment] 2018-03-17 03:28
I'll try. I don't know what MyPaint and Toonz levels are though. I've obly been using the green ones.

**Comment by nisfinx** [comment] 2018-03-22 16:12
I can't get a photo because of certain difficulties. Sorry. Hopefully you understand what I mean by black lines. Maybe they follow the path of my mouse just before I right-click? The seem to be there and I can't undo them either. It's like they're printed on the screen itself. I can't access OpenToonz easily as of now but, soon, will. I just hope the bug is fixed by then :D. Anyway, I hope you understand I mean!

**Comment by nisfinx** [comment] 2018-04-22 20:42
Just tried it again and found it only happens with my tablet. Still not sure why though. It seems as if it's thinking I'm pressing buttons when I'm not. I'm using Mac and when I right click with the tablet plugged in, the "Edit" part of the top bar flashes blue multiple times, indicating that a shorcut to that place has been pressed so many times. And about the black lines, I think it just traces back to where my curser was a few seconds before and thinks that my press was supposed to be when I moved my curser. I still don't know why I can't undo or rub out any of these events or why it only happens when my tablet is plugged in. Coming to think of it, it's probably just my tablet. I have the Huion H420 drawing tablet. Thanks for your help!

**Comment by artisteacher** [comment] 2018-04-23 11:54
@nisfinx what version of OT are you using? There have been a lot of issues using tablets on Macs but some of them have been resolved in the [latest nightly builds](https://github.com/opentoonz/opentoonz/releases/tag/nightly). It's definitely not perfect, but the unintended brush strokes that I've gotten are at least erasable.

**Comment by nisfinx** [comment] 2018-04-23 17:29
Ok thanks. I'll try one of the nightly builds. Hopefully it works!

**Comment by RodneyBaker** [comment] 2018-10-13 02:41
The user @ghost is no longer active (deleted user)
The problem is also very likely resolved.

Recommend closing.

**Closed** 2018-11-30 06:47 UTC
