### ISSUE TITLE
Some toolbar icons are too large and cropped

### ISSUE THREAD

**Issue by Efenstor** [opentoonz/opentoonz#3759] opened 2021-03-13 17:59 UTC
With the latest master, on a HiDPI monitor, having QT_AUTO_SCREEN_SCALE_FACTOR=1 or QT_SCALE_FACTOR=2, some of the toolbar icons do not fit onto the buttons. The system is Debian Buster with MATE + all the backports.

![Screenshot at 2021-03-14 00-53-12](https://user-images.githubusercontent.com/11175574/111039265-b0ecca80-845f-11eb-8cb3-948a47f0bdaa.png)

**Comment by konero** [comment] 2021-03-13 19:36
I tried fixing Hdpi icons here https://github.com/opentoonz/opentoonz/pull/3742 which could have introduced the problem. I could only borrow a Hdpi monitor, and could only test on Windows 10, other users confirmed it fixed it on their end (all Windows I think). Possible the icons need to be set to scale in QPainter, but there's no way for me to fix this without a Hdpi monitor I'm afraid.

**Comment by Efenstor** [comment] 2021-03-13 19:53
Try "QT_SCALE_FACTOR=2 opentoonz". I temporary switched to 1920x1080 and lo-dpi fonts, tried it and it worked. Of course, everything will be huge but at least you can see and hopefully fix the issue.

**Comment by shun-iwasawa** [comment] 2021-03-13 23:27
I tried running the following lines on Command Prompt on Win10:
```
> set QT_SCALE_FACTOR=2
> OpenToonz.exe
```

And (unfortunately) the issue seems not to be represented.
![image](https://user-images.githubusercontent.com/17974955/111052504-96861180-849e-11eb-9734-0556dd215934.png)

Please note that I put another OT window with regular scale side-by-side for comparison.

**Comment by konero** [comment] 2021-03-14 01:38
@shun-iwasawa  I tried on Ubuntu and there's an issue. I installed through VMWare and set the display scaling to 200%

Seems to be happening to the icons I changed to 16x16 recently, but also happens to all icons on the FX nodes already, I've spent a couple hours trying to figure it out but it doesn't make sense. The Schematic window is a good example, in red are the icons that changed to 16x16, the ones in blue are 20x20 and ones I didn't change at all. So what is different here?

![image](https://user-images.githubusercontent.com/19820721/111053244-08883780-845a-11eb-9eac-74bf771f3eae.png)

They look like they scale up by the scale factor amount.

- It happens to menu icons (16x16)
- Command bar icons (only to the 16x16 icons that get composited onto a 20x20 QRect) 🔗 [see here](https://github.com/opentoonz/opentoonz/pull/3742/files#diff-d457a1a8b38387954a0c6b8cc0c484ab8d0c36a0fc9ea610abe1fba4d3965005R365-R367).

I used Affinity Designer, their SVG export gets updated so much on each release it could be the problem. I compared XML of an icon I didn't change like [brush.svg](https://github.com/opentoonz/opentoonz/blame/master/toonz/sources/toonz/icons/dark/tools/20/brush.svg), to one I did like [actual_pixel_size.svg](https://github.com/opentoonz/opentoonz/blame/master/toonz/sources/toonz/icons/dark/actions/16/actual_pixel_size.svg) but nothing is revealed to me.

Possible `createQIcon` requires something, or I didn't do it in a very efficient way, I think it needs a second opinion since it got merged so fast. Really hard to resolve, since I've got no experience building on Linux. But I tested exporting an SVG from InkScape, recreating one from scratch, re-using one of the toolbar icons that render correctly as a template, and testing with a Git artifact, but they all wrongly scale, it's very strange.

**Comment by konero** [comment] 2021-03-15 21:15
So I believe the problem is narrowed down to `compositePixmap()` function, the SVGs are fine. Sorry, I tried but I don't know enough about Qt's Hdpi methods to solve this. Sorry to trouble you @shun-iwasawa, I think the icon generator needs to be re-written by someone who knows their stuff. 🙏 

In Windows, you can break the same icons by setting `set QT_SCALE_FACTOR=1.25` for testing, except they will be small, not enlarged. But you might (I'm really not sure) might want to work with devicePixelRatio that returns float instead of int, since with int 1.25 scale still returns 1, you can do that using:

``` c++
QScreen *screen = QApplication::primaryScreen();
const qreal dpr = screen->devicePixelRatio();
```

I'll outline what I discovered and what my intention was with my previous fix.

Before merging #3742, icons that were resized down to 16x16 looked pixelated when upscaled to fit in a 20x20 tool button. This image is at `2x devicePixelRatio`, notice the icons look out of focus and somewhat fuzzy. They're also a little too big. This is due to extracting the pixmap from the QIcon::fromTheme, because returning just the QIcon results in a smooth image, except it's still a bit too big, and we can't adjust the pixmap, of course.

![image](https://user-images.githubusercontent.com/19820721/111216766-b6b3ee80-85cc-11eb-8140-08469e7fbe45.png)

How I intended to solve this to prevent the upscaling was to draw the icon onto a bigger pixmap, I did it using QRect. This is loaded into the icon along with the original 16x16 icon, so Qt can decide which to use. Which solved that problem, but has produced the new problem on Linux.

![image](https://user-images.githubusercontent.com/19820721/111216024-caab2080-85cb-11eb-8459-9fb30ef7f538.png) ![image](https://user-images.githubusercontent.com/19820721/111216792-c2071a00-85cc-11eb-81a2-a9a1302ef4c6.png)

I found that using QSvgRenderer and rendering the SVG to a QImage, then composing that onto a bigger QImage and offsetting it produced a good result on Linux and technically fixes this issue. But then the problem of how to load the icon files, we would need to dump them into the same folder and no longer use GNOME specs, which is not a big issue.

``` c++
// Path to file, can swap theme (as a folder) here
QString path = QString(":/icons/dark/") + iconSVGName ".svg";

// Render SVG to QImage
QSvgRenderer renderer(path);
QImage img(iconSize * dpr, iconSize * dpr, QImage::Format_ARGB32);
img.fill(Qt::transparent);
QPainter p(&img);
p.setRenderHint(QPainter::Antialiasing, true);
p.renderer.render(&p);
p.end();

// Set the size of the QImage to act as the buffer zone around the SVG if it's 16x16
int destinationW = 20;
int destinationH = 20;

QImage destination(destinationW * dpr, destinationH * dpr, QImage::Format_ARGB32);
p.begin(&combined);
p.drawImage(2 * dpr, 2 * dpr, img);
p.end();

QPixmap pm = QPixmap::fromImage(destination);

QIcon icon;
icon.addPixmap(pm);

return icon;
```

There's also a method that could paint icons with good antialiasing, it's [`QIcon::paint`](https://doc.qt.io/qt-5/qicon.html#paint), but it's not something I was successful at implementing, but others assured me it would probably solve a lot of issues and linked me to this thread with an answer: https://forum.qt.io/topic/113319/how-to-draw-pixmap-with-same-anti-alias-quality-as-qpushbutton-icon/17

But, the problem does lay within `compositePixmap()`, I would hope it's a simple fix here of me miscalculating the devicePixelRatio.

Sorry for the trouble, it's not something I know how to fix. 😩

**Comment by shun-iwasawa** [comment] 2021-03-15 21:23
Thank you @konero for the deep investigation, it's very helpful. I'll look into this and try to fix after releasing v1.5 RC.

**Comment by konero** [comment] 2021-03-22 01:34
Just an update, seems some Windows users are running into this problem with 1.5rc. Seems to be that if you have multiple displays connected, like primary 4K (200%/300% scale) and have OpenToonz on a secondary 2K display.

Not sure if this helps, but this is what happens at different scale factors on Windows for reference:

1.0
![image](https://user-images.githubusercontent.com/19820721/111929264-c42a1680-8aad-11eb-8030-7b7bf25c5d64.png)

1.25
![image](https://user-images.githubusercontent.com/19820721/111928458-9217b500-8aab-11eb-8970-173eeb5f5bfa.png)

1.50
![image](https://user-images.githubusercontent.com/19820721/111928490-abb8fc80-8aab-11eb-980f-574eab426adf.png)

1.75
![image](https://user-images.githubusercontent.com/19820721/111928513-c25f5380-8aab-11eb-8f58-d69d9ecb9612.png)

2.0
![image](https://user-images.githubusercontent.com/19820721/111928539-d6a35080-8aab-11eb-9642-d90332b1da5b.png)

2.5
![image](https://user-images.githubusercontent.com/19820721/111928569-eae74d80-8aab-11eb-99cb-64db6a1fb33b.png)

And problematic icons have these values passed:

https://github.com/opentoonz/opentoonz/blob/96a86d9e5d1c2a595c31af274cbd7bec810a5810/toonz/sources/toonzqt/gutil.cpp#L365-L373

**Comment by konero** [comment] 2021-03-23 11:58
@shun-iwasawa I got a Linux environment setup for building and I got a fix for this, I know what's wrong now I think, if you haven't worked on it already I'll post a PR assuming it works under Windows, I'm still testing it, I'll do it later today hopefully. 😆 

`QIcon::fromTheme()` was returning a pixmap with **_double_** the devicePixelRatio, so at 200% it was returning 400%. I tested in Qt Creator and got the same result, I didn't figure out why, but it's a Qt class so I'm ignoring it.

So when I tried to paint it onto a 20x20 pixmap, a 16x16 pixmap was actually 64x64 (at 2x scale) which is why we only see the one quarter of the image (it should be 32x32).

To workaround it, by setting devicePixelRatio to the pixmap manually and scaling it, we get the correct sizes.

I'll remove `compositePixmap()` and just modify `setOpacity()` to accept a size since it's already composing two images, that will probably do until rewriting the entire engine is worth the time.

**Comment by shun-iwasawa** [comment] 2021-03-23 14:02
Thank you @konero , I haven't tackled with this and your fix will be much appreciated!

> QIcon::fromTheme() was returning a pixmap with double the devicePixelRatio, so at 200% it was returning 400%. I tested in Qt Creator and got the same result, I didn't figure out why, but it's a Qt class so I'm ignoring it.

I'm not 100% sure but setting `Qt::AA_UseHighDpiPixmaps` [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/main.cpp#L399-L400) may be related.

**Closed** 2021-03-29 00:40 UTC
