### ISSUE TITLE
Level replaced (filenaming issue?)

### ISSUE THREAD

**Issue by memyselfaneye** [opentoonz/opentoonz#3203] opened 2020-04-01 13:46 UTC
### Issue Summary
After dragging a level "Flügel.pli" from the finder into a scene, the column with "Butterfly.pli" was automatically replaced with another column present in the scene (I don't remember the name, I thin it was something like  "Butty Flügel" ...). I lost the whole level "Butterfly.pli", it now contains the drawings from "Butty Flügel". A whole day's work :/ If I search in the finder, the butterfly.pli now contains the butterfly's wings.

### Screenshot or Video Reference
The blue bubbles to the right are the imported wings for the bee in col6, imported with the same method before - dragging from the finder. In the schematic you can see that the wings were connected to the body of the butterfly.
<img width="234" alt="image" src="https://user-images.githubusercontent.com/62648150/78144002-506fa380-742f-11ea-9b15-ea26ad162a8b.png">
<img width="769" alt="image" src="https://user-images.githubusercontent.com/62648150/78145843-ae9d8600-7431-11ea-8e80-78d6d9992771.png">

Where the body of the insect is supposed to be, there's now a copy of the wings:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/62648150/78144762-50bc6e80-7430-11ea-93e9-4ac27ffc09b8.png">

### Steps to Reproduce
Drag an existing level from the finder to the columns ...

### Expected Results
import the dragged level (which happened) without erasing other levels.

### Actual Results
A whole level was replaced by another one. I cannot see how this is related to dragging a pli file with a different name into the scene...

### System Information
* **OpenToonz Version**: 1.4
* **Operating System**: Mac OS 10.15.3
* **CPU**: Intel i5
* **Memory**: 8GB
* **Graphics Card**: Intel
* **Graphics Tablet**: none

**Comment by artisteacher** [comment] 2020-04-01 14:12
Weird. I've lost levels before on macOS but they've been deleted, not overwritten. I don't tend to use drag & drop in OT though - maybe that's the problem? I'll experiment later and see if I can trigger this too.

I would check in Finder to see if you have any backups of the original pli in the project's Drawings folder. It would likely be butterfly.pli.bak. Try renaming it to a new name (ie. butterfly-new.pli). You might be lucky and be able to recover the original that way. For now, you might want to load through right-clicking in the Xsheet or in the Browser room instead of drag & drop.

Personally, I like to keep the number of backups set to 2 in preferences, in case levels get lost. The default is 1, I think.

**Comment by memyselfaneye** [comment] 2020-04-01 14:26
Thanks for your reply Aristeacher. I already tried the backup, but it contains the same wings … I’m dragging from the finder because the internal file browser always crashes when trying to acces the drawings folder. I switched on auto-save because of the many crashes which seems to have overwritten the pli and the pli.bak files … I did not expect to loose a whole bunch of drawings... I’m certainly quite demotivated for now… Thanks for the preferences tip on several backups!

**Comment by artisteacher** [comment] 2020-04-01 14:59
That's too bad. You must have a corrupt file in the drawings folder, if accessing it in the internal file browser results in a crash. Does list view vs icon view in the browser have any impact?

You could remove all of the drawings from the folder and return them individually, until you find the problem file.

**Comment by RodneyBaker** [comment] 2020-04-01 16:42
I note that the names "Flügel.pli" and "Butty Flügel" have some non standard characters.
This seems to be a likely suspect as there have been problems of that kind reported in the past.

**Comment by memyselfaneye** [comment] 2020-04-01 17:37
At least I found the corrupt pli file … the internal browser works now! Thanks again!

**Comment by memyselfaneye** [comment] 2020-04-01 17:37
Must be because of its name! :’o)

**Comment by RodneyBaker** [comment] 2020-04-01 21:26
I've temporarily renamed the topic title pending more validation on what the problem might be.
Feel free to adjust the title as necessary. 

There is likely a report open for that aspect already and we may never know the cause for this short of you being able to take the time to investigate.  If you do find some free time and can investigate your feedback will be very useful and appreciated.

**Comment by RodneyBaker** [comment] 2022-02-17 13:44
Closing per response from original reporter.

**Closed by RodneyBaker** 2022-02-17 13:44 UTC
Labels: needs info
