### ISSUE TITLE
with touch enabled pen scrolls

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#2101] opened 2018-06-23 09:38 UTC
Surface 3 tablet Windows 10 latest update

with touch gestures enabled the surface pen draws a line and scrolls the canvas at the same time

**Comment by openanim** [comment] 2018-06-23 10:19
Is surface three Ntrig or wacom? The problem you are talking about seems similar to a known wacom problem, if surface 3 does have wacom drivers, will update your driver or go back to the previous drivers. Because wacom has distributed several drivers with this problem even after these fixes.

**Comment by bobbybutterfly** [comment] 2018-06-23 11:44
@openanim  

Its ntrig 
I use the newest surface pen (2017)

**Comment by bobbybutterfly** [comment] 2018-07-14 09:05
i just bought a new Surface pro (2017) 8GB i5 and installed the latest build of OT 1.2.1

and i hope not to hurt anbodys feelings by saying that, for pen tablet users, this program is a mess.
- no pen pressure
- if touch gesture Control enabled, the pen doesnt draw but moves the canvas and finger pinch zoom is  miles Offset. touch rotate has still no horizontal snap (which is state of the art an other apps)

- still not able to activate one of the brushes from the raster Level Palette for my raster Level.

and by the way, the brushes Palette looks like from a childs drawing app. I dont need hundreds of fun-brushes, but 10 or 20 serious brushes in a practical, clear arrangement which are accessable right from the start


For a pen tablet user (and this is the future) this program has still major problems and nobody seems to care



For pen tablet users

**Comment by manongjohn** [comment] 2018-07-14 13:33
I have a laptop-tablet and only last week did I find the cause of OT's no pen pressure (and subsequently the pen-touch issue). OT currently doesn't support pen data from Windows Ink.

I managed to find a solution developed elsewhere and confirmed it fixes your 1st 2 issues. We are currently trying to secure the rights to officially use it in OT. If not, it may take a little while longer to fix.

If you can somehow turn off Windows Ink, it might fix your pen and touch issue. Let me know if can because I have yet to figure out how to turn it off.

As for your 3rd issue, I don't have that issue that I am aware of unless there is something I am missing in trying to reproduce it. If we can't easily reproduce it it makes it harder to find the problen and fix it.

As for the "fun" brushes? The MyPaint brushes are pretty popular in some circles from my understanding. Its far better than what we had before in my opinion. The developer who took the time and implemented it did a great job of integrating it.

Can it use some work? Can some stuff be improved? Can we do stuff to enhance our workflows? Sure submit a feature request on the forum for stuff like a favorite brush panel or something. 

When a developer has time to do it and the knowledge of how maybe they can do it. We don't have a lot of developers so our time and experience varies. We can't get to everything, especially when we can't reproduce a bug. Putting bountues out there may help attract some developers.

And for the record...I care..but can only do so. much.

**Comment by openanim** [comment] 2018-07-14 13:41
I'm sorry for your hardware problems. I had also the problem of the scroll, I know how annoying it is even if I'm not on ntrig.

Post perhaps videos to help the developers. Was the problem in previous versions?

I think you're talking about the Mypaint brush. Because when you choose a default level, plain will fit your default choice, too. So you'll be on toonz's native raster brush but not on my paint which are good additions. What you ask for is more like a request for functionality to display the panel you want among the others. or that some specifics brushes are by default also.

**Comment by turtletooth** [comment] 2018-07-15 20:23
@bobbybutterfly I built the touch controls on a Surface Pro 2017.  Do you have the ntrig drivers installed?  For now OpenToonz on a surface pro needs the ntrig drivers installed.

**Comment by bobbybutterfly** [comment] 2018-07-15 20:41
@turtletooth i think, that my Surface pro 2017 has ntrig drivers installed by default, otherwise my ntrig pen wouldnt work i think

**Comment by turtletooth** [comment] 2018-07-15 21:44
Sorry - I meant the wintab drivers.  You can get them here: https://www.microsoft.com/en-us/download/details.aspx?id=49498  

It says Surface Pro 4, but the drivers still work.

**Comment by bobbybutterfly** [comment] 2018-07-20 08:14
ok, installed the wintab Drivers:
- without touch gesture Control, it works all Right( but i dont have touch gesture Control:/
- with touch gesture enabled the pen tip does all Tasks but Always moves the canvas a bit
Maybe Windows ink support will help here.

I Tried Krita from time to time in the last years, but dismissed it for no support of my Surface pen.
Inspired by this thread i installed the new Version and it runs very well but two remarks here:
-Canvas Rotation on krita? Space+Shift+drag? really? without touch gesture conrol possible?
-Two finger touch for canvas move has Always the Problem that one finger touches the screen first an sets a dot in brush mode


Two wishes for Opentoonz touch mode: pinch zoom without Offset and Rotate snap.

im not a programmer, but the Code could be:

if (getRotateCanvasValue) <=5  setAttr CanvasRotate 0;

**Comment by manongjohn** [comment] 2018-11-07 01:00
Enabling Win Ink support in OT should fix this without having to install wintab drivers anymore. Recommend closing.

**Comment by bobbybutterfly** [comment] 2018-11-07 13:52
still this behavior: #2220

**Comment by manongjohn** [comment] 2018-11-07 15:00
Ok. I'd suggest leaving that open and closing this one.

**Closed** 2018-12-03 05:30 UTC
