### ISSUE TITLE
Codec Listings / Availability

### ISSUE THREAD

**Issue by SPH404** [opentoonz/opentoonz#4010] opened 2021-07-12 12:39 UTC
I installed the K-Lite_Codec_Pack_1630_Mega.exe
Despite this, I still cannot export an OpenToonz animation to .H264
Why ?

**Comment by RodneyBaker** [comment] 2021-07-12 13:14
It isn't clear how installing a codec pack would allow Opentoonz to render or export to any codec as Opentoonz doesn't automatically search for installed codecs in an operating system.

**Comment by SPH404** [comment] 2021-07-12 13:40
What is the official method to install the H264 codec in OpenToonz?
Thx.

**Comment by RodneyBaker** [comment] 2021-07-12 14:21
An excellent question which I don't know the answer to short of programming it in with code.
I believe what most would do is render images out to image sequence and then use a program to encode that sequence into whatever codec desired.

Opentoonz does (optionally) use FFMPEG which can encode and decode to/from H264.
Even there however that would be using FFMPEG from command line and not via the program.

We will have to wait until someone more knowledgeable about the process arrives at this topic.
In the meantime I would suggest rendering to a high resolution format such as TIF (which can be up to 64bit) with the goal to encode that sequence of images in another utility/program.

Of course I might be missing something and perhaps we can render to H264.
However, I am not aware of how that would be done directly via Opentoonz.

**Comment by SPH404** [comment] 2021-07-15 15:32
I came across the menu:
http://xmas.free.fr/fastmp4.bmp
Which extension must have the ffmpeg file to put in "preference" / "import / export" ??

Thx

**Comment by artisteacher** [comment] 2021-07-15 16:55
Choose the directory that holds both the ffprobe and ffmpeg executables.

**Comment by SPH404** [comment] 2021-07-16 06:00
I tried 10 times but it doesn't work ...

**Comment by artisteacher** [comment] 2021-07-17 03:00
While it might vary based on OS, you need something like this:
<img width="299" alt="Screen Shot 2021-07-16 at 10 51 10 PM" src="https://user-images.githubusercontent.com/21159116/126023124-0fa0bcb4-a0d2-4c47-b856-e7dce9aecdb0.png">
<img width="578" alt="Screen Shot 2021-07-16 at 10 52 58 PM" src="https://user-images.githubusercontent.com/21159116/126023183-8c4a793d-0cb0-403f-ba63-3231d6aa7487.png">

You do need to restart OT after setting the correct path. It'll add rendering with mp4, gif or webm.

Not sure if this is relevant to you, but on some versions of macOS, the executables need to be run once each through Terminal before ffmpeg will work with OT due to a permissions thing.

**Comment by SPH404** [comment] 2021-07-17 17:54
I did it several times with several versions of FFmpeg and rebooting OT but nothing to do ...

**Comment by artisteacher** [comment] 2021-07-17 18:44
So if you try to use the fast render command, nothing happens? MP4, Gif & etc. still don't show up as options in the output settings?

Just an FYI, even with ffmpeg setup, you still won't be able to render with a specific encoding from within OT. It will just give you a couple additional formats.

Maybe you should just try the [Tahoma2D](https://tahoma2d.org) fork of OT instead, since there's no additional setup needed to render to mp4. Scenes/projects from OT should load without issue in Tahoma. Though after you've saved in Tahoma, the scene files might not be backwards compatible with OT.

**Comment by RodneyBaker** [comment] 2021-07-18 11:11
@SPH404  
You should join one of the Opentoonz discords where users can assist you with troubleshooting your primary problem.
The title of this issue is a little misleading because it suggests you need .H264 rendering whereas in fact you cannot connect to ffmpeg.  

I will echo @artisteacher recommendation to try the Tahoma2D fork as that ships with ffmpeg already connected.
Otherwise we need to see more clearly the steps you are using to try to connect to ffmpeg.

Also you appear to be using Windows but have not specifically stated that.

It is likely the fix to the problem is simple but we need to know more about the specific details of what you are doing.
For instance, if you are on Windows and pointing to ffmpeg's directory and not to ffmpeg/bin directory you likely are not pointing to the correct location.

Here is my preferences setup on Windows:
![image](https://user-images.githubusercontent.com/2576432/126064896-6fcc802d-a31e-4df5-b034-af454bb18661.png)


Please share a screenshot of your Preferences window where you have connected to ffmpeg.

**Comment by SPH404** [comment] 2021-07-19 15:19
Thanks for the discord channel.

I downloaded 4 different versions of FFmpeg and I point to the right files (Bin rep):

- ffmpeg-2021-06-27-git-49e3a8165c-full_build \
- ffmpeg-N-102971-g13ec6624b3-win64-gpl-shared \
- ffmpeg-n4.4-78-g031c0cb0b4-win64-gpl-4.4 \
- ffmpeg-n4.4-78-g031c0cb0b4-win64-lgpl-4.4 \

But nothing helps ...

So, I export to .AVI (xvid) and I convert AVI to MP4 with another software ...

And then, someone just told me about a software that I did not know: Tahoma2D
What is the purpose of this software? Just export to MP4 after working on OT?

Thank you for your answers.

**Comment by RodneyBaker** [comment] 2021-07-19 15:50
@SPH404 You may be interested in this program for converting to various codecs:

**Comment by RodneyBaker** [comment] 2021-07-19 16:55
The purpose of Tahoma2D?
Tahoma2D is a fork of Opentoonz initiated by one of the developers of Opentoonz.
Feeling the need to incorporate/develop parts of the software that might not be as easily incorporated into the main Opentoonz program Jeremy forked the source code of Opentoonz and created his third fork... Tahoma2D.  (Prior forks were Motion Monster and OTX).  Jeremy later passed this Tahoma2D fork on to another very active developer of Opentoonz who now maintains and develops fairly exclusively on the T2D fork.  John (@manongjohn) is the maintainer of the T2D fork.   Jeremy still contributes development as time and interest allows.

Many of the features are the same between OT and T2D but there are many differences as well.
The primary difference regarding rendering/output is that whereas for licensing reasons Opentoonz does not include FFMPEG... Tahoma2D does.  In this way users don't have to download and connect to FFMPEG manually.  In this regard OT and T2D operate very much the same once FFMPEG is connected but... as seen in your specific case... some users have difficulties connecting FFMPEG.  As such Tahoma2D can be easier to use especially for those not able to navigate the manual connectivity process.

There is movement of code between OT and T2D although that runs hot/cold depending on the interests of developers.   In my estimation, T2D tends toward more experimental additions with an eye toward ease of use for average users whereas Opentoonz has studio production requirements to consider.

**Comment by artisteacher** [comment] 2021-07-20 00:52
Tahoma2D has a slightly simplified workspace. There's a status bar with helpful hints about shortcuts & etc. Rhubarb Lip Sync is integrated for automated lip syncing. There are some additional stop motion features. There are some additional brush/fill features that are helpful. It's also portable. Otherwise it's pretty much the same program - many OT tutorials can be followed without much of a difference. There are a couple of changes to terminology - ie. smart raster rather than toonz raster or sub-scene rather than sub-xsheet. Since there's no additional setup with FFMPEG, I've found it much easier for my students than OT when they have to work at home.

**Comment by RodneyBaker** [comment] 2021-08-31 13:08
Were you ever able to connect to ffmpeg @SPH404 ?

**Comment by SPH404** [comment] 2021-09-10 16:33
> Avez-vous déjà pu vous connecter à ffmpeg @SPH404 ?

with my brand new laptop, yes!
But it is true that it does not enlighten me on the fact that some computers have a list of codecs for export and other computers do not ...

**Comment by RodneyBaker** [comment] 2021-10-01 20:32
Adjusted the title of this report to get it back to the subject of codecs.
Thanks for your patience @SPH404 
There is an answer in there... we just have to find it.  :)

**Comment by RodneyBaker** [comment] 2022-01-06 04:59
Closing as resolved although there does seem to be some elements of the problem still out there in the wild.
These appear to relate to the specific operating system and/or codec installation itself.

It will be good to keep a close eye open on codec related issues to see if any pattern can be discerned.

**Closed by RodneyBaker** 2022-01-06 04:59 UTC
Labels: needs info, troubleshooting
