### ISSUE TITLE
Crash after Cleanup attempt

### ISSUE THREAD

**Issue by diegoh42** [opentoonz/opentoonz#654] opened 2016-07-20 03:32 UTC
Whenever I attempt to cleanup a .TIFF file, OpenToonz crashes. Similarly, whenever I attempt to save a file, the program crashes aswell. Any Suggestions?

**Comment by turtletooth** [comment] 2016-07-20 03:39
We need some more info before continuing:

- What platform are you on?  
- What type of file are you trying to save.
- What version of OpenToonz?

Shot in the dark:
  What happens if your rename it .tif?

**Comment by diegoh42** [comment] 2016-07-20 03:43
I am using an IMac
I am trying to save TLZ, TNZ, and TIFF files
I am using V1.0
![screen shot 2016-07-19 at 8 42 17 pm](https://cloud.githubusercontent.com/assets/20549895/16974431/63b47f14-4df1-11e6-870f-7cbe952e505a.png)

^^^ That is the message following the crash that occurs when attempting to clean-up my .TIFF files

**Comment by yamisama** [comment] 2016-07-21 11:05
Does this happen with different projects as well? Looking at the error, it looks like your level file might be corrupted. You wouldn't happen to get a separate crash of a program `lzocompress` before that by any chance that might have led to the level file not being created properly (#633)?

By the way, you can copy and paste crash reports like these into your bug reports. If you enclose it in triple back ticks (```), it will get formatted properly. In screenshots like this, some parts of the information are not visible due to scrolling.

**Comment by diegoh42** [comment] 2016-07-22 19:03
The crash occurs with every single file that I attempt to cleanup. On top
of this, I can only load .TIFF files into OpenToonz. The problem seems to
occur when I try to click the clean up button for a drawing.

**Comment by yamisama** [comment] 2016-07-23 13:24
I tried to reproduce it – created a raster level and then ran cleanup on it. I didn't get the assert you got, but I got the same crash of `lzocompress` I described in #633. That's using the July 23rd nightly build under OS X 10.9.5.

**Comment by diegoh42** [comment] 2016-07-24 19:14
What info do you need in order to help me?

**Comment by artisteacher** [comment] 2017-04-12 17:17
I've had several crashes when experimenting with the cleanup settings using the build from March 21st on OS X 10.11.6. Crash reports are attached.
I'm not sure if this is related, but I'm also getting the following warning when trying to cleanup a level:
![screen shot 2017-04-12 at 12 50 18 pm](https://cloud.githubusercontent.com/assets/21159116/24970428/3e14d5e8-1f82-11e7-877c-fac0073c2346.png)

[cleanup1.txt](https://github.com/opentoonz/opentoonz/files/917338/cleanup1.txt)
[cleanup1.txt](https://github.com/opentoonz/opentoonz/files/917339/cleanup1.txt)

**Comment by artisteacher** [comment] 2018-02-20 15:42
In 1.2, I’m getting a repeatable, immediate crash if I have the entire column selected (instead of having the cells themselves selected) and then try to change the line processing from greyscale to color.

**Comment by manongjohn** [comment] 2018-02-20 16:30
Does this happen in timeline mode, xsheet mode or both?

**Comment by artisteacher** [comment] 2018-02-20 19:24
@manongjohn 
It happens with both Xsheet and Timeline modes.

**Comment by norrinra** [comment] 2018-04-20 19:11
Hello I have the same problem on mac. I attached the crash report if it helps.

[41.txt](https://github.com/opentoonz/opentoonz/files/1933328/41.txt)

**Comment by artisteacher** [comment] 2018-11-05 20:00
Cleanup is still really unstable - at least on MacOS. Just changing from one mode to another can cause a crash. Double clicking on the color often causes a crash...

**Comment by artisteacher** [comment] 2019-04-26 02:15
Running with debug, I get a crash trying to save after running cleanup on some png. The error messages are:

> ImagePainter::paintImage() gl_error:1286
2019-04-25 21:43:43.697701-0400 OpenToonz[19635:2165311] nw_path_close_fd Failed to close guarded necp fd 29 [9: Bad file descriptor]
2019-04-25 21:43:43.786515-0400 OpenToonz[19636:2165315] nw_path_close_fd Failed to close guarded necp fd 29 [9: Bad file descriptor]
2019-04-25 21:43:43.931558-0400 OpenToonz[19637:2165328] nw_path_close_fd Failed to close guarded necp fd 29 [9: Bad file descriptor]
create context:0x600000fb57e8 [thread:0x1d435c0]
libpng warning: Application built with libpng-1.4.12 but running with 1.6.37

Xcode thinks the problem is related to tiio_png.cpp:
> void PngWriter::flush() {
  png_write_end(m_png_ptr, m_info_ptr);
  fflush(m_chan);
}
Thread 1: EXC_BAD_ACCESS (code=1, address=0x6e000000cd)

**Comment by RodneyBaker** [comment] 2019-11-10 22:58
For those experiencing this issue if the file is converted to another format other than PNG... say TIF... does the crash still occur?

**Comment by artisteacher** [comment] 2019-11-12 13:47
@RodneyBaker - good catch. I most often try to use Cleanup with pngs. Using a jpg level seems to work without issue. Having a png level active when trying to adjust cleanup settings may be my issue. I'll need to spend more time testing to confirm & to see if there are other problem formats.

**Comment by artisteacher** [comment] 2019-11-12 14:31
Never mind, jpgs can still crash. I loaded an image sequence of jpgs taken from a DSLR and they caused a crash when changing the line processing. Each image was 5-6.2MB. After cropping the images in OT they behaved properly. The image size went down to around 500KB. Perhaps the issue stems from large file sizes?

**Comment by RodneyBaker** [comment] 2020-09-27 08:42
@artisteacher As you were one of the last to report on this perhaps you can verify current status of this bug/crash and we can move to resolve it.

@diegoh42 If you have any updates that will especially be appreciated as this is your report.

Thanks!

**Comment by artisteacher** [comment] 2020-09-28 03:40
I'm not having any issues at the moment, but I don't really use Cleanup due to the unreliability I've experienced. The last time I showed a student the cleanup room (before remote learning with covid started last school year), we got an immediate crash just from changing a setting. 

I think there's more likely to be a crash involving cleanup if the computer has lower processing capabilities and/or the image size is especially large. My computer at home can handle a lot more than the computers we had last year - so I'm less likely to get crashing if there's a processing or memory issue.

**Comment by RodneyBaker** [comment] 2020-09-28 04:09
You raise an interesting point here.
I'm not quite sure how we want to deal with issues that are opened... likely still a problem... and yet cannot be (easily) revalidated.
This is especially important with crashing and show stopping bugs.

Will tag as "Help Wanted" for the present.

**Comment by RodneyBaker** [comment] 2022-02-24 03:20
I still some instablity when using Cleanup but it's not clear how much of that actually relates to Cleanup itself.

It will be good to take a deep dive into the Cleanup process after v1.6 release and see how the process can be stabilized and improved.  While unlikely that GTS would be combined with the cleanup process that would be an intriguing way forward and perhaps even allow the power of GTS to extend to Mac and Linux platforms.  There is also the extended issue of TWAIN and various scanner support.  The question then:  How best to proceed given the current state and availability of options?

**Comment by RodneyBaker** [comment] 2023-05-27 11:19
@diegoh42 
As this is your report from long ago we are very interested in whether you are still experiencing issue (especially a crash) when using Cleanup.

With @artisteacher stating "I'm not having any issues at the moment,... " I'm of the mind to close this report with expectation of a review of the entire Cleanup process to determine what stability improvments, optimations and enhancements (not necessarily in that order!) should be pursued.

**Comment by artisteacher** [comment] 2023-06-03 12:42
I'm mostly not having issues because I don't try to use Cleanup anymore.

**Comment by RodneyBaker** [comment] 2023-06-03 13:26
We have switched places @artisteacher 
I use to rarely use cleanup and now use it quite often.

Given your current feedback will close this pending some other update which suggests other problems with the cleanup tool.
Given how important this feature can and should be perhaps we can give it a solid look with an eye for improving it further.
For instance, not all images are ideal for cleanup given that they aren't black and white or of limited color.
Those images are usually better served by conversion.

Perhaps in the future the conversion and cleanup processes can be better positioned within the software so they are more naturally seen to be extensions of each other.

@diegoh42 Please let us know if you are still having problems.

**Closed by RodneyBaker** 2023-06-03 13:26 UTC
Labels: needs info, os-mac, crash
