### ISSUE TITLE
Unreliable shrinking ability

### ISSUE THREAD

**Issue by MaeEclipse** [opentoonz/opentoonz#4497] opened 2022-08-10 02:09 UTC
### Description

I made a wheel for my project and I tried to duplicate it to shrink behind. What is happening instead when I shrink, I am shrinking the original wheel. I even hid the original from sight and I have locked down to make sure I wasn't. It still shrinks the original.

### Steps to Reproduce

1. Make a copy of Raster level of pre-existing layer
2. Resize the copied layer
3. allow clips to be provided. I have made a clip of the problem with Wondershare that I rather use to show what happens.

### Expected Behavior

This is terribly funny. Be able to copy what I need to an resize the right layer.

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Other

### Graphics Tablet

GAOMON

**Comment by RodneyBaker** [comment] 2022-08-10 05:11
There are a number of ways to achieve your goal here.
It might be best to join an Opentoonz discord and explore those as github isn't particularly designed for that.

Perhaps the most direct way to make a copy of say... a wagon wheel... and then make one smaller than the other is to simply expose the wagon wheel on a second column that is under... that is to say to the left of the original column.  Then use the Animte Tool to adjust the scale of that column to make it smaller.  The main benefit to this approach is that then this wheel can be animated separately from the first and even be swapped out with a different looking wheel.

[Wheels.zip](https://github.com/opentoonz/opentoonz/files/9296890/Wheels.zip)
![wheels](https://user-images.githubusercontent.com/2576432/183820696-f74ee1d8-a541-47b4-a71c-52511fbf4280.gif)

**Comment by RodneyBaker** [comment] 2022-08-10 05:16
If you currently have a similar settup to the one I described then its mostly just a matter of troubleshooting why you are getting the undesired results.  Without knowing more specifics about your project it's hard to suggest any remedies.

**Comment by JPUser1** [comment] 2022-08-10 08:14
I think he is trying to duplicate a column? go to the Level Column u want select it then go to the  cells tab and select clone cells to duplicate those cells on a different column,

**Comment by justburner** [comment] 2022-08-15 15:09
@MaeEclipse 
This is not a bug... manipulating a copy by "instance" will affect all instances... that's expected behavior.

Both methods explained by RodneyBaker and JPUser1 are valid for doing what you need to do.

Rodney approach still use an instance but the animation tool to provide non-destructive keyframed transformations, I'll go this route if the wheels are supposed to look the same since you can quickly tweak them at same time.

JPUser1 approach will do a deep copy of your drawing into it's own level (think of this as it's own image file), go this route if the wheels are supposed to look completely different.

**Comment by RodneyBaker** [comment] 2022-09-25 04:20
Closing as likely resolved and/or abandoned.
@MaeEclipse Please let us know if you are still experiencing problems.

**Closed by RodneyBaker** 2022-09-25 04:20 UTC
Labels: needs info
