### ISSUE TITLE
can't find the precision tool

### ISSUE THREAD

**Issue by DKdexusMusic** [opentoonz/opentoonz#3363] opened 2020-06-23 07:47 UTC
I can't find the precision tool now Hardness appears, and I need to use precision for my drawings

![error](https://user-images.githubusercontent.com/67311534/85375408-df0a3300-b4fb-11ea-8c2b-a749bd00c214.png)

**Comment by RodneyBaker** [comment] 2020-06-23 11:24
Closing as duplicate of #3362

**Closed by RodneyBaker** 2020-06-23 11:24 UTC
