### ISSUE TITLE
Cut Tool Feature Request [$120]

### ISSUE THREAD

**Issue by UncleTan45** [opentoonz/opentoonz#1733] opened 2018-01-14 02:01 UTC
This could go a long way in terms of quality of life for the users of Toonz.
https://www.youtube.com/watch?v=iT_oMHF8Bs0

At 5:31 I want the cut tool to work like this if you mess with the tool options on the cut tool. This should be easy with the 'remove vector overflow' coding that's already in the program. It'd just need a slight adjustment.

**Comment by artisteacher** [comment] 2018-01-14 02:11
That would be really handy!

**Comment by beeheemooth** [comment] 2018-01-14 11:14
In OpenToonz it is possible to do this in Vector and Toonz Raster levels using other approaches to solving this problem.
[https://www.youtube.com/watch?v=N-Gds2B2pLk&t](url)
[https://www.youtube.com/watch?v=_Jr88wsNJfs](url)
However, in this case, you need to do a little more action, but you can embrace a larger range of frames and as a result, the speed of work should increase.

**Comment by Orphanlast** [comment] 2018-01-14 11:59
If you're wanting to cover a large number of frames, then yeah that's an effective meathod. @beeheemooth but using the frame range brush and auto inbetweener isn't always what's needed. I still say this is something that's nice to have on the fly. 

I do believe that using this feature for the cut tool will probably destroy vector guided drawing capability, but, some of us have no intention of using vector guided drawing.

**Comment by RodneyBaker** [comment] 2018-01-15 18:50
Feature Requests must go the route of discovery via the OpenToonz forum.
As such launching a discussion there will get the ball rolling and let other know of your interest.

[Link to Feature Request section of the OpenToonz Forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!categories/opentoonz_en/feature-requests)

**Comment by Orphanlast** [comment] 2018-01-19 12:13
@RodneyBaker so my $70 is just poof gone, is what you're saying?

**Comment by manongjohn** [comment] 2018-01-19 12:32
If there is a bounty on this, post link in here so we know and wont close it.

**Comment by Orphanlast** [comment] 2018-01-19 12:43
The OP has no idea how to do that. And if I can do that, I have no clue how. 

What is the problem? And it still sounds like my $70 went down the shitter. 

I am seriously not happy right now.

**Comment by Orphanlast** [comment] 2018-01-19 12:45
and what's worse is it sounds like you guys have the power, at a whim to make any of my donations go down the toilet, using this donation platform.

I've been generous, and I'm getting hosed, and you guys can hose me any time, any bounty, at any time you want if I continue using this platform.

This is a volatile donation platform. Figure it out! FIX IT!

**Comment by Orphanlast** [comment] 2018-01-19 12:52
I have no idea what anything either of you are talking about. $70 says you fix it.

**Comment by Orphanlast** [comment] 2018-01-19 12:59
You said post the bountysource link here: https://www.bountysource.com/issues/53752277-cut-tool-problem

There. That all? Never had to do that with the Krita-like Assistant Tool Bounty.

If a problem still remains, what is it? 

What was the problem?

Don't repeat, verbatim what has already been said, I don't understand. What is going on?

**Comment by manongjohn** [comment] 2018-01-19 13:02
@Orphanlast Relax. Now that we know there is a bounty on this, it shouldn't be close. If you have placed bounties on other requests and it is not obvious, please update those so they dont get closed.

Keep in mind if someone puts a bounty on an issue we don't know unless someone posts it in the issue, so providing a link to the bounty serves 2 purposes....1) We know there is a bounty 2) Developers may not be using Bountysource or other site and may not know there is a bounty when looking at issues here.

**Comment by Orphanlast** [comment] 2018-01-19 13:05
"If you have placed bounties on other requests and it is not obvious, please update those so they dont get closed."

Place a link in them? Move them to "Discovery"? I have no idea what discovery is and it's not even a tab at the top. 

Is posting a link into the github page a "Discovery"?

**Comment by manongjohn** [comment] 2018-01-19 13:11
Just posting a link like yoy did will suffice.

**Comment by Orphanlast** [comment] 2018-01-19 13:13
So if I posted a video tutorial on how to post a bounty on github and bountysource for Opentoonz/opentoonz and the last step was pasting the bountysource link to here would be proper conduct?

Because I've been thinking of doing that.

**Comment by gab3d** [comment] 2018-01-19 13:32
@orphanlast
in my case, for example, I am reading all of this conversation via email messages, and in neither of this messages tjere were a link that made reference to a bountysource bounty, so up until you posted the link I couldn't access the proper bounty.
perhaps as the conversation (now I see) is replicated in the bountysource page, and you are reading it at that page, ypu assumed everyone knew about it.
but that's not the case for everyone here.

so, as suggested, a link copied in the thread could help make more people aware of it.

**Comment by manongjohn** [comment] 2018-01-19 13:33
@Orphanlast Yeah. I would agree.

I think I will also make a "BountySource" label which we can add to an issue if we see a link was posted. This way, we can easily see which have bouunties and wont have this issue.

**Comment by Orphanlast** [comment] 2018-01-19 13:38
K

**Comment by Orphanlast** [comment] 2018-01-19 14:10
And I am sorry for being upset. I had reason to be but I am developing gradually into being more of a public figure, I guess... kinda... and I need to behave more level headed.

**Comment by RodneyBaker** [comment] 2018-01-19 14:19
I'm a little late to this party...

Hang in there Skyler!
**please understand, a recommendation to close is just that, a recommendation.  It is an invitation for others to also forward their recommendations to include links to bounties, notifications of interested programmers, suggestions the feature is already implemented, etc.**  It's part of the vetting process.

@Orphanlast said:
>  And it still sounds like my $70 went down the shitter.

The way Bounty source *should* work is that no monies are paid until the results are accepted, so...
No.  You shouldn't have paid anything so there is nothing to go down the drain as of yet.
If you did actually lose money and not just the pledge of it then the use of Bountysource will need to be scrutinized a little more carefully.
.
Without the OP (or someone else) stating there is actual interest in a feature request it's just wishful thinking and by stated rules is to be discussed elsewhere.  Again, a recommendation to close is just that, a recommendation.  It is an invitation for others to also forward their recommendations.

The underlying point is there is a vetting system where we all try to get the word out concerning the interest of OpenToonz users (bounty driven or otherwise) but there is an appropriate place for interests that don't have attached programmers or champions that are actively developing the idea.  That development can take on many forms at many stages.  At the initial stage it is important to drop a note into the official forum where others can comment on that idea... perhaps improve upon it even.  A listing on github then suggests it has gone beyond initial discussion and is either being funded for development or is in active development.  Developers themselves get a pass from the standard of not posting to github because their experience in the code allows them to contribute to higher level discussion and assist in the implementation of the idea.

It is the posters responsibility (with all of us assisting) to make sure others understand there is active interest (and not just wishful thinking) attached to a developmental idea.  New users won't know this initially so we help them.

Thanks @manongjohn for adding the Bountysource label!

**Comment by manongjohn** [comment] 2018-01-19 17:09
There is a way to get money back on Closed issues per Bountysource documentation.

I believe we have to close it with the label "Won't Fix" and money is refunded back to the donators.

**Comment by jpturcotte** [comment] 2018-01-19 18:45
The money on Bountysource **do not** disappear when the corresponding issue is closed. Case in point: the macOS tablet issue was closed (and later reopened), and the money is still there.

**Comment by Orphanlast** [comment] 2018-01-19 23:21
Ok. That's good to hear. Keep in mind Bounty Source is very confusing to me. Even the tutorial confused me, so I only got a little ways through it. I know where to look to see the latest issues and pull requests, but that's about it.

**Comment by RNavega** [comment] 2018-01-29 07:04
In TB Harmony, when you draw a pencil line (a spline with thickness) and you finish doing the stroke, the intersections of all the strokes in the drawing are computed.
Using the Cut tool in mouse-gesture-mode (like that video shows) allows you to drag the cursor to draw a line. When that line crosses part of a stroke it erases it. Deletable parts of strokes are delimited by the ending points of the splines as well as the intersections of strokes.

For example, if you draw a long stroke and then draw two other strokes crossing it, you can delete the middle part of the long stroke -- the one that exists because of the two crossings.
Deleting the middle will "break" the long stroke into two parts, the beginning up until the first crossing, and the ending from the second crossing to the end.

All the functionality (especially the intersection of splines) seems to be in the OT libraries already (it's used for the vector fill for example), so this Cut tool would involve mostly writing some new tool code.

**Comment by RNavega** [comment] 2018-01-30 06:11
@Orphanlast if by "vector guided drawing" you mean vector drawings on a vector layer, then yes, a Cut-type tool (which does clipping of splines\curves\paths) would preserve your vector drawing, it can only work with this type of drawing in fact.
This type of tool is a convenient interface to be able to delete clipped segments.

**Comment by Orphanlast** [comment] 2018-02-03 01:35
@RNavega

No... draw a picture on a vector level. (just one frame. It could be a smiley face.) Now go to frame 2 and turn on the onion skin. Now right click on the viewer, select vector guided drawing>nearest (or something)

See how the onion skin changed. It shows the direction of strokes and the order they were drawn to help with auto inbetweening with the level strip and new functions with the brush tool.

**Comment by artisteacher** [comment] 2018-02-03 02:36
The vector guided drawing is just a guide, it would still work without issue. The inbetweener function in the level strip might work fine in some cases but not in others. 

Assuming that using the tool doesn’t impact how OT recognizes stroke order and direction, if 2 drawings are altered in the same way, they should continue to work just fine in the inbetweener. However, some actions if only done on 1 of the drawings would probably break the functionality of the inbetweener. For example, removing the middle segment of a stroke would result in 2 separate strokes instead of 1. On only one drawing that breaks the consistent stroke order. On 2 drawings or if removing overflow with the tool, as long as it maintains stroke order & direction, should do the auto inbetweening just fine.

**Comment by RodneyBaker** [comment] 2018-12-17 09:38
This feature appears to be slipping to 2019 development cycle.
Tagged with 'roadmap' due to active bounty.

**Comment by RodneyBaker** [comment] 2019-09-07 23:18
There is still a $70 bounty on this feature request but no activity/interest being posted for over a year.
Perhaps there are others willing to up the ante and encourage a developer to climb on board?

**Comment by RodneyBaker** [comment] 2019-10-24 04:02
The bounty on this PR has been increased to $120.

**Comment by RodneyBaker** [comment] 2019-10-24 04:30
If a developer would like to see a current workflow allowing this basic capability in current Opentoonz releases I'll be glad to walk them through it.   It is that basic (manual) process that would need to be refined and automated.  To my understanding there are two primary methods that currently work... one for Toonz raster levels and one for vectors.   I am more familiar with the vector approach.

**Comment by RodneyBaker** [comment] 2019-10-24 04:56
Here are three progression shots from a manual workflow in Opentoonz.
Image 1 Initial drawing with overshooting lines and not concern for excess lines
Image 2 Dangling lines left over after first pass.  These were not identified for removal at the first pass.
Image 3 Danglers tagged and removed in second pass producing the desired outcome.
![CutLineWorkflow](https://user-images.githubusercontent.com/2576432/67454681-bf2f1200-f5f0-11e9-9e2d-b0998d3cf487.png)

**Comment by RodneyBaker** [comment] 2020-04-03 05:39
@UncleTan45 As this feature is now added to the Eraser Tool perhaps you may assess it as being implemented.  
There is an additional (earlier version) of the Eraser Tools Segment Erase mode that you might comment on as it provides as similar function but for the Cut Tool.  That PR was closed by the developer as not being as robust or necessary as the feature added to the Eraser Tool.

REF:  #3178

**Comment by RodneyBaker** [comment] 2020-04-15 11:50
@pojienie Have you put in a request for reward of the bounty for this feature?
If you have not yet done so... please do.

**Comment by pojienie** [comment] 2020-04-15 14:27
@RodneyBaker Oh! I did it on Bounty Source. No one in there has interacted with me, though.

**Comment by RodneyBaker** [comment] 2020-04-15 15:19
Thanks.  Good to know.
I'll follow up with @UncleTan45 via discord as he's the primary contributor to the bounty.

**Comment by RodneyBaker** [comment] 2020-04-23 22:18
Closing as fulfilled with #3178

**Closed by RodneyBaker** 2020-04-23 22:18 UTC
Labels: bounty, feature request

**Comment by pojienie** [comment] 2020-04-24 11:55
Thanks @RodneyBaker ! But... shouldn't the PR be #3194 ?

**Comment by RodneyBaker** [comment] 2020-04-24 12:11
PR #3178 was the one that had the bounty.
I'm not sure how bountysource deals the original PR being closed... and a new PR providing the solution.  I don't think bountysource is smart enough to figure that out on it's own without the people involved updating their bounty.

In short, I sense a bit of an unfortunate mess. 
And I assume you still have not as of yet been awarded the bounty.  :(

But yes, you are correct... PR #3194 is the actual implementation of the feature formerly known as Cut Tool Erase which was initiated via #3178.  :)

**Comment by manongjohn** [comment] 2020-04-24 12:41
Bounties are against issues not PRs.  I've not collected a bounty so I'm not sure what's involved in the claim process, but I imagine submitting a claim requires the devloper to provide some proof it's completed after the issue is clossed, or the original bounty owners have to come to the issue page and verify it was resolved.

**Comment by pojienie** [comment] 2020-04-24 23:18
As @manongjohn said, bounties are tied with issue instead of PR. In BountySource site, the issue is marked as closed since this is closed in here. I've claimed the bounty and am now waiting for two bakers to either accept or reject my claim. Thank you for acting on this, @RodneyBaker !

**Comment by RodneyBaker** [comment] 2020-11-19 14:14
According to BountySource the bounty for this feature was paid out.
@pojienie If this is not the case it would be good to know.

So this post is just to close the loop on that open item.
Thanks again for the feature @pojienie!

In other related news:
A similar feature is now available for testing via Tahoma2D branch for toonz raster levels.
Please see:  https://github.com/turtletooth/tahoma2d/pull/518
