### ISSUE TITLE
Crash Reason: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by liopui** [opentoonz/opentoonz#5573] opened 2024-08-25 15:45 UTC
### Description

Crash Reason: EXCEPTION_ACCESS_VIOLATION

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment] 2024-08-25 19:54
Closing as a duplicate of #5574

**Closed by RodneyBaker** 2024-08-25 19:54 UTC
Labels: incomplete report
