### ISSUE TITLE
White Background Disappears

### ISSUE THREAD

**Issue by liaklein** [opentoonz/opentoonz#889] opened 2016-10-27 16:28 UTC
When I am in the drawing room and I select a drawing on the levels pane, my white background disappears.

**Comment by RodneyBaker** [comment] 2016-10-27 16:54
I'm not entirely sure what you are looking at but...  I think...

It's not that the white background is disappearing but rather that you don't have any background at all and when moving to the drawing room the background displays the current (transparent) background.

In order to set the background color go to Xsheet on the top menu and then open your Scene Settings.  There look for the RGBM settings and adjust the M setting to 255.  This will make the alpha channel fully opaque (i.e. not transparent).  You'll see this change in the little square to the left where the checkerboard will change to white.  To change the color click on that square.

Apologies if this isn't related to your problem but that is my best guess.
![transparent background](https://cloud.githubusercontent.com/assets/2576432/19777063/27614e04-9c3c-11e6-8711-4e6d44b0e139.png)

**Comment by turtletooth** [comment] 2016-10-27 17:15
Actually I think this is referencing:
If the level is selected, it doesn't show the white background of the canvas.  If the level is selected, it shows the level separately, not as part of the greater scene.  If you want to see the white background, you need to click a frame in the xsheet.

This is not a bug, but rather a way to show the level in isolation.  
level pane = show only the level (no white background)
xsheet pane = show the levels in context (including the canvas)

@liaklein If you can confirm that this is what you are talking about, this can be closed.

**Comment by automated-reckoning** [comment] 2016-10-27 17:42
This might be working as intended, but it does kind of violate the principle of least astonishment. When I start drawing I have a white background, but if I click on certain things my drawing stays exactly the same but the background is suddenly transparent, with no obvious way to return to the white background. At first I thought it was a bug too, though I decided that it must be a feature I just didn't understand after a while. It was too consistent and too easy to trigger for it to survive multiple updates otherwise.

**Comment by liaklein** [comment] 2016-10-27 17:54
@turtletooth I can confirm that this is what I am talking about. @RodneyBaker I took the steps you recommended, and I now have the functionality that when I click on the frame in the xsheet, the white background appears (exactly how turtletooth described). Thank you everyone for getting back to me so quickly.

**Comment by turtletooth** [comment] 2016-10-27 17:56
@automated-reckoning I can understand your perspective somewhat, but it is a simply a matter of understanding levels vs xsheet.  When I was first learning OT, I too wondered what happened to my background when I clicked on the level pane, but now I see the usefulness of isolating a level on its own.  I'm not sure how you would change it and still keep the same functionality.

**Comment by turtletooth** [comment] 2016-10-27 17:58
@liaklein Thanks!

**Closed by turtletooth** 2016-10-27 17:58 UTC
Labels: Bug

**Comment by automated-reckoning** [comment] 2016-10-27 18:00
@turtletooth I understand, and I'm not advocating reducing functionality to meet user expectations. But I do think it's worth considering if there's any ways to indicate to users 'yes, this is intentional, and it's useful.' Perhaps a better visual indicator of the different views?

**Comment by jaguarus83** [comment] 2017-11-14 10:47
Hello guys, but I have noticed that background disappears only for Toonz Vector Layer and it doesn't affect Toonz Raster Layer. And it really looks like a bug, because when you try to draw some vector - you can't see bounds you want to fit.

**Comment by Povz** [comment] 2018-06-05 03:16
Hello can somebody please help me with my Opentoonz_1.2 I was able to draw and mess around with the previous version of Opentoonz but just after the update to Opentoonz_1.2 I can't draw anymore because the white background is missing from the scene. I tried to change the grey background to white by >Preference>Color>Viewer BG Color, R:255, G:255, and B:255 but still nothing change. Here is a link to a short video I recorded to show my problem >https://www.youtube.com/watch?v=0HhEKK7_3Ho&feature=youtu.be

**Comment by jpturcotte** [comment] 2018-06-05 14:39
Hi @Povz! It is a known problem that should be fixed by installing the latest nightly release: https://github.com/opentoonz/opentoonz/releases/tag/nightly.

**Comment by Povz** [comment] 2018-06-08 05:33
Hi thanks for answered my question,

I just a bit confused about nightly build, there are four different assets.
1.Opentoonz.pkg, 2.OpentoonzSetup.exe, 3.Source code(zip) and 4.Source
code(tar.gz).

And if I am to install the latest nightly release do I have to uninstall
Opentoonz the one I have on my machine?
I know I have this suggest long time ago and I did try to install the
nightly release but it didn't. Now I want to try to again but, I would like
to know which one of the four as I mentioned above do I need to install.

**Comment by jpturcotte** [comment] 2018-06-08 12:34
You do not need to uninstall your current version. It will simply overwrite it. Use OpentoonzSetup.exe.

**Comment by Povz** [comment] 2018-06-12 02:37
Thank you very much J.P. Turcotte with your help I finally get it work
again!  :)

**Comment by jpturcotte** [comment] 2018-06-12 19:36
@Povz I am very happy to hear your problem has been solved. Next week, there will be a new official release, so make sure you update when it is made available!
