### ISSUE TITLE
Issue with Vector level drawings

### ISSUE THREAD

**Issue by telesacko** [opentoonz/opentoonz#1165] opened 2017-04-20 18:13 UTC
I've drawn an image in OpenToonz with the vector level and it worked fine until at some point it started crashing. It could be because I added too many colours, but other drawings I made with the same technique still work fine. maybe the file is corrupted?

**Comment by telesacko** [comment] 2017-04-20 18:24
If I render it, it works fine, but I cant edit the images for some reason

**Comment by RodneyBaker** [comment] 2017-04-20 18:26
More information is needed.
Windows/Mac/Linux?
etc.

Also, perhaps you can share the image.

**Comment by telesacko** [comment] 2017-04-20 18:32
Windows 10, I know its hard to replicate, the rest of my drawings are fine and if I hide the column I can view everything without crashing

**Comment by telesacko** [comment] 2017-04-20 18:35
![hunt walk 0002](https://cloud.githubusercontent.com/assets/27825554/25246742/dbcfa538-2608-11e7-897d-137177283338.jpg)

this is the picture I have trouble with

**Comment by RodneyBaker** [comment] 2017-04-20 18:47
Regarding the inability to edit, I'm going to guess you might have inadvertently selected a different column in your xsheet or level.  

As for crashing more information is needed.
If this is only a one time error then I'd press on.

As a general rule, save often and if you've had OpenToonz open for a long time I'd say Save, Save All and then reopen the scene again to continue.

**Comment by telesacko** [comment] 2017-04-20 19:27
Thank you, but Ive tried these things and it didnt work. Regarding the crashing, it happens when I try to view the image. the rest of the column doesnt produce any problem. it also doesnt show u as an icon on the level strip tab

**Comment by RodneyBaker** [comment] 2017-04-20 20:00
> it also doesnt show u as an icon on the level strip tab

That appears to be a common problem but isn't a show stopper.
Crashing... of course is so we need to address that.

As you state you can view the rest of the column I'd say to try to determine the name of the frame and then reload that.  We can usually identify those frames via OpenToonz browser, just make sure it is set to display image icons otherwise you'll have to open them one at a time to see what they are.

Most people don't want to turn over their computer systems to someone else but that would be another option.  Programs such as Team Viewer allow one person to grant remote access to someone else and then turn that access off.

So the good news is that you have lots of options.  :)

**Comment by artisteacher** [comment] 2017-04-25 12:41
I had a student with the same problem with a vector level on OS X. He had been wondering if he used too many colors on the level. This is a single drawing level but causes a crash anytime the frame is active in the X-sheet - even if a different cell is selected. I've attached the zipped .pli file below. 
[Q.pli.zip](https://github.com/opentoonz/opentoonz/files/955023/Q.pli.zip)

**Comment by turtletooth** [comment] 2017-05-25 13:50
@artisteacher I tried the level you provided and it brought my computer (not just OT) to its knees.  I found that students who use vector levels as a sketch style (lots of little lines) are pretty good at getting OT to lag.  What style of drawing was the student doing?

**Comment by artisteacher** [comment] 2017-05-25 14:44
I think he was using a sketch style. He ended up reworking his workflow and did all of the drawing in Photoshop.
![screen shot 2017-05-25 at 10 42 33 am](https://cloud.githubusercontent.com/assets/21159116/26455046/f46d900c-4136-11e7-8ce6-5c2ecde82401.png)

**Comment by turtletooth** [comment] 2017-05-25 21:01
I believe this is a duplicate of #144

**Closed by turtletooth** 2017-05-25 21:01 UTC
Labels: Bug, Crash
