### ISSUE TITLE
Undo Button Consistently Breaks upon Copy/Pasting Selections onto new frames

### ISSUE THREAD

**Issue by Donnydindon** [opentoonz/opentoonz#5536] opened 2024-07-18 04:07 UTC
### Description

When copy/pasting selections between frames in a raster level, the undo button breaks.

Sometimes, if the change is so recent that the undo button does not have any other actions to possibly undo, it will simply give the error "no more Undo operations available" and be unusable for the rest of the session. 

When there are enough changes built up onto a file, the undo button will undo several other changes which occurred prior but not the most recent one, as if it has trouble recognizing the most recent actions. Some of these changes also include moving or magnifying frame relocations to positions they were not previously in. This seems like it may be because of a misguided effort to "undo" the past relocations by reversing the operation, which somehow also doubles the magnitude of the operation it has just done, and so the next time the "undo" is called, it executes the previous action, which was just doubled and added onto the action history, etc.

Sometimes when the undo button breaks, Opentoonz crashes (though not frequently).

### Steps to Reproduce

1. Make a selection of anything in one frame of a raster level
2. Copy/paste that selection onto another frame elsewhere (either same level or not, doesn't matter). Check to see if undo/redo works here (it should for the first pasting, but it might break here too).
3. Go to the next frame, and paste the same selection. Check to see if undo/redo works here (for me it always breaks here)

### Expected Behavior

I expected the undo button to undo the previous action and not break, making undoing never undo the latest action.

### Screenshots, Video & Crash Logs

The included videos show me opening opentoonz three times. The first and second show a relatively rare occurance which is the undo button breaks after I paste one time after copying a selection. The third shows the much more common occurance where the undo button breaks sometime in the middle of me using it, ignoring any other changes made after the fact (as seen with onion skinning). I had other screen recordings of other issues like the weird frame relocation/deletions but unfortunately those videos are unusable (they don't show the error pop ups for some reason, I have switched screen recording apps).

If you see selections quickly appearing and disappearing it's just me doing ctrl+z and ctrl+y to check undo/redo.

Also I don't know if ya'll can change the file size cap to anything over 10mb because I am trying to export clear videos under that size at 480p and the last video has like a bajillion cuts because of that.

https://github.com/user-attachments/assets/a76b582e-0a5a-4285-a2f8-d1127568da3b

https://github.com/user-attachments/assets/bc181f5e-7c6e-42ee-8a2c-d33a6b86b911

https://github.com/user-attachments/assets/1af8b690-d368-467d-9161-037dce0adab2

### OpenToonz Version

1.7

### OpenToonz Version Information

built May 10 2023

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RattusaurusRex** [comment] 2024-07-18 05:16
Can't reproduce this on the latest nightly.  Have you tried using a nightly?  There have been fixes to undo since the regular 1.7.1 release.  If this seems to be the same bug, it's already been fixed: https://github.com/opentoonz/opentoonz/issues/4910

**Comment by Donnydindon** [comment] 2024-07-18 16:35
I haven't tried a nightly yet. I have downloaded it for windows but it doesn't start up properly for me. I have Windows 11, I don't know if that means anything.
![image](https://github.com/user-attachments/assets/5b8afcab-a070-48b5-8bdc-26333c38a89a)

**Comment by RodneyBaker** [comment] 2024-07-18 19:08
@Donnydindon 
Please see: https://github.com/opentoonz/opentoonz/issues/5351

**Comment by Donnydindon** [comment] 2024-07-18 23:29
I tried finding an SRV directory but it doesn't seem like my Opentoonz has it TT. I even searched through all the files in the folder too
![image](https://github.com/user-attachments/assets/13fe45f3-d454-49c2-b37c-0c16cb1d1315)
![image](https://github.com/user-attachments/assets/7a45d54b-b4b6-42b8-850c-d99b2830d63b)
![image](https://github.com/user-attachments/assets/6bf4e434-3abc-4fe4-b07b-99b88939a12a)

**Comment by RodneyBaker** [comment] 2024-07-19 13:16
The SRV directory is not in the stuff folder.
Try the Opentoonz program files directory at:  C:\Program Files\Opentoonz\SRV

**Comment by RodneyBaker** [comment] 2024-07-20 22:58
Will likely close this report as complete but would be good to have confirmation the latest nightly is working.
There are some persistent Undo shortfalls that are gradually getting addressed as code is updated.
It is important to stay updated with the nigthlies however if the desire is to use those fixes.

**Closed** 2024-08-12 13:30 UTC
