### ISSUE TITLE
Incompatibility with Toonz Harlequin Tutorial Files

### ISSUE THREAD

**Issue by yvanc** [opentoonz/opentoonz#97] opened 2016-03-29 03:31 UTC
I tried to download the Traditional Workflow Materials in this site:
http://www.toonz.com/htm/support/supTWtut.htm

But when I tried to open "\Toonz_TW_Tutorial_Material\Cleaned Up Drawings\b.tlv" nothing is shown but OpenToonz becomes slower.

PS: I'm not sure if the native files used by OpenToonz such as .tlv is proprietary but I couldn't find any specifications for such files. Does anyone know where the specifications or any information to these files be found?

**Comment by odysseywestra** [comment] 2016-03-29 05:23
Have you tried the solution @blurymind had in #80? They are not in the .tlv format. If that works I would close this issue in favor of that one.

**Comment by yvanc** [comment] 2016-03-29 10:42
@odysseywestra I don't think it's related to the layout. The problem is when I opened the tutorial file from the Toonz website the program gets laggy and nothing is shown in the work area.

Here's a video of what I'm talking about:
https://youtu.be/2LP82lqOZJU

**Comment by odysseywestra** [comment] 2016-03-29 17:36
@yvanc video is private so I can't see it.

**Comment by digitallysane** [comment] 2016-03-29 19:08
As discussed here: https://groups.google.com/d/topic/opentoonz_en/VrKShecXoKI/discussion
I couldn't reproduce the problem, Harlequin scenes opened fine in OpenToonz.

**Comment by odysseywestra** [comment] 2016-03-29 19:22
@yvanc what are the specs of the machine you are running this on?

**Comment by yvanc** [comment] 2016-03-30 08:52
@odysseywestra sorry about that. I modified the video to public, see if you can access it.

the specs of my machine are as follows:
Model: Alienware 17 R3
OS: Windows 10 Home 64 Bit
Memory: 16 GB dual channel DDR4 2133MHz
VideoCard: NVidia GeForce GTX 980M 4GB GDDR5
Hard Disk: 256 GB PCIe SSD
CPU: Core i7-6700HQ

**Closed** 2017-05-22 04:40 UTC
Labels: Needs Info
