### ISSUE TITLE
OT1.2 mac tablet issue 

### ISSUE THREAD

**Issue by falls2lawrence** [opentoonz/opentoonz#1679] opened 2017-12-12 18:21 UTC
![tabletissue](https://user-images.githubusercontent.com/22670132/33900556-ad0c4772-df23-11e7-949d-788de5f2956b.gif)

This issue is most easily noticeable using the magnet tool but also heavily effects the tape tool. while using my intuos tablet, when the cursor travels over the tool bar or tools option bar, the cursor (the red circle representing the magnet tool) seems to be lock to the edge of the viewer. clicking into the level strip and back to the xsheet seems to reset the cursor until it travels back to the toolbar or tool option bar.

using my laptop trackpad does not produce this issue; It only happens when using the tablet.

MacBook pro high sierra

**Comment by shun-iwasawa** [comment] 2017-12-13 02:24
Confirmed that the loss of functionality occurs when the pen enters proximity of tablet.

**Comment by artisteacher** [comment] 2018-06-08 00:55
I’m also having both the magnet & tape issues when using a tablet. The tape problems tends to happen after using the fill tool. Otherwise, changing an option in the tool option bar makes the tape tool really unrealiable/hard to control but does kinda maintain some functionality.

**Comment by RodneyBaker** [comment] 2019-07-27 22:25
Is this issue for OT release 1.2 still present in current releases?

**Comment by RodneyBaker** [comment] 2020-01-03 23:13
Recommend closing this after a review of tablet related issues should the issue no longer persist in current releases.  

@falls2lawrence Are you still experiencing similar problems?
It will be good if we can validate that upgrading from v1.2 to current releases, updating a driver or other change resolves the original problem.

**Comment by artisteacher** [comment] 2020-01-06 15:14
@RodneyBaker - I'm not having issues with the magnet tool any longer on macOS 10.14.6 but the tape tool still doesn't work properly when using a Wacom tablet.

**Comment by RodneyBaker** [comment] 2023-09-17 04:56
Closing as the original report appears lkely to be resolved although we haven't had any update since #4860 was merged.
@falls2lawrence @artisteacher If there are still ongoing issues please confirm.

**Closed by RodneyBaker** 2023-09-17 04:56 UTC
Labels: bug, needs info, os-mac
