### ISSUE TITLE
Rendering after import and cleanup renders out of OT with black background

### ISSUE THREAD

**Issue by loris16148** [opentoonz/opentoonz#2623] opened 2019-05-20 17:03 UTC
### Issue Summary
When I try to render after importing a rough sequence (png) and then clean up that sequence in OT, upon export the background is black. This does not happen with other exports and my settings are not set to export in black. 
### Screenshot or Video Reference

![untitled102](https://user-images.githubusercontent.com/6901805/58038897-167f0280-7ae6-11e9-94eb-88e880a25f0f.gif)

### Steps to Reproduce
draw something in another program, export as png. Import png into OT. Scan and cleanup that drawing. color the drawing. I used two colors. Export the drawing as .gif. The drawing background is black. 

### Expected Results
I expect the background to be white as it is upon import and after cleanup

### Actual Results
i looked to see if the other issue that has been submited a while ago applies to my case and it appears that it does not.

### System Information 
* **OpenToonz Version**: 1.3
* **Operating System**: windows 8,1
* **CPU**: i7
* **Memory**: 8 Gig
* **Graphics Card**: intel integrated
* **Graphics Tablet**: wacom cintiq 13hd

**Comment by RodneyBaker** [comment] 2019-05-20 18:59
Just in case... it is important to rule out the alpha channel settings for the scene as transparency is interpreted/displayed as black in many programs

To verify, check the Alpha and Color settings via menu:  Xsheet > Scene Settings.
Default color is black and default alpha channel is fully transparent.
Assuming you want a white background, you may wish to set color to white and alpha to fully opaque.

The animated gif format works quite well with transparency but you may be running afoul of some adverse settings.

Opentoonz may be facilitating the rendering of black background if that setting is not correct.

Another setting to check:
For imported raster images/sequences there is a Level setting that selects a color to be designated transparent.  In one of the many places we can pull up the Level Settings dialog open that and at the bottom check to see if a color is being automatically designated as transparent.
In general this will be the color white as the Japanese animation industry historically drops white out as transparent.

(I'll post some menus as soon as I can fire up OT and grab them)

**Comment by loris16148** [comment] 2019-05-21 00:19
Setting the scene settings to white as background did the trick! I wish i understood better why i have to do this all of a sudden for cleanup frames and i never have before

**Comment by loris16148** [comment] 2019-05-21 00:21
why does it default to black, when everything is set to either transparent or white as far as interpreting the imports goes and background colors respectively. Is this still a bug or my lack of knowledge. Thank you for your help on the matter

**Comment by RodneyBaker** [comment] 2019-05-21 02:54
I don't know the technical/absolute reason why black is used and there are several things going on here at the same time.  

On a practical level (considering interface with the user) the alpha channel/transparency has to be presented in some manner.  Some programs invoke the use a checkered pattern so the user will be able to interpret that area as transparent. 

A problem arises however in the form of image formats and the Alpha channel.
Like the Red, Green and Blue channels each pixel can have a value from 1 to 255.  The Alpha channel in RGBA images similarly can designate grayscale values designating opacity/transparency from  1 to 255.

Many (most) applications will present the alpha channel as black and I suspect this also can be true for conversions... perhaps especially if/when an RGBA image is converted to RGB... as the RGB image has not Alpha channel so it has no choice but to pick a color.  The standard/choice would appear to be black.  I'll go out on a limb an say that might even be an international standard.

Perhaps most importantly... How to prevent this unwanted change?
I'd say the answer would be to have a very good view of what is happening to your image from initial input to final output.  Most programs will have settings that can be monitored and changed as necessary.

An issue with GIF animation is that... you guessed it... there is no alpha channel.
Transparency in the GIF image format is handled by designating a given color as transparent.
This leads to additional difficulties because the program needs to pick a color that isn't elsewhere in the image/sequence.  

It might seem that simply designating the color white to be transparent would be adequate but consider for a moment how many colors have a mixture of white in order to achieve their specific values.  We certainly wouldn't want those gradated areas to drop out as transparent.

My theory of why the color black is used rather than... say.. white... possibly relates to other issues we can encounter with alpha channels and transparency which fall into the realm of Premultiplied Alpha Channels.  Someone likely observed the differences (between use of black vs white) and determined the use of black was the lesser of evils.  Using white in those cases leads to the white halo effect around objects.

Sorry to wander off topic.
Its an interesting topic! :)

As for:  "Is this still a bug or my lack of knowledge?"
It isn't a bug if the code is working as designed and it does help if we know more about a given process.  This can be especially true when transitioning from one file format to another... through one program to another... etc. etc. etc.

You said:
"I wish i understood better why i have to do this all of a sudden for cleanup frames and i never have before"

There was a change in the last major release of Opentoonz that addressed some shortfalls with regard to image formats that do not support alpha channel transparency.  Some of those formats include JPG, BMP and GIF as well as any movie format that does support alpha channels.  What you are experiencing in 'I never had to do this before' is likely a side effect of that fix/enhancement.  Note that the ability to render out to GIF format with animated transparency was an unintentional feature in that and that is good news as very few programs support GIF with fully animated transparency. 

If you want to share your specific workflow... perhaps a video of the process from start to finish... we might be able to deduce more.

**Comment by RodneyBaker** [comment] 2019-05-21 03:06
Closing this issue but discussion can continue and those with better understanding of the process are invited.

Regarding previous discusion about "why black?" I'll add here that one fairly good reason the color black might have been chosen as the default is that on the scale from 1 to 255.. pure black is zero (0)... fully transparent.  So technically speaking black (0) is the most correct color value out of all available values.

**Comment by artisteacher** [comment] 2019-05-21 16:29
I think the black background could be related to #2544 or possibly to #2418.

**Comment by RodneyBaker** [comment] 2019-05-21 21:48
> the black background could be related to #2544 or possibly to #2418.

Thanks!  Yes.  Those are exactly the issues/PRs I had in mind.
There is a lot of good info in what Shun Iwasawa has written there.
Well worth the time reading for those with a desire to better understand the underlying problem.

**Comment by artisteacher** [comment] 2019-05-22 15:36
I'd forgotten about it, but this is probably a duplicate of #2560. There's definitely disparity in the results when trying to render a transparent gif on computers with different specs. I get the same black background on an old iMac, I get a transparent background with ghosting on an old MacBook Pro, and a transparent background without issue on a fairly recent MacBook Pro.

**Comment by RodneyBaker** [comment] 2019-05-22 15:48
@artisteacher As the new gif transparency is/was an unintended feature that derived from that one PR it wouldn't surprise me if there were issues.

Just to check... are those all running a recent (or the latest) release of Opentoonz?
I ask because prior to that PR being merged Ghosting was the ONLY result for GIF transparency. 

As an aside:  There is another issue with GIF and transparency that relates to the first frame leaving artifacts in the transparency.  A workaround for that is to duplicate the first frame (so that both frames 1 and 2 are the first image) and then render starting with frame 2 instead of frame 1.

**Comment by artisteacher** [comment] 2019-05-22 17:15
The old MacBook pro is running a late April release, the others are both current.  This is similar to when we had all of the plastic rendering issues on Mac and Linux. Some of us had blue backgrounds, others had artifacts and/or ghosting.

**Closed** 2019-05-23 09:46 UTC
