### ISSUE TITLE
Scrubbing or playing audio causes OpenToonz to crash in macOS Sierra 10.12.3

### ISSUE THREAD

**Issue by NoahTheAnimator** [opentoonz/opentoonz#1101] opened 2017-03-14 16:48 UTC
Whenever I import audio, I can play all the way through it and then it crashes. If I scrub through it a tiny bit, it also crashes. fix plz

**Comment by turtletooth** [comment] 2017-03-14 16:55
Duplicate of #978

**Closed by turtletooth** 2017-03-14 16:55 UTC
