### ISSUE TITLE
Drawings not shown

### ISSUE THREAD

**Issue by Shadoworker** [opentoonz/opentoonz#1716] opened 2018-01-04 00:42 UTC
I've downloaded Otoonz but my drawings aren't being displayed on the scene, the traditional animation table image isn't appearing !!!!

**Comment by jpturcotte** [comment] 2018-01-04 01:03
Can you tell us more, and preferably send a video or some screenshots of what is happening, please? What are you trying to do? What are your operating system and OpenToonz version? Thank you!

**Comment by turtletooth** [comment] 2018-01-04 01:10
Can you try the modified version here?  https://gum.co/ZgxH

This is probably the same issue that many others have had.

**Comment by manongjohn** [comment] 2018-01-04 01:11
This is likely a duplicate of #1674

**Comment by Shadoworker** [comment] 2018-01-04 01:32
I'm on windows 10 and using the 1.2.0 version of OToonz

Here is what i get 
![image](https://user-images.githubusercontent.com/13294161/34546917-1e279844-f0ef-11e7-90fa-d9386bcc50f9.png)

**Comment by manongjohn** [comment] 2018-01-04 02:09
Yes, it does appear to be the same issue. Using the OTX version mentioned above should get you past this problen for now.

**Comment by Shadoworker** [comment] 2018-01-04 07:39
I'm having the same issue with this version. 
My Graphic Card OpenGL version is 1.1, do you think that the problem may come from there ?

LENOVO G550
windows 10

**Comment by Shadoworker** [comment] 2018-01-04 09:11
I previously downloaded the standard release of the OTX and it didn't work. The Modified release worked for me.

![image](https://user-images.githubusercontent.com/13294161/34556582-c54c2d80-f12e-11e7-8c06-47cce541293e.png)

Thank you guys !

**Closed** 2018-01-20 03:52 UTC
Labels: Duplicate
