### ISSUE TITLE
Crash with Selection Tool in Toonz Raster Level (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1475] opened 2017-09-13 21:11 UTC
This problem is similar to #1209
![ezgif-2-c76d33def5](https://user-images.githubusercontent.com/25724133/30400898-06251552-98e1-11e7-9d93-98959845c06c.gif)

**Comment by artisteacher** [comment] 2017-09-13 21:43
I'm not getting this result. What build are you using?

**Comment by manongjohn** [comment] 2017-09-14 02:33
I can duplicate this on a Windows build.  Only happens on Raster levels.  Doesn't happen on Vector levels.

**Comment by beeheemooth** [comment] 2017-09-14 08:56
Oops, I did not specify that the problem happens only in the Raster and Toonz Raster levels.

**Comment by konero** [comment] 2017-09-14 10:37
@manongjohn Sorry for going off-topic here, but since you do a lot of issue solving... 👍 

If you add `fixes #1475`, or `resolves #1475`, or `closes #1475` to your PR title or anywhere in the textarea, the issue will automatically close when your PR gets merged. Like this...

`This PR fixes #1475.`

I don't use Git a lot but I think that's still the case. I noticed some issues sometimes linger open even though they've been resolved.

_Info: https://github.com/blog/1506-closing-issues-via-pull-requests_

**Comment by manongjohn** [comment] 2017-09-14 11:04
@konero Nice. Didn't know that could be done. Thanks for the info!

**Comment by turtletooth** [comment] 2017-09-23 05:32
Confirmed the fix.  LGTM.  Thanks @manongjohn

**Closed** 2017-09-23 05:33 UTC
