### ISSUE TITLE
 does not start (K-Lite Codec Pack)

### ISSUE THREAD

**Issue by Camila28Lopez** [opentoonz/opentoonz#5090] opened 2023-09-07 20:23 UTC
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-09-07 16:19:25
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 8

Crash File: C:\Users\COREi5\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230907-161925.log
Mini Dump File: C:\Users\COREi5\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230907-161925.dmp

==== Modules ====
D:\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\System32\USER32.dll
D:\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\win32u.dll
D:\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\COMDLG32.dll
D:\OpenToonz\glut64.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\shcore.dll
D:\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\OLEAUT32.dll
D:\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SHLWAPI.dll
D:\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
D:\OpenToonz\image.dll
D:\OpenToonz\tnztools.dll
D:\OpenToonz\tnzstdfx.dll
D:\OpenToonz\tfarm.dll
D:\OpenToonz\Qt5Widgets.dll
D:\OpenToonz\sound.dll
D:\OpenToonz\toonzqt.dll
D:\OpenToonz\Qt5Core.dll
D:\OpenToonz\Qt5Gui.dll
D:\OpenToonz\opencv_world451.dll
D:\OpenToonz\toonzlib.dll
D:\OpenToonz\Qt5Script.dll
D:\OpenToonz\tnzext.dll
D:\OpenToonz\tnzbase.dll
D:\OpenToonz\Qt5OpenGL.dll
D:\OpenToonz\tnzcore.dll
D:\OpenToonz\Qt5Multimedia.dll
D:\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
D:\OpenToonz\MSVCP140_1.dll
D:\OpenToonz\MSVCP140.dll
D:\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MF.dll
D:\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
D:\OpenToonz\libmypaint-1-4-0.dll
D:\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
D:\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
D:\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
D:\OpenToonz\libintl-8.dll
D:\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
D:\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
D:\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\OpenToonz\styles\qwindowsvistastyle.dll
D:\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d60a3faa7932ec00\ig9icd64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d60a3faa7932ec00\igdgmm64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d60a3faa7932ec00\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d60a3faa7932ec00\igdml64.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\WINDOWS\SYSTEM32\ff_vfw.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.2070_none_2713e6537381f706\COMCTL32.dll
C:\Program Files\K-Lite Codec Pack x64\Filters\ffdshow\ffdshow.ax
C:\WINDOWS\SYSTEM32\DINPUT.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\inputhost.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffe055e7a9a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffe0558e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffe05612dee] <ntdll.dll>
  4> DriverProc [0x7ffde8e052e3] <ff_vfw.dll>
  5> ICSendMessage [0x7ffdf946413e] <MSVFW32.dll>
  6> TSmartPointerT<TXshColumn>::operator> [0x7ffded987498] <image.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ffded984bb6] <image.dll>
  8> initImageIo [0x7ffded927ace] <image.dll>
  9> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff76dcc0dae] <OpenToonz.exe>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff76dcc2d41] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76e0eeab7] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76e0ee092] <OpenToonz.exe>
 13> BaseThreadInitThunk [0x7ffe037c26ad] <KERNEL32.DLL>
 14> RtlUserThreadStart [0x7ffe055caa68] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment] 2023-09-16 21:05
Please investigate the K-Lite codec pack you have installed on your system.
That is a likely suspect for your current problems.

**Comment by RodneyBaker** [comment] 2023-09-17 22:20
I'm tagging this as a duplicate of #5052 although that may or may not be the case...
Will keep open for now pending additional information from @Camila28Lopez that confirms status.

**Comment by clsid2** [comment] 2023-09-19 22:22
The 64-bit version of ffdshow VFW (ff_vfw.dll) is not compatible with Windows 8/10/11. It looks like a very old version of K-Lite is installed. Updating to latest version should solve the problem.

**Comment by RodneyBaker** [comment] 2023-10-15 14:12
Closing as likely resolved and/or abandoned.

**Closed by RodneyBaker** 2023-10-15 14:12 UTC
Labels: troubleshooting, duplicate, incomplete report
