### ISSUE TITLE
Glicth using Plastic Tool

### ISSUE THREAD

**Issue by jeneverito** [opentoonz/opentoonz#1337] opened 2017-07-21 23:21 UTC
By testing the "Plastic tool" I discover an error, the whole image is a glitch to the exception of the image with the active skeleton.
[GlitchPlasticTool_video.zip](https://github.com/opentoonz/opentoonz/files/1166955/GlitchPlasticTool_video.zip)

 under UbuntuStudio 14.04 32 bit and OpenToonz Morevna edition

Thanks in advance

**Comment by turtletooth** [comment] 2017-07-30 21:20
This is a duplicate of #1096 
Closing.

**Closed by turtletooth** 2017-07-30 21:20 UTC
