### ISSUE TITLE
(Plastic Tool) Inappropriate box mesh

### ISSUE THREAD

**Issue by Azusapink** [opentoonz/opentoonz#406] opened 2016-06-05 16:20 UTC
Whenever i create the vector in opentoonz or convert my image to vector and then add mesh to it the plastic tool> create mesh button creates a box mesh around the image instead of just the out line.

any ideas on how to remove this box?
![screen shot 2016-06-05 at 10 16 09 am](https://cloud.githubusercontent.com/assets/5882245/15806708/6d55c49c-2b0f-11e6-8920-afa6efe35223.png)

**Comment by animking** [comment] 2016-07-14 13:55
may be due to minimize raster memory fragmentation is on.

**Comment by artisteacher** [comment] 2017-05-25 02:14
Looks similar to the overflowing special styles for vector levels  #891.

**Comment by Silencedpulse** [comment] 2017-08-26 13:04
On Mac Sierra I have the same problem. It even occurs if I draw within OpenToonz and try to create a mesh for plastic binding. I've checked and Minimize Raster Memeory is off. I turned it on and off again but no luck. Any help would be greatly appreciated.

**Comment by artisteacher** [comment] 2017-09-01 22:05
I think someone in another issue discussed placing the vector level in a sub-xsheet before adding the mesh as a workaround. It's an extra step but does work.

**Comment by Silencedpulse** [comment] 2017-09-01 23:53
Artisteacher I had read that. The other thing I've done is draw it as a raster, apply the mesh which does work properly, then convert the column to Vector and it works as well.
Thanks for the feedback.

**Comment by kbilinski74** [comment] 2018-06-22 18:33
Still the same problem OS X. Inaccurate grid (Create mesh). The created grid has the shape of a square.
![zrzut ekranu 2018-06-22 o 16 45 04](https://user-images.githubusercontent.com/40501000/41793130-72690de2-765b-11e8-873c-d36c89e863e0.png)

**Comment by artisteacher** [comment] 2018-06-25 02:59
Yep, there’s been no change. Hopefully this can be fixed in 1.2.2 along with the generated vector styles of #891. Since the drawing outline is ignored in both issues, and a rectangular boundary used instead, hopefully a fix for one will lead to a fix for the other.

**Comment by RodneyBaker** [comment] 2018-12-15 17:09
Part of this was addressed by #2105 but the plastic mesh elements presumably still haven't been resolved (Ref:  #2300)  Workarounds exist for that particular case which should be detailed.

**Comment by artisteacher** [comment] 2018-12-15 18:42
I believe it can’t be reproduced in old versions of OSX but is a problem in recent versions and I’ve experienced this from 10.11 to the latest version of MacOS. If the mesh is applied directly to a vector level, the shape is always rectangular. If the vector level is in a sub-Xsheet & the mesh is applied to the sub-Xsheet, the mesh shape looks as it should.

**Comment by RodneyBaker** [comment] 2018-12-15 18:52
I can get something akin to this rectangle if and only if I increase the mesh margin(pixels) setting up to over 1000.

This suggests a place to look ESPECIALLY if DPI is a factor that needs to be taken into account.

**Comment by artisteacher** [comment] 2018-12-15 19:31
I can’t get below 2, but there’s still a rectangular mesh shape. It doesn’t seem to matter how high or low the edge length, dpi nor mesh margin is - some settings make the mesh bigger but it’s still a rectangle.

**Comment by artisteacher** [comment] 2019-12-19 19:44
On a 2017 iMac with Intel Iris Plus Graphics 640 1536 MB and a MacBook Air with Intel UHD Graphics 617 1536 MB (both running Mojave), I'm not seeing the box mesh on vector levels. It is still an issue on 2011 iMac's running High Sierra and a 2016 MacBook Pro running Catalina. Perhaps this is only an issue with hardware prior to 2017?

**Comment by RodneyBaker** [comment] 2020-01-30 01:22
Tagging as a known issue for specific Mac hardware although exact hardware hasn't been fully pinned down yet.

No box mesh displaying on:
- 2017 iMac with Intel Iris Plus Graphics 640 1536 MB (Mojave)
- MacBook Air with Intel UHD Graphics 617 1536 MB (Mojave)
- In general any hardware 2017 and newer

Still presumed to be an issue on older hardware to include:
- 2011 iMac's running High Sierra 
- 2016 MacBook Pro running Catalina

Thanks to everyone for investigating!

**Comment by anoopalexwork** [comment] 2021-04-04 13:37
I am using Ubuntu 20.04 and seeing this box mesh on vector levels currently. I have Opentoonz 1.4. I can only get it working in vector currently by drawing the shape in raster, making a mesh level, pasting the shape into a vector level, then connecting the raster mesh to the vector level using schematics.

**Comment by RodneyBaker** [comment] 2022-08-13 23:34
Somewhere else we have mentioned a possible work around for the inappropriate box mesh creation with plastic tool.
I am curious if the workaround works in these cases also.

Workaround
Prior to creating a plastic mesh... turn the target column (even if only a single column) into a subxsheet.
Then create the mesh.

**Comment by RodneyBaker** [comment] 2022-09-07 09:01
If Mac and Linux users can confirm that creating a plastic mesh on a subxsheet still results in a box mesh... or doesn't... that will be appreciated.

**Comment by cattegamer15** [comment] 2023-05-30 02:31
I am on Debian 11 and having the same issue on opentoonz 1.7.1 i tried to collapse the vector level and create a mesh,It worked but when i create the skeleton and try to animate the drawing and skeleton dissapears and lags a lot

**Comment by artisteacher** [comment] 2023-06-03 13:39
I can't trigger the box anymore on my MacBook at home but I think I still get it on occasion on the iMac at school when I'm using a projector. Never have a problem with sub-xsheets though.

**Comment by flurick** [comment] 2023-06-15 11:49
I could reproduced this just now in a linux build from a few weeks ago, 
not again in a newer ones though. (Even the 1.7.1 flatpak seems to work atm)

@cattegamer15 any change for you, if not which download link did you use?

Non win32 builds are set to use the default opengl settings for vector levels, 
which explains why the subscene workaround works. And probably that the issues is weird opengl default settings not.

```
#if defined(_WIN32)
    ...
  fmt.setAlpha(true);
    ...
  fmt.setStencil(true);
#elif defined(MACOSX)
  fmt = QGLFormat::defaultFormat();
``` 
[qtofflinegl.cpp](
https://github.com/opentoonz/opentoonz/blob/dd1ea1ebe625545ad201f23e8b1db40566784c46/toonz/sources/common/tvrender/qtofflinegl.cpp#L130)

**Comment by RodneyBaker** [comment] 2023-11-19 09:52
Looking at this report as a candidate for closure.
Opentoonz users still experiencing the problem while using current nightly releases are encouraged to report that.

**Comment by RodneyBaker** [comment] 2024-05-30 20:04
Closing as an issue that appears to apply only to older systems no longer supported.
For those experiencing the box mesh with Plastic Tool recommend opening a new report referencing this report and detaling the specifics of the operating system being used.

**Closed by RodneyBaker** 2024-05-30 20:04 UTC
Labels: bug, os-mac, known issue, workaround
