### ISSUE TITLE
Horizontal timeline

### ISSUE THREAD

**Issue by pculli** [opentoonz/opentoonz#869] opened 2016-10-18 05:47 UTC
Most of the animation softwares nowadays have a horizontal timeline. Now, OpenToonz rather than a timeline has an XSheet.

Would it be possible to add a horizontal timeline, similar, maybe, to that of TVPaint?
I think it could be an addition to the XSheet, rather than a replacement.

I'm thinking of the two most used animation softwares in the world for examples, TVPaint and Toon Boom Harmony. 

One has a large, preview based timeline, and the other, a smaller, keyframe based timeline.

TVPaint:
![captura](https://cloud.githubusercontent.com/assets/22903817/19465723/a7c6aaf6-94dc-11e6-95ad-3bd7e7b92ece.PNG)

Toon Boom Harmony
![captura 2](https://cloud.githubusercontent.com/assets/22903817/19465727/aeea5742-94dc-11e6-8873-7b82f1800b3e.PNG)

Now, TVPaint is similar to OpenToonz in what it wants to achieve. Good 2D traditional/tradigital animation software, so I'm thinking in this case, the TVPaint solution is better. BUT, in order to use the Plastic Tool and other animation tools inside OpenToonz, the "view all keys in timeline" Toon Boom Harmony idea is quite good too. 

I'll try to come up with something between the two, but I think, any shape it takes, would be a massive addition to OpenToonz.

**Comment by adamearle** [comment] 2016-10-18 06:27
This sounds fantastic

Adam

**Comment by turtletooth** [comment] 2016-10-20 19:05
This is a duplicate of #503.

**Closed by turtletooth** 2016-10-20 19:05 UTC
