### ISSUE TITLE
Blur effect not working in render

### ISSUE THREAD

**Issue by Snevetz74** [opentoonz/opentoonz#3483] opened 2020-09-16 23:21 UTC
I'm able in the F/X schematic to parent a node to the child node (insert "blur effect") connected to the X-sheet and output. It works fine in preview mode. However when I render the mp4, the blur effect is gone. Using windows 10

**Comment by RodneyBaker** [comment] 2020-09-17 06:57
Just in case, make sure the Preview Visability toggle is on or else the column will not render to final output.

![image](https://user-images.githubusercontent.com/2576432/93430940-1123fa80-f889-11ea-893c-36fa9edd295a.png)

**Comment by Snevetz74** [comment] 2020-09-17 13:51
Sounds good . Will try that shortly

**Comment by RodneyBaker** [comment] 2020-09-27 00:52
Any update @Snevetz74 ?
Hopefully the problem is now resolved.

**Comment by RodneyBaker** [comment] 2020-12-23 18:40
Closing as likely resolved and/or abandoned.
@Snevetz74 please let us know if that is not the case.

**Closed by RodneyBaker** 2020-12-23 18:40 UTC
Labels: needs info

**Comment by Snevetz74** [comment] 2020-12-24 15:43
Resolved.. thank you
