### ISSUE TITLE
OpenToonz crash

### ISSUE THREAD

**Issue by inFables** [opentoonz/opentoonz#5092] opened 2023-09-09 14:23 UTC
### Description

OpenToonz 1.7.1  (Build May 10 2023)

Report Date: 2023-09-09 16:21:00
Crash Reason: (SIGABRT) Usually caused by an abort() or assert()

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 22.4.0
CPU Threads: 8

Crash File: /Users/m.k.sLibrary/Application Support/OpenToonz/OpenToonz/crash/Crash-20230909-162100.log

==== Backtrace ====
  1> 3   ???                                 0x0000000000000000 0x0 + 0
  2> 4   libsystem_c.dylib                   0x00007ff8091d9b45 abort + 123
  3> 5   libc++abi.dylib                     0x00007ff80926d282 abort_message + 241
  4> 6   libc++abi.dylib                     0x00007ff80925f3fb _ZL28demangling_terminate_handlerv + 267
  5> 7   libobjc.A.dylib                     0x00007ff808f33a7f _ZL15_objc_terminatev + 104
  6> 8   libc++abi.dylib                     0x00007ff80926c6db _ZSt11__terminatePFvvE + 6
  7> 9   libc++abi.dylib                     0x00007ff80926efa7 __cxa_get_exception_ptr + 0
  8> 10  libc++abi.dylib                     0x00007ff80926ef6e _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
  9> 11  libtnzcore.dylib                    0x000000010ebf3ef2 _ZN7TSystem5mkDirERK9TFilePath + 1266
 10> 12  libtnzcore.dylib                    0x000000010ebe72be _ZN11TImageCache10setRootDirERK9TFilePath + 270
 11> 13  OpenToonz                           0x0000000104437b8c main + 7660
 12> 14  dyld                                0x0000000204e5141f start + 1903
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

macOS

### GPU

Other

### Graphics Tablet

XP-Pen

**Comment by RodneyBaker** [comment] 2023-09-09 18:33
It is possible that this is a Mac related issue caused by current building environment.
Other than that... more information required.

There is a PR adjusting Boost dependency that is pending.
I don't think that will resolve this issue but that along with general Mac build updates may.

**Comment by RodneyBaker** [comment] 2023-09-17 04:51
Closing as not having sufficient actionable information to troubleshoot the problem.
@inFables If you have additional information you can share please feel free to add that here or in any of the other similar reports.

**Closed by RodneyBaker** 2023-09-17 04:51 UTC
Labels: os-mac, incomplete report
