### ISSUE TITLE
Add the community development Road Map image to the repo Readme

### ISSUE THREAD

**Issue by Emasoft** [opentoonz/opentoonz#266] opened 2016-05-01 10:07 UTC
Add the community development Road Map image to the readme

https://sites.google.com/site/youropentoonz/

https://docs.google.com/drawings/d/1Rr81BgpUCABqV6ZDXPXoDzVqfTz7AbToBYMm6_MpwVI/edit?usp=sharing

![opentoonz development road map](https://cloud.githubusercontent.com/assets/713559/14941258/46547eaa-0f95-11e6-9e9e-f63564581399.png)

**Comment by blurymind** [comment] 2016-05-01 10:35
This is a roadmap you made as a wishlist? The svg format does not support
many of the features of the current format. I dont think it will be able to
replace it. That depends on people who make the svg specification more than
toonz devs
On 1 May 2016 11:07, "Emasoft" <notifications@github.com> wrote:

Add the community development Road Map image to the readme

https://sites.google.com/site/youropentoonz/

https://docs.google.com/drawings/d/1Rr81BgpUCABqV6ZDXPXoDzVqfTz7AbToBYMm6_MpwVI/edit?usp=sharing

[image: opentoonz development road map]
<https://cloud.githubusercontent.com/assets/713559/14941258/46547eaa-0f95-11e6-9e9e-f63564581399.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/opentoonz/opentoonz/issues/266>

**Comment by blurymind** [comment] 2016-05-01 12:26
I also would like to see a roadmap - but that is something that should be made by the developers- not the users.

Developers who know the code really well, who have previously contributed to it, know the limitations of file formats and their goals (svg), and have coordinated a board meeting in which to discuss the short and long term goals.
Right now It is really easy to see who those people are: https://github.com/opentoonz/opentoonz/pulse
People who know what's doable, know what's missing, know in what order to implement things.
Our job as users is only to inform them what's missing or what would be important to have.

@Emasoft you cant outline a roadmap to software which you are not writing yourself. It's like going to the blender bug tracker and posting a roadmap of your wishlist. I agree we should have one, but not like this.
Developers should outline a roadmap when they are ready.

They need to start having some kind of board meetings like the blender foundation.

**Comment by Emasoft** [comment] 2016-05-01 14:59
What are you talking about?
1 - I have not made the road map. That was created by the community. I just added my contribution like everybody else, with the svg features balloons.
2 - I'm writing the SVG features myself. Have you missed my post on this? It is here: https://github.com/opentoonz/opentoonz/issues/183

**Comment by blurymind** [comment] 2016-05-01 15:18
@Emasoft can you link us to the thread where people contribute ideas to compile the image you shared? It would be good to see more information.
Are any of the people making the roadmap planning on how to implement said features on the roadmap? If not- then its a wishlist regardless of who made it.

On the svg features - I am completely against replacing the current proprietary format for saving the project and the drawings. I am with you for exporting to animated svg, but replacing the actual format that OT uses to store project data is a bad idea - especially when what you want to replace it with doesnt support or have these features on it's roadmap.

You've been lobbying to put animated svg on the vpaint's github and already logged an issue about it here as well - thats why when I saw that mindmap I thought that it is your personal wishlist.

2. Your fork does not yet have any code that is not already here. Forking OT can be done by literally anyone - even non programmers can fork a github project. I am however looking forward to seeing animated svg support exporting. So I will keep an eye on it.

**Comment by Emasoft** [comment] 2016-05-01 20:55
@blurymind I think that it is a little early to talk about the complete replacement of the native format of OT with SVG. We'll talk about it after completing the export feature. By then there will be SVG 2.0 out, and many things that OT does would be replicable in SVG, with or without metadata (Inkscape alternative format is still perfectly valid SVG. It just adds metadata. If you are familiar with XML, you know that you can extend an XML format to include any proprietary data without breaking compatibility. Many features now part of the SVG spec where once just some metadata added by a single software to extend SVG. Eventually we can even ask the SVGWG to add what we added to the file to the official SVG standard. I think that an open source software should use an open standard file format to be truly open, not a proprietary and closed one that no one else can import or exchange. Anyway, we will discuss this when the time will come. Now I need at least a couple of months to write and debug the SVG exporter feature. Then we'll think about the pro and cons of replacing the native format of OT with an open standard.

**Comment by Juls3000** [comment] 2016-05-02 08:15
@Emasoft, I agree with @blurymind (*). 

It is important be precise with the terms, IMO to speak about one "comunity development road map" is not consistent with the real situation. 

Certain number of people initially interested, to some degree, in this software can make a whislist, whith a conceptual map shape, if you want. But the development road map is something different, is a very sensitive tool, which is esential that developers will manage appropiatelly for the feassibility of the project.

(*)
https://github.com/opentoonz/opentoonz/issues/267#issuecomment-216033650

**Comment by blurymind** [comment] 2016-05-02 08:27
The termn 'comunity roadmap' is incredibly vague. The actual roadmap has a lot of features that will benefit nobody but people who use other software with ot. It loiks like something someone made in 5 minutes anf put together in a mindmap app on the top of their head.

Opentoonz needs to sort out regressions from harlequin. It needs to improve its paperless drawing tools and its animation tools. It needs a lot of things that are not on the roadmap you made. It looks like a map made by a file fortmat export enthusiast, not an actual animator using the software

**Comment by adamearle** [comment] 2016-05-02 09:31
I think this is what you are talking about
https://docs.google.com/drawings/d/1Rr81BgpUCABqV6ZDXPXoDzVqfTz7AbToBYMm6_MpwVI/edit

From what i can read it is a mind map and the beginnings of a roadmap.
Perhaps you should consider adding to it.

I just changed some of it so I guess you can add to it as well. Looks it
really community oriented.


*Adam Earle*

**Comment by Juls3000** [comment] 2016-05-02 09:55
@adamearle IMO this is just a mindmap, as explained above a road map is another thing. 

This roadmap can incorporate, or not, alements of this mindmap, issues of this GhitHub, and items of a variety of fonts, e.g. the official user forum. 

But the developers are who has the necessary vision to integrate all this information in the road map.

**Comment by blurymind** [comment] 2016-05-02 10:05
Yes! @Juls3000 put it in the best possible way.

**Comment by turtletooth** [comment] 2017-01-18 22:15
I'm going to close this as there is already a huge backlog of feature requests and this is more of a wish list than an actual roadmap.

**Closed by turtletooth** 2017-01-18 22:15 UTC
Labels: Documentation, Feature Request
