### ISSUE TITLE
Can't adjust thickness of zero-thickness lines

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2400] opened 2018-12-04 21:03 UTC
### Issue Summary

 I periodically have students who draw all of their lines using zero-thickness unintentionally so they need to be able to correct all of their linework in a scene. That can be incredibly time consuming using the pump tool. We should be able to use "Adjust thickness" from the program menu (Levels -> Adjust Thickness), but it does not work on zero-thickness lines. It's understandable that the scaling mode won't work on something with the size of zero, but adding to the thickness should work.
### Screenshot or Video Reference

![screen shot 2018-12-04 at 4 07 41 pm](https://user-images.githubusercontent.com/21159116/49472960-c386ec80-f7de-11e8-93be-7e0e2e47a8fd.png)

### System Information
* **OpenToonz Version**: Nightly build from early September
* **Operating System**: MacOS 10.13.6
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by artisteacher** [comment] 2018-12-07 16:51
So as a workaround, using the pump tool through the select tool when set to "whole level" or etc. does work to add thickness to zero lines (at least when using a mouse). I still think that the "add thickness" mode of "adjust thickness" should work for lines of any thickness - it allows for far greater precision.

**Comment by RodneyBaker** [comment] 2018-12-07 20:29
Closing this as the feature is working as intended.
Please feel free to continue the discussion.

An option to allow for zero thickness lines would be nice to have added to that process.
It would be best to keep it optional however because zero thickness lines are a means to safeguard or hide specific lines in a setup.  One case would be the one stated which is to increase the thickness of all lines including those with zero thickness.  Another case might be that a user would want to use the Adjust Thickness dialog but leave those zero thickness lines as is.  A fuller solution/enhancement then might be to allow for a target range of line thicknesses (minimum and maximum) to be set.

Aside:
We can open a github Project to collect Feature requests with the idea that such requests are acknowledged but awaiting a developer to champion the request.  At the point where the request is being actively developed the issue can then be reopened or a new issue created with reference to the initial request can be created.  

Closed issues can still be commented on and OpenToonz users are encouraged to provide additional information to update the status of any issue.

**Closed by RodneyBaker** 2018-12-07 20:29 UTC
Labels: Enhancement, Feature Request

**Comment by artisteacher** [comment] 2018-12-07 22:15
I can see how there are some cases where changing zero thickness lines could be inconvenient. The “scale thickness” mode should always ignore zero thickness lines because a percentage of zero is still zero.  However for at “add thickness” and maybe “constant thickness” I do really like the idea of being able to set a range of sizes for adjust thickness. It would allow for a lot more flexibility!
