### ISSUE TITLE
How to handle OpenGL drivers that don't support off-screen antialising?

### ISSUE THREAD

**Issue by deanmoriart** [opentoonz/opentoonz#1166] opened 2017-04-24 17:39 UTC
I tried a lot of animation softwares and nearly all of them has a solid antialising system on preview while drawing. I can never get the same stroke quality in open toonz no matter what I do. I am trying to minimize the problem with soft brushes for now. I am on linux. Is this a known problem ? 

Other than that this app is just wonderful. Don't know how to thank you.

**Comment by deanmoriart** [comment] 2017-04-25 19:44
![screenshot_2017-04-25_22-41-00](https://cloud.githubusercontent.com/assets/27736315/25404411/81ffd236-2a08-11e7-94e0-46ef80cdcf1b.png)

This line is vector and that's how it looks in 1080p..

**Comment by deanmoriart** [comment] 2017-04-25 20:09
![test](https://cloud.githubusercontent.com/assets/27736315/25405446/fe9b89b8-2a0b-11e7-8c69-5aa7c28b3f4f.png)

And this is a vector line from Tupi. (Again 1080p)

**Comment by RodneyBaker** [comment] 2017-04-25 20:36
Just to check....

Is it possible you have 'Display vector as Raster' turned on?

**Comment by deanmoriart** [comment] 2017-04-25 20:45
@RodneyBaker Just checked it, it's off. Actually preview window is not that important to me but it effects output as well.

**Comment by artisteacher** [comment] 2017-04-26 11:32
Do you have the camera preview toggled on or off? Try adjusting the view to actual pixel size (N) - if the line quality is still poor, then there is a problem. 

Occasionally I've had issues where the vector lines all look extra jagged but it is very inconsistent. Often restarting the program returns the view of the vector line quality back to normal - on OS X.

**Comment by deanmoriart** [comment] 2017-04-26 13:08
@artisteacher Thanks for the suggestions. But camera preview is off. It gets more jagged when I enable it. Bad thing is, it effects the output image not just a preview problem.

**Comment by artisteacher** [comment] 2017-04-26 14:33
Have you added additional vector brushes? It might not be related but I believe that I first noticed this after adding new brushes. Drawing was pretty laggy too. I ended up removing the new brushes and I don't think I've had the problem since.

**Comment by morevnaproject** [comment] 2017-04-26 15:01
Hello @deanmoriart! Yes, this is a known problem and it is related with videocard driver. I have no antialiasing on Intel card (native OS drivers), but with the same build antialiasing works fine on other machine with NVidia card (proprietary driver). As @blackwarthog suggests, installing official Intel drivers from Intel website could solve the problem, but I didn't tested that yet.

**Comment by deanmoriart** [comment] 2017-04-26 15:25
@morevnaproject  @blackwarthog Hey thanks for writing in. So I guess it's better go with raster for a while since ati graphic cards was already a huge pain in linux I better not to touch any driver again :) . Do you think if there is any hope to fix it in the next releases or it will stay as driver problem ?  

Just for the record my graphics card is  "[AMD/ATI] RV730/M96-XT [Mobility Radeon HD 4670]"

Thank you

**Comment by deanmoriart** [comment] 2017-04-27 16:20
@artisteacher sorry I didn't see your last reply. I havent installed any vector brushes, using the regular one. 

Can someone send a smooth vector line screenshot from Opentoonz please ?

**Comment by RodneyBaker** [comment] 2017-04-27 17:27
Here's the requested screenshot of a smooth vector line:

**Comment by deanmoriart** [comment] 2017-04-27 18:25
Thanks a lot @RodneyBaker . 

So the question is  Why it is effecting the output if it's about graphic card problem ? It should show it as jagged in the preview window but should render correctly as my noob logic saying to me since vector is a   dot in space positioned as mathematical info right ? And why other apps doesn't have that problem ?

**Comment by RodneyBaker** [comment] 2017-04-27 19:21
I'm not sure I fully understand the question because the output isn't being effected other than the fact that vector has to be rendered to raster in most image formats.

The same smooth line that is showing in the preview window is rendering as (relatively) smooth raster output on my end.

Two questions suggest themselves based on this observation:
What is different between your system and mine?
The obvious answer is that you are using Linux and I'm using Win10 but of course there are a lot more variables than that.

Attached is the output of a single three point vector line (thickened by the pump tool) to form a leaf-like line.  This is directly rendered out of Opentoonz to my desktop.

![vectorlines 0001](https://cloud.githubusercontent.com/assets/2576432/25500382/7bd76a66-2b54-11e7-8cb2-c6a4ab146d6a.png)

The second question is similar to the first and that is;  What settings in OpenToonz might be resulting in different display and output?  

Regarding the second we likely need to see a video screen capture of your process and share some files.

**Comment by deanmoriart** [comment] 2017-04-27 22:05
Thank you for your interest @RodneyBaker . This is the most smooth output I can get from vector level.  No matter how high the resolution is it still looks so jagged.(and those jagged parts moves during animation so it becomes more problematic. I thought I was seeing the line like that because of my graphic card but I can see other people's export smooth and without any problems just like your leaf line.So I don't know what's happening.

![untitled31 0001](https://cloud.githubusercontent.com/assets/27736315/25506328/b095b410-2bae-11e7-87fa-2e5a13e2e86f.png)

![untitled30 0001](https://cloud.githubusercontent.com/assets/27736315/25506340/bea91394-2bae-11e7-9138-9025065bffe7.png)

**Comment by morevnaproject** [comment] 2017-04-28 01:59
@deanmoriart  

> So the question is Why it is effecting the output if it's about graphic card problem ? It should show it as jagged in the preview window but should render correctly as my noob logic saying to me since vector is a dot in space positioned as mathematical info right ?

The rendering uses functions of graphic card to process the rendering output. This is why you get aliasing problem on both preview and render.

> Do you think if there is any hope to fix it in the next releases or it will stay as driver problem ?

As far as I know, this can be fixed (at least on rendering level) by implementing antialiasing with software (for the cases when hardware support for necessary functions is missing).
But at the moment this is not on our plans.

**Comment by ideasman42** [comment] 2017-04-28 03:54
Note that using rendering multiple times with jitter and accumulating can work well, Blender uses this calling it 'full samples'.
It has the advantage that it doesn't depend on the graphics drivers AA implementation.

https://developer.blender.org/diffusion/B/browse/master/source/blender/editors/space_view3d/view3d_draw.c;a85f457195045dff3d31d4de739d9a98fba62cc2$3358-3418

**Comment by deanmoriart** [comment] 2017-04-28 17:52
@morevnaproject I understand. Thank you.

**Comment by jpturcotte** [comment] 2017-04-28 17:56
@ideasman42 Could something similar be easily implemented in OpenToonz?

**Comment by ideasman42** [comment] 2017-04-28 18:07
> @ideasman42 Could something similar be easily implemented in OpenToonz?

I don't see why not, though I don't know this code in OpenToonz well.

**Comment by morevnaproject** [comment] 2017-04-28 18:26
@deanmoriart As a temporary workaround, you can render with double resolution and then scale your video down.

**Comment by deanmoriart** [comment] 2017-04-28 19:04
@morevnaproject That worked ! So editing app fixes it while scaling down ? Thanks a lot I really needed that workaround.

![sc](https://cloud.githubusercontent.com/assets/27736315/25543198/2bdcc37a-2c5e-11e7-9aa6-f794e7c2ea06.png)

**Comment by deanmoriart** [comment] 2017-05-02 21:14
Hey, just for the info;

I managed to have perfect smooth lines on preview window with enabling Morphological anti-aliasing based on Jimenez'MLAA in Driconf settings. ..(I don't know what all of this about but it worked) It doesn't fix output tho.

**Comment by jpturcotte** [comment] 2017-05-02 22:53
What is that? Could you tell us more, please?

**Comment by deanmoriart** [comment] 2017-05-02 23:20
It's a configuration tool(applet) for open source drivers in ubuntu. You can find more info in here. 

https://dri.freedesktop.org/wiki/DriConf/

I changed this setting to 12 and it totally fixed the problem for me in preview window. Output still looks jagged.

![sc](https://cloud.githubusercontent.com/assets/27736315/25643165/a941a4f2-2fa6-11e7-8cfe-f07ba0fafe5d.png)

**Comment by deanmoriart** [comment] 2017-05-07 01:26
I installed latest mesa drivers to see if it can fix the output and now even that Jimenez antialising not working on preview. :) I really should stop doing random things.

**Comment by jpturcotte** [comment] 2017-05-07 15:06
@morevnaproject & @ideasman42 If we started a bounty, could any of you or someone you know look into this? This is pretty ridiculous. Also, @shun-iwasawa.

**Comment by morevnaproject** [comment] 2017-05-07 15:16
@blackwarthog what do you think about that?

**Comment by blackwarthog** [comment] 2017-05-07 19:45
I need to investigate sources. I'm not sure that is proper way to evolve OpenToonz - hardware 3d acceleration is now the system requirement, and i don't now why we should introduce the software rendering. I've tried to be wise and objective :), actually i think that final rendering should be as accurate as possible: software or OpenCL (open computing language). Not Open**G**L (open graphics library) - because it will always add some restrictions and simplifications.

In our [lab](https://github.com/blackwarthog/lab/tree/master/c%2B%2B/contourgl) we does not found good solution to render vectors at GPU. At hardware (GPU) we have almost same results as at software (CPU), but we uses only one CPU thread - so actually in our case CPU overtake videocard twice (we tested OpenGL with supersampling and HDR). So in some case it may be good solution to use software-renderer for vectors.

Also we have some artifacts with our renderer:
![2017-05-08 01 51 46](https://cloud.githubusercontent.com/assets/5143743/25784371/3579efce-339e-11e7-917e-c90a31be3bfd.png)

These artifacts seems solvable at HW if we'll use some kind of stencil test, but it will affect antialiasing. I'not sure. @ideasman42, @shun-iwasawa, am i right?

I need to investigate sources to undestand how SW solutions applicable to OpenToonz architecture, and listen the opinions of @ideasman42 and @shun-iwasawa.

**Comment by deanmoriart** [comment] 2017-05-14 17:52
Some more questions; (apologies for being pain in the ass)

-Is there anything we can do to help as non coders ?

-Should I also report this to open source driver developers or they have nothing to do about this ?

- I don't know how to do this but switching to software rendering can fix the problem ? 

- Does the vector antialiasing method Pencil 2d, Inskcape or Tupi uses can be useful to be implemented ? Those apps can view and export the vector lines perfectly. However I have the same problem in blender with grease pencil in viewport but it fixes the output with full sample as @ideasman42 said before.

**Comment by morevnaproject** [comment] 2017-05-15 15:17
@deanmoriart 

> -Is there anything we can do to help as non coders ?

Your best help would give a test to solution when/if we have one. ^__^ Also, when (if ) the bounty will be started you can help tby donating to reach the bounty goal. But at the moment we are still investigating and estimating the requrired efforts for this task.

> -I don't know how to do this but switching to software rendering can fix the problem ?

It is not "just switch" problem. The software rendering should be implemented first (currently it is hardware-based).

> -Does the vector antialiasing method Pencil 2d, Inskcape or Tupi uses can be useful to be implemented ? 

Those applications are rendering lines using software algorithms. They are not benefit from hardware optimization at all. This is why they give image independent from hardware. ^__^

**Comment by morevnaproject** [comment] 2017-05-16 08:04
Quick news: our hired developer Ivan Mahonin (@blackwarthog) finished investigation of this problem and found a solution. Now he is preparing new testing builds with antialiasing for you.

**Comment by blackwarthog** [comment] 2017-05-16 16:01
Problem seems related with implementation of smooth lines in driver. I've wrote simple test of drawing lines with different width. By OpenGL specification width 1.0 (pixel) should be supported with antialiasing in each driver implementation. But i discovered that in some cases one-pixel lines draws aliased. Please, check how lines draws in your system by this test ([aa-test.zip](https://github.com/opentoonz/opentoonz/files/1005008/aa-test.zip)) and, if possible, upload your screenshot here.

![screen](https://cloud.githubusercontent.com/assets/5143743/26115116/b97ef450-3a91-11e7-9587-f8a2ea5dc05a.png)

**Comment by morevnaproject** [comment] 2017-05-16 16:05
Here is how it looks for Intel videocard (default drivers, Ubuntu 16.04.1) - 
![2017-04-36](https://cloud.githubusercontent.com/assets/332868/26116078/13319378-3a8c-11e7-812b-7ef9ae2375c8.png)

**Comment by morevnaproject** [comment] 2017-05-17 12:45
@deanmoriart @jpturcotte Can you please also submit results of your tests?

(BTW, If you don't feel comfortable running third-party binary on your system, then you can compile it from source - it is included in the zip archive).

**Comment by jpturcotte** [comment] 2017-05-17 19:07
I should have access to an up-to-date Mac with no dedicated GPU sometime today. Sadly, I have no Linux machine. Would a VM be worth anything? That machine would have an old Radeon.

**Comment by deanmoriart** [comment] 2017-05-17 20:06
@jpturcotte @blackwarthog @morevnaproject That's amazing thank you so so much! A bit of troubling days going on here so I had to left home without the linux machine. I will send the results immediately after I get the machine back from home. (approximately 3-4 days) I am sorry for that. (It's an ATI Radeon HD 4670)  Thanks a lot for your time and efforts.

**Comment by jpturcotte** [comment] 2017-05-17 23:48
I do not know if this will be of any help, but I installed Xubuntu 16.04 in VBox, and here are the results:
![screenshot_2017-05-17_17-38-17](https://cloud.githubusercontent.com/assets/26857126/26180767/563a92e8-3b39-11e7-98a5-86718b0c2483.png)
I then fiddled a bit, and built from source.
![screenshot_2017-05-17_19-10-21](https://cloud.githubusercontent.com/assets/26857126/26180782/85377250-3b39-11e7-8e17-7fc782b098d8.png)
To me, they both look identical to what @blackwarthog posted.

**Comment by blackwarthog** [comment] 2017-05-18 03:24
Here test for Mac: [aa-test-macos.zip](https://github.com/opentoonz/opentoonz/files/1009665/aa-test-macos.zip) (with sources)

@jpturcotte may you also try OpenToonz appimage in Xubuntu VBox?

**Comment by jpturcotte** [comment] 2017-05-18 14:12
@blackwarthog I did, and here are the results (zipped mp4):
[xubuntu-vbox-appimage-test.zip](https://github.com/opentoonz/opentoonz/files/1011097/xubuntu-vbox-appimage-test.zip)
Sorry for the incorrect framerate. You will notice there is a visible black flicker that does not happen in other apps, nor in any build on my Windows 7 host. AA seems fine, but I never had any problems, contrary to @deanmoriart. However, only in the latest Win nightly, while I resize the Preview window it shows afterimages, as if there were a delay refreshing what is inside the window. If it still happens in v1.1.3, I will fill out a bug report. Finally, I will test it out on macOS later today. Thank you!

**Comment by jpturcotte** [comment] 2017-05-18 16:16
Here are the results on a MacBook Air with Intel HD Graphics 6000 running macOS Sierra 10.12.4:
![18622906_10211960273499744_575093144_n](https://cloud.githubusercontent.com/assets/26857126/26212481/b992545e-3bc3-11e7-971f-c861467dce94.png)

**Comment by virr44** [comment] 2017-05-24 07:25
Hi, 

I just wanted to comment on this because I had the very same issue under Antergos with Nouveau. The problem is not OpenToonz but your system not using the correct drivers. 

You need to install the propietary drivers (in my case nVidia GT 555M) and CUDA and then run OpenToonz: $ optirun opentoonz-git or whatever you have in your system.

This also fixed a problem with the Blender grease pencil lines which were looking very jagged.

Now both Blender grase pencil lines and OpenToonz vector lines look absolutely gorgeous.

**Comment by RNavega** [comment] 2017-05-24 09:02
For comparison on Windows 8.1 64 it looks like this:

Intel HD Graphics 4600:
![aa-test win32 intel hd graphics 4600](https://cloud.githubusercontent.com/assets/28221053/26395195/da1129fe-405e-11e7-934e-06599ee8f9c3.png)

NVIDIA GTX 960m:
![aa-test win32 nvidia gtx 960m](https://cloud.githubusercontent.com/assets/28221053/26395196/da197a46-405e-11e7-82be-f6e552a9ccfd.png)

When you run the app you'll see it on a window and it also saves the output as an image named "aa-test.png" in the same folder where you run it.
Get it here: [aa-test (Win32).zip](https://github.com/opentoonz/opentoonz/files/1024940/aa-test.Win32.zip) (Source is in there too, it's for [BlitzMax](https://nitrologic.itch.io/blitzmax) which is free right now.)

**Comment by jpturcotte** [comment] 2017-05-24 11:53
@virr44 However, @deanmoriart is with AMD, not Nvidia, and as you can see from my test, it does not work on Macs with Intel HD Graphics either. Yes, it _is_ the drivers' fault, but I do not think this will ever get fixed, hence the need for software AA.

**Comment by virr44** [comment] 2017-05-24 13:31
Agreed

I guess I was just too happy to see smooth vector lines.

**Comment by jpturcotte** [comment] 2017-05-24 13:47
Haha, I know! I just did the test on my Win 7 PC with an old Radeon 6850, and it works perfectly, which makes it even more frustrating that it fails on other machines and OSes.

**Comment by deanmoriart** [comment] 2017-05-24 14:53
Me getting kicked out from dad's house timing = legendary.

**Comment by jpturcotte** [comment] 2017-05-24 14:58
Take your time, and send us those sweet test results whenever you can!
@blackwarthog Anything else we can do to help?

**Comment by morevnaproject** [comment] 2017-05-24 15:49
Dear friends! Much thanks to you all for the testing!

Yes, this is a driver problem. It happens only with some drivers on Linux which aren't implement closely OpenGL standard - Intel, Ati and Nouveau. 

Let me explain in more details why the problem happens (DISCLAIMER: this is result of investigation made by @blackwarthog, it's not me found this).

The anti-aliasing in OT is implemented by drawing a thin 1px line across the border of stroke (or shape), By OpenGL standard 1px line should have anti-aliasing, but in reality this depends on driver implementation.

This is exactly what we see in the test - with ATI/Intel cards on Linux the line bottom-right spiral have no anti-aliasing smoothing (you can see that if you open screenshot in GIMP and zoom 300%). So, there are no anti-aliasing for shapes.

OSX and Windows drivers work correctly - if you open test screenshots in GIMP and zoom 300% then you can see the line is smooth. So you have nice anti-aliased vectors in OT.

![01](https://cloud.githubusercontent.com/assets/332868/26412364/beb41224-40d2-11e7-8a8d-8c1362f4a8b3.png)

**Comment by morevnaproject** [comment] 2017-05-24 16:06
> I do not think this will ever get fixed

And here are good news! @blackwarthog have **fixed the issue** by manually re-implemented the algorithm of drawing 1px line using OpenGL.

Please download and test fixed Linux builds here - https://gumroad.com/l/opentoonz#
Source code - https://github.com/blackwarthog/opentoonz/commits/fix_antialiasing

Your donations are appreciated if you are happy with the results. ^__^

**Comment by jpturcotte** [comment] 2017-05-24 16:14
I was talking about the drivers, haha. I knew you guys would find a way. Thank you very much! By the way, I cannot access https://sources.morevnaproject.org/ws-software/OpenToonz.

**Comment by turtletooth** [comment] 2017-05-24 16:19
@morevnaproject Does the fix take into account what drivers the user is using?  If antialiasing can be done on the GPU with some drivers, I would assume that would be faster than CPU rendering.

**Comment by morevnaproject** [comment] 2017-05-24 16:37
> I was talking about the drivers, haha.

Ah, I see now! ^__^ In any case, it worth to submit a bugreport to maintainers of Intel and ATI drivers. You can reference this thread also.

 > By the way, I cannot access https://sources.morevnaproject.org/ws-software/OpenToonz.

Fixed by rebooting, sorry for inconvenience. We have weak servers, so they run out of memory sometimes because of overload. ^__^"

> Does the fix take into account what drivers the user is using? If anti-aliasing can be done on the GPU with some drivers

The fix is implemented purely on GPU. No CPU rendering here.

With this fix the anti-aliasing should be driver-independent now. So, the tests with NVIdia cards are also welcome (just to make sure we don't have any regressions). ^__^

**Comment by turtletooth** [comment] 2017-05-24 16:55
If you submit a PR, I can help confirm that nothing is broken on Windows.

**Comment by morevnaproject** [comment] 2017-05-24 17:06
@turtletooth Done.

**Comment by virr44** [comment] 2017-05-24 17:27
@morevnaproject 
I can confirm that this is working in Linux without 
$ optirun ...
Very cool!

**Comment by turtletooth** [comment] 2017-05-24 17:50
@virr44 Is your text antialiased?  I'm trying to see if another issue is related to this.

**Comment by jpturcotte** [comment] 2017-05-24 18:08
> The fix is implemented purely on GPU. No CPU rendering here.
Just to make sure, it runs on embedded solutions like Intel HD Graphics and AMD APUs, though?

**Comment by virr44** [comment] 2017-05-24 20:09
@turtletooth nope it's jagged...

**Comment by morevnaproject** [comment] 2017-05-25 06:34
> Just to make sure, it runs on embedded solutions like Intel HD Graphics and AMD APUs, though?

Yes, it works on any videocard, even embed one. I have tested the fix on my Intel HD Graphics 3000 CPU-integrated card - now I have anti-aliasing in OT.

>> Is your text antialiased? I'm trying to see if another issue is related to this.

> nope it's jagged...

It is possible to fix the problem with text in the same way as we did here for strokes. Since we are busy with finishing MyPaint brushes now, we will do that later.

**Comment by ideasman42** [comment] 2017-05-25 09:01
Wouldn't it be simpler to do this by jittering the projection matrix and accumulating all buffers back together? - this way there is no need to add jitter support piece-meal to each primitive type.

**Comment by virr44** [comment] 2017-05-25 20:25
by the way @morevnaproject the MyPaint brushes aren't working on this build on Linux. Just a heads up
~' _ '~

**Comment by morevnaproject** [comment] 2017-05-28 16:08
@ideasman42 

> Wouldn't it be simpler to do this by jittering the projection matrix. performing complete renders - and accumulating all buffers back together for the final result?

This will slow down the rendering, because that would require re-rendering same frame several times.

> this way there is no need to add jitter support piece-meal to each primitive type.

We just fixed the implementation that already was in OpenToonz. It is actually possible to implement some other algorithm, which shouldn't cause slowdown (as full-frame jittering does) and @blackwarthog asked about any opinions on this here - https://github.com/opentoonz/opentoonz/issues/1166#issuecomment-299729639
But we got no response, so we just fixed existing approach.

It's actually no problem to add anti-aliasing to shapes (and thus text), but at the moment we are busy with delivering MyPain brushes feature.

The disadvantage of current approach of anti-aliasing can be observed if you create a very thick line and set them semi-transparent. You will notice the line have artifacts on it. You can see that on illustration, provided by @blackwarthog (notice red lines) - 
![3579efce-339e-11e7-917e-c90a31be3bfd](https://cloud.githubusercontent.com/assets/332868/26530176/2e60a0ae-43fa-11e7-9ad1-14ea06c0ccd1.png)

So, of course, it's best to re-implement current anti-aliasing algorithm. As an option, it is possible to do  projection matrix jittering, as you suggested, but **for final rendering only**. I.e. keep current algorithm for workarea preview (to keep fast speed), but use projection matrix jittering for final render (to avoid artifacts). What do you think?

**Comment by ideasman42** [comment] 2017-05-29 03:38
> This will slow down the rendering, because that would require re-rendering same frame several times.

Sure, but this is what the graphics card does internally (in the case of full-sample AA)
keep in mind this is a workaround for old/cheap hardware. And it can be used only for offline rendering.

Probably in a year or two it can be removed, or we just accept that some graphics cards can't render with AA.

My point is that making all code more complicated, just to support rendering on hardware with broken OpenGL support is a net-loss in long term maintainability.

**Comment by morevnaproject** [comment] 2017-05-29 04:16
> And it can be used only for offline rendering, where OpenGL is quite fast already.

This is what I have suggested in the last paragraph of my message - https://github.com/opentoonz/opentoonz/issues/1166#issuecomment-304524023

> Renders may go from 1/50th seconds to 1/10th of a second

If users are agree to have their real-time rendering 5 times slower, then sure we can do that. @deanmoriart,  @jpturcotte do you want this?

Another question - how would you detect if full-sample AA should be enabled or not? Do you suggest to add an option or have some heuristic depending on OS/driver? In our current solution it works for every card without any additional conditions.

I understand the advantage of having full sampling for images, though.

**Comment by ideasman42** [comment] 2017-05-29 05:26
> how would you detect if full-sample AA should be enabled or not?

For off-screen AA render in Blender we check for:

    GL_ARB_texture_multisample
    GL_EXT_framebuffer_blit
    GL_EXT_framebuffer_multisample_blit_scaled
    GL_EXT_framebuffer_multisample

I would guess most or all of these apply to OpenToonz.

Having said that, we found graphics cards can't be relied on to tell the truth (Intel / AMD, especially laptop GPU's), so this should probably be an made an option, "Software Anti-Aliasing".

**Comment by morevnaproject** [comment] 2017-05-29 05:40
> And for people who are seriously working on animations in a studio - they can get well supported hardware for their renderfarms.

There are serious people who work outside of the studio. I am an artist-on-the-go - I am often working on the road, drawing on my Lenovo X220t laptop. It have integrated drawing screen tablet, so it is very comfortable for drawing (including animation). It is not a cheap hardware. Still, it have Intel graphic card and I am on Linux, so I am affected by this issue. There are even more expensive analogues, including Wacom Cintiq Companion 2 (http://wacom.com/en-us/products/pen-computers/cintiq-companion-2) and they all use Intel cards. Your suggestion to make screen refreshing 5 times slower (which will affect not only vectors, but also raster drawing operations) doesn't sounds appealing.

**Comment by ideasman42** [comment] 2017-05-29 05:54
I'm only suggesting to use this for offline rendering. Slower screen refreshing is of course unacceptable.

Any workaround for missing AA will have a performance trade-off, it's not as if rendering multiple passes causes offline rendering to suddenly become unusable.

And over-sampling per-primitive isn't really a great solution either... Im just suggesting if a fallback is needed for poor hardware support. Add one which doesn't add too much maintenance overhead.

**Comment by morevnaproject** [comment] 2017-05-29 05:57
> I'm only suggesting to use this for offline rendering. Slower screen refreshing is of course unacceptable.

In this case I am completely support your proposal! ^__^ I think it would be nice to open separate issue/request for full-sample AA implementation at offline rendering.

**Comment by ideasman42** [comment] 2017-05-29 06:02
@morevnaproject - sure, think its OK to close this report and open an issue for full-sample fallback/workaround.

Note that this feature could be communicated a bit differently. Full samples look noticeably better then the graphics cards over-sampling (especially for textures). And if you have different graphics cards you may notice a difference between the exact method of AA. So suggest to make this an option for offline rendering, so for example - you can do 32x samples ... even if the hardware only supports 8... or whatever.

**Comment by morevnaproject** [comment] 2017-05-29 06:07
Thanks for the hints! Please keep this issue open until we add anti-aliasing for shapes.

**Comment by jpturcotte** [comment] 2017-07-30 19:32
@morevnaproject & @blackwarthog: Hi, guys! Are you still working on this, and can we have any news? Also, @deanmoriart, have you tested this solution? Thank you!

**Comment by morevnaproject** [comment] 2017-07-31 07:03
If everyone is happy with the solution, then we are ready to submit it as pull request (for outlines only).  ^__^ Anti-aliasing for regions will come up later.

**Comment by jpturcotte** [comment] 2017-07-31 12:50
@morevnaproject Thanks a lot! I am eager to see your solution for shapes too.

**Comment by jpturcotte** [comment] 2018-03-04 19:06
Sorry for the bump. @morevnaproject & @blackwarthog I see PR #1218 has been closed. Could we have an update on this, please?

**Closed** 2018-12-17 07:13 UTC
Labels: Enhancement, Help Wanted, OS: Linux
